---
permalink: sm-storage/actions-you-can-perform-on-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volumes 
summary: 您可以对卷执行多种不同的操作：增加容量、删除、复制、初始化、重新分发、 更改所有权、更改缓存设置以及更改介质扫描设置。 
---
= 您可以对卷执行的操作
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以对卷执行多种不同的操作：增加容量、删除、复制、初始化、重新分发、 更改所有权、更改缓存设置以及更改介质扫描设置。



== 增加容量

您可以通过两种方式扩展卷的容量：

* 使用池或卷组中的可用容量。
+
您可以通过选择菜单：Storage[池和卷组>添加容量]向卷添加容量。

* 将未分配的容量(以未使用的驱动器的形式)添加到卷的池或卷组。如果池或卷组中没有可用容量、请使用此选项。
+
您可以通过选择菜单：Storage[池和卷组>添加容量]向池或卷组添加未分配的容量。

+
如果池或卷组中没有可用容量、则无法增加卷的容量。您必须先增加池或卷组的大小、或者删除未使用的卷。



扩展卷容量后、必须手动增加文件系统大小以匹配。如何执行此操作取决于所使用的文件系统。有关详细信息、请参见主机操作系统文档。



== 删除

通常、如果创建的卷参数或容量不正确、不再满足存储配置需求或不再需要用于备份或应用程序测试的快照映像、则可以删除这些卷。删除卷会增加池或卷组中的可用容量。

删除卷会导致这些卷上的所有数据丢失。删除卷还会删除任何关联的快照映像、计划和快照卷、并删除任何镜像关系。



== 复制

复制卷时、您可以在同一存储阵列上为源卷和目标卷这两个不同卷创建一个时间点副本。您可以通过选择菜单：Storage[卷>复制服务>复制卷]来复制卷。



== 初始化

初始化卷会擦除卷中的所有数据。首次创建卷时、系统会自动对其进行初始化。但是、Recovery Guru可能会建议您手动初始化卷、以便从某些故障情况中恢复。初始化卷时、卷会保留其WWN、主机分配、已分配容量和预留容量设置。它还会保留相同的数据保证(Data Assurance、DA)设置和安全设置。

您可以通过选择菜单：Storage[卷>更多>初始化卷]来初始化卷。



== 重新分布

重新分配卷以将卷移回其首选控制器所有者。通常、当主机和存储阵列之间的数据路径出现问题时、多路径驱动程序会从其首选控制器所有者移动卷。

大多数主机多路径驱动程序都会尝试通过指向其首选控制器所有者的路径访问每个卷。但是、如果此首选路径不可用、则主机上的多路径驱动程序将故障转移到备用路径。此故障转移可能会通过发生原因 将卷所有权更改为备用控制器。解决导致故障转移的情况后、某些主机可能会自动将卷所有权移回首选控制器所有者、但在某些情况下、您可能需要手动重新分配卷。

您可以通过选择菜单：Storage[卷>更多>重新分布卷]来重新分布卷。



== 更改卷所有权

更改卷的所有权会更改卷的首选控制器所有权。卷的首选控制器所有者列在菜单：存储(卷)>查看/编辑设置>高级选项卡下。

您可以通过选择菜单：Storage[卷>更多>更改所有权]来更改卷的所有权。



=== 镜像和卷所有权

如果镜像对的主卷属于控制器A、则二级卷也属于远程存储阵列的控制器A。更改主卷的所有者将自动更改二级卷的所有者、以确保这两个卷都属于同一控制器。主端的当前所有权更改会自动传播到辅端的相应当前所有权更改。

如果镜像一致性组包含一个本地二级卷且控制器所有权发生更改、则在首次写入操作时、二级卷会自动传输回其原始控制器所有者。您不能使用*更改所有权*选项更改二级卷的控制器所有权。



=== 复制卷和卷所有权

在复制卷操作期间、同一控制器必须同时拥有源卷和目标卷。有时、在复制卷操作开始时、两个卷都没有相同的首选控制器。因此、目标卷的所有权会自动传输到源卷的首选控制器。卷复制完成或停止后、目标卷的所有权将恢复到其首选控制器。

如果在复制卷操作期间更改了源卷的所有权、则也会更改目标卷的所有权。在某些操作系统环境下、可能需要先重新配置多路径主机驱动程序、然后才能使用I/O路径。(某些多路径驱动程序需要进行编辑才能识别I/O路径。有关详细信息、请参见驱动程序文档。)



== 更改缓存设置

缓存是控制器上的临时易失性存储(RAM)区域、其访问速度比驱动器介质更快。如果使用缓存、则可以提高整体I/O性能、原因如下：

* 从主机请求读取的数据可能已位于先前操作的缓存中、因此无需访问驱动器。
* 写入数据最初会写入缓存、这样、应用程序就可以继续运行、而无需等待数据写入驱动器。


选择菜单：Storage[卷>更多>更改缓存设置]以更改以下缓存设置：

* *读取和写入缓存*—读取缓存是一个缓冲区、用于存储从驱动器读取的数据。用于读取操作的数据可能已位于上次操作的缓存中、因此无需访问驱动器。数据会一直保留在读取缓存中、直到被刷新为止。
+
写入缓存是一个缓冲区、用于存储尚未写入驱动器的主机中的数据。数据会一直保留在写入缓存中、直到写入驱动器为止。写入缓存可以提高I/O性能。

* *使用镜像写入缓存*-如果写入一个控制器的缓存内存中的数据也写入另一个控制器的缓存中、则使用镜像进行写入缓存。因此、如果一个控制器发生故障、另一个控制器可以完成所有未完成的写入操作。只有在启用了写入缓存且存在两个控制器的情况下、写入缓存镜像才可用。创建卷时的默认设置是使用镜像进行写入缓存。
* *无电池写入缓存*—无电池写入缓存设置允许写入缓存继续运行、即使电池缺失、出现故障、已完全放电或未完全充电也是如此。通常不建议选择不带电池的写入缓存、因为断电后数据可能会丢失。通常、在电池充电或更换故障电池之前、控制器会暂时关闭写入缓存。
+
只有在启用写入缓存时、此设置才可用。此设置不适用于精简卷。

* *动态读取缓存预取*—动态缓存读取预取允许控制器在从驱动器向缓存读取数据块时将其他顺序数据块复制到缓存。这种缓存增加了从缓存中填充未来数据请求的可能性。动态缓存读取预取对于使用顺序I/O的多媒体应用程序非常重要预提取到缓存中的数据速率和数据量会根据主机读取的速率和请求大小进行自调整。随机访问不会将发生原因 数据预先提取到缓存中。禁用读取缓存时、此功能不适用。
+
对于精简卷、动态缓存读取预取始终处于禁用状态、并且无法更改。





== 更改介质扫描设置

介质扫描可检测并修复应用程序不常读取的磁盘块上的介质错误。如果池或卷组中的其他驱动器发生故障、则此扫描可以防止发生数据丢失、因为故障驱动器的数据是使用池或卷组中其他驱动器的冗余信息和数据重建的。

介质扫描会根据要扫描的容量和扫描持续时间以恒定速率持续运行。后台扫描可能会被较高优先级的后台任务(例如重建)临时暂停、但会以相同的恒定速率恢复。

您可以通过选择菜单：Storage[卷>更多>更改介质扫描设置]来启用和设置介质扫描的持续时间。

只有在为存储阵列和卷启用了介质扫描选项时、才会扫描此卷。如果还为该卷启用了冗余检查、则会检查该卷中的冗余信息是否与数据一致、前提是该卷具有冗余。创建每个卷时、默认情况下会为其启用具有冗余检查的介质扫描。

如果在扫描期间遇到不可恢复的介质错误、则会使用冗余信息(如果有)修复数据。例如、最佳RAID 5卷、最佳RAID 6卷或只有一个驱动器发生故障的RAID 6卷均提供冗余信息。如果无法使用冗余信息修复不可恢复的错误、则数据块将添加到不可读扇区日志中。可更正和不可更正的介质错误都会报告到事件日志中。

如果冗余检查发现数据与冗余信息不一致、则会向事件日志报告此信息。
