---
permalink: sm-storage/assign-hot-spares-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, assign hot spares 
summary: 您可以在RAID 1、RAID 5或RAID 6卷组中将热备用磁盘分配为备用驱动器、以实现额外的数据保护。如果其中一个卷组中的驱动器发生故障、则控制器会将故障驱动器中的数据重新构建到热备用磁盘中。 
---
= 分配热备用磁盘
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在RAID 1、RAID 5或RAID 6卷组中将热备用磁盘分配为备用驱动器、以实现额外的数据保护。如果其中一个卷组中的驱动器发生故障、则控制器会将故障驱动器中的数据重新构建到热备用磁盘中。

.开始之前
* 必须创建RAID 1、RAID 5或RAID 6卷组。(热备用磁盘不能用于池。相反、池会使用每个驱动器中的备用容量来保护其数据。)
* 必须具有满足以下条件的驱动器：
+
** 未分配、状态为最佳。
** 与卷组中的驱动器类型相同(例如SSD)。
** 与卷组中的驱动器的接口类型相同(例如、SAS)。
** 容量等于或大于卷组中驱动器的已用容量。




.关于此任务
此任务介绍如何从硬件页面手动分配热备用磁盘。建议覆盖的范围是每个驱动器集两个热备件。

[CAUTION]
====
也可以通过初始设置向导分配热备用磁盘。您可以通过在硬件页面上查看以粉色显示的驱动器托架来确定是否已分配热备用磁盘。

====
.步骤
. 选择 * 硬件 * 。
. 如果图形显示了控制器、请单击*显示磁盘架正面*。
+
此图将发生变化、以显示驱动器、而不是控制器。

. 选择要用作热备用磁盘的未分配驱动器(以灰色显示)。
+
此时将打开驱动器的上下文菜单。

. 选择*分配热备用磁盘*。
+
如果驱动器已启用安全保护、则会打开*安全擦除驱动器*对话框。要使用启用了安全保护的驱动器作为热备用驱动器、必须先执行安全擦除操作以删除其所有数据并重置其安全属性。

+
[CAUTION]
====
*可能的数据丢失*—确保选择的驱动器正确无误。完成安全擦除操作后、您将无法恢复任何数据。

====
+
如果驱动器*未*安全启用、则会打开确认分配热备用驱动器对话框。

. 查看对话框中的文本、然后确认操作。
+
驱动器在硬件页面上以粉色显示、表示它现在是热备用磁盘。





== 结果

如果RAID 1、RAID 5或RAID 6卷组中的驱动器发生故障、控制器会自动使用冗余数据将故障驱动器中的数据重建到热备用磁盘。
