---
permalink: sm-storage/automatic-versus-manual-pool-creation.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, automatic, manual, pool 
summary: 您可以自动或手动创建池、以便对物理存储进行分组、然后根据需要动态分配。创建池时、您可以添加物理驱动器。 
---
= 自动创建池与手动创建池
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以自动或手动创建池、以便对物理存储进行分组、然后根据需要动态分配。创建池时、您可以添加物理驱动器。



== 自动创建

当System Manager检测到存储阵列中的未分配容量时、将启动自动池创建。检测到未分配的容量后、System Manager会自动提示您创建一个或多个池、或者将未分配的容量添加到现有池、或者同时添加这两者。

如果满足以下条件之一、则会自动创建池：

* 存储阵列中不存在池、并且有足够的类似驱动器来创建新池。
* 新驱动器将添加到至少具有一个池的存储阵列中。


池中的每个驱动器必须具有相同的驱动器类型(HDD或SSD)、并且具有类似的容量。System Manager将提示您完成以下任务：

* 如果这些类型的驱动器数量充足、请创建一个池。
* 如果未分配的容量包含不同的驱动器类型、请创建多个池。
* 如果已在存储阵列中定义池、请将驱动器添加到现有池、然后将相同驱动器类型的新驱动器添加到该池。
* 将相同驱动器类型的驱动器添加到现有池中、如果新驱动器的驱动器类型不同、请使用其他驱动器类型创建不同的池。




== 手动创建

如果自动创建无法确定最佳配置、您可能需要手动创建池。出现这种情况的原因可能如下：

* 新驱动器可能会添加到多个池中。
* 一个或多个新池候选项可以使用磁盘架丢失保护或抽屉丢失保护。
* 一个或多个当前池候选项无法保持其磁盘架丢失保护或抽盒丢失保护状态。


如果存储阵列上有多个应用程序、而不希望这些应用程序争用相同的驱动器资源、您可能还需要手动创建池。在这种情况下、您可能会考虑手动为一个或多个应用程序创建一个较小的池。您只能分配一个或两个卷、而不能将工作负载分配给一个大型池、该池包含许多卷、可用于分布数据。手动创建专用于特定应用程序工作负载的单独池可以提高存储阵列操作的执行速度、并减少争用。
