---
permalink: sm-storage/capacity-for-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, capacity, volumes, 
summary: 存储阵列中的驱动器可为数据提供物理存储容量。开始存储数据之前、必须先将分配的容量配置到称为池或卷组的逻辑组件中。您可以使用这些存储对象配置、存储、维护和保留存储阵列上的数据。 
---
= 如何在 SANtricity System Manager 中分配卷容量
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
存储阵列中的驱动器可为数据提供物理存储容量。开始存储数据之前、必须先将分配的容量配置到称为池或卷组的逻辑组件中。您可以使用这些存储对象配置、存储、维护和保留存储阵列上的数据。



== 使用容量创建和扩展卷

您可以从池或卷组中的未分配容量或可用容量创建卷。

* 使用未分配的容量创建卷时、您可以同时创建池或卷组和卷。
* 使用可用容量创建卷时、您要在已有的池或卷组上创建额外的卷。


扩展卷容量后、必须手动增加文件系统大小以匹配。如何执行此操作取决于所使用的文件系统。有关详细信息、请参见主机操作系统文档。



== 厚卷和精简卷的容量类型

您可以创建厚卷或精简卷。对于厚卷、报告的容量和分配的容量相同、但对于精简卷、报告的容量和分配的容量不同。

* 对于厚卷、报告的卷容量等于分配的物理存储容量。必须存在全部物理存储容量。物理分配的空间等于向主机报告的空间。
+
通常、您会将厚卷的报告容量设置为您认为卷将增长到的最大容量。厚卷可为应用程序提供可预测的高性能、这主要是因为所有用户容量都是在创建时预留和分配的。

* 对于精简卷、报告的容量是指向主机报告的容量、而分配的容量是指当前为写入数据而分配的驱动器空间量。
+
报告的容量可能大于存储阵列上分配的容量。可以调整精简卷的大小以适应增长、而不考虑当前可用资产。



[NOTE]
====
SANtricity System Manager不提供创建精简卷的选项。如果要创建精简卷、请使用命令行界面(CLI)。

====


== 厚卷的容量限制

厚卷的最小容量为1 MiB、最大容量由池或卷组中驱动器的数量和容量决定。

增加厚卷的报告容量时、请记住以下准则：

* 您最多可以指定三个小数位(例如、55.375 GiB)。
* 容量必须小于(或等于)卷组中的最大可用容量。
+
创建卷时、系统会为动态区块大小(DSS)迁移预先分配一些额外容量。DSS迁移是软件的一项功能、可用于更改卷的区块大小。

* 某些主机操作系统支持大于2 TiB的卷(报告的最大容量由主机操作系统决定)。事实上、某些主机操作系统最多支持128个TiB卷。有关更多详细信息、请参见主机操作系统文档。




== 精简卷的容量限制

您可以创建报告容量较大且分配容量相对较小的精简卷、这有利于提高存储利用率和效率。精简卷有助于简化存储管理、因为分配的容量可以随着应用程序需求的变化而增加、而不会中断应用程序、从而提高存储利用率。

除了报告的容量和分配的容量之外、精简卷还包含写入容量。写入容量是指从为精简卷分配的预留容量中写入的容量。

下表列出了精简卷的容量限制。

[cols="3*"]
|===
| 容量类型 | 最小大小 | 最大大小 


 a| 
已报告
 a| 
32 MiB
 a| 
256 TiB



 a| 
已分配
 a| 
4 MiB
 a| 
64 TiB

|===
对于精简卷、如果已达到报告的最大容量256 TiB、则无法增加其容量。确保精简卷的预留容量设置为大于报告的最大容量的大小。

系统会根据已分配的容量限制自动扩展已分配的容量。通过分配的容量限制、您可以将精简卷的自动增长限制为低于报告的容量。当写入的数据量接近分配的容量时、您可以更改分配的容量限制。

要更改已分配的容量限制、请选择菜单：Storage[卷>精简卷监控选项卡>更改限制]。

由于System Manager在创建精简卷时不会分配全部容量、因此池中可能存在不足的可用容量。空间不足不仅会阻止对精简卷的写入、还会阻止对需要池中容量的其他操作(例如、快照映像或快照卷)的写入。但是、您仍然可以从池执行读取操作。如果发生这种情况、您将收到警报阈值警告。
