---
permalink: sm-storage/capacity-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, capacity terms 
summary: 了解容量术语如何应用于存储阵列。 
---
= 容量术语
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解容量术语如何应用于存储阵列。



== 存储对象

以下术语介绍了可与存储阵列交互的不同类型的存储对象。

[cols="25h,~"]
|===
| 存储对象 | Description 


 a| 
主机
 a| 
主机是指向存储阵列上的卷发送I/O的服务器。



 a| 
LUN
 a| 
逻辑单元号(LUN)是分配给主机用于访问卷的地址空间的编号。卷以LUN的形式呈现给主机。

每个主机都有自己的LUN地址空间。因此、不同的主机可以使用同一个LUN来访问不同的卷。



 a| 
镜像一致性组
 a| 
镜像一致性组是一个或多个镜像对的容器。对于异步镜像操作、必须创建镜像一致性组。



 a| 
镜像卷对
 a| 
镜像对由两个卷组成、一个是主卷、一个是二级卷。



 a| 
池
 a| 
池是指一组按逻辑分组的驱动器。您可以使用池创建一个或多个可供主机访问的卷。(您可以从池或卷组创建卷。)



 a| 
Snapshot一致性组
 a| 
快照一致性组是创建快照映像时视为单个实体的卷的集合。其中每个卷都有自己的快照映像、但所有映像都是在同一时间点创建的。



 a| 
Snapshot组
 a| 
快照组是一组来自单个基础卷的快照映像。



 a| 
Snapshot卷
 a| 
主机可通过Snapshot卷访问Snapshot映像中的数据。快照卷包含自己的预留容量、这样可以在不影响原始快照映像的情况下保存对基础卷所做的任何修改。



 a| 
Volume
 a| 
卷是应用程序，数据库和文件系统用于存储数据的容器。它是为主机创建的逻辑组件，用于访问存储阵列上的存储。



 a| 
卷组
 a| 
卷组是具有共享特征的卷的容器。卷组已定义容量和RAID级别。您可以使用卷组创建一个或多个可供主机访问的卷。(您可以从卷组或池创建卷。)

|===


== 存储容量

以下术语介绍了存储阵列上使用的不同容量类型。

[cols="25h,~"]
|===
| 容量类型 | Description 


 a| 
已分配容量
 a| 
已分配容量是指从池或卷组中的驱动器分配的物理容量。

您可以使用已分配的容量创建卷并执行复制服务操作。



 a| 
可用容量
 a| 
可用容量是指池或卷组中尚未分配给卷创建或复制服务操作和存储对象的可用容量。



 a| 
池或卷组容量
 a| 
池、卷或卷组容量是指存储阵列中已分配给池或卷组的容量。此容量用于创建卷并满足副本服务操作和存储对象的各种容量需求。



 a| 
池不可用容量
 a| 
池不可用容量是指池中由于驱动器大小不匹配而无法使用的空间。



 a| 
保留容量
 a| 
保留容量是指池中为支持潜在驱动器故障而预留的容量(驱动器数量)。



 a| 
已报告容量
 a| 
报告的容量是指向主机报告并可由主机访问的容量。



 a| 
预留容量
 a| 
预留容量是指用于任何复制服务操作和存储对象的物理分配容量。主机不能直接读取它。



 a| 
SSD 缓存
 a| 
[NOTE]
====
EF600或EF300存储系统不支持此功能。

====
SSD缓存是一组固态磁盘(SSD)驱动器、您可以在存储阵列中对这些驱动器进行逻辑分组。SSD缓存功能可将最常访问的数据("热"数据)缓存到延迟较低的SSD驱动器上、以动态加速应用程序工作负载。



 a| 
未分配的容量
 a| 
未分配容量是指存储阵列中已*未*分配给池或卷组的空间。



 a| 
写入容量
 a| 
写入容量是指从为精简卷分配的预留容量中写入的容量。

|===