---
permalink: sm-storage/change-cache-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, cache settings 
summary: 您可以更改读取缓存和写入缓存设置、以影响卷的整体I/O性能。 
---
= 更改卷的缓存设置
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以更改读取缓存和写入缓存设置、以影响卷的整体I/O性能。

.关于此任务
更改卷的缓存设置时、请记住以下准则：

* 打开更改缓存设置对话框后、您可能会看到选定缓存属性旁边显示的图标。此图标表示控制器已暂时暂停缓存操作。
+
如果新电池正在充电、已删除控制器或控制器检测到缓存大小不匹配、则可能会发生此操作。清除此条件后、在对话框中选择的缓存属性将变为活动状态。如果选定缓存属性未处于活动状态、请联系技术支持。

* 您可以更改一个卷或一个存储阵列上多个卷的缓存设置。您可以同时更改所有标准卷或所有精简卷的缓存设置。


.步骤
. 选择菜单： Storage[Volumes] 。
. 选择任何卷，然后选择菜单：更多（更改缓存设置）。
+
此时将显示更改缓存设置对话框。存储阵列上的所有卷都会显示在此对话框中。

. 选择*基本*选项卡可更改读取缓存和写入缓存的设置。
+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 缓存设置 | Description 


 a| 
读取缓存
 a| 
读取缓存是一个缓冲区、用于存储已从驱动器读取的数据。用于读取操作的数据可能已位于上次操作的缓存中、因此无需访问驱动器。数据会一直保留在读取缓存中、直到被刷新为止。



 a| 
写入缓存
 a| 
写入缓存是一个缓冲区、用于存储尚未写入驱动器的主机中的数据。数据会一直保留在写入缓存中、直到写入驱动器为止。写入缓存可以提高I/O性能。


NOTE: 对卷禁用*写入缓存*后、缓存会自动刷新。

|===
====
. 选择*高级*选项卡可更改厚卷的高级设置。高级缓存设置仅适用于厚卷。
+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 缓存设置 | Description 


 a| 
动态读取缓存预取
 a| 
动态缓存读取预取允许控制器在从驱动器向缓存读取数据块时将其他顺序数据块复制到缓存中。这种缓存增加了从缓存中填充未来数据请求的可能性。动态缓存读取预取对于使用顺序I/O的多媒体应用程序非常重要预提取到缓存中的数据速率和数据量会根据主机读取的速率和请求大小进行自调整。随机访问不会将发生原因 数据预先提取到缓存中。禁用读取缓存时、此功能不适用。

对于精简卷、动态缓存读取预取始终处于禁用状态、并且无法更改。



 a| 
无电池写入缓存
 a| 
不使用电池的写入缓存设置允许写入缓存继续运行、即使电池缺失、出现故障、已完全放电或未完全充电也是如此。通常不建议选择不带电池的写入缓存、因为断电后数据可能会丢失。通常、在电池充电或更换故障电池之前、控制器会暂时关闭写入缓存。


CAUTION: *可能丢失数据*-如果选择此选项而没有通用电源进行保护、则可能会丢失数据。此外、如果您没有控制器电池、并且启用了*无电池写入缓存*选项、则可能会丢失数据。

只有在启用写入缓存时、此设置才可用。此设置不适用于精简卷。



 a| 
使用镜像进行写入缓存
 a| 
如果写入到一个控制器的缓存内存中的数据也写入到另一控制器的缓存中、则会发生具有镜像功能的写入缓存。因此、如果一个控制器发生故障、另一个控制器可以完成所有未完成的写入操作。只有在启用了写入缓存且存在两个控制器的情况下、写入缓存镜像才可用。创建卷时的默认设置是使用镜像进行写入缓存。

只有在启用写入缓存时、此设置才可用。此设置不适用于精简卷。

|===
====
. 单击*保存*以更改缓存设置。

