---
permalink: sm-storage/change-host-port-identifiers-for-a-host.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, host port, identifiers, host 
summary: 如果要更改主机端口标识符上的用户标签、向主机添加新的主机端口标识符或从主机中删除主机端口标识符、请更改主机端口标识符。 
---
= 更改主机的主机端口标识符
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要更改主机端口标识符上的用户标签、向主机添加新的主机端口标识符或从主机中删除主机端口标识符、请更改主机端口标识符。

.关于此任务
更改主机端口标识符时、请记住以下准则：

* *添加*—添加主机端口时、要将主机端口标识符与为连接到存储阵列而创建的主机相关联。您可以使用主机总线适配器(HBA)实用程序手动输入端口信息。
* *编辑*—您可以编辑主机端口以将主机端口移动(关联)到其他主机。您可能已将主机总线适配器或iSCSI启动程序移动到其他主机、因此必须将主机端口移动(关联)到新主机。
* *删除*—您可以删除主机端口以从主机中删除(取消关联)主机端口。


.步骤
. 选择菜单： Storage[Hosts] 。
. 选择要与端口关联的主机，然后单击 * 查看 / 编辑设置 * 。
+
如果要向主机集群中的主机添加端口、请展开主机集群并选择所需主机。您不能在主机集群级别添加端口。

+
此时将显示一个对话框，其中显示了当前主机设置。

. 单击 * 主机端口 * 选项卡。
+
此对话框将显示当前主机端口标识符。

. 根据需要更改主机端口标识符设置。
+
[cols="25h,~"]
|===
| 正在设置 ... | Description 


 a| 
主机端口
 a| 
您可以选择以下选项之一：

** *添加*—使用添加将新的主机端口标识符与主机关联。主机端口标识符名称的长度由主机接口技术决定。光纤通道和Infiniband主机端口标识符名称必须包含16个字符。iSCSI 主机端口标识符名称最多包含 223 个字符。此端口必须是唯一的。不允许使用已配置的端口号。
** *删除*—使用删除删除删除主机端口标识符(取消关联)。删除选项不会物理删除主机端口。此选项将删除主机端口与主机之间的关联。除非您删除主机总线适配器或 iSCSI 启动程序，否则控制器仍可识别主机端口。
+
[NOTE]
====
如果删除主机端口标识符、它将不再与此主机关联。此外、主机将无法通过此主机端口标识符访问其分配的任何卷。

====




 a| 
Label
 a| 
要更改端口标签名称、请单击*编辑*图标(铅笔)。端口标签名称必须是唯一的。不允许使用已配置的标签名称。



 a| 
CHAP机密
 a| 
仅对iSCSI主机显示。您可以为启动程序(iSCSI主机)设置或更改CHAP密钥。

System Manager使用质询握手身份验证协议(Challenge Handshake Authentication Protocol、CHAP)方法、在初始链接期间验证目标和启动程序的身份。身份验证基于一个称为CHAP机密的共享安全密钥。

|===
. 单击 * 保存 * 。

