---
permalink: sm-storage/change-the-settings-for-a-snapshot-schedule.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, settings, snapshot, schedule 
summary: 对于快照计划、您可以更改自动收集时间或收集频率。 
---
= 更改快照计划的设置
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
对于快照计划、您可以更改自动收集时间或收集频率。

.关于此任务
您可以从现有快照计划导入设置、也可以根据需要修改设置。

由于快照计划与快照组或快照一致性组关联、因此、计划设置更改可能会影响预留的容量。

.步骤
. 选择菜单：Storage[Snapshots]。
. 单击*计划*选项卡。
. 选择要更改的快照计划、然后单击*编辑*。
+
此时将显示编辑Snapshot计划对话框。

. 执行以下操作之一：
+
** *使用其他快照对象中先前定义的计划*-单击*导入计划*、选择具有要导入计划的对象、然后单击*导入*。
** *编辑计划设置*—请参见下面的字段详细信息。
+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 正在设置 ... | Description 


 a| 
天/月
 a| 
选择以下选项之一：

*** *每日/每周*-为同步快照选择单独的日期。如果要设置每日计划、也可以选中右上角的*选择所有日期*复选框。
*** *每月/每年*-为同步快照选择单个月。在*日期*字段中、输入月中要进行同步的天数。有效条目为* 1 *到* 31 *和*最后一个*。您可以使用逗号或分号分隔多天。使用连字符表示包含的日期。例如：1、3、4、10-15、last。如果您希望使用每月计划、也可以选中右上角的*选择所有月份*复选框。




 a| 
开始时间
 a| 
从下拉列表中、为每日快照选择新的开始时间。所选内容以半小时为间隔提供。开始时间默认为比当前时间提前半小时。



 a| 
时区
 a| 
从下拉列表中、选择存储阵列的时区。



 a| 
每天创建快照

快照之间的时间
 a| 
选择每天要创建的快照映像数。

如果选择多个、还可以选择还原点之间的时间。对于多个还原点、请确保预留了足够的容量。



 a| 
Start date

End date

无结束日期
 a| 
输入开始同步的开始日期。此外、请输入结束日期或选择*无结束日期*。

|===
====


. 单击 * 保存 * 。

