---
permalink: sm-storage/change-settings-for-a-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, settings, volume 
summary: 您可以更改卷的设置、例如名称、主机分配、区块大小、修改优先级、缓存、 等等。 
---
= 更改 SANtricity System Manager 中的卷设置
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以更改卷的设置、例如名称、主机分配、区块大小、修改优先级、缓存、 等等。

.开始之前
要更改的卷处于最佳状态。


NOTE: 在对卷设置进行更改时、某些操作可能不可用

.步骤
. 从左侧面板中，选择菜单：Storage[Volumes]。
. 选择要更改的卷，然后单击 menu:ellipsis icon[Edit Settings]。
+
此时将显示 Edit Volume Settings（编辑卷设置）窗口，其中显示选定卷的配置设置。

. 根据需要配置卷设置：
+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 正在设置 ... | Description 


 a| 
Name
 a| 
显示卷的名称。如果当前名称不再有意义或适用、请更改卷的名称。



 a| 
主机
 a| 
显示卷分配。您可以将卷分配给主机或主机集群、以便可以对其进行访问以执行I/O操作。此分配授予主机或主机集群对特定卷或存储阵列中的多个卷的访问权限。

** *已分配给*-标识可访问选定卷的主机或主机集群。
** * LUN *—逻辑单元号(LUN)是指分配给主机用于访问卷的地址空间的编号。卷以LUN的形式呈现给主机。每个主机都有自己的LUN地址空间。因此、不同的主机可以使用同一个LUN来访问不同的卷。
+

NOTE: 对于NVMe接口、此列显示命名空间ID。命名空间是指为块访问而格式化的NVM存储。它类似于SCSI中的逻辑单元、它与存储阵列中的卷相关。命名空间ID是NVMe控制器在命名空间中的唯一标识符、可设置为1到255之间的值。它类似于SCSI中的逻辑单元号(Logical Unit Number、LUN)。





 a| 
分段规模估算
 a| 
显示了分段大小调整设置、此设置仅对卷组中的卷显示。您可以更改区块大小以优化性能。

*允许的区块大小转换*- System Manager确定允许的区块大小转换。与当前区块大小的过渡不适当的区块大小在下拉列表中不可用。允许的过渡通常是当前区块大小的两倍或一半。例如，如果当前卷分段大小为 32 KiB ，则允许使用新的卷分段大小 16 KiB 或 64 KiB 。

已启用SSD缓存的卷*—您可以为已启用SSD缓存的卷指定4-KiB分段大小。确保仅为支持 SSD 缓存且处理小块 I/O 操作的卷（例如， 16 KiB I/O 块大小或更小）选择 4-KiB 区块大小。如果为处理大型块顺序操作且已启用 SSD 缓存的卷选择 4 KiB 作为分段大小，则性能可能会受到影响。

*更改区块大小所需的时间*-更改卷区块大小所需的时间取决于以下变量：

** 主机的 I/O 负载
** 卷的修改优先级
** 卷组中的驱动器数量
** 驱动器通道的数量
** 更改卷的区块大小时存储阵列控制器的处理能力、I/O性能会受到影响、但数据仍可用。




 a| 
修改优先级
 a| 
显示了修改优先级的设置、此设置仅适用于卷组中的卷。

修改优先级用于定义为卷修改操作分配的处理时间与系统性能相关。您可以提高卷修改优先级、但这可能会影响系统性能。

移动滑块条以选择优先级。

*修改优先级速率*—最低优先级速率有利于系统性能、但修改操作所需时间较长。最高优先级比率有利于修改操作、但系统性能可能会受到影响。

|===
====
. 单击 * 保存 * 。
+
System Manager会根据您的选择更改卷的设置。



.完成后
选择菜单：Storage[Operations in Progress] 以查看当前为所选卷运行的更改操作的进度。
