---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-consistency-group-member-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, consistency group, member volume 
summary: 您可以更改一致性组成员卷的设置、以调整在成员卷的预留容量接近全满时System Manager发送警报通知的百分比点、并更改在预留容量达到其定义的最大容量时使用的策略 百分比。 
---
= 更改一致性组成员卷的预留容量设置
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以更改一致性组成员卷的设置、以调整SANtricity系统管理器在成员卷的预留容量接近全满时发送警报通知的百分比值、并更改在预留容量达到其最大定义百分比时要使用的策略。

.关于此任务
更改单个成员卷的预留容量设置还会更改与一致性组关联的所有成员卷的预留容量设置。

.步骤
. 选择菜单：Storage[Pools & Volume Groups]。
. 单击*预留容量*选项卡。
. 选择要编辑的一致性组成员卷、然后单击*查看/编辑设置*。
+
此时将显示成员卷预留容量设置对话框。

. 根据需要更改成员卷的预留容量设置。
+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 正在设置 ... | Description 


 a| 
在以下情况下提醒我...
 a| 
使用spinner框调整当成员卷的预留容量接近全满时System Manager发送警报通知的百分比。

当成员卷的预留容量超过指定阈值时、System Manager会发送警报、以便您有时间增加预留容量或删除不必要的对象。


NOTE: 更改一个成员卷的警报设置将更改属于同一一致性组的_all_成员卷的警报设置。



 a| 
预留容量全满的策略
 a| 
您可以选择以下策略之一：

** *清除最旧的快照映像*- System Manager会自动清除一致性组中最早的快照映像、从而释放成员的预留容量、以便在组中重复使用。
** *拒绝向基础卷写入数据*-当预留容量达到其最大定义百分比时、System Manager将拒绝向基础卷发出的任何I/O写入请求、此请求会触发预留容量访问。


|===
====
. 单击*保存*以应用所做的更改。


.结果
System Manager会更改成员卷的预留容量设置、以及一致性组中所有成员卷的预留容量设置。
