---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-snapshot-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, snapshot, group 
summary: 您可以更改快照组的设置以更改其名称、自动删除设置、允许的最大快照映像数、System Manager发送预留容量警报通知的百分比点或预留容量达到其最大定义百分比时要使用的策略。 
---
= 更改快照组的预留容量设置
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以更改快照组的设置、以更改其名称、自动删除设置、允许的最大快照映像数、SANtricity系统管理器发送预留容量警报通知的百分比或预留容量达到最大定义百分比时要使用的策略。

在创建快照组期间、系统会创建预留容量来存储组中所有快照映像的数据。

.步骤
. 选择菜单：Storage[Pools & Volume Groups]。
. 单击*预留容量*选项卡。
. 选择要编辑的快照组、然后单击*查看/编辑设置*。
+
此时将显示Snapshot组设置对话框。

. 根据需要更改快照组的设置。
+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 正在设置 ... | Description 


 a| 
* Snapshot组设置*



 a| 
Name
 a| 
快照组的名称。需要为快照组指定名称。



 a| 
自动删除
 a| 
一种将组中的快照映像总数保持在或低于用户定义的最大值的设置。启用此选项后、System Manager会在创建新快照时自动删除组中最早的快照映像、以符合组允许的最大快照映像数。



 a| 
Snapshot映像限制
 a| 
一个可配置的值、用于指定快照组允许的最大快照映像数。



 a| 
Snapshot计划
 a| 
如果是、则会为自动创建快照设置计划。



 a| 
*预留容量设置*



 a| 
在以下情况下提醒我...
 a| 
使用spinner框调整当快照组的预留容量接近全满时System Manager发送警报通知的百分比。

当快照组的预留容量超过指定阈值时、System Manager会发送警报、以便您有时间增加预留容量或删除不必要的对象。



 a| 
预留容量全满的策略
 a| 
您可以选择以下策略之一：

** *清除最旧的快照映像*- System Manager会自动清除快照组中最旧的快照映像、从而释放快照映像预留容量、以便在组中重复使用。
** *拒绝向基础卷写入数据*-当预留容量达到其最大定义百分比时、System Manager将拒绝向基础卷发出的任何I/O写入请求、此请求会触发预留容量访问。




 a| 
*关联对象*



 a| 
基础卷
 a| 
用于组的基础卷的名称。基础卷是创建快照映像的源卷。它可以是厚卷或精简卷、通常分配给主机。基础卷可以位于卷组或磁盘池中。



 a| 
Snapshot映像
 a| 
从此组创建的映像数。快照映像是指在特定时间点捕获的卷数据的逻辑副本。与还原点一样，您可以通过快照映像回滚到已知正常的数据集。尽管主机可以访问快照映像、但它无法直接对其进行读写。

|===
====
. 单击*保存*将所做的更改应用于快照组设置。

