---
permalink: sm-storage/change-host-port-identifiers-for-a-host.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, host port, identifiers, host 
summary: 如果要更改主机端口标识符上的用户标签、向主机添加新的主机端口标识符或从主机中删除主机端口标识符、请更改主机端口标识符。 
---
= 在 SANtricity System Manager 中更改主机的主机端口标识符
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要更改主机端口标识符上的用户标签、向主机添加新的主机端口标识符或从主机中删除主机端口标识符、请更改主机端口标识符。

.关于此任务
更改主机端口标识符时、请记住以下准则：

* *添加*—添加主机端口时、要将主机端口标识符与为连接到存储阵列而创建的主机相关联。您可以使用主机总线适配器(HBA)实用程序手动输入端口信息。
* *编辑*—您可以编辑主机端口以将主机端口移动(关联)到其他主机。您可能已将主机总线适配器或iSCSI启动程序移动到其他主机、因此必须将主机端口移动(关联)到新主机。
* *删除*—您可以删除主机端口以从主机中删除(取消关联)主机端口。


.步骤
. 在左侧面板中，选择菜单： Storage [Hosts]。
. 选择要关联端口的主机，然后单击菜单：省略号图标 [Edit Settings]。
+
如果要将端口添加到主机群集中的主机，请选择所需的主机。无法在主机群集级别添加端口。

+
此时会显示编辑主机设置屏幕，其中显示当前的主机设置。

. 根据需要更改主机端口标识符设置。
+
[cols="25h,~"]
|===
| 正在设置 ... | Description 


 a| 
主机端口
 a| 
您可以选择以下选项之一：

** *添加主机端口* -- 单击 *添加主机端口* 将新的主机端口标识符关联到主机。主机端口标识符名称的长度由主机接口技术决定。Fibre Channel 和 Infiniband 主机端口标识符名称必须包含 16 个字符。iSCSI 主机端口标识符名称最多包含 223 个字符。端口必须是唯一的。不允许使用已配置的端口号。
** *删除（X 图标）* -- 单击 *X* 图标以删除（取消关联）主机端口标识符。删除选项不会物理删除主机端口。此选项删除主机端口和主机之间的关联。除非您卸下主机总线适配器或 iSCSI 启动程序，否则控制器仍可识别主机端口。
+
[NOTE]
====
如果删除主机端口标识符、它将不再与此主机关联。此外、主机将无法通过此主机端口标识符访问其分配的任何卷。

====




 a| 
Name
 a| 
如果需要，您可以更改端口标签名称。端口标签名称必须是唯一的。不允许使用已配置的标签名称。



 a| 
CHAP机密
 a| 
仅对iSCSI主机显示。您可以为启动程序(iSCSI主机)设置或更改CHAP密钥。

System Manager使用质询握手身份验证协议(Challenge Handshake Authentication Protocol、CHAP)方法、在初始链接期间验证目标和启动程序的身份。身份验证基于一个称为CHAP机密的共享安全密钥。

|===
. 单击 * 保存 * 。

