---
permalink: sm-storage/comparison-between-thick-volumes-and-thin-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, comparison, thick volumes, thin volumes 
summary: 厚卷始终为完全配置卷、这意味着在创建卷时会分配所有容量。精简卷始终采用精简配置、这意味着在将数据写入卷时会分配容量。 
---
= 厚卷与精简卷之间的比较
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
厚卷始终为完全配置卷、这意味着在创建卷时会分配所有容量。精简卷始终采用精简配置、这意味着在将数据写入卷时会分配容量。

[NOTE]
====
System Manager不提供创建精简卷的选项。如果要创建精简卷、请使用命令行界面(CLI)。

====
[cols="25h,~"]
|===
| Volume type | Description 


 a| 
厚卷
 a| 
* 厚卷是从池或卷组创建的。
* 对于厚卷、预先提供大量存储空间、以满足未来的存储需求。
* 厚卷是使用创建卷时在物理存储上预先分配的卷的整个大小创建的。这种预分配意味着、创建100 GiB卷实际上会占用驱动器上已分配的100 GiB容量。但是、此空间可能会保持未使用状态、从而导致存储容量利用率不足。
* 创建厚卷时、请确保不要为单个卷过度分配容量。单个卷的容量过度分配可能会迅速占用系统中的所有物理存储。
* 请注意、复制服务(Snapshot映像、Snapshot卷、卷副本和异步镜像)也需要存储容量、因此请勿将所有容量分配给厚卷。空间不足可能会阻止对池或卷组的写入。如果发生这种情况、您将收到可用容量警报阈值警告。




 a| 
精简卷
 a| 
* 精简卷仅从池创建、而不是从卷组创建。
* 精简卷必须为RAID 6。
* 精简卷在EF600或EF300存储系统上不可用。
* 您必须使用命令行界面创建精简卷。
* 与厚卷不同、精简卷所需的空间不会在创建期间分配、而是在稍后按需提供。
* 精简卷允许您过度分配其大小。也就是说、您可以分配大于卷大小的LUN。然后、您可以根据需要扩展卷(如有必要、可在此过程中添加驱动器)、而无需扩展LUN大小、因此无需断开用户连接。
* 您可以使用精简配置块空间回收(UNMAP)通过主机发出的SCSI UNMAP命令回收存储阵列上精简配置卷的块。支持精简配置的存储阵列可以重新利用回收的空间来满足同一存储阵列中其他精简配置卷的分配请求、从而可以更好地报告磁盘空间使用情况并更高效地利用资源。


|===


== 精简卷限制

精简卷支持所有厚卷操作、但以下情况除外：

* 您不能更改精简卷的区块大小。
* 您不能为精简卷启用预读取冗余检查。
* 在复制卷操作中、不能使用精简卷作为目标卷。
* 您只能在异步镜像对的主端更改精简卷的已分配容量限制和警告阈值。主端对这些参数所做的任何更改都会自动传播到二级端。

