---
permalink: sm-storage/copy-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, copy volume 
summary: '您可以将数据从一个卷复制到同一存储阵列中的另一个卷、并为源卷创建物理时间点副本(克隆)。' 
---
= 在 SANtricity System Manager 中复制卷
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将数据从一个卷复制到同一存储阵列中的另一个卷、并为源卷创建物理时间点副本(克隆)。

.开始之前
* 必须停止源卷和目标卷的所有I/O活动。
* 必须卸载源卷和目标卷上的任何文件系统。
* 如果您之前在复制卷操作中使用过目标卷、则不再需要该数据或已备份数据。


.关于此任务
源卷是接受主机I/O并存储应用程序数据的卷。启动复制卷后、源卷中的数据将全部复制到目标卷。

目标卷是一个标准卷、用于维护源卷中的数据副本。复制卷操作完成后、目标卷与源卷相同。目标卷必须与源卷具有相同或更大的容量；但是、它可以具有不同的RAID级别。

.有关联机和脱机副本的更多信息
[%collapsible]
====
*联机副本*

联机副本会为存储阵列中的任何卷创建一个时间点副本、同时仍可在副本正在进行时向卷写入数据。此功能可通过创建卷的快照并使用该快照作为副本的实际源卷来实现。创建时间点映像的卷称为基础卷、可以是存储阵列中的标准卷或精简卷。

*脱机副本*

脱机副本将从源卷读取数据并将其复制到目标卷、同时暂停对正在进行的源卷进行的所有更新。源卷的所有更新都将暂停、以防止在目标卷上创建按时间顺序排列的不一致。脱机卷副本关系位于源卷和目标卷之间。

====
[NOTE]
====
复制卷操作会覆盖目标卷上的数据、并使与目标卷关联的所有快照卷失败(如果存在)。

====
.步骤
. 选择菜单： Storage[Volumes] 。
. 选择要用作复制卷操作源的卷、然后选择菜单：复制服务[复制卷]。
+
此时将显示复制卷选择目标对话框。

. 选择要将数据复制到的目标卷。
+
此对话框中显示的表列出了所有符合条件的目标卷。

. 使用滑块栏为复制卷操作设置复制优先级。
+
与服务I/O请求相比、复制优先级可确定用于完成复制卷操作的系统资源的数量。

+
.有关副本优先级速率的更多信息
[%collapsible]
====
复制优先级有五种：

** 最低
** 低
** 中等
** 高
** 最高


如果将副本优先级设置为最低速率、则会优先处理I/O活动、并且复制卷操作所需时间会更长。如果将副本优先级设置为最高比率、则会优先执行复制卷操作、但存储阵列的I/O活动可能会受到影响。

====
. 选择是要创建联机副本还是脱机副本。要创建联机副本、请选中"*在复制操作期间保持源卷联机"*复选框。
. 执行以下操作之一：
+
** 要执行_online _复制操作、请单击*下一步*继续显示*预留容量*对话框。
** 要执行_offline_副本操作、请单击*完成*以启动脱机副本。


. 如果选择创建联机副本、请设置用于存储联机副本的数据和其他信息所需的预留容量、然后单击*完成*启动联机副本。
+
卷候选表仅显示支持指定预留容量的候选卷。预留容量是指用于任何复制服务操作和存储对象的物理分配容量。主机不能直接读取它。

+
按照以下准则分配预留容量：

+
** 预留容量的默认设置为基础卷容量的40%、通常此容量已足够。
** 但是、预留容量会根据原始数据的更改次数而有所不同。存储对象处于活动状态的时间越长、预留容量就越大。




.结果
System Manager会将源卷中的所有数据复制到目标卷。复制卷操作完成后、目标卷将自动成为主机的只读卷。

.完成后
选择菜单：主页(查看正在执行的操作)以查看复制卷操作的进度。此操作可能会很长，并且可能会影响系统性能。
