---
permalink: sm-storage/copy-volume-function.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, copy, volume, 
summary: 通过复制卷功能、您可以在同一存储阵列上创建两个单独的卷、即源卷和目标卷、从而创建卷的时间点副本。 
---
= 复制卷概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过复制卷功能、您可以在同一存储阵列上创建两个单独的卷、即源卷和目标卷、从而创建卷的时间点副本。

此功能会逐字节执行从源卷到目标卷的复制、从而使目标卷上的数据与源卷上的数据完全相同。



== 复制数据以提高访问能力

随着卷的存储要求发生变化、您可以使用复制卷功能将数据从使用较小容量驱动器的池或卷组复制到使用较大容量驱动器的池或卷组。例如、您可以使用复制卷功能执行以下操作：

* 将数据移动到更大的驱动器。
* 更改为数据传输速率较高的驱动器。
* 使用新技术更改驱动器以提高性能。
* 将精简卷更改为厚卷。




== 将精简卷更改为厚卷

如果要将精简卷更改为厚卷、请使用复制卷操作创建精简卷的副本。复制卷操作的目标始终是厚卷。

[NOTE]
====
System Manager不提供创建精简卷的选项。如果要创建精简卷、请使用命令行界面(CLI)。

====


== 备份数据

通过复制卷功能、您可以通过将数据从一个卷复制到同一存储阵列上的另一个卷来备份卷。您可以使用目标卷作为源卷的备份、用于系统测试或备份到其他设备、例如磁带驱动器。



== 将Snapshot卷数据还原到基础卷

如果需要将数据从关联的Snapshot卷还原到基础卷、可以使用复制卷功能将数据从快照卷复制到基础卷。您可以为快照卷上的数据创建卷副本、然后将数据复制到基础卷。



== 源卷和目标卷

下表指定了可用于具有复制卷功能的源卷和目标卷的卷类型。

[cols="1a,1a,1a,1a"]
|===
| Volume type | 使卷副本源卷脱机 | 联机卷副本源卷 | 目标卷联机和脱机 


 a| 
池中的厚卷
 a| 
是的。
 a| 
是的。
 a| 
是的。



 a| 
卷组中的厚卷
 a| 
是的。
 a| 
是的。
 a| 
是的。



 a| 
精简卷
 a| 
是的。
 a| 
是的。
 a| 
否



 a| 
Snapshot卷
 a| 
是^1^
 a| 
否
 a| 
否



 a| 
Snapshot基础卷
 a| 
是的。
 a| 
否
 a| 
否



 a| 
远程镜像主卷
 a| 
是^2^
 a| 
否
 a| 
是的。

|===
^1^在联机复制操作完成之前、您不能使用Snapshot卷副本。

^2^如果源卷是主卷、则目标卷的容量必须等于或大于源卷的可用容量。
