---
permalink: sm-storage/create-pool-automatically.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, pool, automatically 
summary: 当System Manager检测到存储阵列中未分配的驱动器时、将自动启动池创建。您可以使用自动创建池将存储阵列中所有未分配的驱动器轻松配置到一个池中、并将驱动器添加到现有池中。 
---
= 自动创建池
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当System Manager检测到存储阵列中未分配的驱动器时、将自动启动池创建。您可以使用自动创建池将存储阵列中所有未分配的驱动器轻松配置到一个池中、并将驱动器添加到现有池中。

.开始之前
如果满足以下条件之一、则可以启动池自动配置对话框：

* 至少检测到一个未分配的驱动器、可以将其添加到具有类似驱动器类型的现有池中。
* 检测到可用于创建新池的11个或更多未分配驱动器(如果由于驱动器类型不同而无法将其添加到现有池中)。


.关于此任务
请记住以下几点：

* 向存储阵列添加驱动器时、System Manager会自动检测这些驱动器、并提示您根据驱动器类型和当前配置创建一个或多个池。
* 如果先前已定义池、则System Manager会自动提示您选择将兼容驱动器添加到现有池。将新驱动器添加到现有池后、System Manager会自动在新容量中重新分布数据、现在、新容量包含您添加的新驱动器。
* 在配置EF600或EF300存储阵列时、请确保每个控制器可以访问前12个插槽中相同数量的驱动器、以及最后12个插槽中相同数量的驱动器。此配置有助于控制器更有效地使用驱动器端PCIe总线。


您可以使用以下任一方法启动池自动配置对话框：

* 检测到未分配的容量后、"通知"区域的主页页面上将显示池自动配置建议。单击*查看池自动配置*以启动对话框。
* 您还可以从"池和卷组"页面启动"池自动配置"对话框、如以下任务所述。


.步骤
. 选择菜单：Storage[Pools & Volume Groups]。
. 选择菜单：更多[启动池自动配置]。
+
此结果表列出了新池、已添加驱动器的现有池或这两者。默认情况下、新池使用序列号命名。

+
System Manager将执行以下任务：

+
** 如果有足够数量的驱动器具有相同的驱动器类型(HDD或SSD)并具有类似的容量、则创建一个池。
** 如果未分配的容量包含不同的驱动器类型、则创建多个池。
** 如果已在存储阵列中定义池、则将驱动器添加到现有池、并将相同驱动器类型的新驱动器添加到该池。
** 将相同驱动器类型的驱动器添加到现有池中、如果新驱动器的驱动器类型不同、则使用其他驱动器类型创建不同的池。


. 要更改新池的名称、请单击*编辑*图标(铅笔)。
. 要查看池的其他特征、请将光标置于或轻触*详细信息*图标(页面)。
+
此时将显示有关驱动器类型、安全功能、数据保证(Data Assurance、DA)功能、磁盘架丢失保护和抽盒丢失保护的信息。

+
对于EF600和EF300存储阵列、还会显示资源配置和卷块大小的设置。

. 单击 * 接受 * 。

