---
permalink: sm-storage/create-snapshot-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, snapshot, consistency group 
summary: 为了确保副本一致、您可以创建一组多个卷、称为快照一致性组。 
---
= 创建快照一致性组
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
为了确保副本一致、您可以创建一组多个卷、称为_snapshot一致性组_。

通过此组、您可以同时为所有卷创建快照映像、以确保一致性。属于快照一致性组的每个卷都称为_member volume"。将卷添加到快照一致性组时、系统会自动创建与此成员卷对应的新快照组。

.关于此任务
通过快照一致性组创建序列、您可以为组选择成员卷并为成员卷分配容量。

创建快照一致性组的过程包括多步操作步骤。



== 第1步：向快照一致性组添加成员

选择成员以指定构成快照一致性组的一组卷。对快照一致性组执行的任何操作都会统一扩展到选定的成员卷。

.开始之前
成员卷必须是最佳卷。

.步骤
. 选择菜单：Storage[Snapshots]。
. 单击* Snapshot一致性组*选项卡。
. 选择菜单：创建[ Snapshot一致性组]。
+
此时将显示创建Snapshot一致性组对话框。

. 选择要作为成员卷添加到快照一致性组的卷。
. 单击*下一步*、然后转到 <<第2步：为快照一致性组预留容量>>。




== 第2步：为快照一致性组预留容量

将预留容量与快照一致性组相关联。System Manager会根据快照一致性组的属性建议卷和容量。您可以接受建议的预留容量配置或自定义分配的存储。

.关于此任务
在预留容量对话框中、卷候选表仅显示支持指定预留容量的候选卷。预留容量是指用于任何复制服务操作和存储对象的物理分配容量。主机不能直接读取它。

.步骤
. 使用spinner框为快照一致性组分配预留容量。执行以下操作之一：
+
** *接受默认设置*。
+
使用此建议选项可使用默认设置为每个成员卷分配预留容量。

** *分配您自己的预留容量设置以满足您的数据存储需求。*
+
按照以下准则分配预留容量。

+
*** 预留容量的默认设置为基础卷容量的40%。通常、此容量足以满足要求。
*** 所需容量因卷I/O写入的频率和大小以及快照映像收集的数量和持续时间而异。




. *可选：*如果更改默认预留容量设置、请单击*刷新候选容量*以刷新指定预留容量的候选列表。
. 单击*下一步*、然后转到 <<第3步：编辑快照一致性组的设置>>。




== 第3步：编辑快照一致性组的设置

接受或选择快照一致性组的自动删除设置和预留容量警报阈值。

.关于此任务
通过快照一致性组创建序列、您可以为组选择成员卷并为成员卷分配容量。

.步骤
. 根据需要接受或更改快照一致性组的默认设置。
+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 正在设置 ... | Description 


 a| 
* Snapshot一致性组设置*



 a| 
Name
 a| 
指定快照一致性组的名称。



 a| 
在以下情况下启用Snapshot映像自动删除...
 a| 
如果要在指定限制后自动删除快照映像、请保持选中此复选框；使用spinner框更改此限制。如果清除此复选框、则在创建32个映像后将停止创建快照映像。



 a| 
*预留容量设置*



 a| 
在以下情况下提醒我...
 a| 
使用spinner框调整在快照一致性组的预留容量接近全满时系统发送警报通知的百分比点。

如果快照一致性组的预留容量超过指定阈值、请使用提前通知增加预留容量或删除不必要的对象、以免剩余空间用尽。



 a| 
预留容量全满的策略
 a| 
选择以下策略之一：

** *清除最旧的快照映像*-系统会自动清除快照一致性组中最早的快照映像、从而释放快照映像预留容量、以便在组中重复使用。
** *拒绝向基础卷写入数据*-当预留容量达到其最大定义百分比时、系统会拒绝向基础卷发出的任何I/O写入请求、这些请求会触发预留容量访问。


|===
====
. 对快照一致性组配置感到满意后、单击*完成*。

