---
permalink: sm-storage/create-snapshot-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, snapshot, volume 
summary: 您可以创建一个快照卷、以使主机能够访问卷或快照一致性组的快照映像。您可以将快照卷指定为只读或读写卷。 
---
= 创建Snapshot卷
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以创建一个快照卷、以使主机能够访问卷或快照一致性组的快照映像。您可以将快照卷指定为只读或读写卷。

通过快照卷创建序列、您可以从快照映像创建快照卷、并提供在卷为读/写卷时分配预留容量的选项。快照卷可以指定为以下卷之一：

* 只读快照卷使主机应用程序可以对快照映像中所含数据的副本进行读取访问、但无法修改快照映像。只读Snapshot卷没有关联的预留容量。
* 读写Snapshot卷使主机应用程序能够对快照映像中所含数据的副本进行写入访问。它具有自己的预留容量、用于将主机应用程序后续所做的任何修改保存到基础卷、而不会影响引用的快照映像。


创建快照卷的过程包括多步操作步骤。



== 第1步：查看快照卷的成员

选择基础卷的快照映像或快照一致性组。如果选择快照一致性组快照映像、则会显示快照一致性组的成员卷以供查看。

.步骤
. 选择菜单：Storage[Snapshots]。
. 选择* Snapshot Volumes*选项卡。
. 选择 * 创建 * 。
+
此时将显示创建Snapshot卷对话框。

. 选择要转换为快照卷的快照映像(卷或快照一致性组)、然后单击*下一步*。在*筛选器*字段中使用文本条目缩小列表范围。
+
如果选择的是快照一致性组快照映像、则会显示查看成员对话框。

+
在查看成员对话框中、查看选择转换为快照卷的卷列表、然后单击*下一步*。

. 转至  2: Assign snapshot volume to host。




== 第2步：将快照卷分配给主机

选择特定的主机或主机集群以将其分配给快照卷。此分配将授予主机或主机集群对快照卷的访问权限。如果需要、您可以选择稍后分配主机。

.开始之前
* 主机页面下存在有效的主机或主机集群。
* 必须已为主机定义主机端口标识符。
* 在创建启用了DA的卷之前、请验证计划的主机连接是否支持数据保证(Data Assurance、DA)功能。如果存储阵列中控制器上的任何主机连接不支持 DA ，则关联的主机将无法访问已启用 DA 的卷上的数据。


分配卷时、请记住以下准则：

* 主机的操作系统可以对主机可以访问的卷数设置特定限制。
* 您可以为存储阵列中的每个快照卷定义一个主机分配。
* 分配的卷在存储阵列中的控制器之间共享。
* 主机或主机集群不能使用同一逻辑单元号(LUN)两次来访问快照卷。您必须使用唯一的LUN。


[NOTE]
====
如果您尝试将卷分配给与主机集群中已建立的主机分配冲突的主机集群、则向主机分配卷将失败。

====
.步骤
. 在*分配给主机*对话框中、选择要分配给新卷的主机或主机集群。如果要在不分配主机的情况下创建卷、请从下拉列表中选择*稍后分配*。
. 选择访问模式。选择以下选项之一：
+
** *读/写*—此选项为主机提供对快照卷的读/写访问权限、并需要预留容量。
** *只读*—此选项为主机提供对快照卷的只读访问权限、而不需要预留容量。


. 单击*下一步*、然后执行以下操作之一：
+
** 如果快照卷为读/写卷、则会显示查看容量对话框。转至  3: Reserve capacity for a snapshot volume。
** 如果快照卷为只读卷、则会显示编辑优先级对话框。转至  4: Edit settings for a snapshot volume。






== 第3步：为快照卷预留容量

将预留容量与读/写Snapshot卷关联。System Manager会根据基础卷或快照一致性组的属性建议卷和容量。您可以接受建议的预留容量配置或自定义分配的存储。

您可以根据需要增加或减少为快照卷预留的容量。如果发现Snapshot预留容量大于所需容量、则可以减小其大小以释放其他逻辑卷所需的空间。

.步骤
. 使用spinner框为快照卷分配预留容量。
+
卷候选表仅显示支持指定预留容量的候选对象。

+
执行以下操作之一：

+
** *接受默认设置*。
+
使用此建议选项可使用默认设置为快照卷分配预留容量。

** *分配您自己的预留容量设置以满足您的数据存储需求*。
+
如果更改默认预留容量设置、请单击*刷新候选容量*以刷新指定预留容量的候选列表。

+
按照以下准则分配预留容量。

+
*** 预留容量的默认设置为基础卷容量的40%、通常此容量已足够。
*** 所需容量因卷I/O写入的频率和大小以及快照映像收集的数量和持续时间而异。




. *可选：*如果要为快照一致性组创建快照卷、"更改候选项"选项将显示在"预留容量候选项"表中。单击*更改候选项*以选择备用预留容量候选项。
. 单击*下一步*、然后转到  4: Edit settings for a snapshot volume。




== 第4步：编辑快照卷的设置

更改快照卷的设置、例如名称、缓存、预留容量警报阈值等。

您可以将卷添加到固态磁盘(SSD)缓存中、以提高只读性能。SSD缓存由一组SSD驱动器组成、这些驱动器会在存储阵列中进行逻辑分组。

.步骤
. 根据需要接受或更改快照卷的设置。
+
.字段详细信息
====
[cols="25h,~"]
|===
| 正在设置 ... | Description 


 a| 
* Snapshot卷设置*



 a| 
Name
 a| 
指定快照卷的名称。



 a| 
启用SSD缓存
 a| 
选择此选项可在SSD上启用只读缓存。注：EF600或EF300存储系统不支持此功能。



 a| 
*预留容量设置*



 a| 
在以下情况下提醒我...
 a| 
*仅对读/写Snapshot卷显示*。

使用spinner框调整当快照组的预留容量接近全满时系统发送警报通知的百分比点。

如果快照组的预留容量超过指定阈值、请使用提前通知增加预留容量或删除不必要的对象、以免剩余空间用尽。

|===
====
. 查看快照卷配置。单击*返回*进行任何更改。
. 对快照卷配置感到满意后、单击*完成*。

