---
permalink: sm-storage/create-workloads.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, workloads 
summary: 您可以为任何类型的应用程序创建工作负载。 
---
= 创建工作负载
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以为任何类型的应用程序创建工作负载。

.关于此任务
工作负载是指支持应用程序的存储对象。您可以为每个应用程序定义一个或多个工作负载或实例。对于某些应用程序、系统会将工作负载配置为包含具有类似底层卷特征的卷。这些卷特征会根据工作负载支持的应用程序类型进行优化。例如、如果您创建了一个支持Microsoft SQL Server应用程序的工作负载、然后为该工作负载创建了卷、则底层卷特征将进行优化以支持Microsoft SQL Server。

System Manager建议仅为以下应用程序类型优化卷配置：

* Microsoft®SQL Server (Microsoft®SQL Server)
* Microsoft®Exchange Server (Microsoft®Exchange Server)
* 视频监控
* VMware ESXi TM (适用于要与虚拟机文件系统结合使用的卷)


请牢记以下准则：

* 使用特定于应用程序的工作负载时、系统建议使用经过优化的卷配置、以最大程度地减少应用程序工作负载I/O与应用程序实例中的其他流量之间的争用。您可以查看建议的卷配置、然后使用添加/编辑卷对话框编辑、添加或删除系统建议的卷和特征。
* 使用其他应用程序类型时、您可以使用添加/编辑卷对话框手动指定卷配置。


.步骤
. 选择菜单： Storage[Volumes] 。
. 选择菜单：创建[工作负载]。
+
此时将显示创建应用程序工作负载对话框。

. 使用下拉列表选择要为其创建工作负载的应用程序类型、然后键入工作负载名称。
. 单击 * 创建 * 。


.完成后
您已准备好向创建的工作负载添加存储容量。使用*创建卷*选项为应用程序创建一个或多个卷、并为每个卷分配特定容量。
