---
permalink: sm-storage/create-volume-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, volume, group 
summary: 您可以使用卷组创建一个或多个可供主机访问的卷。卷组是指具有RAID级别和容量等共享特征的卷的容器。 
---
= 创建卷组
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用卷组创建一个或多个可供主机访问的卷。卷组是指具有RAID级别和容量等共享特征的卷的容器。

借助容量更大的驱动器以及在控制器之间分布卷的功能、可以为每个卷组创建多个卷、从而充分利用存储容量并保护数据。

在创建卷组之前、请查看以下准则：

* 您至少需要一个未分配的驱动器。
* 一个卷组中可以包含的驱动器数量存在限制。这些限制因RAID级别而异。
* 要启用磁盘架/抽盒丢失保护、您必须创建一个卷组、该卷组使用至少位于三个磁盘架或抽盒中的驱动器、除非您使用的是RAID 1、其中至少包含两个磁盘架/抽盒。
* 如果您使用的是EF600或EF300存储阵列、并且计划手动创建卷组、请确保每个控制器都可以访问前12个插槽中相同数量的驱动器、以及最后12个插槽中相同数量的驱动器。此配置有助于控制器更有效地使用驱动器端PCIe总线。目前、System Manager允许在创建卷组时在"高级"功能下选择驱动器。
* 查看您选择的RAID级别如何影响卷组的容量：
+
** 如果选择RAID 1、则必须一次添加两个驱动器、以确保选择镜像对。如果选择四个或更多驱动器、则会实现镜像和条带化(称为RAID 10或RAID 1+0)。
** 如果选择RAID 5、则必须至少添加三个驱动器才能创建卷组。
** 如果选择RAID 6、则必须至少添加五个驱动器才能创建卷组。




.步骤
. 选择菜单：Storage[Pools & Volume Groups]。
. 单击菜单：创建[卷组]。
+
此时将显示创建卷组对话框。

. 键入卷组的名称。
. 选择最符合数据存储和保护要求的RAID级别。
+
此时将显示卷组候选表、并且仅显示支持选定RAID级别的候选卷。

. *可选：*如果存储阵列中有多种类型的驱动器、请选择要使用的驱动器类型。
+
此时将显示卷组候选表、并且仅显示支持选定驱动器类型和RAID级别的候选卷。

. *可选：*您可以选择自动方法或手动方法来定义要在卷组中使用的驱动器。默认选择为"Automatic"方法。
+
要手动选择驱动器、请单击*手动选择驱动器(高级)*链接。单击后、它将更改为*自动选择驱动器(高级)*。

+
使用手动方法可以选择卷组包含哪些特定驱动器。您可以选择特定的未分配驱动器以获取所需的容量。如果存储阵列包含具有不同介质类型或不同接口类型的驱动器、则只能为单个驱动器类型选择未配置的容量来创建新的卷组。

+
[NOTE]
====
只有了解驱动器冗余和最佳驱动器配置的专家才应使用手动方法。

====
. 根据显示的驱动器特征、选择要在卷组中使用的驱动器、然后单击*创建*。
+
显示的驱动器特征取决于您选择的是自动方法还是手动方法。

+
.自动方法驱动器特征
====
[cols="25h,~"]
|===
| 特性 | 使用 ... 


 a| 
可用容量
 a| 
显示可用容量(以GiB为单位)。选择一个具有满足应用程序存储需求的容量的卷组候选项。



 a| 
驱动器总数
 a| 
显示可用于此卷组的驱动器数量。选择包含所需驱动器数量的卷组候选项。



 a| 
驱动器块大小(仅限EF300和EF600)
 a| 
显示了组中的驱动器可以写入的块大小(扇区大小)。值可能包括：

** 512—512字节扇区大小。
** 4k—4、096字节扇区大小。




 a| 
支持安全保护
 a| 
指示此卷组候选项是否全部由具有安全功能的驱动器组成、这些驱动器可以是全磁盘加密(Full Disk Encryption、FDE)驱动器、也可以是联邦信息处理标准(Federal Information Processing Standard、FIPS)驱动器。

** 您可以使用驱动器安全保护卷组、但所有驱动器都必须具有安全功能才能使用此功能。
** 如果要创建仅FDE卷组、请在安全功能列中查找*是- FDE*。如果要创建仅FIPS卷组、请在安全功能列中查找*是- FIPS *。
** 您可以创建一个由驱动器组成的卷组、这些驱动器可能支持安全功能、也可能不支持安全功能、或者混合了多种安全级别。如果卷组中的驱动器包含不支持安全的驱动器、则无法确保卷组的安全。




 a| 
是否启用安全性？
 a| 
提供了使用支持安全的驱动器启用驱动器安全功能的选项。如果卷组具有安全功能、并且您已设置安全密钥、则可以选中此复选框来启用驱动器安全性。


NOTE: 启用驱动器安全性后删除驱动器安全性的唯一方法是删除卷组并擦除驱动器。



 a| 
支持DA
 a| 
指示数据保证(Data Assurance、DA)是否可用于此组。数据保证(Data Assurance、DA)可检查并更正在数据通过控制器向下传输到驱动器时可能发生的错误。

如果要使用DA、请选择一个支持DA的卷组。(对于支持DA的驱动器、在池中创建的卷会自动启用DA。)

卷组可以包含支持DA或不支持DA的驱动器、但要使用此功能、所有驱动器都必须支持DA。



 a| 
支持资源配置(仅限EF300和EF600)
 a| 
显示资源配置是否可用于此组。资源配置是EF300和EF600存储阵列中提供的一项功能、可在不执行后台初始化过程的情况下立即使用卷。



 a| 
磁盘架丢失保护
 a| 
显示磁盘架丢失保护是否可用。磁盘架丢失保护功能可确保在与磁盘架完全失去通信时能够访问卷组中卷上的数据。



 a| 
抽盒丢失保护
 a| 
显示是否提供了抽盒丢失保护、只有在使用包含抽盒的驱动器架时、才会提供此保护。如果与驱动器架中的单个抽盒完全失去通信、则抽盒丢失保护功能可确保能够访问卷组中卷上的数据。



 a| 
支持的卷块大小(仅限EF300和EF600)
 a| 
显示了可为组中的卷创建的块大小：

** 512n—512字节原生。
** 512e—模拟512字节。
** 4 k—4、096字节。


|===
====
+
.手动方法驱动器特征
====
[cols="25h,~"]
|===
| 特性 | 使用 ... 


 a| 
介质类型
 a| 
指示介质类型。支持以下介质类型：

** 硬盘驱动器
** 固态磁盘(SSD)


一个卷组中的所有驱动器都必须具有相同的介质类型(所有SSD或所有硬盘驱动器)。卷组不能混合使用介质类型或接口类型。



 a| 
驱动器块大小(仅限EF300和EF600)
 a| 
显示了组中的驱动器可以写入的块大小(扇区大小)。值可能包括：

** 512—512字节扇区大小。
** 4k—4、096字节扇区大小。




 a| 
驱动器容量
 a| 
指示驱动器容量。

** 尽可能选择容量等于卷组中当前驱动器容量的驱动器。
** 如果您必须添加容量较小的未分配驱动器、请注意、卷组中当前每个驱动器的可用容量会减少。因此、卷组中的驱动器容量相同。
** 如果您必须添加容量更大的未分配驱动器、请注意、添加的未分配驱动器的可用容量会减少、以便与卷组中驱动器的当前容量匹配。




 a| 
托盘
 a| 
指示驱动器的托盘位置。



 a| 
插槽
 a| 
指示驱动器的插槽位置。



 a| 
转速(rpm)
 a| 
指示驱动器的速度。



 a| 
逻辑扇区大小
 a| 
指示扇区大小和格式。



 a| 
支持安全保护
 a| 
指示此卷组候选项是否全部由具有安全功能的驱动器组成、这些驱动器可以是全磁盘加密(Full Disk Encryption、FDE)驱动器、也可以是联邦信息处理标准(Federal Information Processing Standard、FIPS)驱动器。

** 您可以使用驱动器安全保护卷组、但所有驱动器都必须具有安全功能才能使用此功能。
** 如果要创建仅FDE卷组、请在安全功能列中查找*是- FDE*。如果要创建仅FIPS卷组、请在安全功能列中查找*是- FIPS *。
** 您可以创建一个由驱动器组成的卷组、这些驱动器可能支持安全功能、也可能不支持安全功能、或者混合了多种安全级别。如果卷组中的驱动器包含不支持安全的驱动器、则无法确保卷组的安全。




 a| 
支持DA
 a| 
指示数据保证(Data Assurance、DA)是否可用于此组。数据保证(Data Assurance、DA)可检查并更正数据通过控制器向下传输到驱动器时可能发生的错误。

如果要使用DA、请选择一个支持DA的卷组。(对于支持DA的驱动器、在池中创建的卷会自动启用DA。)

卷组可以包含支持DA或不支持DA的驱动器、但要使用此功能、所有驱动器都必须支持DA。



 a| 
支持的卷块大小(仅限EF300和EF600)
 a| 
显示了可为组中的卷创建的块大小：

** 512n—512字节原生。
** 512e—模拟512字节。
** 4 k—4、096字节。




 a| 
支持资源配置(仅限EF300和EF600)
 a| 
显示资源配置是否可用于此组。资源配置是EF300和EF600存储阵列中提供的一项功能、可在不执行后台初始化过程的情况下立即使用卷。

|===
====

