---
permalink: sm-storage/disable-resource-provisioning-on-existing-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, disable, resource provisioning, 
summary: 您可以在现有池或卷组上启用或禁用资源配置。 
---
= 在现有卷组和池上启用或禁用资源配置
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
对于任何支持DULBE-的驱动器、您可以在池或卷组中的现有卷上启用或禁用资源配置。

资源配置是EF300和EF600存储阵列中提供的一项功能、可在不执行后台初始化过程的情况下立即使用卷。分配给卷的所有驱动器块都会进行取消分配(未映射)、这样可以延长SSD的使用寿命并提高最大写入性能。

默认情况下、在驱动器支持DULBE"的系统上启用资源配置。除非您先前已禁用资源配置、否则无需启用该配置。

.开始之前
* 您必须具有EF300或EF600存储阵列。
* 您必须具有SSD卷组或池、其中的所有驱动器都支持NVMe已取消分配或未写入逻辑块错误启用(DULBEe)错误恢复功能。否则、资源配置选项将不可用。


.关于此任务
在为现有卷组和池启用资源配置时、选定卷组或池中的所有卷都会发生更改、以允许取消分配这些块。此过程可能涉及后台操作、以确保在取消映射粒度处分配一致。此操作不会取消映射任何空间。后台操作完成后、操作系统需要取消映射任何未使用的块以创建可用空间。

在为现有卷组或池禁用资源配置时、后台操作会重新写入每个卷中的所有逻辑块。现有数据保持不变。写入操作将在与卷组或池关联的驱动器上映射或配置块。


NOTE: 对于新的卷组和池、您可以从菜单：设置[系统>其他设置>启用/禁用资源配置的卷]启用或禁用资源配置。

.步骤
. 选择菜单：Storage[Pools & Volume Groups]。
. 从列表中选择一个池或卷组。
+
一次只能选择一个池或卷组。向下滚动列表以查看其他池或卷组。

. 选择*不常见任务*、然后选择*启用资源配置*或*禁用资源配置*。
. 在对话框中、确认操作。



NOTE: *如果您重新启用DULBE*-后台操作完成后、您可能需要重新启动主机以检测到DULBE*配置更改、然后重新挂载所有文件系统。
