---
permalink: sm-storage/faq-snapshots.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= SANtricity System Manager 快照常见问题解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== 为什么我看不到所有卷、主机或主机集群？

具有已启用DA的基础卷的Snapshot卷不能分配给不支持数据保证(Data Assurance、DA)的主机。您必须先在基础卷上禁用DA、然后才能将快照卷分配给不支持DA的主机。

对于要将快照卷分配到的主机、请考虑以下准则：

* 如果主机通过不支持DA的I/O接口连接到存储阵列、则该主机将不支持DA。
* 如果主机集群至少有一个主机成员不支持DA、则此主机集群不支持DA。


[NOTE]
====
您不能在与快照(一致性组、快照组、快照映像和快照卷)、卷副本、 和镜像。必须先删除所有关联的预留容量和快照对象、然后才能在基础卷上禁用DA。

====


== 什么是快照映像？

快照映像是在特定时间点捕获的卷内容的逻辑副本。Snapshot映像使用的存储空间极少。

Snapshot映像数据存储如下：

* 创建快照映像时、该映像与基础卷完全匹配。创建快照后、如果对基础卷上的任何块或块集发出首次写入请求、则在将新数据写入基础卷之前、原始数据会复制到快照预留容量。
* 后续快照仅包含自创建第一个快照映像以来发生更改的数据块。在将新数据写入基础卷之前、后续的每次写入时复制操作都会将基础卷上即将覆盖的原始数据保存到Snapshot预留容量中。




== 为什么使用Snapshot映像？

您可以使用快照防止数据意外或恶意丢失或损坏、并允许从这种情况中恢复。

选择一个基础卷或一组称为快照一致性组的基础卷、然后通过以下一种或多种方式捕获快照映像：

* 您可以为一个基础卷或一个由多个基础卷组成的快照一致性组创建快照映像。
* 您可以手动创建快照、也可以为基础卷或快照一致性组创建计划、以自动捕获定期快照映像。
* 您可以为快照映像创建主机可访问的快照卷。
* 您可以执行回滚操作以还原快照映像。


系统会保留多个快照映像作为还原点、您可以使用这些映像在特定时间点回滚到已知正常的数据集。回滚功能可防止数据意外删除和数据损坏。



== 可以使用哪些类型的卷来创建快照？

标准卷和精简卷是唯一可用于存储快照映像的卷类型。不能使用非标准卷。基础卷可以驻留在池或卷组上。



== 为什么要创建快照一致性组？

如果要确保同时在多个卷上创建快照映像、请创建快照一致性组。

例如、如果数据库由多个卷组成、并且需要保持一致才能进行恢复、则需要使用快照一致性组来收集所有卷的协调快照、并使用这些快照还原整个数据库。

快照一致性组中包含的卷称为_member volumes_。

您可以对快照一致性组执行以下快照操作：

* 创建快照一致性组的快照映像、以同时获取成员卷的映像。
* 为快照一致性组创建一个计划、以自动捕获成员卷的定期并发映像。
* 为快照一致性组映像创建主机可访问的快照卷。
* 对快照一致性组执行回滚操作。




== 什么是Snapshot卷？何时需要预留容量？

主机可通过Snapshot卷访问Snapshot映像中的数据。快照卷包含自己的预留容量、这样可以在不影响原始快照映像的情况下保存对基础卷所做的任何修改。主机无法读取或写入Snapshot映像。如果要读取或写入快照数据、请创建一个快照卷并将其分配给主机。

您可以创建两种类型的快照卷。Snapshot卷的类型决定了它是否使用预留容量。

* *只读*—创建为只读的快照卷可以使主机应用程序对快照映像中所含数据的副本具有读取访问权限。只读Snapshot卷不使用预留容量。
* *读写*—创建为读写的快照卷可以在不影响引用的快照映像的情况下对快照卷进行更改。读写Snapshot卷使用预留容量存储这些更改。您可以随时将只读快照卷转换为读写卷。




== 什么是快照组？

Snapshot组是一个关联基础卷的时间点快照映像的集合。

System Manager会将快照映像组织为_snapshot groups_.Snapshot组无需用户操作、但您可以随时调整Snapshot组上的预留容量。此外、在满足以下条件时、系统可能会提示您创建预留容量：

* 每当为尚未创建快照组的基础卷创建快照时、System Manager都会自动创建快照组。这样会为基础卷创建预留容量、用于存储后续的快照映像。
* 每当为基础卷创建快照计划时、System Manager都会自动创建快照组。




== 为什么要禁用Snapshot卷？

如果要为快照映像分配不同的快照卷、则可以禁用快照卷。您可以预留已禁用的快照卷以供日后使用。

如果您不再需要快照卷或一致性组快照卷、并且不打算稍后重新创建该卷、则应删除该卷、而不是将其禁用。



== 什么是"已禁用"状态？

当前未将处于已禁用状态的快照卷分配给快照映像。要启用快照卷、必须使用重新创建操作为已禁用的快照卷分配新的快照映像。

快照卷的特征由分配给它的快照映像定义。在处于已禁用状态的快照卷上、读写活动将暂停。



== 为什么要暂停快照计划？

暂停计划后、不会按计划创建快照映像。您可以暂停快照计划以节省存储空间、然后稍后恢复计划的快照。

如果不需要快照计划、应删除该计划、而不是暂停该计划。
