---
permalink: sm-storage/faq-storage-drives.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= SANtricity System Manager 存储驱动器常见问题解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== 什么是热备用驱动器？

热备用磁盘在RAID 1、RAID 5或RAID 6卷组中充当备用驱动器。它们是功能完备的驱动器、不包含任何数据。如果卷组中的驱动器发生故障、控制器会自动将故障驱动器中的数据重新构建为热备用磁盘。

如果存储阵列中的某个驱动器发生故障、则热备用驱动器会自动替换故障驱动器、而无需物理交换。如果在驱动器发生故障时热备用驱动器可用、则控制器会使用冗余数据将故障驱动器中的数据重建到热备用驱动器。

热备用驱动器并非专用于特定卷组。相反、您可以为存储阵列中容量相同或容量较小的任何故障驱动器使用热备用驱动器。热备用驱动器的介质类型(HDD或SSD)必须与它所保护的驱动器相同。

[NOTE]
====
池不支持热备用驱动器。池使用构成池的每个驱动器中的保留容量、而不是热备用驱动器。

====


== 什么是保留容量？

保留容量是指池中为支持潜在驱动器故障而预留的容量(驱动器数量)。

创建池时、系统会根据池中的驱动器数量自动预留默认保留容量。

池会在重建期间使用保留容量、而卷组则会出于相同目的使用热备用驱动器。与热备用驱动器相比、保留容量方法有所改进、因为它可以更快地进行重建。对于热备用驱动器、保留容量会分布在池中的多个驱动器上、而不是分布在一个驱动器上、因此您不会受到一个驱动器的速度或可用性的限制。



== 为什么要从逻辑上更换驱动器？

如果某个驱动器发生故障或您出于任何其他原因需要更换它、并且您的存储阵列中有一个未分配的驱动器、则可以从逻辑上将故障驱动器替换为未分配的驱动器。如果您没有未分配的驱动器、则可以改用物理方式更换该驱动器。

原始驱动器中的数据将复制或重建到替代驱动器上。



== 在何处可以查看正在重建的驱动器的状态？

您可以从"正在执行的操作"信息板查看驱动器重建状态。

在主页页面中、单击右上角的*查看正在进行的操作*链接。

根据驱动器的不同、完全重建可能需要相当长的时间。如果卷所有权发生变化、则可能会进行完全重建、而不是快速重建。
