---
permalink: sm-storage/faq-storage-array-settings.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= SANtricity System Manager 的存储阵列设置常见问题解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== 什么是自动负载平衡？

自动负载平衡功能可实现自动I/O平衡、并确保在两个控制器之间动态管理和平衡来自主机的传入I/O流量。

自动负载平衡功能可以随着时间的推移对负载变化做出动态响应、并自动调整卷控制器所有权、以便在工作负载在控制器之间移动时更正任何负载不平衡问题、从而改进了I/O资源管理。

系统会持续监控每个控制器的工作负载、并在主机上安装的多路径驱动程序的配合下、在必要时自动实现平衡。在控制器之间自动重新平衡工作负载时、存储管理员无需再承担手动调整卷控制器所有权以适应存储阵列上的负载变化的负担。

启用自动负载平衡后、它将执行以下功能：

* 自动监控和平衡控制器资源利用率。
* 根据需要自动调整卷控制器所有权、从而优化主机和存储阵列之间的I/O带宽。


[NOTE]
====
分配给使用控制器SSD缓存的任何卷均不符合自动负载平衡传输的条件。

====


== 什么是控制器缓存？

控制器缓存是一种物理内存空间、可简化两种类型的I/O (输入/输出)操作：控制器和主机之间以及控制器和磁盘之间。

对于读写数据传输、主机和控制器通过高速连接进行通信。但是、从控制器后端到磁盘的通信速度较慢、因为磁盘是相对较慢的设备。

当控制器缓存接收数据时、控制器向主机应用程序确认它现在保存数据。这样、主机应用程序就无需等待I/O写入磁盘。相反、应用程序可以继续运行。服务器应用程序也可以轻松访问缓存的数据、从而无需额外的磁盘读取即可访问数据。

控制器缓存会通过多种方式影响存储阵列的整体性能：

* 缓存可用作缓冲区、因此无需同步主机和磁盘数据传输。
* 用于从主机执行读取或写入操作的数据可能位于先前操作的缓存中、因此无需访问磁盘。
* 如果使用了写入缓存、则主机可以在将先前写入操作中的数据写入磁盘之前发送后续写入命令。
* 如果启用了缓存预取、则会优化顺序读取访问。缓存预取使读取操作更有可能在缓存中找到其数据、而不是从磁盘读取数据。


[CAUTION]
====
*可能丢失数据*-如果启用*不使用电池的写入缓存*选项并且没有通用电源进行保护、则可能会丢失数据。此外、如果您没有控制器电池、并且启用了*无电池写入缓存*选项、则可能会丢失数据。

====


== 什么是缓存刷新？

当缓存中未写入的数据量达到某个级别时、控制器会定期将缓存的数据写入驱动器。此写入过程称为"刷新"。

控制器使用两种算法来刷新缓存：基于需求和基于年龄。控制器使用基于需求的算法、直到缓存的数据量降至缓存刷新阈值以下。默认情况下、当80%的缓存正在使用时、将开始刷新。

在System Manager中、您可以设置"开始`S请求缓存刷新`"阈值、以便最适合您环境中使用的I/O类型。在以写入操作为主的环境中、您应将"开始需求缓存刷新`S`"百分比设置为高、以增加缓存处理任何新写入请求而无需转到磁盘的可能性。高百分比设置会限制缓存刷新的数量、以使更多数据保留在缓存中、从而增加缓存命中的几率。

在I/O不稳定(发生数据突发)的环境中、您可以使用低缓存刷新、以便系统在数据突发之间频繁地刷新缓存。在处理各种负载的多样化I/O环境中、或者在负载类型未知时、将阈值设置为50%、以作为一个良好的中间地带。请注意、如果您选择的起始百分比低于80%、则性能可能会降低、因为主机读取所需的数据可能不可用。选择较低的百分比还会增加保持缓存级别所需的磁盘写入次数、从而增加系统开销。

基于期限的算法指定写入数据在符合向磁盘转储的条件之前可以保留在缓存中的时间段。在达到缓存刷新阈值之前、控制器会使用基于期限的算法。默认值为10秒、但此时间段仅在非活动期间计算在内。您不能在System Manager中修改刷新计时、而是必须在命令行界面(CLI)中使用*设置存储阵列*命令。

[CAUTION]
====
*可能丢失数据*-如果启用*不使用电池的写入缓存*选项并且没有通用电源进行保护、则可能会丢失数据。此外、如果您没有控制器电池、并且启用了*无电池写入缓存*选项、则可能会丢失数据。

====


== 什么是缓存块大小？

存储阵列的控制器将其缓存组织为"块"、这些块是一个内存块、大小可以为8、16、32 KiB。存储系统上的所有卷共享相同的缓存空间；因此、这些卷只能具有一个缓存块大小。

应用程序使用不同的块大小、这可能会影响存储性能。默认情况下、System Manager中的块大小为32 KiB、但您可以将该值设置为8、16、32 KiB。对于文件系统或数据库应用程序来说、较小的大小是一个不错的选择。对于需要大型数据传输、顺序I/O或高带宽(如多媒体)的应用程序来说、较大的大小是一个不错的选择。



== 何时应同步存储阵列时钟？

如果您发现SANtricity系统管理器中显示的时间戳与管理客户端(通过浏览器访问SANtricity系统管理器的计算机)中显示的时间戳不一致、则应手动同步存储阵列中的控制器时钟。只有在SANtricity系统管理器中未启用网络时间协议(Network Time Protocol、NTP)时、才需要执行此任务。

[NOTE]
====
强烈建议您使用NTP服务器、而不是手动同步时钟。NTP会使用SNTP (简单网络时间协议)自动将时钟与外部服务器同步。

====
您可以从同步存储阵列时钟对话框中检查同步状态、该对话框可从系统页面访问。如果对话框中显示的时间不匹配、请运行同步。您可以定期查看此对话框、此对话框指示控制器时钟显示的时间是否已偏离并不再同步。
