---
permalink: sm-storage/faq-volumes-workloads.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= SANtricity System Manager 卷和工作负载常见问题解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== 什么是卷？

卷是应用程序，数据库和文件系统用于存储数据的容器。它是为主机创建的逻辑组件，用于访问存储阵列上的存储。

卷是使用池或卷组中的可用容量创建的。卷已定义容量。尽管一个卷可能包含多个驱动器、但一个卷在主机中显示为一个逻辑组件。



== 当卷组中有足够的可用容量来创建卷时、为什么会出现容量过度分配错误？

选定卷组可能具有一个或多个可用容量区域。可用容量区域是指删除卷或在创建卷期间未使用所有可用容量时可能产生的可用容量。

在卷组中创建具有一个或多个可用容量区域的卷时、卷的容量将限制为该卷组中最大的可用容量区域。例如、如果一个卷组的可用容量总计为15 GiB、而最大可用容量区域为10 GiB、则可以创建的最大卷为10 GiB。

如果卷组具有可用容量区域、则卷组图形包含一个链接、指示现有可用容量区域的数量。选择此链接可显示一个弹出窗口、指示每个区域的容量。

通过整合可用容量、您可以从卷组中的最大可用容量创建更多卷。您可以使用以下方法之一整合选定卷组上的现有可用容量：

* 如果至少为卷组检测到一个可用容量区域、则"通知"区域的主页页面上将显示"整合可用容量"建议。单击*整合可用容量*链接以启动对话框。
* 您也可以选择菜单：池和卷组(不常见的任务>整合卷组可用容量)以启动此对话框。


如果要使用特定的可用容量区域、而不是最大可用容量区域、请使用命令行界面(CLI)。



== 选定工作负载对卷创建有何影响？

在创建卷期间、系统会提示您提供有关工作负载使用情况的信息。系统会使用此信息为您创建最佳卷配置、您可以根据需要对其进行编辑。或者、您也可以在卷创建序列中跳过此步骤。

工作负载是指支持应用程序的存储对象。您可以为每个应用程序定义一个或多个工作负载或实例。对于某些应用程序、系统会将工作负载配置为包含具有类似底层卷特征的卷。这些卷特征会根据工作负载支持的应用程序类型进行优化。例如、如果您创建了一个支持Microsoft SQL Server应用程序的工作负载、然后为该工作负载创建了卷、则底层卷特征将进行优化以支持Microsoft SQL Server。

* *应用程序专用*—当您使用应用程序专用工作负载创建卷时、系统可能会建议优化卷配置、以最大程度地减少应用程序工作负载I/O与应用程序实例中的其他流量之间的争用。对于为以下应用程序类型创建的工作负载、系统会自动建议并优化卷特征、例如I/O类型、区块大小、控制器所有权以及读写缓存。
+
** Microsoft®SQL Server (Microsoft®SQL Server)
** Microsoft®Exchange Server (Microsoft®Exchange Server)
** 视频监控应用程序
** VMware ESXi®(适用于要与虚拟机文件系统结合使用的卷)
+
您可以使用添加/编辑卷对话框查看建议的卷配置以及编辑、添加或删除系统建议的卷和特征。



* *其他*(或不支持特定卷创建的应用程序)— 其他工作负载使用的卷配置、您必须在创建与特定应用程序无关的工作负载时手动指定、或者如果您要在存储阵列上使用的应用程序没有内置优化功能、则必须手动指定。您必须使用添加/编辑卷对话框手动指定卷配置。




== 为什么这些卷与工作负载没有关联？

如果卷是使用命令行界面(CLI)创建的、或者已从其他存储阵列迁移(导入/导出)、则卷不会与工作负载关联。



== 为什么我无法删除选定的工作负载？

此工作负载由一组使用命令行界面(CLI)创建或从其他存储阵列迁移(导入/导出)的卷组成。因此、此工作负载中的卷不会与特定于应用程序的工作负载关联、因此无法删除此工作负载。



== 应用程序特定的工作负载如何帮助我管理存储阵列？

应用程序特定工作负载的卷特征决定了该工作负载如何与存储阵列的组件进行交互、并有助于确定给定配置下环境的性能。

应用程序是指SQL Server或Exchange等软件。您可以定义一个或多个工作负载来支持每个应用程序。



== 提供此信息如何帮助创建存储？

工作负载信息用于优化选定工作负载的卷特征、例如I/O类型、区块大小和读/写缓存。这些优化特性决定了工作负载与存储阵列组件的交互方式。

System Manager会根据您提供的工作负载信息创建相应的卷、并将其放置在系统上当前存在的可用池或卷组上。系统将根据当前选定工作负载的最佳实践创建卷并优化其特征。

在为给定工作负载创建卷之前、您可以查看建议的卷配置、并使用添加/编辑卷对话框编辑、添加或删除系统建议的卷和特征。

有关最佳实践信息、请参见您的应用程序专用文档。



== 要识别扩展的容量、我需要执行哪些操作？

如果增加卷的容量、则主机可能无法立即识别卷容量的增加。

大多数操作系统都会识别扩展后的卷容量、并在启动卷扩展后自动进行扩展。但是、有些可能不会。如果操作系统无法自动识别扩展的卷容量、则可能需要执行磁盘重新扫描或重新启动。

扩展卷容量后、必须手动增加文件系统大小以匹配。如何执行此操作取决于所使用的文件系统。

有关更多详细信息、请参见主机操作系统文档。



== 为什么我看不到所有池和/或卷组？

无法将卷移动到的任何池或卷组不会显示在列表中。

由于以下任一原因、池或卷组均不符合条件：

* 池或卷组池的数据保证(Data Assurance、DA)功能不匹配。
* 池或卷组处于非最佳状态。
* 池或卷组的容量太小。




== 什么是区块大小？

区块是指存储阵列移至条带中的下一个驱动器(RAID组)之前存储在驱动器上的数据量(以千字节(KiB)为单位)。区块大小仅适用于卷组、而不适用于池。

区块大小由其包含的数据块数定义。在确定区块大小时、您必须了解要在卷中存储的数据类型。如果应用程序通常使用小型随机读取和写入(IOPS)、则较小的区块大小通常效果会更好。或者、如果应用程序具有较大的顺序读取和写入(吞吐量)、则较大的区块大小通常会更好。

无论应用程序使用小型随机读取和写入还是大型顺序读取和写入、如果区块大小大于典型的数据块区块大小、存储阵列的性能都会更高。这通常可以使驱动器更轻松、更快地访问数据、这对于提高存储阵列性能非常重要。



=== IOPS性能非常重要的环境

在每秒I/O操作数(IOPS)环境中、如果使用的区块大小大于读取/写入到驱动器的典型数据块大小("`chunk`")、则存储阵列的性能会更好。这样可确保每个区块写入一个驱动器。



=== 吞吐量非常重要的环境

在吞吐量环境中、数据区块大小应为数据驱动器总数的偶数部分、也应为典型数据区块大小(I/O大小)。这样、数据就会作为一个条带在卷组中的驱动器之间分布、从而加快读取和写入速度。



== 什么是首选控制器所有权？

首选控制器所有权用于定义指定为卷的拥有或主控制器的控制器。

控制器所有权非常重要、应仔细规划。对于总I/O、控制器应尽可能保持平衡。

例如、如果一个控制器主要读取大型连续数据块、而另一个控制器具有频繁读取和写入的小型数据块、则负载会截然不同。通过了解哪些卷包含哪种类型的数据、您可以在两个控制器之间平均平衡I/O传输。



== 稍后要在何时使用分配主机选项？

如果要加快创建卷的过程、可以跳过主机分配步骤、使新创建的卷脱机初始化。

必须初始化新创建的卷。系统可以使用以下两种模式之一进行初始化：即即时可用格式(Immediate Available Format、IAF)后台初始化过程或脱机过程。

将卷映射到主机时、它会强制该组中所有初始化的卷过渡到后台初始化。此后台初始化过程允许并发主机I/O、这有时可能非常耗时。

如果未映射卷组中的任何卷、则会执行脱机初始化。脱机过程比后台进程快得多。



== 关于主机块大小要求、我需要了解哪些信息？

对于EF300和EF600系统、可以将卷设置为支持512字节或4KiB块大小(也称为"扇区大小")。您必须在创建卷期间设置正确的值。如果可能、系统会建议适当的默认值。

在设置卷块大小之前、请阅读以下限制和准则。

* 某些操作系统和虚拟机(尤其是VMware、目前)需要512字节的块大小、并且不支持4KiB、因此请确保在创建卷之前了解主机要求。通常、您可以通过将卷设置为显示4KiB块大小来实现最佳性能；但是、请确保主机支持4KiB (或"`4Kn`")块。
* 为池或卷组选择的驱动器类型还决定了支持的卷块大小、如下所示：
+
** 如果使用写入512字节块的驱动器创建卷组、则只能创建包含512字节块的卷。
** 如果使用写入4KiB块的驱动器创建卷组、则可以创建包含512字节或4KiB块的卷。


* 如果阵列具有iSCSI主机接口卡、则所有卷都将限制为512字节的块(无论卷组块大小如何)。这是由于实施了特定的硬件造成的。
* 设置块大小后、您将无法更改块大小。如果需要更改块大小、则必须删除卷并重新创建它。

