---
permalink: sm-storage/faq-systems-clusters.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= SANtricity System Manager 的主机系统和主机集群常见问题解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== 什么是主机和主机集群？

主机是指向存储阵列上的卷发送I/O的服务器。主机集群是一组主机。您可以创建一个主机集群、以便轻松地将相同的卷分配给多个主机。

您可以单独定义主机。它可以是一个独立的实体、也可以添加到主机集群中。您可以将卷分配给单个主机、也可以将主机作为主机集群的一部分、与主机集群中的其他主机共享对一个或多个卷的访问权限。

主机集群是您在SANtricity 系统管理器中创建的逻辑实体。您必须先将主机添加到主机集群、然后才能分配卷。



== 为什么需要创建主机集群？

如果要使两个或更多主机共享对同一组卷的访问、则需要创建主机集群。通常、各个主机都安装了集群软件来协调卷访问。



== 如何知道哪种主机操作系统类型正确？

主机操作系统类型字段包含主机的操作系统。您可以从下拉列表中选择建议的主机类型。

下拉列表中显示的主机类型取决于存储阵列型号和固件版本。最新版本会首先显示最常见的选项、最有可能是最合适的选项。此列表中的显示并不表示完全支持此选项。

[NOTE]
====
有关主机支持的详细信息、请参见 https://imt.netapp.com/matrix/#welcome["NetApp 互操作性表工具"^]。

====
列表中可能会显示以下某些主机类型：

[cols="35h,~"]
|===
| 主机操作系统类型 | 操作系统(OS)和多路径驱动程序 


 a| 
Linux DM-MP (内核3.10或更高版本)
 a| 
支持使用设备映射程序多路径故障转移解决方案 和3.10或更高版本内核的Linux操作系统。



 a| 
VMware ESXi
 a| 
支持使用VMware内置存储阵列类型策略模块sap_alUA运行原生 多路径插件(NMP)架构的VMware ESXi操作系统。



 a| 
Windows (集群或非集群)
 a| 
支持未运行ATTO多路径驱动程序的Windows集群或非集群配置。



 a| 
ATTO集群(所有操作系统)
 a| 
支持使用ATTO Technology、Inc.多路径驱动程序的所有集群配置。



 a| 
Linux (Veritas DMP)
 a| 
支持使用Veritas DMP多路径解决方案 的Linux操作系统。



 a| 
Linux (ATTO)
 a| 
支持使用ATTO Technology、Inc.多路径驱动程序的Linux操作系统。



 a| 
Mac OS (ATTO)
 a| 
支持使用ATTO Technology、Inc.多路径驱动程序的Mac OS版本。



 a| 
Windows (ATTO)
 a| 
支持使用ATTO Technology、Inc.多路径驱动程序的Windows操作系统。



 a| 
IBM服务
 a| 
支持IBM SAN卷控制器配置。



 a| 
出厂默认值
 a| 
为存储阵列的初始启动预留。如果您的主机操作系统类型设置为出厂默认值、请将其更改为与所连接主机上运行的主机操作系统和多路径驱动程序匹配。



 a| 
Linux DM-MP (内核3.9或更早版本)
 a| 
支持使用具有3.9或更早内核的设备映射程序多路径故障转移解决方案 的Linux操作系统。



 a| 
窗口集群(已弃用)
 a| 
如果主机操作系统类型设置为此值、请改用Windows (集群或非集群)设置。

|===


== 什么是HBA和适配器端口？

主机总线适配器(HBA)是驻留在主机中并包含一个或多个主机端口的板。主机端口是主机总线适配器(HBA)上的一个端口、用于与控制器建立物理连接并用于I/O操作。

HBA上的适配器端口称为主机端口。大多数HBA都有一个或两个主机端口。HBA具有唯一的全球通用标识符(World Wide Identifier、WWID)、每个HBA主机端口都有一个唯一的WWID。通过SANtricity系统管理器手动创建主机时、可以使用主机端口标识符将相应的HBA与物理主机相关联。



== 如何将主机端口与主机匹配？

如果要手动创建主机、则必须首先使用主机上可用的相应主机总线适配器(HBA)实用程序来确定与主机中安装的每个HBA关联的主机端口标识符。

获得此信息后、请从创建主机对话框中提供的列表中选择已登录到存储阵列的主机端口标识符。

[NOTE]
====
确保为要创建的主机选择适当的主机端口标识符。如果关联的主机端口标识符不正确、则可能会发生原因 从另一台主机意外访问此数据。

====


== 如何创建CHAP密码？

如果在连接到存储阵列的任何iSCSI主机上设置质询握手身份验证协议(CHAP)身份验证、则必须为每个iSCSI主机重新输入该启动程序CHAP密钥。

为此、您可以在创建主机操作中使用System Manager、也可以通过查看/编辑设置选项使用System Manager。

如果使用CHAP相互身份验证、则还必须在设置页面中为存储阵列定义目标CHAP密钥、然后在每个iSCSI主机上重新输入该目标CHAP密钥。



== 默认集群是什么？

默认集群是一个系统定义的实体、它允许登录到存储阵列的任何未关联主机端口标识符访问分配给默认集群的卷。未关联的主机端口标识符是指与特定主机没有逻辑关联、但实际安装在主机中并登录到存储阵列的主机端口。

[NOTE]
====
如果您希望主机对存储阵列中的某些卷具有特定访问权限、则必须使用默认集群。而是必须将主机端口标识符与其对应的主机相关联。此任务可以在创建主机操作期间手动完成。然后、将卷分配给单个主机或主机集群。

====
在特殊情况下、如果外部存储环境有利于允许连接到存储阵列的所有主机和所有已登录主机端口标识符都能够访问所有卷、则应使用默认集群(完全访问模式) 而不是专门使存储阵列或用户界面知道这些主机。

最初、您只能通过命令行界面(CLI)将卷分配给默认集群。但是、在将至少一个卷分配给默认集群后、此实体(称为默认集群)将显示在用户界面中、您可以在此界面中管理此实体。



== 什么是主机连接报告？

启用主机连接报告后、存储阵列会持续监控控制器与已配置主机之间的连接、然后在连接中断时向您发出警报。

如果主机出现松动、损坏或缺失的缆线或其他问题、可能会中断连接。在这些情况下、系统可能会打开Recovery Guru消息：

* "Host Redundancy Lost"(主机冗余丢失)*—如果任一控制器无法与主机进行通信、则会打开。
* *主机类型不正确*—如果在存储阵列上错误指定主机类型、则会打开此窗口、从而可能导致故障转移问题。


如果重新启动控制器所需时间可能超过连接超时、您可能需要禁用主机连接报告。禁用此功能将禁止恢复消息。

[NOTE]
====
禁用主机连接报告还会禁用自动负载平衡、从而监控和平衡控制器资源使用情况。但是、如果重新启用主机连接报告、则不会自动重新启用自动负载平衡功能。

====