---
permalink: sm-storage/faq-remote-storage.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= SANtricity System Manager 远程存储常见问题解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== 在创建远程存储连接之前、我需要了解哪些信息？

要配置远程存储功能、您必须通过iSCSI直接连接远程设备和目标存储系统。

要设置iSCSI系统连接、请参见：

* link:../sm-hardware/configure-iscsi-ports-hardware.html["配置iSCSI端口"]
* https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["远程存储技术报告"^]




== 为什么系统会提示我删除远程卷？

当远程卷达到其最大数量时、存储系统会自动检测任何未使用的远程卷并提示您删除这些卷。

在某些情况下、未使用的远程卷在创建过程中不会被清理。在开始任何其他导入操作之前、请验证您的系统是否最佳且网络连接是否稳定。



== 为什么我看不到目标阵列上的所有卷？

在为远程存储功能配置导入时、您可能会注意到、由于块大小、容量或卷可用性、某些卷不会显示在目标候选卷列表中。

要显示在列表中、卷候选项必须具有：

* 容量等于或大于远程卷。
* 与远程卷相同的块大小。
* 当前最佳状态。


如果候选卷具有以下特性、则这些候选卷将从列表中排除：

* 以下任意关系：卷副本、快照或镜像。
* 正在执行重新配置操作。
* 映射到其他设备(主机或主机集群)。
* 已启用读取闪存缓存。




== 需要了解有关导入中的远程卷的哪些信息？

使用远程存储功能时、请注意、远程卷是数据源。

导入过程中、数据将从远程卷传输到目标存储系统上的目标卷。这两个卷必须具有匹配的块大小。



== 在开始远程存储导入之前、我需要了解哪些信息？

通过远程存储功能、您可以将数据从远程存储系统复制到本地E系列存储系统上的卷。在使用此功能之前、请查看以下准则。



=== Configuration

在创建远程存储导入之前、您必须完成以下操作并验证以下条件：

* 确保本地E系列存储系统的每个控制器都与远程存储系统建立了iSCSI连接。
* 在本地E系列存储系统上、为导入操作创建一个目标卷。确保卷的容量等于或大于源卷、块大小与源卷匹配且未映射。请参见 link:create-volumes.html["创建卷"]。
* 使用iSCSI限定名称(IQN)将本地E系列存储系统设置为远程系统上的主机。您可以从菜单：设置[系统> iSCSI设置>目标IQN]查看IQN。此外、请务必根据所使用的系统设置适当的主机类型。
* 停止所有I/O、卸载任何文件系统、并删除对远程存储系统上选定卷的主机或应用程序的任何分配。
* 将卷分配给远程存储系统、并分配给新创建的本地E系列存储系统主机。
* 从远程存储系统收集以下信息、以便创建导入：
+
** iSCSI限定名称(IQN)
** iSCSI IP地址
** 源数据所在的远程存储设备的LUN编号


* 导入过程开始后、整个本地目标卷将被复制的数据覆盖。创建导入后、写入本地目标卷的任何新数据都会传播到远程存储设备上的卷。因此、建议您在开始导入过程之前备份远程存储系统上的卷。




=== 导入过程

以下步骤概述了导入过程。

. 访问System Manager界面、然后转到*远程存储*页面。选择*导入*以开始创建新的导入。有关详细说明、请参见 link:rtv-import-remote-storage.html["导入远程存储"]。
+
如果要执行脱机导入、请在导入完成后再映射目标卷。

. 监控导入进度。
+
导入开始后、便可映射目标卷。完成导入操作所需的时间取决于远程存储设备(源卷)的大小、导入的优先级设置以及两个存储系统及其关联卷上的I/O负载量。

+
导入完成后、目标卷将与源卷重复。

. 准备好中断映射关系后、从*正在执行的操作*面板对导入对象执行*断开连接*。


导入断开后、本地目标的性能将恢复正常、不再受远程连接的影响。



=== 限制

远程存储功能具有以下限制：

* 必须禁用镜像。
* E 系列系统上的目标卷不能具有快照。
* 在启动导入之前，不得将 E 系列系统上的目标卷映射到任何主机。
* E 系列系统上的目标卷必须已禁用资源配置。
* 不支持将远程存储卷直接映射到一个或多个主机。
* 不支持 Web 服务代理。
* 不支持 iSCSI CHAP 密码。
* 不支持 SMcli 。
* 不支持 VMware 数据存储库。
* 如果存在导入对，则一次只能升级关系 / 导入对中的一个存储系统。




=== 追加信息

有关远程存储功能的详细信息、请参见 https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["远程存储技术报告"^]。
