---
permalink: sm-storage/faq-pools-volume-groups.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= SANtricity System Manager 的池和卷组常见问题解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== 什么是卷组？

卷组是具有共享特征的卷的容器。卷组已定义容量和RAID级别。您可以使用卷组创建一个或多个可供主机访问的卷。(您可以从卷组或池创建卷。)



== 什么是池？

池是指一组按逻辑分组的驱动器。您可以使用池创建一个或多个可供主机访问的卷。(您可以从池或卷组创建卷。)

通过池、管理员无需监控每个主机上的使用情况、即可确定存储空间何时可能用尽、并避免传统的磁盘大小调整中断。当池即将耗尽时、可以无中断地向池中添加更多驱动器、并且容量增长对主机是透明的。

对于池、数据会自动重新分布以保持平衡。通过在池中分布奇偶校验信息和备用容量、可以使用池中的每个驱动器重建故障驱动器。此方法不使用专用热备用驱动器、而是在整个池中保留保留(备用)容量。驱动器发生故障时、系统会读取其他驱动器上的区块以重新创建数据。然后、选择一个新驱动器来写入故障驱动器上的每个区块、以便在驱动器之间保持数据分布。



== 什么是预留容量？

预留容量是指物理分配的容量、用于存储Snapshot映像、一致性组成员卷和镜像对卷等副本服务对象的数据。

与复制服务操作关联的预留容量卷位于池或卷组中。您可以从池或卷组创建预留容量。



== 什么是FDE/Fips安全性？

FDE/Fips安全性是指在写入期间对数据进行加密的安全驱动器、以及在读取期间使用唯一加密密钥对数据进行解密的驱动器。这些支持安全的驱动器可防止未经授权访问从存储阵列中物理删除的驱动器上的数据。

支持安全的驱动器可以是全磁盘加密(Full Disk Encryption、FDE)驱动器、也可以是联邦信息处理标准(Federal Information Processing Standard、FIPS)驱动器。FIPS驱动器已通过认证测试。

[NOTE]
====
对于需要FIPS支持的卷、请仅使用FIPS驱动器。在卷组或池中混用FIPS和FDE驱动器将导致所有驱动器被视为FDE驱动器。此外、FDE驱动器不能添加到纯FIPS卷组或池中或用作备用磁盘。

====


== 什么是冗余检查？

冗余检查可确定池或卷组中卷上的数据是否一致。如果池或卷组中的某个驱动器发生故障、则可以使用冗余数据快速重建替代驱动器上的信息。

一次只能对一个池或卷组执行此检查。卷冗余检查将执行以下操作：

* 扫描RAID 3卷、RAID 5卷或RAID 6卷中的数据块、然后检查每个块的冗余信息。(只能使用命令行界面将RAID 3分配给卷组。)
* 比较RAID 1镜像驱动器上的数据块。
* 如果控制器固件确定数据不一致、则返回冗余错误。


[NOTE]
====
立即对同一个池或卷组运行冗余检查可能会出现发生原因 错误。要避免此问题、请等待一到两分钟、然后再对同一个池或卷组运行另一个冗余检查。

====


== 池和卷组之间有何区别？

池与卷组类似、但存在以下差异。

* 池中的数据随机存储在池中的所有驱动器上、而卷组中的数据则存储在同一组驱动器上。
* 驱动器发生故障时、池的性能下降较小、重建所需时间也较短。
* 池具有内置的保留容量、因此不需要专用的热备用驱动器。
* 池允许对大量驱动器进行分组。
* 池不需要指定的RAID级别。




== 为什么要手动配置池？

以下示例说明了您希望手动配置池的原因。

* 如果存储阵列上有多个应用程序、并且不希望它们争用相同的驱动器资源、则可以考虑手动为一个或多个应用程序创建一个较小的池。
+
您只能分配一个或两个卷、而不能将工作负载分配给一个大型池、该池包含许多卷、可用于分布数据。手动创建专用于特定应用程序工作负载的单独池可以提高存储阵列操作的执行速度、并减少争用。

+
要手动创建池、请选择*存储*、然后选择*池和卷组*。从所有容量选项卡中、单击菜单：创建[池]。

* 如果存在多个驱动器类型相同的池、则会显示一条消息、指示System Manager无法自动为池推荐驱动器。但是、您可以手动将驱动器添加到现有池。
+
要手动将驱动器添加到现有池：从"池和卷组"页面中、选择该池、然后单击*添加容量*。





== 容量警报为何重要？

容量警报指示何时向池添加驱动器。池需要足够的可用容量才能成功执行存储阵列操作。您可以通过将SANtricity系统管理器配置为在池的可用容量达到或超过指定百分比时发送警报来防止这些操作中断。

在使用*池自动配置*选项或*创建池*选项创建池时、可以设置此百分比。如果选择自动选项、则默认设置会自动确定何时接收警报通知。如果您选择手动创建池、则可以确定警报通知设置；如果愿意、也可以接受默认设置。您可以稍后在菜单：Settings[警报]中调整这些设置。

[NOTE]
====
当池中的可用容量达到指定百分比时、将使用您在警报配置中指定的方法发送警报通知。

====


== 为什么我无法提高我的保存能力？

如果已在所有可用容量上创建卷、则可能无法增加保留容量。

保留容量是指池中为支持潜在驱动器故障而预留的容量(驱动器数量)。创建池时、系统会根据池中的驱动器数量自动预留默认保留容量。如果已在所有可用容量上创建卷、则在不通过添加驱动器或删除卷向池添加容量的情况下、无法增加保留容量。

您可以从*池和卷组*更改保留容量。选择要编辑的池。单击*查看/编辑设置*、然后选择*设置*选项卡。

[NOTE]
====
保留容量指定为多个驱动器、即使实际保留容量分布在池中的驱动器之间也是如此。

====


== 可以从池中删除的驱动器数量是否有限制？

SANtricity系统管理器会为您可以从池中删除的驱动器数量设置限制。

* 不能将池中的驱动器数量减少到少于11个驱动器。
* 如果池中没有足够的可用容量来容纳已删除驱动器中的数据、则在将该数据重新分配到池中的其余驱动器时、您无法删除驱动器。
* 一次最多可以删除60个驱动器。如果选择的驱动器超过60个、则删除驱动器选项将被禁用。如果需要删除60个以上的驱动器、请重复执行删除驱动器操作。




== 驱动器支持哪些介质类型？

支持以下介质类型：硬盘驱动器(HDD)和固态磁盘(SSD)。



== 为什么某些驱动器不显示？

在添加容量对话框中、并非所有驱动器都可用于向现有池或卷组添加容量。

驱动器不符合条件的原因如下：

* 驱动器必须已取消分配、并且未启用安全保护。驱动器已属于另一个池、另一个卷组或配置为热备用磁盘不符合条件。如果某个驱动器未分配但已启用安全保护、则必须手动擦除该驱动器才能使其符合条件。
* 处于非最佳状态的驱动器不符合条件。
* 如果驱动器容量太小、则不符合条件。
* 驱动器介质类型必须在池或卷组中匹配。您不能混用以下内容：
+
** 采用固态磁盘(SSD)的硬盘驱动器(HDD)
** 采用SAS驱动器的NVMe
** 卷块大小为512字节和4 KiB的驱动器


* 如果池或卷组包含所有支持安全的驱动器、则不会列出不支持安全的驱动器。
* 如果池或卷组包含所有联邦信息处理标准(FIPS)驱动器、则不会列出非FIPS驱动器。
* 如果池或卷组包含支持所有数据保证(DA)的驱动器、并且池或卷组中至少有一个已启用DA的卷、则不支持DA的驱动器将不符合条件、因此无法将其添加到该池或卷组。但是、如果池或卷组中没有启用了DA的卷、则可以将不支持DA的驱动器添加到该池或卷组中。如果决定混用这些驱动器、请记住、您不能创建任何已启用DA的卷。


[NOTE]
====
可以通过添加新驱动器或删除池或卷组来增加存储阵列中的容量。

====


== 如何维护磁盘架/抽屉丢失保护？

要为池或卷组维护磁盘架/抽屉丢失保护、请使用下表中指定的标准。

[cols="1a,1a,1a"]
|===
| 级别 | 磁盘架/抽屉丢失保护的标准 | 所需的最小磁盘架/抽屉数 


 a| 
池
 a| 
对于磁盘架、池中一个磁盘架中的驱动器不能超过两个。

对于抽盒、池中每个抽盒中必须包含相同数量的驱动器。
 a| 
6个用于磁盘架

5个用于抽盒



 a| 
RAID 6
 a| 
卷组在一个磁盘架或抽屉中包含的驱动器不超过两个。
 a| 
3.



 a| 
RAID 3或RAID 5
 a| 
卷组中的每个驱动器都位于一个单独的磁盘架或抽屉中。
 a| 
3.



 a| 
RAID 1
 a| 
镜像对中的每个驱动器都必须位于单独的磁盘架或抽屉中。
 a| 
2.



 a| 
RAID 0
 a| 
无法实现磁盘架/抽屉丢失保护。
 a| 
不适用

|===
[NOTE]
====
如果池或卷组中的驱动器已发生故障、则不会保持磁盘架/抽屉丢失保护。在这种情况下、如果无法访问某个驱动器架或抽盒、进而无法访问池或卷组中的另一个驱动器、则会导致数据丢失。

====


== 池和卷组的最佳驱动器定位是什么？

创建池和卷组时、请确保在上部和下部驱动器插槽之间平衡驱动器选择。

对于EF600和EF300控制器、驱动器插槽0-11连接到一个PCI网桥、而插槽12-23连接到另一个PCI网桥。为了获得最佳性能、您应平衡驱动器选择、使其包含上插槽和下插槽中的驱动器数量大致相等。这种定位可确保卷不会比需要时更早地达到带宽限制。



== 哪种RAID级别最适合我的应用程序？

要最大程度地提高卷组的性能、必须选择适当的RAID级别。您可以通过了解正在访问卷组的应用程序的读写百分比来确定适当的RAID级别。使用性能页面可获取这些百分比。



=== RAID级别和应用程序性能

RAID依靠一系列称为_levels_的 配置来确定如何从驱动器写入和检索用户和冗余数据。每个RAID级别提供不同的性能功能。由于RAID 5和RAID 6配置具有出色的读取性能、读取百分比较高的应用程序在使用RAID 5卷或RAID 6卷时性能良好。

读取百分比较低(写入密集型)的应用程序在RAID 5卷或RAID 6卷上的性能较差。性能下降是由于控制器将数据和冗余数据写入RAID 5卷组或RAID 6卷组中的驱动器的方式造成的。

根据以下信息选择RAID级别。

* RAID 0*

* * 问题描述 *
+
** 非冗余条带化模式。


* *工作原理*
+
** RAID 0可在卷组中的所有驱动器之间对数据进行条带化。


* *数据保护功能*
+
** 不建议使用RAID 0来满足高可用性需求。RAID 0更适合非关键数据。
** 如果卷组中的一个驱动器发生故障、则所有关联卷都会发生故障、并且所有数据都将丢失。


* *驱动器编号要求*
+
** RAID级别0至少需要一个驱动器。
** RAID 0卷组可以包含30个以上的驱动器。
** 您可以创建一个包含存储阵列中所有驱动器的卷组。




* RAID 1或RAID 10*

* * 问题描述 *
+
** 条带化/镜像模式。


* *工作原理*
+
** RAID 1使用磁盘镜像将数据同时写入两个重复磁盘。
** RAID 10使用驱动器条带化功能在一组镜像驱动器对之间条带化数据。


* *数据保护功能*
+
** RAID 1和RAID 10可提供高性能和最佳数据可用性。
** RAID 1和RAID 10使用驱动器镜像从一个驱动器精确复制到另一个驱动器。
** 如果驱动器对中的一个驱动器发生故障、存储阵列可以立即切换到另一个驱动器、而不会丢失任何数据或服务。
** 单个驱动器故障会导致关联卷降级。镜像驱动器允许访问数据。
** 卷组中的驱动器对故障会导致所有关联卷出现故障、并且可能会发生数据丢失。


* *驱动器编号要求*
+
** RAID 1至少需要两个驱动器：一个驱动器用于用户数据、一个驱动器用于镜像数据。
** 如果选择四个或更多驱动器、则会在卷组中自动配置RAID 10：两个驱动器用于用户数据、两个驱动器用于镜像数据。
** 卷组中的驱动器数量必须为偶数。如果驱动器数量不是偶数、并且还有一些未分配的驱动器、请转到*池和卷组*向卷组添加其他驱动器、然后重试此操作。
** RAID 1和RAID 10卷组可以包含30个以上的驱动器。可以创建一个包含存储阵列中所有驱动器的卷组。




* RAID 5*

* * 问题描述 *
+
** 高I/O模式。


* *工作原理*
+
** 用户数据和冗余信息(奇偶校验)在驱动器之间进行条带化。
** 一个驱动器的等效容量用于提供冗余信息。


* *数据保护功能*
+
** 如果RAID 5卷组中的一个驱动器发生故障、则所有关联卷都会降级。冗余信息允许仍访问数据。
** 如果RAID 5卷组中的两个或更多驱动器发生故障、则所有关联卷都会发生故障、并且所有数据都将丢失。


* *驱动器编号要求*
+
** 卷组中必须至少有三个驱动器。
** 通常、卷组中最多只能包含30个驱动器。




* RAID 6*

* * 问题描述 *
+
** 高I/O模式。


* *工作原理*
+
** 用户数据和冗余信息(双奇偶校验)在驱动器之间进行条带化。
** 两个驱动器的等效容量用于提供冗余信息。


* *数据保护功能*
+
** 如果RAID 6卷组中的一个或两个驱动器发生故障、则所有关联卷都会降级、但冗余信息仍允许访问数据。
** 如果RAID 6卷组中的三个或更多驱动器发生故障、则所有关联卷都会发生故障、并且所有数据都将丢失。


* *驱动器编号要求*
+
** 卷组中必须至少有五个驱动器。
** 通常、卷组中最多只能包含30个驱动器。




[NOTE]
====
您不能更改池的RAID级别。用户界面会自动将池配置为RAID 6。

====


=== RAID级别和数据保护

RAID 1、RAID 5和RAID 6向驱动器介质写入冗余数据以实现容错。冗余数据可以是数据的副本(镜像)、也可以是从数据派生的错误更正代码。如果驱动器发生故障、您可以使用冗余数据快速重建替代驱动器上的信息。

您可以在一个卷组中配置一个RAID级别。该卷组的所有冗余数据都存储在该卷组中。卷组的容量等于成员驱动器的聚合容量减去为冗余数据预留的容量。冗余所需的容量取决于使用的RAID级别。



== 什么是数据保证？

数据保证(Data Assurance、DA)实施了T10保护信息(Protection Information、PI)标准、该标准可通过检查并更正在I/O路径上传输数据时可能发生的错误来提高数据完整性。

通常情况下、使用数据保证功能将检查控制器和驱动器之间I/O路径的部分。DA 功能在池和卷组级别提供。

启用此功能后、存储阵列会向卷中的每个数据块附加错误检查代码(也称为循环冗余检查或CRC)。移动数据块后、存储阵列会使用这些CRC代码来确定传输期间是否发生任何错误。可能损坏的数据既不会写入磁盘、也不会返回到主机。如果要使用DA功能、请在创建新卷时选择一个支持DA的池或卷组(在Pool and volume group candidates表中、查找"DA"旁边的"Yes")。

请确保使用支持DA的I/O接口将这些启用了DA的卷分配给主机。支持DA的I/O接口包括光纤通道、SAS、基于TCP/IP的iSCSI、NVMe/FC、NVMe/IB、 NVMe/RoCE和iSER over InfiniBand (适用于RDMA/IB的iSCSI扩展)。基于InfiniBand的SRP不支持DA。



== 什么是安全功能(驱动器安全)？

驱动器安全性是一项功能、可防止在从存储阵列中删除启用了安全功能的驱动器上的数据时未经授权进行访问。这些驱动器可以是全磁盘加密(Full Disk Encryption、FDE)驱动器、也可以是联邦信息处理标准(Federal Information Processing Standard、FIPS)驱动器。



== 增加预留容量需要了解哪些信息？

通常、当您收到警告、指出预留容量可能会变满时、应增加容量。您只能以8 GiB为增量增加预留容量。

* 池或卷组中必须有足够的可用容量、以便可以根据需要进行扩展。
+
如果任何池或卷组上没有可用容量、则可以将未使用的驱动器形式的未分配容量添加到池或卷组中。

* 池或卷组中的卷必须处于最佳状态、并且不能处于任何修改状态。
* 要用于增加容量的池或卷组中必须存在可用容量。
* 您不能增加只读快照卷的预留容量。只有读写Snapshot卷才需要预留容量。


对于快照操作、预留容量通常为基础卷的40%。对于异步镜像操作、预留容量通常为基础卷的20%。如果您认为基础卷会发生许多更改、或者存储对象的复制服务操作的预计预期寿命很长、请使用较高的百分比。



== 为什么我不能选择其他要减少的金额？

您只能将预留容量减少到用于增加的容量。只能按与添加成员卷相反的顺序删除为其预留的容量。

如果存在以下条件之一、则不能减少存储对象的预留容量：

* 存储对象是镜像对卷。
* 存储对象仅包含一个用于预留容量的卷。存储对象必须至少包含两个用于预留容量的卷。
* 存储对象是已禁用的快照卷。
* 存储对象包含一个或多个关联的快照映像。


您只能按与添加卷相反的顺序删除预留容量卷。

您不能减少只读快照卷的预留容量、因为它没有任何关联的预留容量。只有读写Snapshot卷才需要预留容量。



== 为什么需要为每个成员卷预留容量？

快照一致性组中的每个成员卷都必须有自己的预留容量、才能将主机应用程序所做的任何修改保存到基础卷、而不会影响引用的一致性组快照映像。通过预留容量、主机应用程序可以对成员卷中指定为读写的数据副本进行写入访问。

主机无法直接读取或写入一致性组快照映像。而是使用快照映像仅保存从基础卷捕获的数据。

在创建指定为读写的一致性组快照卷期间、System Manager会为一致性组中的每个成员卷创建一个预留容量。通过此预留容量、主机应用程序可以对一致性组快照映像中所含数据的副本进行写入访问。



== 如何查看和解释所有SSD缓存统计信息？

您可以查看SSD缓存的标称统计信息和详细统计信息。标称统计信息是详细统计信息的一部分。

只有在将所有SSD统计信息导出到`.csv`文件时、才能查看详细统计信息。在查看和解释统计信息时、请记住、某些解释是通过结合统计信息得出的。



=== 标称统计信息

要查看SSD缓存统计信息、请选择菜单：存储(池和卷组)。选择要查看统计信息的SSD缓存、然后选择菜单：更多(查看统计信息)。标称统计信息显示在"查看SSD缓存统计信息"对话框中。

以下列表包含标称统计信息、这些统计信息是详细统计信息的一部分。

[cols="25h,~"]
|===
| 标称统计信息 | Description 


 a| 
读取/写入
 a| 
主机从启用了SSD缓存的卷读取数据或主机写入数据的总数。比较读取与写入之间的关系。要实现有效的SSD缓存操作、读取次数必须大于写入次数。读取与写入的比率越大、缓存的运行就越好。



 a| 
缓存命中
 a| 
缓存命中数的计数。



 a| 
缓存命中率(%)
 a| 
派生自缓存命中/(读取+写入)。对于有效的SSD缓存操作、缓存命中百分比应大于50%。少量数字可能表示以下几个方面：

* 读取与写入的比率太小
* 不会重复读取
* 缓存容量太小




 a| 
缓存分配(%)
 a| 
分配的SSD缓存存储容量、以此控制器可用的SSD缓存存储的百分比表示。源自已分配的字节/可用字节。缓存分配百分比通常显示为100%。如果此数字小于100%、则表示缓存尚未预热或SSD缓存容量大于所访问的所有数据。在后一种情况下、较小的SSD缓存容量可以提供相同级别的性能。请注意、这并不表示缓存的数据已放置到SSD缓存中；它只是一个准备步骤、然后才能将数据放置到SSD缓存中。



 a| 
缓存利用率(%)
 a| 
包含已启用卷中的数据的SSD缓存存储容量、以分配的SSD缓存存储百分比表示。此值表示SSD缓存的利用率或密度、该缓存是从用户数据字节/已分配字节派生的。缓存利用率百分比通常低于100%、可能要低得多。此数字显示已填充缓存数据的SSD缓存容量百分比。此数字低于100%、因为SSD缓存的每个分配单元(SSD缓存块)都划分为称为子块的较小单元、这些子块在一定程度上是独立填充的。数字越高通常越好、但即使数字越小、性能也会显著提高。

|===


=== 详细统计信息

详细统计信息包括名义统计信息和其他统计信息。这些附加统计信息会与标称统计信息一起保存、但与标称统计信息不同、它们不会显示在"查看SSD缓存统计信息"对话框中。只有在将统计信息导出到`.csv`文件后、才能查看详细统计信息。

查看`.csv`文件时、请注意、详细统计信息列在标称统计信息之后：

[cols="25h,~"]
|===
| 详细统计信息 | Description 


 a| 
读取块
 a| 
主机读取中的块数。



 a| 
写入块
 a| 
主机写入的块数。



 a| 
完整命中块
 a| 
缓存命中中的块数。完整命中块表示已从SSD缓存中完全读取的块数。SSD缓存只会对完全缓存命中的操作的性能产生影响。



 a| 
部分命中
 a| 
至少有一个块(而不是所有块)位于SSD缓存中的主机读取次数。部分命中是SSD缓存*未命中*、其中从基础卷读取的结果已满足。



 a| 
Partial Hits—块
 a| 
部分命中中的块数。部分缓存命中和部分缓存命中块是由于在SSD缓存中仅包含一部分数据的操作而导致的。在这种情况下、操作必须从缓存的硬盘驱动器(HDD)卷中获取数据。SSD缓存不会为这种类型的命中带来任何性能优势。如果部分缓存命中块数高于完整缓存命中块数、则不同的I/O特征类型(文件系统、数据库或Web服务器)可以提高性能。在SSD缓存预热期间、与缓存命中相比、部分命中和未命中的数量预计会更多。



 a| 
未命中
 a| 
SSD缓存中没有块的主机读取次数。如果满足从基础卷读取的要求、则会发生SSD缓存未命中。在SSD缓存预热期间、与缓存命中相比、部分命中和未命中的数量预计会更多。



 a| 
未命中—块
 a| 
未命中的块数。



 a| 
填充操作(主机读取)
 a| 
将数据从基础卷复制到SSD缓存的主机读取次数。



 a| 
填充操作(主机读取)—块
 a| 
填充操作(主机读取)中的块数。



 a| 
填充操作(主机写入)
 a| 
将数据从基础卷复制到SSD缓存的主机写入次数。对于因写入I/O操作而未填充缓存的缓存配置设置、填充操作(主机写入)计数可能为零。



 a| 
填充操作(主机写入)—块
 a| 
填充操作(主机写入)中的块数。



 a| 
使操作失效
 a| 
数据失效或从SSD缓存中删除的次数。对于每个主机写入请求、每个具有强制单元访问(FUA)的主机读取请求、每个验证请求以及某些其他情况、都会执行缓存失效操作。



 a| 
回收操作
 a| 
SSD缓存块重新用于另一个基础卷和/或不同逻辑块寻址(Logical Block Addressing、LBA)范围的次数。为了有效地执行缓存操作、与读取和写入操作的总数相比、回收的数量必须较小。如果回收操作的数量接近读取和写入的总数、则SSD缓存将会达到最大值。需要增加缓存容量或工作负载不适合与SSD缓存一起使用。



 a| 
可用字节数
 a| 
SSD缓存中可供此控制器使用的字节数。



 a| 
已分配字节
 a| 
此控制器从SSD缓存分配的字节数。从SSD缓存分配的字节数可能为空、或者可能包含基础卷中的数据。



 a| 
用户数据字节
 a| 
SSD缓存中包含基础卷中的数据的已分配字节数。可用字节数、已分配字节数和用户数据字节数用于计算缓存分配百分比和缓存利用率百分比。

|===


== 什么是池的优化容量？

如果未分配一部分容量、SSD驱动器的使用寿命将会延长、并且最大写入性能也会提高。

对于与池关联的驱动器、未分配的容量包括池的保留容量、可用容量(卷未使用的容量)以及作为额外优化容量而预留的部分可用容量。额外的优化容量可通过减少可用容量来确保最低的优化容量级别、因此不可用于创建卷。

创建池时、系统会生成一个建议的优化容量、以便在性能、驱动器使用寿命和可用容量之间实现平衡。"池设置"对话框中的"其他优化容量"滑块可用于调整池的优化容量。调整滑块可以提高性能和驱动器磨损寿命、而不会影响可用容量、也不会影响性能和驱动器磨损寿命。

[NOTE]
====
附加优化容量滑块仅适用于EF600和EF300存储系统。

====


== 卷组的优化容量是多少？

如果未分配一部分容量、SSD驱动器的使用寿命将会延长、并且最大写入性能也会提高。

对于与卷组关联的驱动器、未分配的容量由卷组的可用容量(卷未使用的容量)以及作为优化容量预留的部分可用容量组成。额外的优化容量可通过减少可用容量来确保最低的优化容量级别、因此不可用于创建卷。

创建卷组时、系统会生成一个建议的优化容量、以便在性能、驱动器使用寿命和可用容量之间取得平衡。通过"卷组设置"对话框中的"其他优化容量"滑块、可以调整卷组的优化容量。调整滑块可以提高性能和驱动器磨损寿命、而不会影响可用容量、也不会影响性能和驱动器磨损寿命。

[NOTE]
====
附加优化容量滑块仅适用于EF600和EF300存储系统。

====


== 什么是资源配置功能？

资源配置是EF300和EF600存储阵列中提供的一项功能、可在不执行后台初始化过程的情况下立即使用卷。

资源配置卷是SSD卷组或池中的厚卷、在创建卷时会分配(分配给卷)驱动器容量、但会取消分配(取消映射)驱动器块。相比之下、在传统厚卷中、所有驱动器块都会在后台卷初始化操作期间映射或分配、以便初始化数据保证保护信息字段并使每个RAID条带中的数据和RAID奇偶校验保持一致。对于资源配置的卷、不会进行有时间限制的后台初始化。而是在首次写入条带中的卷块时初始化每个RAID条带。

只有SSD卷组和池支持资源配置的卷、其中组或池中的所有驱动器都支持NVMe已取消分配或未写入逻辑块错误启用(DULBE")错误恢复功能。创建资源配置的卷时、分配给该卷的所有驱动器块都会进行取消分配(未映射)。此外、主机还可以使用NVMe Dataset Management命令或SCSI Unmap命令取消分配卷中的逻辑块。取消分配块可以延长SSD的使用寿命并提高最大写入性能。性能提升因驱动器型号和容量而异。


NOTE: 目前、EF300C或EF600C存储阵列不支持DULBE。



== 关于资源配置卷功能、我需要了解哪些信息？

资源配置是EF300和EF600存储阵列中提供的一项功能、可在不执行后台初始化过程的情况下立即使用卷。

资源配置卷是SSD卷组或池中的厚卷、在创建卷时会分配(分配给卷)驱动器容量、但会取消分配(取消映射)驱动器块。相比之下、在传统厚卷中、所有驱动器块都会在后台卷初始化操作期间映射或分配、以便初始化数据保证保护信息字段并使每个RAID条带中的数据和RAID奇偶校验保持一致。对于资源配置的卷、不会进行有时间限制的后台初始化。而是在首次写入条带中的卷块时初始化每个RAID条带。

只有SSD卷组和池支持资源配置的卷、其中组或池中的所有驱动器都支持NVMe已取消分配或未写入逻辑块错误启用(DULBE")错误恢复功能。创建资源配置的卷时、分配给该卷的所有驱动器块都会进行取消分配(未映射)。此外、主机还可以使用NVMe Dataset Management命令或SCSI Unmap命令取消分配卷中的逻辑块。取消分配块可以延长SSD的使用寿命并提高最大写入性能。性能提升因驱动器型号和容量而异。

在驱动器支持DULBE"的系统上、默认情况下会启用资源配置。您可以在*池和卷组*中禁用此默认设置。


NOTE: 目前、EF300C或EF600C存储阵列不支持DULBE。
