---
permalink: sm-storage/host-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, host, terms 
summary: 了解主机术语如何应用于存储阵列。 
---
= 了解 SANtricity 软件中的主机术语
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解主机术语如何应用于存储阵列。

[cols="25h,~"]
|===
| 组件 | 定义 


 a| 
主机
 a| 
主机是指向存储阵列上的卷发送I/O的服务器。



 a| 
主机名
 a| 
主机名应等于主机的系统名称。



 a| 
主机集群
 a| 
主机集群是一组主机。您可以创建一个主机集群、以便轻松地将相同的卷分配给多个主机。



 a| 
主机接口协议
 a| 
主机接口协议是指控制器与主机之间的连接(例如光纤通道、iSCSI等)。



 a| 
HBA或网络接口卡(NIC)
 a| 
主机总线适配器(HBA)是驻留在主机中并包含一个或多个主机端口的板。



 a| 
主机端口
 a| 
主机端口是主机总线适配器(HBA)上的一个端口、用于与控制器建立物理连接并用于I/O操作。



 a| 
主机端口标识符
 a| 
主机端口标识符是与主机总线适配器(HBA)上的每个主机端口关联的唯一全球通用名称。

* Internet小型计算机系统接口(iSCSI)主机端口标识符必须包含1到233个字符。iSCSI主机端口标识符以标准IQN格式显示(例如、`iqn.xxx.com.xxx:8b3ad`)。
* 光纤通道和串行连接SCSI (SAS)等非iSCSI主机端口标识符每两个字符(例如、`xx：yy：zz`)后显示为以冒号分隔。光纤通道主机端口标识符必须包含16个字符。




 a| 
主机操作系统类型
 a| 
主机操作系统类型是一种配置设置、用于定义存储阵列中的控制器如何根据主机的操作系统(或变体)对I/O做出响应。这有时也称为_host type_、简称为。



 a| 
控制器主机端口
 a| 
控制器主机端口是控制器上的一个端口、用于与主机建立物理连接并用于I/O操作。



 a| 
LUN
 a| 
逻辑单元号(LUN)是分配给主机用于访问卷的地址空间的编号。卷以LUN的形式呈现给主机。

每个主机都有自己的LUN地址空间。因此、不同的主机可以使用同一个LUN来访问不同的卷。

|===