---
permalink: sm-storage/how-reserved-capacity-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved, capacity, 
summary: '在为卷提供复制服务操作(例如快照或异步镜像操作)时、系统会自动创建预留容量。' 
---
= 预留容量的工作原理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在为卷提供复制服务操作(例如快照或异步镜像操作)时、系统会自动创建预留容量。

预留容量的目的是、在出现问题时、将数据更改存储在这些卷上。与卷一样、预留容量也是从池或卷组创建的。



== 复制使用预留容量的服务对象

预留容量是以下副本服务对象使用的底层存储机制：

* Snapshot组
* 读/写Snapshot卷
* 一致性组成员卷
* 镜像对卷


创建或扩展这些副本服务对象时、必须从池或卷组创建新的预留容量。对于快照操作、预留容量通常为基础卷的40%、对于异步镜像操作、预留容量通常为基础卷的20%。但是、预留容量会根据原始数据的更改次数而有所不同。



== 精简卷和预留容量

对于精简卷、如果已达到报告的最大容量256 TiB、则无法增加其容量。确保精简卷的预留容量设置为大于报告的最大容量的大小。(精简卷始终采用精简配置、这意味着在将数据写入卷时会分配容量。)

如果使用池中的精简卷创建预留容量、请查看以下预留容量操作和结果：

* 如果精简卷的预留容量发生故障、精简卷本身不会自动过渡到故障状态。但是、由于精简卷上的所有I/O操作都需要访问预留容量卷、因此I/O操作始终会导致将检查条件返回给发出请求的主机。如果可以解决预留容量卷的根本问题、预留容量卷将返回到最佳状态、精简卷将再次正常运行。
* 如果使用现有精简卷完成异步镜像对、则该精简卷将使用新的预留容量卷重新初始化。在初始同步过程中、仅传输主端配置的块。




== 容量警报

副本服务对象具有可配置的容量警告和警报阈值、并在预留容量已满时提供可配置的响应。

当副本服务对象卷的预留容量接近填充点时、系统会向用户发出警报。默认情况下、如果预留容量卷已满75%、则会发出此警报；但是、您可以根据需要上调或下调此警报点。如果您收到此警报、则可以在此时增加预留容量卷的容量。在这方面、可以单独配置每个副本服务对象。



== 孤立的预留容量卷

孤立预留容量卷是指由于其关联的副本服务对象已被删除而不再存储用于复制服务操作的数据的卷。删除副本服务对象时、其预留容量卷也应被删除。但是、无法删除预留容量卷。

由于任何主机都不会访问孤立的预留容量卷、因此它们是可回收的候选卷。手动删除孤立的预留容量卷、以便可以将其容量用于其他操作。

System Manager会在主页的通知区域中显示一条"回收未使用的容量"消息、提醒您已创建的已预留容量卷。您可以单击*回收未使用的容量*以显示回收未使用的容量对话框、在此可以删除孤立的预留容量卷。



== 预留容量的特征

* 在创建卷期间、需要考虑为预留容量分配的容量、以保留足够的可用容量。
* 预留容量可以小于基础卷(最小大小为8 MiB)。
* 元数据占用了一些空间、但空间非常小(192 KiB)、因此在确定预留容量卷的大小时无需考虑这些空间。
* 预留容量不能直接从主机读取或写入。
* 每个读/写Snapshot卷、快照组、一致性组成员卷和镜像对卷都有预留容量。

