---
permalink: sm-storage/how-do-i-view-and-interpret-all-ssd-cache-statistics.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ssd cache, statistics 
summary: 您可以查看SSD缓存的标称统计信息和详细统计信息。标称统计信息是详细统计信息的一部分。 
---
= 如何查看和解释所有SSD缓存统计信息？
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以查看SSD缓存的标称统计信息和详细统计信息。标称统计信息是详细统计信息的一部分。

只有在将所有SSD统计信息导出到`.csv`文件时、才能查看详细统计信息。在查看和解释统计信息时、请记住、某些解释是通过结合统计信息得出的。



== 标称统计信息

要查看SSD缓存统计信息、请选择菜单：存储(池和卷组)。选择要查看统计信息的SSD缓存、然后选择菜单：更多(查看统计信息)。标称统计信息显示在"查看SSD缓存统计信息"对话框中。

以下列表包含标称统计信息、这些统计信息是详细统计信息的一部分。

[cols="25h,~"]
|===
| 标称统计信息 | Description 


 a| 
读取/写入
 a| 
主机从启用了SSD缓存的卷读取数据或主机写入数据的总数。比较读取与写入之间的关系。要实现有效的SSD缓存操作、读取次数必须大于写入次数。读取与写入的比率越大、缓存的运行就越好。



 a| 
缓存命中
 a| 
缓存命中数的计数。



 a| 
缓存命中率(%)
 a| 
派生自缓存命中/(读取+写入)。对于有效的SSD缓存操作、缓存命中百分比应大于50%。少量数字可能表示以下几个方面：

* 读取与写入的比率太小
* 不会重复读取
* 缓存容量太小




 a| 
缓存分配(%)
 a| 
分配的SSD缓存存储容量、以此控制器可用的SSD缓存存储的百分比表示。源自已分配的字节/可用字节。缓存分配百分比通常显示为100%。如果此数字小于100%、则表示缓存尚未预热或SSD缓存容量大于所访问的所有数据。在后一种情况下、较小的SSD缓存容量可以提供相同级别的性能。请注意、这并不表示缓存的数据已放置到SSD缓存中；它只是一个准备步骤、然后才能将数据放置到SSD缓存中。



 a| 
缓存利用率(%)
 a| 
包含已启用卷中的数据的SSD缓存存储容量、以分配的SSD缓存存储百分比表示。此值表示SSD缓存的利用率或密度、该缓存是从用户数据字节/已分配字节派生的。缓存利用率百分比通常低于100%、可能要低得多。此数字显示已填充缓存数据的SSD缓存容量百分比。此数字低于100%、因为SSD缓存的每个分配单元(SSD缓存块)都划分为称为子块的较小单元、这些子块在一定程度上是独立填充的。数字越高通常越好、但即使数字越小、性能也会显著提高。

|===


== 详细统计信息

详细统计信息包括名义统计信息和其他统计信息。这些附加统计信息会与标称统计信息一起保存、但与标称统计信息不同、它们不会显示在"查看SSD缓存统计信息"对话框中。只有在将统计信息导出到`.csv`文件后、才能查看详细统计信息。

查看`.csv`文件时、请注意、详细统计信息列在标称统计信息之后：

[cols="25h,~"]
|===
| 详细统计信息 | Description 


 a| 
读取块
 a| 
主机读取中的块数。



 a| 
写入块
 a| 
主机写入的块数。



 a| 
完整命中块
 a| 
缓存命中中的块数。完整命中块表示已从SSD缓存中完全读取的块数。SSD缓存只会对完全缓存命中的操作的性能产生影响。



 a| 
部分命中
 a| 
至少有一个块(而不是所有块)位于SSD缓存中的主机读取次数。部分命中是SSD缓存*未命中*、其中从基础卷读取的结果已满足。



 a| 
Partial Hits—块
 a| 
部分命中中的块数。部分缓存命中和部分缓存命中块是由于在SSD缓存中仅包含一部分数据的操作而导致的。在这种情况下、操作必须从缓存的硬盘驱动器(HDD)卷中获取数据。SSD缓存不会为这种类型的命中带来任何性能优势。如果部分缓存命中块数高于完整缓存命中块数、则不同的I/O特征类型(文件系统、数据库或Web服务器)可以提高性能。在SSD缓存预热期间、与缓存命中相比、部分命中和未命中的数量预计会更多。



 a| 
未命中
 a| 
SSD缓存中没有块的主机读取次数。如果满足从基础卷读取的要求、则会发生SSD缓存未命中。在SSD缓存预热期间、与缓存命中相比、部分命中和未命中的数量预计会更多。



 a| 
未命中—块
 a| 
未命中的块数。



 a| 
填充操作(主机读取)
 a| 
将数据从基础卷复制到SSD缓存的主机读取次数。



 a| 
填充操作(主机读取)—块
 a| 
填充操作(主机读取)中的块数。



 a| 
填充操作(主机写入)
 a| 
将数据从基础卷复制到SSD缓存的主机写入次数。对于因写入I/O操作而未填充缓存的缓存配置设置、填充操作(主机写入)计数可能为零。



 a| 
填充操作(主机写入)—块
 a| 
填充操作(主机写入)中的块数。



 a| 
使操作失效
 a| 
数据失效或从SSD缓存中删除的次数。对于每个主机写入请求、每个具有强制单元访问(FUA)的主机读取请求、每个验证请求以及某些其他情况、都会执行缓存失效操作。



 a| 
回收操作
 a| 
SSD缓存块重新用于另一个基础卷和/或不同逻辑块寻址(Logical Block Addressing、LBA)范围的次数。为了有效地执行缓存操作、与读取和写入操作的总数相比、回收的数量必须较小。如果回收操作的数量接近读取和写入的总数、则SSD缓存将会达到最大值。需要增加缓存容量或工作负载不适合与SSD缓存一起使用。



 a| 
可用字节数
 a| 
SSD缓存中可供此控制器使用的字节数。



 a| 
已分配字节
 a| 
此控制器从SSD缓存分配的字节数。从SSD缓存分配的字节数可能为空、或者可能包含基础卷中的数据。



 a| 
用户数据字节
 a| 
SSD缓存中包含基础卷中的数据的已分配字节数。可用字节数、已分配字节数和用户数据字节数用于计算缓存分配百分比和缓存利用率百分比。

|===