---
permalink: sm-storage/how-ssd-cache-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ssd cache, 
summary: 'SSD缓存功能是一种基于控制器的解决方案 、可将最常访问的数据("热"数据)缓存到延迟较低的固态驱动器(SSD)上、以动态提高系统性能。SSD缓存仅用于主机读取。' 
---
= SSD缓存的工作原理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSD缓存功能是一种基于控制器的解决方案 、可将最常访问的数据("热"数据)缓存到延迟较低的固态驱动器(SSD)上、以动态提高系统性能。SSD缓存仅用于主机读取。

[NOTE]
====
EF600或EF300存储系统不支持此功能。

====


== SSD缓存与主缓存

SSD缓存是一种二级缓存、可与控制器动态随机存取存储器(DRAM)中的主缓存结合使用。

SSD缓存的运行方式与主缓存不同：

* 对于主缓存、每个I/O操作都必须通过缓存暂存数据才能执行此操作。
+
在主缓存中、数据会在主机读取后存储在DRAM中。

* 仅使用SSD缓存将数据置于缓存中有利于提高整体系统性能。
+
在SSD缓存中、数据会从卷中复制并存储在两个内部RAID卷(每个控制器一个)上、这两个卷在创建SSD缓存时会自动创建。



内部RAID卷用于内部缓存处理。这些卷不可访问或显示在用户界面中。但是、这两个卷会计入存储阵列中允许的卷总数。



== 如何使用SSD缓存

智能缓存会将数据放置在低延迟驱动器中、以便能够更快地响应未来对该数据的请求。如果某个程序请求缓存中的数据(称为"`cache hit`")、则延迟较低的驱动器可以处理该事务。否则、将出现"`cache miss`"、并且必须从速度较慢的原始驱动器访问数据。随着缓存命中次数的增加、整体性能也会提高。

当主机程序访问存储阵列的驱动器时、数据存储在SSD缓存中。当主机程序再次访问相同的数据时、系统会从SSD缓存而非硬盘驱动器中读取这些数据。通常访问的数据存储在SSD缓存中。只有在无法从SSD缓存读取数据时、才会访问硬盘驱动器。

只有在将数据置于缓存中有利于提高整体系统性能时、才会使用SSD缓存。

当CPU需要处理读取数据时、它会执行以下步骤：

. 检查DRAM缓存。
. 如果在DRAM缓存中未找到、请检查SSD缓存。
. 如果在SSD缓存中未找到、请从硬盘驱动器获取。如果认为数据值得缓存、请复制到SSD缓存。




== 提高了性能

将访问量最多的数据(热点)复制到SSD缓存可以提高硬盘运行效率、降低延迟并加快读取和写入速度。使用高性能SSD缓存HDD卷中的数据可提高I/O性能和响应时间。

使用简单的卷I/O机制将数据移入和移出SSD缓存。在缓存数据并将其存储在SSD上后、随后会在SSD缓存上执行这些数据的读取、从而无需访问HDD卷。



== SSD缓存和驱动器安全功能

要在同时使用驱动器安全(已启用安全保护)的卷上使用SSD缓存、该卷的驱动器安全功能必须与SSD缓存匹配。如果不匹配、则此卷将不会启用安全保护。



== 实施SSD缓存

要实施SSD缓存、请执行以下操作：

. 创建SSD缓存。
. 将SSD缓存与要实施SSD读取缓存的卷相关联。


[NOTE]
====
分配给使用控制器SSD缓存的任何卷均不符合自动负载平衡传输的条件。

====