---
permalink: sm-storage/how-volumes-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volume, copy, 
summary: 卷是一种数据容器，用于管理和组织存储阵列上的存储空间。 
---
= 卷的工作原理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
卷是一种数据容器，用于管理和组织存储阵列上的存储空间。

您可以使用存储阵列上的可用存储容量创建卷、并轻松组织和使用系统资源。这一概念类似于在计算机上使用文件夹/目录来组织文件、以便于轻松快速地访问。

卷是主机唯一可见的数据层。在SAN环境中、卷会映射到主机可以看到的逻辑单元号(LUN)。LUN用于保存可使用存储阵列支持的一个或多个主机访问协议(包括FC、iSCSI和SAS)访问的用户数据。



== 可以从池和卷组创建的卷类型

卷从池或卷组中提取容量。您可以从存储阵列上的池或卷组创建以下类型的卷。

* *从池*—您可以从池中创建卷、使其成为_Fully Provisioned (thick) volumes_或_thiny-provisioned (thin) volumes_
+
[NOTE]
====
System Manager界面不提供创建精简卷的选项。如果要创建精简卷、请使用命令行界面(CLI)。

====
* *从卷组*—您只能从卷组创建卷作为完全配置(厚)卷_。


厚卷和精简卷通过不同方式从存储阵列中提取容量：

* 厚卷的容量是在创建该卷时分配的。
* 写入到精简卷时、精简卷的容量将作为数据进行分配。


精简配置有助于避免浪费已分配的容量、并可节省企业前期存储成本。但是、完全配置的优势在于延迟更短、因为在创建厚卷时会一次性分配所有存储。

[NOTE]
====
EF600和EF300存储系统不支持精简配置。

====


== 卷的特征

池或卷组中的每个卷都可以根据要存储的数据类型具有自己的特征。其中一些特征包括：

* *区块大小*—区块是指存储阵列移至条带中下一个驱动器(RAID组)之前存储在驱动器上的数据量(以千字节(KiB)为单位)。区块大小等于或小于卷组的容量。区块大小是固定的、不能为池更改。
* *容量*-使用池或卷组中的可用容量创建卷。在创建卷之前、池或卷组必须已存在、并且必须具有足够的可用容量来创建卷。
* *控制器所有权*-所有存储阵列均可具有一个或两个控制器。在单控制器阵列上、卷的工作负载由单个控制器管理。在双控制器阵列上、卷将具有一个首选控制器(A或B)、该控制器"`拥有`"卷。在双控制器配置中、使用自动负载平衡功能自动调整卷所有权、以便在工作负载在控制器之间移动时更正任何负载平衡问题。自动负载平衡可实现自动I/O工作负载平衡、并确保在两个控制器之间动态管理和平衡来自主机的传入I/O流量。
* *卷分配*—您可以在创建卷时或稍后为主机授予对卷的访问权限。所有主机访问均通过逻辑单元号(LUN)进行管理。主机会检测分配给卷的LUN。如果要将卷分配给多个主机、请使用集群软件确保卷可供所有主机使用。
+
主机类型可以对主机可以访问的卷数进行特定限制。在创建卷供特定主机使用时、请记住此限制。

* *描述性名称*—您可以根据需要为卷命名任何名称、但我们建议将此名称设置为描述性名称。


在创建卷期间、系统会为每个卷分配容量、并为其分配名称、区块大小(仅限卷组)、控制器所有权以及卷到主机的分配。卷数据会根据需要在控制器之间自动进行负载平衡。
