---
permalink: sm-storage/interpret-performance-data.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, interpret, performance data 
summary: 性能数据可以指导您调整存储阵列的性能。 
---
= 解读性能数据
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
性能数据可以指导您调整存储阵列的性能。

在解释性能数据时、请记住、影响存储阵列性能的因素有多种。下表介绍了需要考虑的主要方面。

[cols="25h,~"]
|===
| 性能数据 | 对性能调整的影响 


 a| 
延迟(毫秒或毫秒)
 a| 
监控特定对象的I/O活动。

可能会发现瓶颈对象：

* 如果一个卷组在多个卷之间共享、则各个卷可能需要自己的卷组来提高驱动器的顺序性能并降低延迟。
* 使用池时、延迟会增加、驱动器之间可能存在不平衡的工作负载、因此延迟值的意义会降低、而且通常会更高。
* 驱动器类型和速度会影响延迟。使用随机I/O时、旋转速度更快的驱动器在磁盘上不同位置之间的移动时间更短。
* 驱动器太少会导致排队的命令增多、驱动器处理命令的时间也会延长、从而增加系统的一般延迟。
* 由于传输数据需要额外的时间、I/O越大、延迟越长。
* 较高的延迟可能表示I/O模式本质上是随机的。与使用顺序流的驱动器相比、具有随机I/O的驱动器的延迟更大。
* 一个通用卷组中的驱动器或卷之间的延迟差异可能表示驱动器速度较慢。




 a| 
IOPS
 a| 
影响每秒输入/输出操作数(IOPS或IOS/sec)的因素包括：

* 访问模式(随机或顺序)
* I/O大小
* RAID级别
* 缓存块大小
* 是否启用读取缓存
* 是否启用写入缓存
* 动态缓存读取预取
* 区块大小
* 卷组或存储阵列中的驱动器数量


缓存命中率越高、I/O速率就越高。与禁用写入缓存相比、启用写入缓存时的写入I/O速率更高。在确定是否为单个卷启用写入缓存时、请查看当前IOPS和最大IOPS。顺序I/O模式的速率应高于随机I/O模式。无论I/O模式如何、都可以启用写入缓存、以最大程度地提高I/O速率并缩短应用程序响应时间。

您可以看到因更改卷的IOPS统计信息中的区块大小而导致的性能提升。尝试确定最佳区块大小、或者使用文件系统大小或数据库块大小。



 a| 
MiB/秒
 a| 
传输速率或吞吐量速率由应用程序I/O大小和I/O速率决定。一般来说、小型应用程序I/O请求会降低传输速率、但I/O速率更快、响应时间更短。对于较大的应用程序I/O请求、可以提高吞吐量。

了解典型的应用程序I/O模式有助于确定特定存储阵列的最大I/O传输速率。



 a| 
CPU
 a| 
此值表示正在使用的处理容量的百分比。

您可能会发现相同类型的对象的CPU使用率存在差异。例如、一个控制器的CPU使用率较高或随着时间的推移而增加、而另一个控制器的CPU使用率则较轻或较稳定。在这种情况下、您可能需要将一个或多个卷的控制器所有权更改为CPU百分比较低的控制器。

您可能需要监控存储阵列中的CPU。如果随着时间的推移、CPU会继续增加、而应用程序性能会降低、则可能需要添加存储阵列。通过向企业添加存储阵列、您可以继续以可接受的性能级别满足应用程序需求。



 a| 
余量
 a| 
性能余量是指控制器、控制器主机通道和控制器驱动器通道的剩余性能。此值以百分比表示、表示这些对象能够提供的最大可能性能与当前性能级别之间的差距。

* 对于控制器、余量是指最大可能IOPS的百分比。
* 对于通道、余量是最大吞吐量的百分比或MiB/秒计算中包括读取吞吐量、写入吞吐量和双向吞吐量。


|===