---
permalink: sm-storage/performance-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, performance, terms 
summary: 了解性能术语如何应用于存储阵列。 
---
= 性能术语
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解性能术语如何应用于存储阵列。

[cols="25h,~"]
|===
| 期限 | Description 


 a| 
应用程序
 a| 
应用程序是一种软件程序、例如SQL或Exchange。



 a| 
CPU
 a| 
CPU是"中央处理单元"的缩写。 CPU表示正在使用的存储阵列处理容量的百分比。



 a| 
主机
 a| 
主机是指向存储阵列上的卷发送I/O的服务器。



 a| 
IOPS
 a| 
IOPS表示每秒输入/输出操作数。



 a| 
延迟
 a| 
延迟是指读取或写入命令等请求与主机或存储阵列响应之间的时间间隔。



 a| 
LUN
 a| 
逻辑单元号(LUN)是分配给主机用于访问卷的地址空间的编号。卷以LUN的形式呈现给主机。

每个主机都有自己的LUN地址空间。因此、不同的主机可以使用同一个LUN来访问不同的卷。



 a| 
MIB
 a| 
MIB是兆字节(megb二进制字节)的缩写。一个MIB为220或1、048、576字节。请比较MB、它表示基数为10。1 MB等于1、024字节。



 a| 
对象
 a| 
对象是任何逻辑或物理存储组件。

逻辑对象包括卷组、池和卷。物理对象包括存储阵列、阵列控制器、主机和驱动器。



 a| 
池
 a| 
池是指一组按逻辑分组的驱动器。您可以使用池创建一个或多个可供主机访问的卷。(您可以从池或卷组创建卷。)



 a| 
读取
 a| 
Read是"读取操作"的缩写、当主机从存储阵列请求数据时会发生此操作。



 a| 
Volume
 a| 
卷是应用程序，数据库和文件系统用于存储数据的容器。它是为主机创建的逻辑组件，用于访问存储阵列上的存储。

卷是使用池或卷组中的可用容量创建的。卷已定义容量。尽管一个卷可能包含多个驱动器、但一个卷在主机中显示为一个逻辑组件。



 a| 
Volume name
 a| 
卷名称是指在创建卷时为其分配的字符串。您可以接受默认名称、也可以提供更具描述性的名称来指示卷中存储的数据类型。



 a| 
卷组
 a| 
卷组是具有共享特征的卷的容器。卷组已定义容量和RAID级别。您可以使用卷组创建一个或多个可供主机访问的卷。(您可以从卷组或池创建卷。)



 a| 
工作负载
 a| 
工作负载是指支持应用程序的存储对象。您可以为每个应用程序定义一个或多个工作负载或实例。对于某些应用程序、系统会将工作负载配置为包含具有类似底层卷特征的卷。这些卷特征会根据工作负载支持的应用程序类型进行优化。例如、如果您创建了一个支持Microsoft SQL Server应用程序的工作负载、然后为该工作负载创建了卷、则底层卷特征将进行优化以支持Microsoft SQL Server。



 a| 
写入
 a| 
写入是"写入操作"的缩写、当数据从主机发送到阵列进行存储时。

|===