---
permalink: sm-storage/replace-drive-logically-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, replace, drive, logically 
summary: 如果某个驱动器发生故障或您出于任何其他原因需要更换它、并且您的存储阵列中有一个未分配的驱动器、则可以从逻辑上将故障驱动器替换为未分配的驱动器。如果您没有未分配的驱动器、则可以改用物理方式更换该驱动器。 
---
= 从逻辑上更换驱动器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果某个驱动器发生故障或您出于任何其他原因需要更换它、并且您的存储阵列中有一个未分配的驱动器、则可以从逻辑上将故障驱动器替换为未分配的驱动器。如果您没有未分配的驱动器、则可以改用物理方式更换该驱动器。

.关于此任务
如果从逻辑上将某个驱动器替换为未分配的驱动器、则此未分配的驱动器将变为已分配、然后成为关联池或卷组的永久成员。您可以使用logical replace选项替换以下类型的驱动器：

* 故障驱动器
* 缺少驱动器
* Recovery Guru通知您即将停产的SSD驱动器
* Recovery Guru通知您驱动器即将发生故障的硬盘驱动器
* 已分配的驱动器(仅适用于卷组中的驱动器、而不适用于池中的驱动器)


替代驱动器必须具有以下特征：

* 处于最佳状态
* 处于未分配状态
* 与要更换的驱动器具有相同的属性(介质类型、接口类型等)
* 相同的FDE功能(建议、但不要求)
* 相同的DA功能(建议使用、但不要求使用)


.步骤
. 选择 * 硬件 * 。
. 如果图形显示了控制器、请单击*显示磁盘架正面*。
+
此图将发生变化、以显示驱动器、而不是控制器。

. 单击要在逻辑上替换的驱动器。
+
此时将显示驱动器的上下文菜单。

. 单击*逻辑替换*。
. *可选：*选中*更换后故障驱动器*复选框、以便在更换后使原始驱动器发生故障。
+
只有在原始分配的驱动器未出现故障或不缺失时、才会启用此复选框。

. 从*选择替代驱动器*表中、选择要使用的替代驱动器。
+
此表仅列出与要更换的驱动器兼容的驱动器。如果可能、请选择一个将保持磁盘架丢失保护和抽屉丢失保护的驱动器。

. 单击*替换*。
+
如果原始驱动器出现故障或丢失、则会使用奇偶校验信息在替代驱动器上重建数据。此重建将自动开始。驱动器的故障指示灯熄灭、池或卷组中驱动器的活动指示灯开始闪烁。

+
如果原始驱动器未出现故障或丢失、则其数据将复制到替代驱动器。此复制操作将自动开始。复制操作完成后、系统会将原始驱动器过渡到未分配状态、或者如果选中了复选框、则过渡到故障状态。


