---
permalink: sm-storage/rtv-how-remote-storage-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, storage 
summary: 通过远程存储功能、您可以将数据从远程存储系统导入到本地E系列存储系统。如果您希望简化数据迁移并最大限度地减少停机时间、例如在设备升级期间、此功能将非常有用。 
---
= 远程存储的工作原理
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过远程存储功能、您可以将数据从远程存储系统导入到本地E系列存储系统。如果您希望简化数据迁移并最大限度地减少停机时间、例如在设备升级期间、此功能将非常有用。

要配置远程存储功能、必须先设置硬件、然后使用System Manager创建远程存储对象。完成此配置后、导入过程将开始。



== 硬件设置

使用以下工作流准备硬件连接。

有关这些步骤的详细信息、请参见E系列和SANtricity 文档中心上的《远程存储功能用户指南》 https://docs.netapp.com/us-en/e-series/remote-storage-volumes/index.html["远程存储卷概述"^]和中的 https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["远程存储技术报告"^]。

在本地E系列存储系统上：

. 确保每个控制器都与远程存储系统建立iSCSI连接。通过此连接、本地E系列系统充当iSCSI启动程序、可将其设置为远程系统上的主机。
. 为导入操作创建目标卷。确保卷的容量等于或大于远程存储系统上的源卷、块大小匹配且未映射。请参见 link:create-volumes.html["创建卷"]。
. 从System Manager界面收集本地E系列系统的iSCSI限定名称(IQN)。稍后将使用IQN将本地E系列系统设置为远程存储系统上的主机。在System Manager中、转至：菜单：设置[系统> iSCSI设置>目标IQN]。


在远程存储系统上：

. 使用IQN将本地E系列系统设置为远程系统上的主机。请确保设置适当的主机类型、如下所示：
+
** 如果远程系统为E系列型号、请参见 link:overview-hosts.html["主机和主机集群概述"]。使用主机类型"出厂默认值"。
** 如果远程系统来自其他供应商、请根据可用选项选择适当的主机类型。


. 停止所有I/O、卸载任何文件系统、并删除对源卷的主机或应用程序的任何分配。
. 将卷分配给新创建的本地E系列存储系统主机。
. 对于选定源卷、从远程存储系统收集以下信息、以便创建导入：
+
** iSCSI限定名称(IQN)
** iSCSI IP地址
** 源卷的LUN编号






== System Manager设置

使用以下工作流为导入创建远程存储对象：

. 使用System Manager界面中的远程存储向导、将远程存储设备(数据导入的源)映射到E系列系统上的目标卷。选择*完成*后、导入过程将开始。
. 从"查看操作"对话框或"正在执行的操作"面板监控导入。如有必要、您还可以暂停并恢复此过程。
. (可选)在导入完成后断开源卷和目标卷之间的连接、或者保持连接以供将来导入。

