---
permalink: sm-storage/rtv-what-do-i-need-to-know-before-starting-a-remote-storage-import.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, storage, import 
summary: 通过远程存储功能、您可以将数据从远程存储系统复制到本地E系列存储系统上的卷。在使用此功能之前、请查看以下准则。 
---
= 在开始远程存储导入之前、我需要了解哪些信息？
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过远程存储功能、您可以将数据从远程存储系统复制到本地E系列存储系统上的卷。在使用此功能之前、请查看以下准则。



== Configuration

在创建远程存储导入之前、您必须完成以下操作并验证以下条件：

* 确保本地E系列存储系统的每个控制器都与远程存储系统建立了iSCSI连接。
* 在本地E系列存储系统上、为导入操作创建一个目标卷。确保卷的容量等于或大于源卷、块大小与源卷匹配且未映射。请参见 link:create-volumes.html["创建卷"]。
* 使用iSCSI限定名称(IQN)将本地E系列存储系统设置为远程系统上的主机。您可以从菜单：设置[系统> iSCSI设置>目标IQN]查看IQN。此外、请务必根据所使用的系统设置适当的主机类型。
* 停止所有I/O、卸载任何文件系统、并删除对远程存储系统上选定卷的主机或应用程序的任何分配。
* 将卷分配给远程存储系统、并分配给新创建的本地E系列存储系统主机。
* 从远程存储系统收集以下信息、以便创建导入：
+
** iSCSI限定名称(IQN)
** iSCSI IP地址
** 源数据所在的远程存储设备的LUN编号


* 导入过程开始后、整个本地目标卷将被复制的数据覆盖。创建导入后、写入本地目标卷的任何新数据都会传播到远程存储设备上的卷。因此、建议您在开始导入过程之前备份远程存储系统上的卷。




== 导入过程

以下步骤概述了导入过程。

. 访问System Manager界面、然后转到*远程存储*页面。选择*导入*以开始创建新的导入。有关详细说明、请参见 link:rtv-import-remote-storage.html["导入远程存储"]。
+
如果要执行脱机导入、请在导入完成后再映射目标卷。

. 监控导入进度。
+
导入开始后、便可映射目标卷。完成导入操作所需的时间取决于远程存储设备(源卷)的大小、导入的优先级设置以及两个存储系统及其关联卷上的I/O负载量。

+
导入完成后、目标卷将与源卷重复。

. 准备好中断映射关系后、从*正在执行的操作*面板对导入对象执行*断开连接*。


导入断开后、本地目标的性能将恢复正常、不再受远程连接的影响。



== 限制

远程存储功能具有以下限制：

* 必须禁用镜像。
* E 系列系统上的目标卷不能具有快照。
* 在启动导入之前，不得将 E 系列系统上的目标卷映射到任何主机。
* E 系列系统上的目标卷必须已禁用资源配置。
* 不支持将远程存储卷直接映射到一个或多个主机。
* 不支持 Web 服务代理。
* 不支持 iSCSI CHAP 密码。
* 不支持 SMcli 。
* 不支持 VMware 数据存储库。
* 如果存在导入对，则一次只能升级关系 / 导入对中的一个存储系统。




== 追加信息

有关远程存储功能的详细信息、请参见 https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["远程存储技术报告"^]。
