---
permalink: sm-storage/schedule-snapshot-images.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, schedule, snapshot, images 
summary: 您可以创建快照计划、以便在基础卷出现问题时进行恢复、并执行计划备份。可以在一天中的任意时间按每日、每周或每月计划创建基础卷或快照一致性组的快照。 
---
= 计划快照映像
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以创建快照计划、以便在基础卷出现问题时进行恢复、并执行计划备份。可以在一天中的任意时间按每日、每周或每月计划创建基础卷或快照一致性组的快照。

.开始之前
基础卷必须是最佳卷。

.关于此任务
此任务介绍如何为现有快照一致性组或基础卷创建快照计划。

[NOTE]
====
您还可以在创建基础卷或快照一致性组的快照映像的同时创建快照计划。

====
.步骤
. 执行以下操作之一以创建快照计划：
+
** 选择菜单： Storage[Volumes] 。
+
为此快照计划选择对象(卷或快照一致性组)、然后选择菜单：复制服务[创建快照计划]。

** 选择菜单：Storage[Snapshots]。
+
选择*计划*选项卡、然后单击*创建*。



. 为此快照计划选择对象(卷或快照一致性组)、然后单击*下一步*。
+
此时将显示创建Snapshot计划对话框。

. 执行以下操作之一：
+
** *使用来自另一个快照对象的先前定义的计划*。
+
确保显示高级选项。单击*显示更多选项*。单击*导入计划*、选择具有要导入计划的对象、然后单击*导入*。

** *修改基本或高级选项*。
+
在对话框右上角、单击*显示更多选项*以显示所有选项、然后参阅下表。



+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 字段 | Description 


 a| 
*基本设置*



 a| 
选择天
 a| 
为快照映像选择一周中的各个日期。



 a| 
开始时间
 a| 
从下拉列表中、为每日快照选择一个新的开始时间(所选时间以半小时为间隔)。开始时间默认为比当前时间提前半小时。



 a| 
时区
 a| 
从下拉列表中、选择阵列的时区。



 a| 
* 高级设置 *



 a| 
天/月
 a| 
选择以下选项之一：

** *每日/每周*-为同步快照选择单独的日期。如果要设置每日计划、也可以选中右上角的*选择所有日期*复选框。
** *每月/每年*-为同步快照选择单个月。在*日期*字段中、输入月中要进行同步的天数。有效条目为* 1 *到* 31 *和*最后一个*。您可以使用逗号或分号分隔多天。使用连字符表示包含的日期。例如：1、3、4、10-15、last。如果您希望使用每月计划、也可以选中右上角的*选择所有月份*复选框。




 a| 
开始时间
 a| 
从下拉列表中、为每日快照选择一个新的开始时间(所选时间以半小时为间隔)。开始时间默认为比当前时间提前半小时。



 a| 
时区
 a| 
从下拉列表中、选择阵列的时区。



 a| 
每日快照数/快照之间的时间
 a| 
选择每天要创建的快照映像数。如果选择多个、还可以选择快照映像之间的时间。对于多个快照映像、请确保预留了足够的容量。



 a| 
是否立即创建快照映像？
 a| 
选中此复选框可创建即时映像以及要计划的自动映像。



 a| 
开始/结束日期或无结束日期
 a| 
输入开始同步的开始日期。此外、请输入结束日期或选择*无结束日期*。

|===
====
. 执行以下操作之一：
+
** 如果对象是快照一致性组、请单击*创建*以接受设置并创建计划。
** 如果对象是卷、请单击*下一步*为快照映像分配预留容量。
+
卷候选表仅显示支持指定预留容量的候选卷。预留容量是指用于任何复制服务操作和存储对象的物理分配容量。主机不能直接读取它。



. 使用spinner框为快照映像分配预留容量。执行以下操作之一：
+
** *接受默认设置。*
+
使用此建议选项可使用默认设置为快照映像分配预留容量。

** *分配您自己的预留容量设置以满足您的数据存储需求。*
+
如果更改默认预留容量设置、请单击*刷新候选容量*以刷新指定预留容量的候选列表。

+
按照以下准则分配预留容量：

+
*** 预留容量的默认设置为基础卷容量的40%。通常、此容量足以满足要求。
*** 所需容量因卷I/O写入的频率和大小以及快照映像收集的数量和持续时间而异。




. 单击 * 下一步 * 。
+
此时将显示编辑设置对话框。

. 根据需要编辑快照计划的设置、然后单击*完成*。
+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 正在设置 ... | Description 


 a| 
* Snapshot映像限制*



 a| 
在以下情况下启用Snapshot映像自动删除...
 a| 
如果要在指定限制后自动删除快照映像、请保持选中此复选框；使用spinner框更改此限制。如果清除此复选框、则在创建32个映像后将停止创建快照映像。



 a| 
*预留容量设置*



 a| 
在以下情况下提醒我...
 a| 
使用spinner框调整当计划的预留容量接近全满时系统发送警报通知的百分比点。

如果计划的预留容量超过指定阈值、请使用提前通知增加预留容量或删除不必要的对象、以免剩余空间用尽。



 a| 
预留容量全满的策略
 a| 
选择以下策略之一：

** *清除最旧的快照映像*-系统会自动清除最旧的快照映像、从而释放快照映像预留容量、以便在快照组中重复使用。
** *拒绝向基础卷写入数据*-当预留容量达到其最大定义百分比时、系统会拒绝向基础卷发出的任何I/O写入请求、这些请求会触发预留容量访问。


|===
====

