---
permalink: sm-storage/snapshot-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, snapshot, terms 
summary: 了解快照术语如何应用于存储阵列。 
---
= Snapshot术语
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解快照术语如何应用于存储阵列。

[cols="25h,~"]
|===
| 期限 | Description 


 a| 
Snapshot功能
 a| 
Snapshot功能用于创建和管理卷的映像。



 a| 
Snapshot映像
 a| 
快照映像是指在特定时间点捕获的卷数据的逻辑副本。与还原点一样，您可以通过快照映像回滚到已知正常的数据集。尽管主机可以访问快照映像、但它无法直接对其进行读写。



 a| 
基础卷
 a| 
基础卷是创建快照映像的源卷。它可以是厚卷或精简卷、通常分配给主机。基础卷可以位于卷组或磁盘池中。



 a| 
Snapshot卷
 a| 
主机可通过Snapshot卷访问Snapshot映像中的数据。快照卷包含自己的预留容量、这样可以在不影响原始快照映像的情况下保存对基础卷所做的任何修改。



 a| 
Snapshot组
 a| 
快照组是一组来自单个基础卷的快照映像。



 a| 
预留容量卷
 a| 
预留容量卷可跟踪覆盖基础卷中的哪些数据块以及这些数据块中保留的内容。



 a| 
Snapshot计划
 a| 
快照计划是创建自动快照映像的时间表。通过该计划、您可以控制创建映像的频率。



 a| 
Snapshot一致性组
 a| 
快照一致性组是创建快照映像时视为单个实体的卷的集合。其中每个卷都有自己的快照映像、但所有映像都是在同一时间点创建的。



 a| 
Snapshot一致性组成员卷
 a| 
属于快照一致性组的每个卷都称为成员卷。将卷添加到快照一致性组时、System Manager会自动创建与此成员卷对应的新快照组。



 a| 
回滚
 a| 
回滚是指将基础卷中的数据返回到上一时间点的过程。



 a| 
预留容量
 a| 
预留容量是指用于任何复制服务操作和存储对象的物理分配容量。主机不能直接读取它。

|===