---
permalink: sm-storage/start-snapshot-image-rollback-for-base-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, start, snapshot, image, rollback, base, volume 
summary: 您可以执行回滚操作来更改基础卷的内容、使其与保存在快照映像中的内容匹配。回滚操作不会更改与基础卷关联的快照映像的内容。 
---
= 启动基础卷的快照映像回滚
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以执行回滚操作来更改基础卷的内容、使其与保存在快照映像中的内容匹配。

回滚操作不会更改与基础卷关联的快照映像的内容。

.开始之前
* 预留的容量足以启动回滚操作。
* 选定快照映像为最佳映像、选定卷为最佳卷。
* 选定卷尚未执行回滚操作。


.关于此任务
通过回滚开始顺序、您可以在提供添加存储容量选项的同时、对基础卷的快照映像开始回滚。不能同时为基础卷启动多个回滚操作。

[NOTE]
====
主机可以立即访问新的回滚基础卷、但在回滚开始后、现有基础卷不允许主机读写访问。您可以在开始回滚之前创建基础卷的快照、以保留回滚前的基础卷以供恢复。

====
.步骤
. 选择菜单：Storage[Snapshots]。
. 选择* Snapshot映像*选项卡。
. 选择快照映像、然后选择菜单：Rollback[启动]。
+
此时将显示确认开始回滚对话框。

. *可选：*如果需要、选择*增加容量*选项。
+
此时将显示增加预留容量对话框。

+
.. 使用spinner框调整容量百分比。
+
如果包含选定存储对象的池或卷组中不存在可用容量、并且存储阵列具有未分配的容量、则可以添加容量。您可以创建新的池或卷组、然后使用该池或卷组上的新可用容量重试此操作。

.. 单击 * 增加 * 。


. 确认要执行此操作、然后单击*回滚*。


.结果
System Manager将执行以下操作：

* 还原包含保存在选定快照映像上的内容的卷。
* 使回滚卷可立即供主机访问。您无需等待回滚操作完成。


.完成后
选择菜单：主页(查看正在执行的操作)以查看回滚操作的进度。

如果回滚操作不成功、此操作将暂停。您可以恢复已暂停的操作、如果仍不成功、请按照Recovery Guru操作步骤 更正问题或联系技术支持。
