---
permalink: sm-storage/start-snapshot-image-rollback-for-consistency-group-member-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, start, snapshot, image, rollback, snapshot, consistency, group, member, volumes 
summary: 您可以执行回滚操作、以更改快照一致性组成员卷的内容、使其与保存在快照映像中的内容匹配。 
---
= 为快照一致性组成员卷启动快照映像回滚
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以执行回滚操作、以更改快照一致性组成员卷的内容、使其与保存在快照映像中的内容匹配。

回滚操作不会更改与快照一致性组关联的快照映像的内容。

.开始之前
* 预留的容量足以启动回滚操作。
* 选定快照映像为最佳映像、选定卷为最佳卷。
* 选定卷尚未执行回滚操作。


.关于此任务
通过回滚开始序列、您可以在快照一致性组的快照映像上开始回滚、同时提供添加存储容量的选项。不能同时为快照一致性组启动多个回滚操作。

[NOTE]
====
主机可以立即访问新的回滚卷、但在回滚开始后、现有成员卷不再允许主机读写访问。您可以在开始回滚之前创建成员卷的快照映像、以保留回滚前的基本卷以供恢复使用。

====
开始回滚快照一致性组的快照映像的过程是一个多步骤操作步骤。



== 第1步：选择成员

您必须选择要回滚的成员卷。

.步骤
. 选择菜单：Storage[Snapshots]。
. 选择* Snapshot映像*选项卡。
. 选择快照一致性组快照映像、然后选择菜单：Rollback[启动]。
+
此时将显示开始回滚对话框。

. 选择一个或多个成员卷。
. 单击*下一步*、然后执行以下操作之一：
+
** 如果任何选定成员卷与多个存储快照映像的预留容量对象关联、则会显示查看容量对话框。转至 <<第2步：查看容量>>。
** 如果选定成员卷均未与多个存储快照映像的预留容量对象关联、则会显示编辑优先级对话框。转至 <<第3步：编辑优先级>>。






== 第2步：查看容量

如果您选择了与多个预留容量对象关联的成员卷、例如快照组和预留容量卷、则可以查看并增加回滚卷的预留容量。

.步骤
. 在预留容量极低(或为零)的任何成员卷旁边、单击*编辑*列中的*增加容量*链接。
+
此时将显示增加预留容量对话框。

. 使用spinner框调整容量百分比、然后单击*增加*。
+
如果包含选定存储对象的池或卷组中不存在可用容量、并且存储阵列具有未分配的容量、则可以添加容量。您可以创建新的池或卷组、然后使用该池或卷组上的新可用容量重试此操作。

. 单击*下一步*、然后转到 <<第3步：编辑优先级>>。
+
此时将显示编辑优先级对话框。





== 第3步：编辑优先级

您可以根据需要编辑回滚操作的优先级。

.关于此任务
回滚优先级决定了在牺牲系统性能的情况下专用于回滚操作的系统资源数量。

.步骤
. 使用滑块根据需要调整回滚优先级。
. 确认要执行此操作、然后单击*完成*。


.结果
System Manager将执行以下操作：

* 还原包含保存在选定快照映像上的内容的快照一致性组成员卷。
* 使回滚卷可立即供主机访问。您无需等待回滚操作完成。


.完成后
选择菜单：主页(查看正在执行的操作)以查看回滚操作的进度。

如果回滚操作不成功、此操作将暂停。您可以恢复已暂停的操作、如果仍不成功、请按照Recovery Guru操作步骤 更正问题或联系技术支持。
