---
permalink: sm-storage/types-of-copy-volume-operations.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, copy, volume, 
summary: 您可以执行脱机复制卷操作或联机复制卷操作。脱机操作会从源卷读取数据并将其复制到目标卷。联机操作使用快照卷作为源卷、并将其数据复制到目标卷。 
---
= 复制卷操作的类型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以执行_offline"复制卷"操作或"_online"复制卷操作。脱机操作会从源卷读取数据并将其复制到目标卷。联机操作使用快照卷作为源卷、并将其数据复制到目标卷。

为确保数据完整性、在任何一种类型的复制卷操作期间、目标卷的所有I/O活动都将暂停。发生此暂停的原因是、在操作步骤 完成之前、目标卷上的数据状态不一致。

下面介绍了脱机和联机复制卷操作。



== 脱机复制卷操作

脱机复制卷关系位于源卷与目标卷之间。脱机副本将从源卷读取数据并将其复制到目标卷、同时暂停对正在进行的源卷进行的所有更新。源卷的所有更新都将暂停、以防止在目标卷上创建按时间顺序排列的不一致。

[cols="25h,~"]
|===
2+| 有关脱机副本操作的信息 


 a| 
读取和写入请求
 a| 
* 参与脱机副本的源卷可用于只读I/O活动、而复制卷操作的状态为"正在进行"或"待定"。
* 脱机副本完成后、允许写入请求。
* 为防止出现写保护错误消息、请勿访问状态为正在进行的复制卷操作中的源卷。




 a| 
日志记录文件系统
 a| 
* 如果源卷已使用日志文件系统进行格式化、则存储阵列控制器可能会拒绝任何对源卷执行问题描述 读取请求的尝试、并可能会显示错误消息。
* 日志文件系统驱动程序会在尝试对读取请求进行问题描述 之前发出写入请求。控制器拒绝写入请求、并且可能由于写入请求被拒绝而无法发出读取请求。此情况可能会导致显示错误消息、指示源卷受写保护。
* 要防止发生此问题描述 、请勿在复制卷操作的状态为正在进行时尝试访问参与脱机副本的源卷。


|===


== 联机复制卷操作

联机复制卷关系位于快照卷和目标卷之间。您可以在源卷联机并可用于数据写入的情况下启动复制卷操作。此功能可通过创建卷的快照并使用该快照作为副本的实际源卷来实现。

在对源卷启动复制卷操作时、System Manager会为基础卷创建一个快照映像、并在基础卷的快照映像与目标卷之间创建一个复制关系。使用快照映像作为源卷可以使存储阵列在复制过程中继续向源卷写入数据。

在联机复制操作期间、由于写入时复制操作步骤 、会对性能产生影响。联机副本完成后、将还原基础卷性能。

[cols="25h,~"]
|===
2+| 有关联机副本操作的信息 


 a| 
可以使用哪种类型的卷？
 a| 
* 创建时间点映像的卷称为基础卷、必须是存储阵列上的标准卷或精简卷。
* 目标卷可以是卷组中的标准卷、也可以是池中的标准卷。目标卷不能是精简卷或快照组中的基础卷。
* 您可以使用联机复制卷功能将数据从精简卷复制到位于同一存储阵列中的池中的标准卷。但是、您不能使用复制卷功能将数据从标准卷复制到精简卷。




 a| 
基本卷性能
 a| 
* 如果用作副本源的Snapshot卷处于活动状态、则由于写入时复制操作、基础卷性能将下降。复制完成后、快照将被禁用、并还原基础卷性能。尽管快照已禁用、但预留容量卷和副本关系仍保持不变。




 a| 
创建的卷类型
 a| 
* 在联机复制操作期间、系统会创建一个快照卷和一个预留容量卷。
* 快照卷不是包含数据的实际卷、而是指某个卷在特定时间包含的数据。
* 对于所创建的每个快照、系统会创建一个预留容量卷来存放快照的数据。预留容量卷仅用于管理快照映像。




 a| 
预留容量卷
 a| 
* 在修改源卷上的数据块之前、要修改的数据块的内容会复制到预留容量卷中以供安全保存。
* 由于预留容量卷会将原始数据的副本存储在这些数据块中、因此对这些数据块进行的进一步更改仅会写入源卷。
* 联机副本操作使用的磁盘空间少于完整物理副本、因为存储在预留容量卷中的数据块仅为自创建快照以来发生更改的数据块。


|===