---
permalink: sm-storage/volume-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volume, terms 
summary: 了解卷术语如何应用于存储阵列。 
---
= 卷术语
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解卷术语如何应用于存储阵列。



== 所有卷类型

[cols="25h,~"]
|===
| 期限 | Description 


 a| 
已分配容量
 a| 
您可以使用已分配的容量创建卷并执行复制服务操作。

对于厚卷、分配的容量和报告的容量相同、但对于精简卷、分配的容量和报告的容量不同。对于厚卷、物理分配的空间等于向主机报告的空间。对于精简卷、报告的容量是指向主机报告的容量、而分配的容量是指当前为写入数据而分配的驱动器空间量。



 a| 
应用程序
 a| 
应用程序是指SQL Server或Exchange等软件。您可以定义一个或多个工作负载来支持每个应用程序。对于某些应用程序、系统会自动建议一种可优化存储的卷配置。卷配置包括I/O类型、区块大小、控制器所有权以及读写缓存等特征。



 a| 
Capacity
 a| 
容量是指可存储在卷中的数据量。



 a| 
控制器所有权
 a| 
控制器所有权用于定义指定为卷的拥有或主控制器的控制器。卷可以具有一个"`拥有`"卷的首选控制器(A或B)。使用自动负载平衡功能自动调整卷所有权、以便在工作负载在控制器之间移动时更正任何负载平衡问题。自动负载平衡可实现自动I/O工作负载平衡、并确保在两个控制器之间动态管理和平衡来自主机的传入I/O流量。



 a| 
动态缓存读取预取
 a| 
动态缓存读取预取允许控制器在从驱动器向缓存读取数据块时将其他顺序数据块复制到缓存中。这种缓存增加了从缓存中填充未来数据请求的可能性。动态缓存读取预取对于使用顺序I/O的多媒体应用程序非常重要预提取到缓存中的数据速率和数据量会根据主机读取的速率和请求大小进行自调整。随机访问不会将发生原因 数据预先提取到缓存中。禁用读取缓存时、此功能不适用。

对于精简卷、动态缓存读取预取始终处于禁用状态、并且无法更改。



 a| 
可用容量区域
 a| 
可用容量区域是指删除卷或在创建卷期间未使用所有可用容量时可能产生的可用容量。在卷组中创建具有一个或多个可用容量区域的卷时、卷的容量将限制为该卷组中最大的可用容量区域。例如、如果一个卷组的可用容量总计为15 GiB、而最大可用容量区域为10 GiB、则可以创建的最大卷为10 GiB。

通过整合可用容量、您可以从卷组中的最大可用容量创建更多卷。



 a| 
主机
 a| 
主机是指向存储阵列上的卷发送I/O的服务器。



 a| 
主机集群
 a| 
主机集群是一组主机。您可以创建一个主机集群、以便轻松地将相同的卷分配给多个主机。



 a| 
热备用驱动器
 a| 
只有卷组才支持热备用驱动器。热备用驱动器不包含任何数据、并在卷组中包含的RAID 1、RAID 3、RAID 5或RAID 6卷中的驱动器发生故障时充当备用驱动器。热备用驱动器可为存储阵列添加另一个冗余级别。



 a| 
LUN
 a| 
逻辑单元号(LUN)是分配给主机用于访问卷的地址空间的编号。卷以LUN的形式呈现给主机。

每个主机都有自己的LUN地址空间。因此、不同的主机可以使用同一个LUN来访问不同的卷。



 a| 
介质扫描
 a| 
通过介质扫描、可以在正常读取或写入驱动器期间检测到驱动器介质错误。介质扫描作为后台操作执行、并扫描定义的用户卷中的所有数据和冗余信息。



 a| 
命名空间
 a| 
命名空间是指为块访问而格式化的NVM存储。它类似于SCSI中的逻辑单元、它与存储阵列中的卷相关。



 a| 
池
 a| 
池是指一组按逻辑分组的驱动器。您可以使用池创建一个或多个可供主机访问的卷。(您可以从池或卷组创建卷。)



 a| 
池或卷组容量
 a| 
池、卷或卷组容量是指存储阵列中已分配给池或卷组的容量。此容量用于创建卷并满足副本服务操作和存储对象的各种容量需求。



 a| 
读取缓存
 a| 
读取缓存是一个缓冲区、用于存储已从驱动器读取的数据。用于读取操作的数据可能已位于上次操作的缓存中、因此无需访问驱动器。数据会一直保留在读取缓存中、直到被刷新为止。



 a| 
已报告容量
 a| 
报告的容量是指向主机报告并可由主机访问的容量。

对于厚卷、报告的容量和分配的容量相同、但对于精简卷、报告的容量和分配的容量不同。对于厚卷、物理分配的空间等于向主机报告的空间。对于精简卷、报告的容量是指向主机报告的容量、而分配的容量是指当前为写入数据而分配的驱动器空间量。



 a| 
区块大小
 a| 
区块是指存储阵列移至条带中的下一个驱动器(RAID组)之前存储在驱动器上的数据量(以千字节(KiB)为单位)。区块大小等于或小于卷组的容量。区块大小是固定的、不能为池更改。



 a| 
条带化
 a| 
条带化是一种将数据存储在存储阵列上的方式。条带化会将数据流拆分为特定大小的块(称为"块大小")、然后将这些块逐个写入驱动器。这种数据存储方式用于在多个物理驱动器之间分布和存储数据。条带化是RAID 0的同义词、它会在RAID组中的所有驱动器之间分布数据、而不进行奇偶校验。



 a| 
Volume
 a| 
卷是应用程序，数据库和文件系统用于存储数据的容器。它是为主机创建的逻辑组件，用于访问存储阵列上的存储。



 a| 
卷分配
 a| 
卷分配是将主机LUN分配给卷的方式。



 a| 
Volume name
 a| 
卷名称是指在创建卷时为其分配的字符串。您可以接受默认名称、也可以提供更具描述性的名称来指示卷中存储的数据类型。



 a| 
卷组
 a| 
卷组是具有共享特征的卷的容器。卷组已定义容量和RAID级别。您可以使用卷组创建一个或多个可供主机访问的卷。(您可以从卷组或池创建卷。)



 a| 
工作负载
 a| 
工作负载是指支持应用程序的存储对象。您可以为每个应用程序定义一个或多个工作负载或实例。对于某些应用程序、系统会将工作负载配置为包含具有类似底层卷特征的卷。这些卷特征会根据工作负载支持的应用程序类型进行优化。例如、如果您创建了一个支持Microsoft SQL Server应用程序的工作负载、然后为该工作负载创建了卷、则底层卷特征将进行优化以支持Microsoft SQL Server。



 a| 
写入缓存
 a| 
写入缓存是一个缓冲区、用于存储尚未写入驱动器的主机中的数据。数据会一直保留在写入缓存中、直到写入驱动器为止。写入缓存可以提高I/O性能。



 a| 
使用镜像进行写入缓存
 a| 
如果写入到一个控制器的缓存内存中的数据也写入到另一控制器的缓存中、则会发生具有镜像功能的写入缓存。因此、如果一个控制器发生故障、另一个控制器可以完成所有未完成的写入操作。只有在启用了写入缓存且存在两个控制器的情况下、写入缓存镜像才可用。创建卷时的默认设置是使用镜像进行写入缓存。



 a| 
无电池写入缓存
 a| 
不使用电池的写入缓存设置允许写入缓存继续运行、即使电池缺失、出现故障、已完全放电或未完全充电也是如此。通常不建议选择不带电池的写入缓存、因为断电后数据可能会丢失。通常、在电池充电或更换故障电池之前、控制器会暂时关闭写入缓存。

|===


== 特定于精简卷

[NOTE]
====
System Manager不提供创建精简卷的选项。如果要创建精简卷、请使用命令行界面(CLI)。

====
[NOTE]
====
精简卷在EF600或EF300存储系统上不可用。

====
[cols="25h,~"]
|===
| 期限 | Description 


 a| 
已分配容量限制
 a| 
已分配容量限制是指为精简卷分配的物理容量增长的上限。



 a| 
写入容量
 a| 
写入容量是指从为精简卷分配的预留容量中写入的容量。



 a| 
警告阈值
 a| 
您可以设置一个警告阈值警报、以便在为精简卷分配的容量达到全满百分比(警告阈值)时发出此警报。

|===