---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 11.90 
summary: SANtricity OS 中的新增功能。 
---
= SANtricity OS 11.90中的新增功能
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ./media/


[role="lead"]
下表介绍了SANtricity系统管理器11.9中的新增功能。



== 11.90R2中的新增功能

此版本仅包含少量更改、没有任何新功能。有关此版本中变更的详细信息，请参阅 https://library.netapp.com/ecm/ecm_download_file/ECMLP3334464["E系列11.90发行说明"^]。



== 11.90R1中的新增功能

[cols="35h,~"]
|===
| 新增功能 | Description 


 a| 
新存储系统型号—EF300C和EF600C
 a| 
此版本推出了EF300C和EF600C全闪存NVMe存储系统。EF300C和EF600C是现有EF300和EF600存储系统的高容量闪存版本。EF300C和EF600C支持30 TB或60 TB大小的高容量NVMe SSD驱动器。EF300C/EF600C仅兼容动态磁盘池、不支持原有RAID。



 a| 
支持EF4000上的12 Gb SAS接口
 a| 
E4000控制器现在支持12 Gb SAS主机接口卡。

|===


== 11.90版中的新增功能

[cols="35h,~"]
|===
| 新增功能 | Description 


 a| 
新存储系统型号— E4000
 a| 
此版本引入了E4000低成本存储系统。E4000支持12个和60个驱动器以及每个控制器一个主机接口卡(Host Interface Card、HIC)。初始版本支持的主机接口卡包括iSCSI和光纤通道。可以在Unified Manager中查看和管理E4000存储系统和其他E系列存储系统。



 a| 
增加了动态磁盘池的容量
 a| 
只要动态磁盘池(Dynamic Disk Pool、DDP)中每个驱动器的容量超过23 TB、该容量就会增加到12 PB。如果单个驱动器容量小于23 TB、则DDP容量为6 PB。



 a| 
增加了默认介质扫描设置
 a| 
默认介质扫描速率已增加到120天。



 a| 
专用密钥现在可用于外部密钥管理
 a| 
现在、可以通过System Manager导入外部通过私钥和公共密钥对生成的证书签名请求(CSR)文件。



 a| 
现在、Web服务可以使用登录锁定功能
 a| 
现在、嵌入式Web服务和代理Web服务均可使用新的登录锁定设置、该设置仅可通过REST API进行配置。

|===