---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 12.00 
summary: SANtricity OS 中的新增功能。 
---
= SANtricity OS 12.00 中的新增功能
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ./media/


[role="lead"]
下表介绍了 SANtricity System Manager 12.0 中的新功能。



== 版本 12.0R1 中的新增功能

此版本仅包含小的更改，没有新功能。有关此版本中更改的更多信息，请参见 E-Series SANtricity 操作系统 12.0R1 README。



== 版本 12.0 中的新增功能


NOTE: SANtricity OS 12.0 版本仅与新的 EF80 和 EF50 全闪存存储系统兼容。如果使用的是 SANtricity OS 11.9 或更早版本，请参阅 link:known-issues.html["已知问题"] 以获取以前版本中的新功能列表。

[cols="35h,~"]
|===
| 新增功能 | Description 


 a| 
新存储系统型号 – EF80 和 EF50 全闪存存储系统
 a| 
此版本引入了 EF80 和 EF50 全 NVMe 闪存存储系统。EF80 和 EF50 支持 24 个 NVME SSD 驱动器和每个控制器一个控制器间镜像卡。支持的 NVMe over Fabrics 主机接口包括 NVMe over RoCE、NVMe over IB、EF80 的 NVMe over FC 和 EF50 的 NVMe over FC。支持的 SCSI 接口是两个系统的光纤通道。EF50 支持每个控制器最多两个主机接口卡，而 EF80 支持每个控制器最多三个主机接口卡。

EF80 和 EF50 也支持 30TB 或 60TB 大小的大容量 NVMe SSD 驱动器。EF80 和 EF50 只能在阵列装有 30TB 或 60TB 驱动器时使用动态磁盘池。



 a| 
SANtricity System Manager 的新用户界面
 a| 
对于新的 EF80 和 EF50 控制器，SANtricity System Manager 用户界面经过重新设计，以提供更现代的外观和感觉。新界面包括左侧面板导航和增强的可用性，以简化管理任务。


NOTE: 新的用户界面目前仅适用于带有 SANtricity 12.00 版本的 EF80 和 EF50 存储系统。如果使用的是 SANtricity 11.9 或更早版本，请参阅 link:https://docs.netapp.com/us-en/e-series-santricity-119/system-manager/index.html["SANtricity系统管理器11.9."] 使用旧版用户界面的说明。



 a| 
服务器证书的使用者备用名称 (SAN) 现在仅允许字母、数字和连字符
 a| 
在 SANtricity System Manager 或 Unified Manager 中创建或编辑服务器证书时，使用者备用名称 (SAN) 字段现在只允许使用字母、数字和连字符。此更改可增强安全性，并确保与 SSL/TLS 证书的行业标准兼容。



 a| 
对于基于 SSD 和 NVMe 的系统，动态磁盘池段大小现在默认为 32K
 a| 
对于基于 SSD 和 NVMe 的系统上的动态磁盘池，默认数据段大小已更改为 32K。以前，这些系统的动态磁盘池默认段大小固定为 128K。此更改可优化涉及小型和大型 I/O 操作混合的工作负载的性能。



 a| 
现在可在 SANtricity System Manager 中使用脚本编辑器
 a| 
SANtricity System Manager 中现在提供了新的脚本编辑器。脚本编辑器允许您创建或编辑脚本文件，将脚本文件保存到存储管理站的本地磁盘，或从磁盘加载脚本文件。脚本编辑器提供用于管理存储系统的语法检查和命令执行功能。有关详细信息，请参见 link:sm-support/use-script-editor.html["使用脚本编辑器"^]。

|===