---
permalink: sm-mirroring/asynchronous-mirror-status.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, asynchronous, mirror, status, consistency, group, 
summary: 镜像状态用于定义镜像一致性组和镜像卷对的状态。 
---
= 异步镜像状态
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
镜像状态用于定义镜像一致性组和镜像卷对的状态。

[NOTE]
====
EF600或EF300存储系统不支持此功能。

====


== 镜像一致性组的状态

[cols="25h,~"]
|===
| Status | Description 


 a| 
同步(初始同步)
 a| 
在镜像卷对之间完成的初始数据同步的进度。

在初始同步期间、卷可以过渡到以下状态：已降级/失败/最佳/未知。



 a| 
同步(间隔同步)
 a| 
在镜像卷对之间完成的定期数据同步的进度。



 a| 
系统已暂停
 a| 
存储系统在镜像一致性组级别暂停同步所有镜像对上的数据。

镜像一致性组中至少有一个镜像对处于已停止或失败状态。



 a| 
用户已暂停
 a| 
在镜像一致性组级别、用户暂停同步所有镜像对上的数据。

此状态有助于减少在将本地存储阵列上的任何更改数据复制到远程存储阵列时可能对主机应用程序产生的任何性能影响。



 a| 
已暂停
 a| 
由于访问远程存储阵列时出错、数据同步过程已暂时暂停。



 a| 
孤立
 a| 
如果在一致性镜像组的一端(主端或二级端)上删除了一致性镜像组中的成员卷、而不是在另一端删除了该成员卷、则会存在孤立的镜像对卷。

在恢复阵列间通信且镜像配置的两端协调镜像参数时、系统会检测到孤立的镜像对卷。

您可以删除镜像对以更正孤立的镜像对状态。



 a| 
角色更改待定/进行中
 a| 
镜像一致性组之间的角色更改处于待定状态或正在进行中。

角色反转更改(对主角色或二级角色)会影响选定镜像一致性组中的所有异步镜像对。

您可以取消待定角色更改、但不能取消正在进行的角色更改。



 a| 
角色冲突
 a| 
在角色更改操作期间、由于本地存储阵列与远程存储阵列之间存在通信问题、镜像一致性组之间发生角色冲突。

解决通信问题后、将发生角色冲突。使用Recovery Guru从此错误中恢复。

解决角色冲突时、不允许强制升级。

|===


== 镜像对的状态

镜像对的状态指示主卷和二级卷上的数据是否已同步。

[cols="25h,~"]
|===
| Status | Description 


 a| 
正在同步
 a| 
在镜像对之间完成的初始或定期数据同步的进度。

同步有两种类型：初始同步和定期同步。初始同步进度也会显示在长时间运行操作对话框中。



 a| 
最佳
 a| 
镜像对中的卷会进行同步、这表示存储阵列之间的连接正常运行、并且每个卷都处于所需的工作状态。



 a| 
未完成
 a| 
远程存储阵列上的异步镜像对不完整、因为镜像对创建序列是在System Manager不支持的存储阵列上启动的、而镜像对尚未在二级存储阵列上完成。

将卷添加到远程存储阵列上的镜像一致性组后、镜像对创建过程完成。此卷将成为异步镜像对中的二级卷。

如果远程存储阵列由System Manager管理、则镜像对将自动完成。



 a| 
失败
 a| 
由于主卷、二级卷或镜像预留容量出现故障、异步镜像操作无法正常运行。



 a| 
孤立
 a| 
如果在一致性镜像组的一端(主端或二级端)上删除了一致性镜像组中的成员卷、而不是在另一端删除了该成员卷、则会存在孤立的镜像对卷。

在两个存储阵列之间恢复通信且镜像配置的两端协调镜像参数时、系统会检测到孤立的镜像对卷。

您可以删除镜像对以更正孤立的镜像对状态。



 a| 
已停止
 a| 
镜像对处于stopped状态、因为镜像一致性组处于系统暂停状态。

|===