---
permalink: sm-mirroring/complete-mirrored-pair-for-primary-volumes-created-on-legacy-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, complete, mirrored, pair, volumes, created, legacy, 
summary: 如果您在无法由SANtricity System Manager管理的旧存储阵列上创建了主卷、则可以使用System Manager在此阵列上创建二级卷。 
---
= 在原有系统上创建的主卷的完整镜像对
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您在旧存储阵列上创建了无法由SANtricity System Manager管理的主卷、则可以使用SANtricity System Manager在此阵列上创建二级卷。

.关于此任务
您可以在使用不同接口的原有阵列与可由System Manager管理的较新阵列之间执行异步镜像。

* 如果要在使用System Manager的两个存储阵列之间进行镜像、则可以跳过此任务、因为您已在镜像对创建序列中完成镜像对。
* 在远程存储阵列上执行此任务。


.步骤
. 选择菜单：Storage[Asynchronous Mirroring]。
. 选择*镜像对*选项卡。
+
此时将显示镜像对表、并显示与存储阵列关联的所有镜像对。

. 找到状态为未完成的镜像对卷、然后单击镜像对列中显示的*完整镜像对*链接。
. 选择以下单选按钮之一、选择是要自动还是手动完成镜像对创建序列：
+
** *自动*—创建新的二级卷。
+
通过选择要在其中创建二级卷的现有池或卷组、接受镜像对远程端的默认设置。使用此建议选项可使用默认设置为二级卷分配预留容量。

** *手动*-选择现有卷。
+
为二级卷定义您自己的参数。

+
... 单击*下一步*以选择二级卷。
... 选择要用作二级卷的现有卷、然后单击*下一步*以分配预留容量。
... 分配预留容量。执行以下操作之一：
+
**** 接受默认设置。
+
预留容量的默认设置为基础卷容量的20%、通常此容量已足够。

**** 分配您自己的预留容量设置、以满足与异步镜像相关的数据存储需求。
+
所需容量因向主卷写入I/O的频率和大小以及保留容量所需的时间而异。通常、如果存在以下一种或两种情况、请为预留容量选择更大的容量：

+
***** 您打算将镜像对保留很长时间。
***** 由于I/O活动繁重、主卷上的数据块会发生很大一部分更改。使用历史性能数据或其他操作系统实用程序帮助您确定主卷的典型I/O活动。








. 选择*完成*。


.结果
System Manager将执行以下操作：

* 在远程存储阵列上创建二级卷、并为镜像对的远程端分配预留容量。
* 开始在本地存储阵列和远程存储阵列之间进行初始同步。
* 如果要镜像的卷是精简卷、则在初始同步期间、只会将分配的块传输到二级卷。此传输可减少完成初始同步所需传输的数据量。
* 在本地存储阵列和远程存储阵列上为镜像对创建预留容量。

