---
permalink: sm-mirroring/faq-async-mirroring.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= SANtricity System Manager 异步镜像常见问题解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== 异步镜像与同步镜像有何不同？

异步镜像功能与同步镜像功能在一个基本方面有所不同：它可以捕获源卷在特定时间点的状态、并仅复制自上次映像捕获以来发生更改的数据。

使用同步镜像时、不会在某个时间点捕获主卷的状态、而是反映主卷上对二级卷所做的所有更改。二级卷每次与主卷相同、因为使用此类镜像时、每次对主卷执行写入时、都会对二级卷执行写入。在使用主卷上所做的更改成功更新二级卷之前、主机不会收到写入成功的确认。

使用异步镜像时、远程存储阵列与本地存储阵列未完全同步、因此、如果应用程序因丢失本地存储阵列而需要过渡到远程存储阵列、则某些事务可能会丢失。

镜像功能之间的比较：

[cols="1a,1a"]
|===
| 异步镜像 | 同步镜像 


 a| 
*复制方法*



 a| 
* *时间点*
+
镜像可按需执行、也可根据用户定义的计划自动执行。可以按分钟的粒度定义计划。两次同步的最短时间为10分钟。


 a| 
* *持续*
+
镜像会自动持续执行、每次写入主机时都会复制数据。





 a| 
*预留容量*



 a| 
* *多个*
+
每个镜像对都需要一个预留容量的卷。


 a| 
* * 单个 *
+
所有镜像卷都需要一个预留容量卷。





 a| 
*通信*



 a| 
* * iSCSI和光纤通道*
+
支持存储阵列之间的iSCSI和光纤通道接口。


 a| 
* *光纤通道*
+
仅支持存储阵列之间的光纤通道接口。





 a| 
*距离*



 a| 
* *无限制*
+
支持在本地存储阵列和远程存储阵列之间设置几乎无限的距离、而距离通常仅受网络功能和通道扩展技术的限制。


 a| 
* *受限*
+
通常、距离本地存储阵列不超过10公里(6.2英里)、以满足延迟和应用程序性能要求。



|===


== 为什么我无法访问我选择的镜像功能？

镜像可在SANtricity统一管理器界面中配置。

[NOTE]
====
EF600/EF600C或EF300/EF300C存储阵列不支持同步镜像。

====
要在两个阵列之间启用和配置镜像、请验证以下内容：

* Web服务代理服务必须正在运行。(Unified Manager与Web服务代理一起安装在主机系统上。)
* Unified Manager必须通过HTTPS连接在本地主机上运行。
* 必须在Unified Manager中发现要用于镜像的两个存储阵列。
* Unified Manager必须具有适用于存储阵列的有效SSL证书。您可以从Unified Manager接受自签名证书或安装CA签名证书。


有关配置说明、请参见以下内容：

* link:../um-manage/create-asynchronous-mirrored-pair-um.html["创建异步镜像对(在Unified Manager中)"]
* link:../um-manage/create-synchronous-mirrored-pair-um.html["创建同步镜像对(在Unified Manager中)"]




== 在创建镜像一致性组之前、我需要了解哪些信息？

在创建镜像一致性组之前、请遵循以下准则。

[NOTE]
====
EF600/EF600C或EF300/EF300C存储系统不支持同步镜像。

====
您可以在Unified Manager中的创建镜像对向导中创建一致性组。

满足以下Unified Manager要求：

* Web服务代理服务必须正在运行。
* Unified Manager必须通过HTTPS连接在本地主机上运行。
* Unified Manager必须显示存储阵列的有效SSL证书。您可以使用Unified Manager接受自签名证书或安装自己的安全证书、并导航到菜单：Certificate[证书管理]。


此外、请确保满足以下存储阵列要求：

* 必须在Unified Manager中发现这两个存储阵列。
* 每个存储阵列必须具有两个控制器。
* 主阵列和二级阵列中的每个控制器都必须配置一个以太网管理端口、并且必须连接到您的网络。
* 存储阵列的最低固件版本为7.84。(它们可以分别运行不同的操作系统版本。)
* 您必须知道本地和远程存储阵列的密码。
* 本地和远程存储阵列通过光纤通道网络结构或iSCSI接口进行连接。




== 异步镜像—在创建镜像对之前、我需要了解哪些信息？

您可以在SANtricity统一管理器界面中配置镜像对、然后在SANtricity系统管理器中管理这些对。

创建镜像对之前、请遵循以下准则。

* 您必须有两个存储阵列。
* 每个存储阵列必须具有两个控制器。
* 主阵列和二级阵列中的每个控制器都必须配置一个以太网管理端口、并且必须连接到您的网络。
* 本地和远程存储阵列通过光纤通道网络结构或iSCSI接口进行连接。
* 存储阵列的最低固件版本为7.84。(它们可以分别运行不同的操作系统版本。)
* 您必须知道本地和远程存储阵列的密码。
* 您必须在远程存储阵列上具有足够的可用容量、才能创建一个等于或大于要镜像的主卷的二级卷。
* 您已安装Web服务代理和Unified Manager。镜像对在Unified Manager界面中进行配置。
* 这两个存储阵列会在Unified Manager中发现。
* 存储阵列必须至少包含一个镜像一致性组。您可以在Unified Manager中的创建镜像对向导中创建一致性组。




== 在增加镜像对卷上的预留容量之前、我需要了解哪些信息？

通常、当您收到警告、指出镜像对的预留容量已满时、应增加预留容量。您只能以8 GiB为增量增加预留容量。

对于异步镜像操作、预留容量通常为基础卷的20%。如果存在以下一种或两种情况、请为预留容量选择更大的容量：

* 您打算将镜像对保留很长时间。
* 由于I/O活动繁重、主卷上的数据块会发生很大一部分更改。使用历史性能数据或其他操作系统实用程序帮助您确定主卷的典型I/O活动。


您可以通过执行以下操作之一来增加镜像对的预留容量：

* 通过选择菜单：Storage[池和卷组]并单击*预留容量*选项卡来调整镜像对卷的容量百分比。
* 使用池或卷组上的可用容量创建新卷。
+
如果任何池或卷组上没有可用容量、则可以将未配置的容量以未使用驱动器的形式添加到池或卷组中。





== 为什么我无法将预留容量增加到我请求的数量？

您只能以4 GiB为增量增加预留容量。

请查看以下准则：

* 池或卷组中必须有足够的可用容量、以便可以根据需要进行扩展。
+
如果任何池或卷组上没有可用容量、则可以将未使用的驱动器形式的未分配容量添加到池或卷组中。

* 池或卷组中的卷必须处于最佳状态、并且不能处于任何修改状态。
* 要用于增加容量的池或卷组中必须存在可用容量。


对于异步镜像操作、预留容量通常为基础卷的20%。如果您认为基础卷会发生许多更改、或者存储对象的复制服务操作的预计预期寿命很长、请使用较高的百分比。



== 为什么要更改此百分比？

对于快照操作、预留容量通常为基础卷的40%、对于异步镜像操作、预留容量通常为基础卷的20%。

通常、此容量足以满足要求。所需容量因向基础卷写入I/O的频率和大小以及要使用存储对象的副本服务操作的时间而异。

通常、如果存在以下一种或两种情况、请选择较大的预留容量百分比：

* 如果特定存储对象的复制服务操作的生命周期很长。
* 如果由于I/O活动繁重而导致基础卷上的大量数据块发生更改、使用历史性能数据或其他操作系统实用程序帮助您确定基础卷的典型I/O活动。




== 为什么我会看到多个预留容量候选项？

如果一个池或卷组中有多个卷满足为存储对象选择的容量百分比量、则会显示多个候选卷。

您可以通过更改要在基础卷上为复制服务操作预留的物理驱动器空间百分比来刷新建议候选对象列表。根据您的选择显示最佳候选对象。



== 为什么表中显示的值不可用？

此表列出了无法显示远程存储阵列上的数据时的不可用值。

要显示远程存储阵列数据、请从Unified Manager启动System Manager。



== 为什么我看不到所有的池和卷组？

为异步镜像对创建二级卷时、系统会显示一个列表、其中列出了该异步镜像对符合条件的所有池和卷组。不符合使用条件的任何池或卷组不会显示在该列表中。

由于以下任何原因、池或卷组可能不符合条件。

* 池或卷组的安全功能不匹配。
* 池或卷组处于非最佳状态。
* 池或卷组的容量太小。




== 异步镜像 - 为什么我看不到所有卷？

为镜像对选择主卷时、列表将显示所有符合条件的卷。

不符合使用条件的任何卷不会显示在该列表中。由于以下任一原因、卷可能不符合条件：

* 此卷不是最佳卷。
* 此卷已加入镜像关系。
* 对于精简卷、必须启用自动扩展。



NOTE: 对于EF600和EF300控制器、异步镜像对中的主卷和二级卷必须匹配相同的协议、托盘级别、区块大小、安全类型和RAID级别。不符合条件的异步镜像对不会显示在可用卷列表中。



== 异步镜像 - 为什么我看不到远程存储阵列上的所有卷？

在远程存储阵列上选择二级卷时、列表将显示该镜像对的所有符合条件的卷。

不符合使用条件的任何卷不会显示在该列表中。由于以下任一原因、卷可能不符合条件：

* 此卷不是最佳卷。
* 此卷已加入镜像关系。
* 主卷与二级卷之间的精简卷属性不匹配。
* 如果您使用的是数据保证(Data Assurance、DA)、则主卷和二级卷必须具有相同的DA设置。
+
** 如果主卷已启用DA、则二级卷必须已启用DA。
** 如果主卷未启用DA、则二级卷不能启用DA。






== 为什么要更新远程存储阵列的 IP 地址？

如果iSCSI端口的IP地址发生变化、而本地存储阵列无法与远程存储阵列通信、则可以更新远程存储阵列的IP地址。

在与iSCSI连接建立异步镜像关系时、本地和远程存储阵列会在异步镜像配置中存储远程存储阵列的IP地址记录。如果iSCSI端口的IP地址发生变化、尝试使用该端口的远程存储阵列将遇到通信错误。

IP地址已更改的存储阵列会向与配置为通过iSCSI连接进行镜像的镜像一致性组关联的每个远程存储阵列发送一条消息。接收此消息的存储阵列会自动更新其远程目标IP地址。

如果IP地址已更改的存储阵列无法向远程存储阵列发送其阵列间消息、则系统会向您发送连接问题描述 警报。使用Update Remote IP Address选项重新与本地存储阵列建立连接。
