---
permalink: sm-mirroring/faq-sync-mirroring.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= SANtricity System Manager 同步镜像常见问题解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== 异步镜像与同步镜像有何不同？

异步镜像功能与同步镜像功能在一个基本方面有所不同：它可以捕获源卷在特定时间点的状态、并仅复制自上次映像捕获以来发生更改的数据。

使用同步镜像时、不会在某个时间点捕获主卷的状态、而是反映主卷上对二级卷所做的所有更改。二级卷每次与主卷相同、因为使用此类镜像时、每次对主卷执行写入时、都会对二级卷执行写入。在使用主卷上所做的更改成功更新二级卷之前、主机不会收到写入成功的确认。

使用异步镜像时、远程存储阵列与本地存储阵列未完全同步、因此、如果应用程序因丢失本地存储阵列而需要过渡到远程存储阵列、则某些事务可能会丢失。

镜像功能之间的比较：

[cols="1a,1a"]
|===
| 异步镜像 | 同步镜像 


 a| 
*复制方法*



 a| 
* *时间点*
+
镜像可按需执行、也可根据用户定义的计划自动执行。可以按分钟的粒度定义计划。两次同步的最短时间为10分钟。


 a| 
* *持续*
+
镜像会自动持续执行、每次写入主机时都会复制数据。





 a| 
*预留容量*



 a| 
* *多个*
+
每个镜像对都需要一个预留容量的卷。


 a| 
* * 单个 *
+
所有镜像卷都需要一个预留容量卷。





 a| 
*通信*



 a| 
* * iSCSI和光纤通道*
+
支持存储阵列之间的iSCSI和光纤通道接口。


 a| 
* *光纤通道*
+
仅支持存储阵列之间的光纤通道接口。





 a| 
*距离*



 a| 
* *无限制*
+
支持在本地存储阵列和远程存储阵列之间设置几乎无限的距离、而距离通常仅受网络功能和通道扩展技术的限制。


 a| 
* *受限*
+
通常、距离本地存储阵列不超过10公里(6.2英里)、以满足延迟和应用程序性能要求。



|===


== 同步镜像 - 为什么我看不到所有卷？

为镜像对选择主卷时、列表将显示所有符合条件的卷。

不符合使用条件的任何卷不会显示在该列表中。由于以下任一原因、卷可能不符合条件：

* 此卷是非标准卷、例如Snapshot卷或精简卷。
* 此卷不是最佳卷。
* 此卷已加入镜像关系。




== 同步镜像 - 为什么我看不到远程存储阵列上的所有卷？

在远程存储阵列上选择二级卷时、列表将显示该镜像对的所有符合条件的卷。

不符合使用条件的任何卷不会显示在该列表中。由于以下任一原因、卷可能不符合条件：

* 此卷是非标准卷、例如Snapshot卷或精简卷。
* 此卷不是最佳卷。
* 此卷已加入镜像关系。
* 如果您使用的是数据保证(Data Assurance、DA)、则主卷和二级卷必须具有相同的DA设置。
+
** 如果主卷已启用DA、则二级卷必须已启用DA。
** 如果主卷未启用DA、则二级卷不能启用DA。






== 同步镜像—在创建镜像对之前、我需要了解哪些信息？

您可以在SANtricity统一管理器界面中配置镜像对、然后在SANtricity系统管理器中管理这些对。

创建镜像对之前、请遵循以下准则：

* 您必须有两个存储阵列。
* 每个存储阵列必须具有两个控制器。
* 主阵列和二级阵列中的每个控制器都必须配置一个以太网管理端口、并且必须连接到您的网络。
* 本地和远程存储阵列通过光纤通道网络结构进行连接。
* 存储阵列的最低固件版本为7.84。(它们可以分别运行不同的操作系统版本。)
* 您必须知道本地和远程存储阵列的密码。
* 您必须在远程存储阵列上具有足够的可用容量、才能创建一个等于或大于要镜像的主卷的二级卷。
* 您已安装Web服务代理和Unified Manager。镜像对在Unified Manager界面中进行配置。
* 这两个存储阵列会在Unified Manager中发现。




== 同步优先级对同步速率有何影响？

同步优先级用于定义为同步活动分配的处理时间与系统性能相关。

主卷的控制器所有者在后台执行此操作。同时、控制器所有者会处理对主卷的本地I/O写入以及对二级卷的相关远程写入。由于重新同步会使控制器处理资源偏离I/O活动、因此重新同步可能会影响主机应用程序的性能。

请牢记以下准则、以帮助您确定同步优先级可能需要多长时间以及同步优先级如何影响系统性能。

.关于同步优先级速率
[%collapsible]
====
可以使用以下优先级：

* 最低
* 低
* 中等
* 高
* 最高


最低优先级速率支持系统性能、但重新同步所需时间较长。最高优先级速率支持重新同步、但系统性能可能会受到影响。

====
这些准则大致近似于优先级之间的差异。

[cols="35h,~"]
|===
| 完全同步的优先级速率 | 与最高同步速率相比所用时间 


 a| 
最低
 a| 
约为最高优先级速率的八倍。



 a| 
低
 a| 
约为最高优先级速率的六倍。



 a| 
中等
 a| 
大约是最高优先级速率的三倍半。



 a| 
高
 a| 
大约是最高优先级速率时的两倍。

|===
卷大小和主机I/O速率负载会影响同步时间比较。



== 为什么建议使用手动同步策略？

建议使用手动重新同步、因为它可以让您以最佳机会恢复数据的方式管理重新同步过程。

如果使用自动重新同步策略、并且在重新同步期间发生间歇性通信问题、则二级卷上的数据可能会暂时损坏。重新同步完成后、数据将得到更正。
