---
permalink: sm-mirroring/role-change-of-a-mirror-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, role, change, mirror, consistency, group, secondary, mirror, consistency, group, 
summary: 您可以更改镜像一致性组中镜像对之间的角色。为此、您可以将主镜像一致性组降级为二级角色、或者将二级镜像一致性组提升为主角色。 
---
= 镜像一致性组的角色更改
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以更改镜像一致性组中镜像对之间的角色。为此、您可以将主镜像一致性组降级为二级角色、或者将二级镜像一致性组提升为主角色。

[NOTE]
====
EF600或EF300存储系统不支持此功能。

====
查看有关角色更改操作的以下信息：

* 角色更改会影响选定镜像一致性组中的所有镜像对。
* 当镜像一致性组降级到二级角色时、该镜像一致性组中的所有镜像对也会降级到二级角色、反之亦然。
* 当主镜像一致性组降级为二级角色时、已分配给该组中成员卷的主机将不再具有对其的写入访问权限。
* 将镜像一致性组提升为主角色后、访问该组中成员卷的所有主机现在都可以向其写入数据。
* 如果本地存储阵列无法与远程存储阵列通信、您可以在本地存储阵列上强制更改角色。




== 强制更改角色

如果本地存储阵列与远程存储阵列之间的通信问题阻止提升二级镜像一致性组中的成员卷或使主镜像一致性中的成员卷降级、则可以强制更改镜像一致性组之间的角色 组。

您可以强制二级端上的镜像一致性组过渡到主角色。之后、恢复主机便可访问该镜像一致性组中新提升的成员卷、业务运营便可继续进行。



== 何时允许和不允许强制促销？

只有在镜像一致性组的所有成员卷均已同步且具有一致的恢复点时、才允许强制提升镜像一致性组。

在以下情况下、不允许强制提升镜像一致性组：

* 镜像一致性组的任何成员卷都正在进行初始同步。
* 镜像一致性组的任何成员卷都没有恢复点的时间点映像(例如、由于预留的容量全满错误)。
* 镜像一致性组不包含成员卷。
* 镜像一致性组处于Failed、Role-Change-Pending或Role-Change-in-progress状态、或者任何关联成员卷或预留容量卷出现故障。




== 镜像组角色冲突

解决本地和远程存储阵列之间的通信问题后、将发生镜像组角色冲突情况。使用Recovery Guru从此错误中恢复。解决双重角色冲突时、不允许强制升级。

要避免出现镜像组角色冲突情况并执行后续恢复步骤、请等待存储阵列之间的连接正常运行、以强制更改角色。



== 角色更改正在进行中状态

如果镜像配置中的两个存储阵列断开连接、并且镜像一致性组的主端强制降级为二级角色、而镜像一致性组的二级端强制提升为主角色、 然后、在恢复通信后、两个存储阵列上的镜像一致性组将置于Role-Change-in-progress状态。

系统将通过传输更改日志、重新同步、将镜像一致性组状态设置回正常运行状态以及继续定期同步来完成角色更改过程。
