---
permalink: sm-mirroring/role-change-of-volumes-in-a-mirrored-pair.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, role, change, between, volume, mirrored, pair, 
summary: 您可以更改镜像对中卷之间的角色。为此、您可以将主卷降级为二级角色或将二级卷提升为主角色。 
---
= 镜像对中的卷之间的角色更改
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以更改镜像对中卷之间的角色。为此、您可以将主卷降级为二级角色或将二级卷提升为主角色。

[NOTE]
====
EF600或EF300存储系统不支持此功能。

====
查看有关角色更改操作的以下信息：

* 当主卷降级为二级角色时、该镜像对中的二级卷将提升为主角色、反之亦然。
* 当主卷降级为二级角色时、已分配给该卷的主机将不再具有对该卷的写入访问权限。
* 当二级卷提升为主角色时、访问该卷的所有主机现在都能够向该卷写入数据。
* 如果本地存储阵列无法与远程存储阵列通信、您可以在本地存储阵列上强制更改角色。




== 强制更改角色

如果本地存储阵列与远程存储阵列之间的通信问题导致无法提升二级卷或使主卷降级、则可以强制在镜像对中的卷之间更改角色。

您可以强制二级卷过渡到主角色。然后、恢复主机可以访问新提升的卷、业务运营可以继续进行。

[NOTE]
====
当远程存储阵列已恢复且任何通信问题均已解决时、将发生同步镜像-主卷冲突情况。恢复步骤包括重新同步卷。使用Recovery Guru从此错误中恢复。

====


== 何时允许和不允许强制促销？

在以下情况下、不允许强制提升镜像对中的卷：

* 镜像对中的任何卷都正在进行初始同步。
* 镜像对处于Failed、Role-Change-Pending或Role-Change-in-progress状态、或者任何关联的预留容量卷出现故障。




== 角色更改正在进行中状态

如果镜像配置中的两个存储阵列断开连接、并且镜像对的主卷强制降级为二级角色、而镜像对的二级卷强制提升为主角色、 然后、在恢复通信后、两个存储阵列上的卷将置于Role-Change-in-progress状态。

系统将通过传输更改日志、重新同步、将镜像对状态设置回正常运行状态以及继续同步来完成角色更改过程。
