---
permalink: sm-mirroring/test-communication-for-mirror-consistency-groups.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, test, communication, mirror, consistency, groups, 
summary: 您可以测试通信链路、以诊断本地存储阵列与与镜像一致性组关联的远程存储阵列之间可能存在的通信问题。 
---
= 测试镜像一致性组的通信
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以测试通信链路、以诊断本地存储阵列与与镜像一致性组关联的远程存储阵列之间可能存在的通信问题。

.开始之前
要测试的镜像一致性组必须位于本地和远程存储阵列上。

.关于此任务
您可以运行四种不同的测试：

* *连接*-验证两个控制器是否具有通信路径。连接测试会在存储阵列之间发送一条阵列间消息、然后验证远程存储阵列上的相应镜像一致性组是否存在。它还会验证远程存储阵列上的镜像一致性组的成员卷是否与本地存储阵列上的镜像一致性组的成员卷匹配。
* *延迟*-向与镜像一致性组关联的远程存储阵列上的每个镜像卷发送SCSI测试单元命令、以测试最小、平均和最大延迟。
* *带宽*—向远程存储阵列发送两条阵列间消息、以测试执行测试的阵列上端口的最小、平均和最大带宽以及协商的链路速度。
* *端口连接*-显示本地存储阵列上用于镜像的端口以及远程存储阵列上接收镜像数据的端口。


.步骤
. 选择菜单：Storage[Asynchronous Mirroring]。
. 选择*镜像一致性组*选项卡、然后选择要测试的镜像一致性组。
. 选择*测试通信*。
+
此时将显示测试通信对话框。

. 选择一个或多个要在与选定镜像一致性组关联的本地和远程存储阵列之间执行的通信测试、然后单击*测试*。
. 查看结果窗口中显示的信息。
+
[cols="35h,~"]
|===
| 通信测试状态 | Description 


 a| 
正常、无错误
 a| 
镜像一致性组正在正确通信。



 a| 
已通过状态(但不正常)
 a| 
请检查可能的网络或连接问题、然后重试此测试。



 a| 
失败状态
 a| 
指示失败的原因。要更正此问题、请参见Recovery Guru。



 a| 
端口连接错误
 a| 
原因可能是本地存储阵列未连接或无法联系远程存储阵列。要更正此问题、请参见Recovery Guru。

|===


.结果
通信测试完成后、此对话框将显示正常状态、已通过状态或失败状态。

如果通信测试返回失败状态、则在关闭此对话框后、此测试将继续运行、直到镜像一致性组之间的通信恢复为止。
