---
permalink: sm-interface/administrator-password-protection.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, admin password 
summary: 您必须使用管理员密码配置存储阵列、以防止其遭受未经授权的访问。 
---
= 在 SANtricity System Manager 中管理密码保护
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须为存储阵列配置密码、以防止其遭受未经授权的访问。



== 设置和更改密码

首次启动System Manager时、系统会提示您设置管理员密码。具有管理员密码的任何用户都可以对存储阵列进行配置更改、例如添加、更改或删除对象或设置。要在初始启动期间设置管理员密码、请参见 link:../san-getstarted/access-sam.html["访问System Manager"]。

出于安全原因、您只能在存储阵列进入"锁定"状态之前尝试输入五次密码。在此状态下、存储阵列将拒绝后续的密码尝试。您必须等待10分钟、使存储阵列重置为"正常"状态、然后才能再次尝试输入密码。

除了管理员密码之外、存储阵列还包括预定义的用户配置文件、其中包含一个或多个映射到这些配置文件的角色。有关详细信息，请参见 link:../sm-settings/permissions-for-mapped-roles.html["映射角色的权限"]。无法更改用户配置文件和映射。只能修改密码。如果要更改管理员密码或其他用户密码、请参见 link:../sm-settings/change-passwords.html["更改密码"]。



== 在会话超时后重新输入密码

系统仅会在单个管理会话期间提示您输入密码一次。但是、如果会话处于非活动状态30分钟、则会超时、此时您必须再次输入密码。如果从另一个管理客户端管理同一存储阵列的另一用户在会话期间更改了密码、则在下次尝试配置操作或查看操作时、系统会提示您输入密码。

您可以调整会话超时、也可以完全禁用会话超时。请参见 link:../sm-settings/manage-session-timeouts-sam.html["管理会话超时"]。



== 删除驱动器或密码保护

如果删除受密码保护的驱动器或要禁用密码保护、请注意以下事项：

* *如果删除具有密码保护的驱动器*-密码存储在存储阵列上每个驱动器的保留区域。如果从存储阵列中删除所有驱动器、则其密码将不再起作用。要更正此情况、请将原始驱动器之一重新安装到存储阵列。
* *如果要删除密码保护*-如果您不再希望命令受密码保护、请输入当前管理员密码、并将新密码文本框留空。


[CAUTION]
====
在存储阵列上运行配置命令可能会造成发生原因 严重损坏、包括数据丢失。因此、您应始终为存储阵列设置管理员密码。请使用长度较长的管理员密码并至少包含15个字母数字字符、以提高安全性。

====