---
permalink: sm-interface/faq-storage-system-setup.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= SANtricity System Manager 的存储系统设置常见问题解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== 如果我没有看到所有硬件组件怎么办？

如果验证硬件对话框中未显示所有硬件组件、则可能表示驱动器架连接不正确或存储阵列中安装了不兼容的磁盘架。

验证所有驱动器架是否均已正确连接。如果您不确定哪些驱动器架兼容、请联系技术支持。



== 如果我没有看到所有主机怎么办？

如果未看到已连接的主机、则自动检测失败、主机连接不正确或当前未连接任何主机。

完成设置后、您可以稍后配置主机。您可以按如下所示手动创建主机：

* 您可以转到菜单：Storage[Hosts]手动创建主机并关联相应的主机端口标识符。手动创建的主机也会显示在*初始设置*向导中。
* 必须为目标和主机配置主机端口类型(例如、iSCSI或基于RoCE的NVMe)、并且在自动检测之前与存储建立的会话将起作用。




== 识别应用程序如何帮助我管理存储阵列？

在确定应用程序时、SANtricity系统管理器会自动根据应用程序类型建议可优化存储的卷配置。

按应用程序优化卷可以提高数据存储操作的效率。卷配置包括I/O类型、区块大小、控制器所有权以及读写缓存等特征。此外、您还可以按应用程序和工作负载查看性能数据、以评估应用程序及其关联工作负载的延迟、IOPS和MiB/秒数。



== 什么是工作负载？

对于网络中的某些应用程序、例如SQL Server或Exchange、您可以定义一个工作负载来优化该应用程序的存储。

工作负载是指支持应用程序的存储对象。您可以为每个应用程序定义一个或多个工作负载或实例。对于某些应用程序、系统会将工作负载配置为包含具有类似底层卷特征的卷。这些卷特征会根据工作负载支持的应用程序类型进行优化。例如、如果您创建了一个支持Microsoft SQL Server应用程序的工作负载、然后为该工作负载创建了卷、则底层卷特征将进行优化以支持Microsoft SQL Server。

在创建卷期间、系统会提示您回答有关工作负载使用情况的问题解答 问题。例如、如果要为Microsoft Exchange创建卷、系统会询问您需要多少邮箱、平均邮箱容量要求是多少以及所需数据库副本的数量。系统会使用此信息为您创建最佳卷配置、您可以根据需要对其进行编辑。



== 如何配置AutoSupport 的交付方法？

要访问AutoSupport 交付方法的配置任务、请转到菜单：Support[支持中心]、然后单击* AutoSupport *选项卡。

支持以下协议：HTTPS和SMTP。



== 如何知道是否应接受建议的池配置？

是否接受建议的池配置取决于几个因素。

回答以下问题、确定最符合您要求的存储类型：

* 您是否更喜欢容量较小的多个池、而不是可能的最大池？
* 您是否更喜欢RAID卷组而不是池？
* 您是否更愿意手动配置驱动器、而不是建议您使用的配置？


如果您对上述任一问题回答是、请考虑拒绝建议的池配置。



== SANtricity系统管理器未检测到任何主机。我该怎么办？

如果未看到已连接的主机、则自动检测失败、主机连接不正确或当前未连接任何主机。

完成设置后、您可以稍后配置主机。您可以按如下所示手动创建主机：

* 您可以转到菜单：Storage[Hosts]手动创建主机并关联相应的主机端口标识符。手动创建的主机也会显示在*初始设置*向导中。
* 必须为目标和主机配置主机端口类型(例如、iSCSI或基于RoCE的NVMe)、并且在自动检测之前与存储建立的会话将起作用。

