---
permalink: sm-interface/faq-management-interface.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= SANtricity System Manager 管理界面常见问题解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== 支持哪些浏览器？

SANtricity系统管理器支持这些浏览器版本。

[cols="1a,1a"]
|===
| 浏览器 | 最低版本 


 a| 
Google Chrome
 a| 
81.



 a| 
Mozilla Firefox
 a| 
80



 a| 
Safari
 a| 
14.



 a| 
Microsoft Edge
 a| 
90

|===


== 什么是键盘快捷键？

您可以仅使用键盘在SANtricity系统管理器中导航。



=== 整体导航

[cols="1a,1a"]
|===
| Action | 键盘快捷方式 


 a| 
移至下一项。
 a| 
选项卡



 a| 
移至上一项。
 a| 
Shift + Tab



 a| 
选择一个项目。
 a| 
输入 ...



 a| 
下拉列表—移动到下一个或上一个项目。
 a| 
向下箭头或向上箭头



 a| 
复选框—选择一个项目。
 a| 
空格键



 a| 
单选按钮—在项目之间切换。
 a| 
向下箭头或向上箭头



 a| 
可扩展文本—展开或缩减项目。
 a| 
输入 ...

|===


=== 表导航

[cols="1a,1a"]
|===
| Action | 键盘快捷方式 


 a| 
选择一行。
 a| 
按Tab键选择行、然后按Enter键



 a| 
向上或向下滚动。
 a| 
向下箭头/向上箭头或向下翻页/向上翻页



 a| 
更改列的排序顺序。
 a| 
按Tab键选择列标题、然后按Enter键

|===


=== 日历导航

[cols="1a,1a"]
|===
| Action | 键盘快捷方式 


 a| 
移至上个月。
 a| 
向上翻页



 a| 
移至下个月。
 a| 
下一页



 a| 
移至上一年。
 a| 
Control + Page Up



 a| 
迁移到下一年。
 a| 
Control + Page Down



 a| 
如果已关闭、请打开日期选择器。
 a| 
控制+主页



 a| 
移至当前月份。
 a| 
控制/命令+主页



 a| 
移至前一天。
 a| 
控制/命令+左侧



 a| 
移至第二天。
 a| 
控制/命令+右



 a| 
移至上一周。
 a| 
控制/命令+启动



 a| 
移至下一周。
 a| 
控制/命令+关闭



 a| 
选择关注的日期。
 a| 
输入 ...



 a| 
关闭日期选择器并擦除日期。
 a| 
控制/命令+结束



 a| 
关闭日期选择器而不进行选择。
 a| 
转义

|===


== 各个卷的性能统计信息与总数有何关系？

池和卷组的统计信息是通过聚合所有卷计算得出的、包括预留容量卷。

预留容量由存储系统内部使用、用于支持精简卷、快照和异步镜像、不会对I/O主机可见。因此、池、控制器和存储阵列统计信息的总和可能不等于可查看卷的总和。

但是、对于应用程序和工作负载统计信息、只会聚合可见的卷。



== 为什么数据在图形和表中显示为零？

如果在图形和表中为某个数据点显示零、则表示该对象在该时间点没有I/O活动。发生这种情况的原因可能是主机未向该对象启动I/O、或者该对象本身存在问题。

仍可查看对象的历史数据。一旦对象开始发生I/O活动、图形和表将显示非零数据。

下表列出了任何给定对象的数据点值可能为零的最常见原因。

[cols="25h,~"]
|===
| 阵列级别的对象类型 | 原因数据显示为零 


 a| 
Volume
 a| 
* 卷未分配主机。




 a| 
卷组
 a| 
* 正在导入卷组。
* 卷组不包含分配给主机的卷、*卷组和_*卷组不包含任何预留容量。




 a| 
驱动器
 a| 
* 驱动器出现故障。
* 已删除驱动器。
* 驱动器处于未知状态。




 a| 
控制器
 a| 
* 控制器已脱机。
* 控制器出现故障。
* 已删除控制器。
* 控制器处于未知状态。




 a| 
存储阵列
 a| 
* 存储阵列不包含卷。


|===


== 延迟图显示了什么内容？

延迟图形可提供卷、卷组、池的延迟统计信息、以毫秒(ms)为单位。 应用程序和工作负载。此图形显示在逻辑视图、物理视图以及应用程序和工作负载视图选项卡中。

延迟是指读取或写入数据时发生的任何延迟。将光标悬停在图形上的某个点上、可查看该时间点的以下值(以毫秒(ms)为单位)：

* 读取时间。
* 写入时间。
* 平均I/O大小。




== IOPS图显示了什么？

IOPS图显示每秒输入/输出操作的统计信息。在主页页面上、此图显示存储阵列的统计信息。在性能图块的逻辑视图、物理视图以及应用程序和工作负载视图选项卡中、此图显示存储阵列、卷、卷组、池、应用程序、 和工作负载。

IOPS是_input/output (I/O) operations per second_的缩写。将光标悬停在图形上的某个点上、可查看该时间点的以下值：

* 读取操作的数量。
* 写入操作的数量。
* 读取和写入操作总数的总和。




== MIB/s图显示什么？

MIB/s图以每秒兆字节为单位显示传输速度统计信息。在主页页面上、此图显示存储阵列的统计信息。在性能图块的逻辑视图、物理视图以及应用程序和工作负载视图选项卡中、此图显示存储阵列、卷、卷组、池、应用程序、 和工作负载。

MiB/秒是_mebibytes per second_的缩写、即1、048、576字节/秒。将光标悬停在图形上的某个点上、可查看该时间点的以下值：

* 读取的数据量。
* 写入的数据量。
* 读取和写入的总数据量。




== CPU图形显示了什么？

CPU图形显示了每个控制器(控制器A和控制器B)的处理容量统计信息。CPU是_central processing unit_的缩写。在主页页面上、此图显示存储阵列的统计信息。在性能图块的物理视图选项卡上、此图显示存储阵列和驱动器的统计信息。

CPU图形显示了阵列上的操作所使用的CPU处理容量百分比。即使没有发生外部I/O、CPU利用率百分比也可以不为零、因为存储操作系统可能正在执行后台操作和监控。将光标悬停在图形上的某个点上、可查看该时间点所使用的处理能力百分比。



== 性能余量图显示了哪些内容？

性能余量图与存储阵列控制器的剩余性能功能相关。此图形可在主页页面和性能图块的物理视图选项卡上查看。

性能余量图显示了存储系统中物理对象的剩余性能。将光标悬停在图中的某个点上方、可查看控制器A和控制器B的剩余IOPS和MiB/秒功能百分比



== 在哪里可以找到有关显示首选项的详细信息？

要查找有关可用显示选项的信息、请执行以下操作：

* 要阅读有关显示容量值的默认单位的详细信息、请参见 link:set-default-units-for-capacity-values.html["设置容量值的默认单位"]。
* 要阅读有关显示性能图形的默认时间范围的详细信息、请参见 link:set-default-time-frame-for-performance-graphs.html["设置性能图形的默认时间范围"]。

