---
permalink: sm-interface/overview-interface-sam.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, 
summary: 您可以导航主界面以访问System Manager功能和任务。 
---
= 了解 SANtricity System Manager 界面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity系统管理器是一个基于Web的界面、可用于在一个视图中管理存储阵列。



== 主页

主页页面提供了用于存储阵列日常管理的信息板视图。登录到System Manager时、主页页面将显示第一个屏幕。

仪表板视图包括三个摘要区域，其中包含有关存储阵列状态和运行状况的关键信息。您可以在摘要区域找到更多信息。

[cols="25h,~"]
|===
| 区域 | Description 


 a| 
性能
 a| 
通过"性能"区域、您可以比较和对比一段时间内的资源使用情况。您可以查看存储阵列的响应时间(IOPS)、传输速率(MiB/秒)和正在使用的处理容量(CPU)性能指标。



 a| 
Capacity
 a| 
容量区域显示存储阵列中已分配容量、可用存储容量和未分配存储容量的图表视图。



 a| 
存储层次结构
 a| 
"存储层次结构"区域提供了存储阵列管理的各种硬件组件和存储对象的有序视图。单击下拉箭头对该硬件组件或存储对象执行特定操作。

|===


== 通知区域

通知区域可通过窗口上角的铃铛图标访问。通知区域显示指示存储阵列及其组件状态的问题通知。此外，此部分还会显示自动警报，以帮助您在问题影响存储环境的其他区域之前对其进行故障排除。



== 接口设置

您可以从主界面更改显示首选项和其他设置。



== 用户登录和密码

当前登录系统的用户将显示在用户设置中。

有关用户和密码的详细信息、请参见：

* link:administrator-password-protection.html["设置管理员密码保护"]
* link:../sm-settings/change-passwords.html["更改密码"]

