---
permalink: sm-interface/setup-wizard-overview.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, setup wizard 
summary: 使用设置向导配置存储阵列、包括硬件、主机、应用程序、工作负载、 池、警报和AutoSupport。 
---
= 设置向导概述
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用设置向导配置存储阵列、包括硬件、主机、应用程序、工作负载、 池、警报和AutoSupport。



== 首次设置

首次打开System Manager时、设置向导将启动。设置向导会提示您执行基本配置任务、例如命名存储阵列、配置主机、选择应用程序以及创建存储池。


NOTE: 在继续进行初始设置之前、请转到升级中心(菜单：支持[升级中心])并确保您的SANtricity OS软件是最新的。如果需要、请升级到最新版本并刷新浏览器以继续设置。有关详细信息，请参见 link:../sm-support/overview-upgrade-center.html["升级中心概述"]。

如果取消此向导、则无法手动重新启动它。在打开 System Manager 或刷新浏览器且至少满足以下条件之一时，向导将自动重新启动：

* 未检测到池和卷组。
* 未检测到工作负载。
* 未配置任何通知。




== 术语

设置向导使用以下术语。

[cols="25h,~"]
|===
| 期限 | Description 


 a| 
应用程序
 a| 
应用程序是一种软件程序、例如Microsoft SQL Server或Microsoft Exchange。



 a| 
警报
 a| 
警报会向管理员通知存储阵列上发生的重要事件。可以通过电子邮件、SNMP陷阱或系统日志发送警报。



 a| 
AutoSupport
 a| 
AutoSupport 功能可监控存储阵列的运行状况、并向技术支持发送自动派单。



 a| 
硬件
 a| 
存储系统硬件包括存储阵列、控制器和驱动器。



 a| 
主机
 a| 
主机是指向存储阵列上的卷发送I/O的服务器。



 a| 
对象
 a| 
对象是任何逻辑或物理存储组件。逻辑对象包括卷组、池和卷。物理对象包括存储阵列、阵列控制器、主机和驱动器。



 a| 
池
 a| 
池是指一组按逻辑分组的驱动器。您可以使用池创建一个或多个可供主机访问的卷。(您可以从池或卷组创建卷。)



 a| 
Volume
 a| 
卷是应用程序，数据库和文件系统用于存储数据的容器。它是为主机创建的逻辑组件，用于访问存储阵列上的存储。

卷是使用池或卷组中的可用容量创建的。卷已定义容量。尽管一个卷可能包含多个驱动器、但一个卷在主机中显示为一个逻辑组件。



 a| 
卷组
 a| 
卷组是具有共享特征的卷的容器。卷组已定义容量和RAID级别。您可以使用卷组创建一个或多个可供主机访问的卷。(您可以从卷组或池创建卷。)



 a| 
工作负载
 a| 
工作负载是指支持应用程序的存储对象。您可以为每个应用程序定义一个或多个工作负载或实例。对于某些应用程序、系统会将工作负载配置为包含具有类似底层卷特征的卷。这些卷特征会根据工作负载支持的应用程序类型进行优化。例如、如果您创建了一个支持Microsoft SQL Server应用程序的工作负载、然后为该工作负载创建了卷、则底层卷特征将进行优化以支持Microsoft SQL Server。

|===