---
permalink: sm-interface/view-storage-hierarchy.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, storage hierarchy 
summary: 主界面上的存储层次结构可提供存储阵列所管理的各种硬件组件和存储对象的有序视图。 
---
= 查看存储层次结构
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
主界面上的存储层次结构可提供存储阵列所管理的各种硬件组件和存储对象的有序视图。

要查看存储层次结构、请转到主页页面、然后单击存储阵列组件或存储对象上的下拉箭头。存储阵列由一组物理组件和逻辑组件组成。



== 物理组件

此表介绍了存储阵列的物理组件。

[cols="25h,~"]
|===
| 组件 | Description 


 a| 
控制器
 a| 
控制器由主板，固件和软件组成。它控制驱动器并实施 System Manager 功能。



 a| 
磁盘架
 a| 
磁盘架是安装在机柜或机架中的机箱。它包含存储阵列的硬件组件。磁盘架有两种类型：控制器磁盘架和驱动器磁盘架。控制器架包括控制器和驱动器。驱动器架包括输入 / 输出模块（ IOM ）和驱动器。

[NOTE]
====
如果存储阵列包含不同的介质类型或不同的接口类型、则会显示每种驱动器类型的驱动器架。

====


 a| 
驱动器
 a| 
驱动器是一种为数据提供物理存储介质的机械设备或固态内存设备。



 a| 
主机
 a| 
主机是指向存储阵列上的卷发送I/O的服务器。



 a| 
主机总线适配器(HBA)
 a| 
主机总线适配器(HBA)是驻留在主机中并包含一个或多个主机端口的板。



 a| 
主机端口
 a| 
主机端口是主机总线适配器(HBA)上的一个端口、用于与控制器建立物理连接并用于I/O操作。



 a| 
管理客户端
 a| 
管理客户端是指安装了浏览器以访问System Manager的计算机。

|===


== 逻辑组件

存储阵列中的驱动器可为数据提供物理存储容量。使用System Manager将物理容量配置为逻辑组件、例如池、卷组和卷。这些组件是用于配置、存储、维护和保留存储阵列上的数据的工具。此表介绍了存储阵列的逻辑组件。

[cols="25h,~"]
|===
| 组件 | Description 


 a| 
池
 a| 
池是指一组按逻辑分组的驱动器。您可以使用池创建一个或多个可供主机访问的卷。(您可以从池或卷组创建卷。)



 a| 
卷组
 a| 
卷组是具有共享特征的卷的容器。卷组已定义容量和RAID级别。您可以使用卷组创建一个或多个可供主机访问的卷。(您可以从卷组或池创建卷。)



 a| 
Volume
 a| 
卷是应用程序，数据库和文件系统用于存储数据的容器。它是为主机创建的逻辑组件，用于访问存储阵列上的存储。



 a| 
逻辑单元号(LUN)
 a| 
逻辑单元号(LUN)是分配给主机用于访问卷的地址空间的编号。卷以LUN的形式呈现给主机。

每个主机都有自己的LUN地址空间。因此、不同的主机可以使用同一个LUN来访问不同的卷。

|===