---
permalink: sm-hardware/allow-remote-login.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, login, 
summary: 远程登录允许局域网外部的用户启动SSH会话并更改控制器上的设置。 
---
= 配置远程登录(SSH)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过启用远程登录、您可以允许局域网外部的用户启动控制器上的SSH会话和访问设置。

对于SANtricity 11.74及更高版本、您还可以通过要求用户输入SSH密钥和/或SSH密码来配置多因素授权(Multifactor Authorization、MFA)。对于SANtricity 11.73及更早版本、此功能不包含使用SSH密钥和密码进行多因素授权的选项。

[CAUTION]
====
*安全风险*-出于安全原因、只有技术支持人员才应使用远程登录功能。

====
.步骤
. 选择 * 硬件 * 。
. 如果图形显示了驱动器，请单击 * 显示磁盘架背面 * 。
+
此图将发生变化，以显示控制器，而不是驱动器。

. 单击要为其配置远程登录的控制器。
+
此时将显示控制器的上下文菜单。

. 选择*配置远程登录(SSH)*。(对于SANtricity 11.73及更早版本、此菜单项为*更改远程登录*。)
+
此时将打开一个对话框、用于启用远程登录。

. 选中*启用远程登录*复选框。
+
此设置提供远程登录、并提供三个授权选项：

+
** *仅限密码*。对于此选项、您已完成并可以单击*保存*。如果您使用的是双工系统、则可以按照上述步骤在第二个控制器上启用远程登录。
** * SSH密钥或密码*。对于此选项、请继续执行下一步。
** *密码和SSH密钥*。对于此选项、选中*需要授权的公有 密钥和密码才能进行远程登录*复选框、然后继续下一步。


. 填充*授权公有 密钥*字段。此字段包含一个授权公有 密钥列表、格式为OpenSSH *授权密钥*文件。
+
填充*授权公有 密钥*字段时、请注意以下准则：

+
** "*授权公有 key*"字段适用场景 两个控制器、只需要在第一个控制器上配置。
** *授权密钥*文件每行只能包含一个密钥。以#开头的行和空行将被忽略。有关文件格式的详细信息、请参见 link:https://www.ssh.com/academy/ssh/authorized-keys-openssh["为OpenSSH配置授权密钥"^]。
** 一个*授权密钥*文件应类似于以下示例：
+
[listing]
----
ssh-rsa
AAAAB3NzaC1yc2EAAAADAQABAAABAQDJlG20rYTk4ok+xFjkPHYp/R0LfJqEYDLXA5AJ49w3DvAWLrUg+1CpNq76WSqmQBmoG9jgbcAB5ABGdswdeMQZHilJcu29iJ3OKKv6SlCulAj1tHymwtbdhPuipd2wIDAQAB
----


. 完成后、单击*保存*。
. 对于双工系统、您可以按照上述步骤在第二个控制器上启用远程登录。如果要为密码和SSH密钥配置选项、请务必再次选中*需要授权的公有 密钥和密码才能进行远程登录*复选框。
. 技术支持完成故障排除后、您可以返回配置远程登录对话框并取消选中*启用远程登录*复选框来禁用远程登录。如果在第二个控制器上启用了远程登录、则会打开一个确认对话框、并允许您同时禁用第二个控制器上的远程登录。
+
禁用远程登录将终止任何当前SSH会话并拒绝任何新的登录请求。


