---
permalink: sm-hardware/configure-ntp-server-addresses.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, ntp, server, addresses, network, time, protocol, 
summary: '您可以配置与网络时间协议(NTP)服务器的连接、以便控制器定期查询NTP服务器以更新其内部时间时钟。' 
---
= 配置NTP服务器地址
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以配置与网络时间协议(NTP)服务器的连接、以便控制器定期查询NTP服务器以更新其内部时间时钟。

.开始之前
* 必须在网络中安装和配置NTP服务器。
* 您必须知道主NTP服务器和可选备份NTP服务器的地址。这些地址可以是完全限定域名、IPv4地址或IPv6地址。


[NOTE]
====
如果输入NTP服务器的一个或多个域名、则还必须配置DNS服务器以解析NTP服务器地址。您只需要在配置了NTP并提供了域名的控制器上配置DNS服务器。

====
.关于此任务
通过NTP、存储阵列可以使用简单网络时间协议(Simple Network Time Protocol、SNTP)自动将控制器的时钟与外部主机同步。控制器会定期查询已配置的NTP服务器、然后使用结果更新其内部时间时钟。如果只有一个控制器启用了NTP、则备用控制器会定期将其时钟与启用了NTP的控制器同步。如果这两个控制器均未启用NTP、则这些控制器会定期同步各自的时钟。

[NOTE]
====
您无需在两个控制器上配置NTP；但是、这样做可以提高存储阵列在发生硬件或通信故障期间保持同步的能力。

====
.步骤
. 选择 * 硬件 * 。
. 如果图形显示了驱动器，请单击 * 显示磁盘架背面 * 。
+
此图将发生变化，以显示控制器，而不是驱动器。

. 单击要配置的控制器。
+
此时将显示控制器的上下文菜单。

. 选择*配置NTP服务器*。
+
此时将打开配置网络时间协议(NTP)服务器对话框。

. 选择*我要在控制器*上启用NTP (* A*或* B*)。
+
其他选择将显示在对话框中。

. 选择以下选项之一：
+
** *自动从DHCP服务器获取NTP服务器地址*-显示检测到的NTP服务器地址。
+
[NOTE]
====
如果存储阵列设置为使用静态NTP地址、则不会显示任何NTP服务器。

====
** *手动指定NTP服务器地址*-输入主NTP服务器地址和备份NTP服务器地址。备份服务器是可选的。(选择单选按钮后、将显示这些地址字段。) 服务器地址可以是完全限定域名、IPv4地址或IPv6地址。


. *可选：*输入备份NTP服务器的服务器信息和身份验证凭据。
. 单击 * 保存 * 。


.结果
NTP服务器配置显示在控制器设置的* DNS / nttp*选项卡中。
