---
permalink: sm-hardware/configure-management-ports.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, management, port, 
summary: 此控制器包含一个用于系统管理的以太网端口。如有必要、您可以更改其传输参数和IP地址。 
---
= 配置管理端口
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
此控制器包含一个用于系统管理的以太网端口。如有必要、您可以更改其传输参数和IP地址。

.关于此任务
在此操作步骤 期间、您可以选择端口1、然后确定速度和端口寻址方法。端口1连接到管理客户端可访问控制器和System Manager的网络。

[NOTE]
====
请勿使用任一控制器上的端口2。端口2已保留供技术支持使用。

====
.步骤
. 选择 * 硬件 * 。
. 如果图形显示了驱动器，请单击 * 显示磁盘架背面 * 。
+
此图将发生变化，以显示控制器，而不是驱动器。

. 单击包含要配置的管理端口的控制器。
+
此时将显示控制器的上下文菜单。

. 选择*配置管理端口*。
+
此时将打开配置管理端口对话框。

. 确保显示端口1、然后单击*下一步*。
. 选择配置端口设置，然后单击 * 下一步 * 。
+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 字段 | Description 


 a| 
速度和双工模式
 a| 
如果您希望System Manager确定存储阵列与网络之间的传输参数、或者如果您知道网络的速度和模式、请从下拉列表中选择参数、请保留自动协商设置。列表中仅显示有效的速度和双工组合。



 a| 
启用 IPv4/Enable IPv6
 a| 
选择一个或两个选项以启用对 IPv4 和 IPv6 网络的支持。

|===
====
+
如果选择*启用IPv*、则在单击*下一步*后、将打开一个对话框、用于选择IPv4设置。如果选择*启用IPv6*、则在单击*下一步*后、将打开一个对话框、用于选择IPv6设置。如果同时选择这两个选项、则会首先打开IPv4设置对话框、然后单击*下一步*、将打开IPv6设置对话框。

. 自动或手动配置 IPv4 和 / 或 IPv6 设置。
+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 字段 | Description 


 a| 
自动从 DHCP 服务器获取配置
 a| 
选择此选项可自动获取配置。



 a| 
手动指定静态配置
 a| 
选择此选项、然后输入控制器的IP地址。(如果需要、可以剪切地址并将其粘贴到字段中。) 对于IPv4、请包括网络子网掩码和网关。对于 IPv6 ，请包括可路由的 IP 地址和路由器 IP 地址。


NOTE: 如果更改IP地址配置、则会丢失存储阵列的管理路径。如果您使用SANtricity 统一管理器全局管理网络中的阵列、请打开用户界面并转到菜单：管理[发现]。如果您使用的是SANtricity 存储管理器、则必须从企业管理窗口(EMW)中删除此设备、并通过选择菜单：编辑(添加存储阵列)将其重新添加到EMW中、然后输入新的IP地址。

|===
====
. 单击 * 完成 * 。


.结果
管理端口配置显示在控制器设置的管理端口选项卡中。
