---
permalink: sm-hardware/erase-drive.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, erase, drives, removal, 
summary: 您可以使用擦除选项准备要从系统中删除的未分配驱动器。此操作步骤 会永久删除数据、以确保无法再次读取数据。 
---
= 擦除驱动器
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用擦除选项准备要从系统中删除的未分配驱动器。此操作步骤 会永久删除数据、以确保无法再次读取数据。

驱动器必须处于未分配状态。

只有在要永久删除驱动器上的所有数据时、才使用擦除选项。如果驱动器已启用安全保护、则擦除选项将执行加密擦除、并将驱动器的安全属性重置回支持安全保护的属性。

[NOTE]
====
擦除功能不支持某些旧型号的驱动器。如果您尝试擦除其中一个较旧的型号、则会显示一条错误消息。

====
.步骤
. 选择 * 硬件 * 。
. 如果图形显示了控制器、请单击*显示磁盘架正面*。
+
此图将发生变化、以显示驱动器、而不是控制器。

. 您也可以使用筛选器字段查看磁盘架中所有未分配的驱动器。从*显示驱动器...*下拉列表中、选择*未分配*。
+
磁盘架视图仅显示未分配的驱动器；所有其他驱动器均显示为灰色。

. 要打开驱动器的上下文菜单、请单击要擦除的驱动器。(如果要选择多个驱动器、可以在擦除驱动器对话框中执行此操作。)
+
[CAUTION]
====
*可能的数据丢失*-擦除操作无法撤消。确保在操作步骤 期间选择正确的驱动器。

====
. 从上下文菜单中、选择*擦除*。
+
此时将打开擦除驱动器对话框、其中显示了所有符合擦除操作条件的驱动器。

. 如果需要、请从表中选择其他驱动器。您不能选择_all_驱动器；请确保仍有一个驱动器处于未选中状态。
. 键入`erase`确认操作、然后单击*擦除*。
+
[CAUTION]
====
请务必继续执行此操作。在下一个对话框中单击是后、此操作将无法中止。

====
. 在估计完成时间对话框中、单击*是*继续执行擦除操作。


擦除操作可能需要几分钟或几小时。您可以在菜单：主页(查看正在执行的操作)中查看状态。擦除操作完成后、驱动器可在其他卷组或磁盘池中或其他存储阵列中使用。

如果要再次使用该驱动器、必须先对其进行初始化。要执行此操作、请从驱动器的上下文菜单中选择*初始化*。
