---
permalink: sm-hardware/faq-storage-controller.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= SANtricity System Manager 的存储控制器常见问题解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== 什么是自动协商？

自动协商是指网络接口能够自动将其自身的连接参数(速度和双工)与另一个网络接口进行协调。

自动协商通常是配置管理端口的首选设置；但是、如果协商失败、不匹配的网络接口设置可能会严重影响网络性能。如果这种情况不可接受、您应手动将网络接口设置为正确的配置。自动协商由控制器的以太网管理端口执行。iSCSI主机总线适配器不会执行自动协商。

[NOTE]
====
如果自动协商失败、控制器将尝试在10BASE-T半双工位置建立连接、这是最低的通用分母。

====


== 什么是IPv6无状态地址自动配置？

使用无状态自动配置时、主机不会从服务器获取地址和其他配置信息。

IPv6中的无状态自动配置功能包括链路本地地址、多播和邻居发现(ND)协议。IPv6可以从底层数据链路层地址生成地址的接口ID。

无状态自动配置与有状态自动配置互为补充。例如、主机可以使用无状态自动配置来配置自己的地址、但可以使用有状态自动配置来获取其他信息。有状态自动配置允许主机从服务器获取地址和其他配置信息。Internet协议版本6 (IPv6)还定义了一种方法、可通过此方法一次性重新编号网络上的所有IP地址。IPv6为网络上的设备定义了一种无需服务器即可自动配置其IP地址和其他参数的方法。

使用无状态自动配置时、设备会执行以下步骤：

. *生成链路本地地址*-设备生成链路本地地址、地址有10位、后跟54个零、后跟64位接口ID。
. *测试链路本地地址的唯一性*—节点将进行测试、以确保其生成的链路本地地址未在本地网络上使用。节点使用NDD协议发送邻居请求消息。作为响应、本地网络会侦听邻居公告消息、这表示另一个设备已在使用链路本地地址。如果是、则必须生成新的链路本地地址或自动配置失败、并且必须使用另一种方法。
. *分配链路本地地址*-如果设备通过唯一性测试、则设备会将链路本地地址分配给其IP接口。链路本地地址可用于在本地网络上进行通信、但不能通过Internet进行通信。
. *联系路由器*—节点尝试联系本地路由器、以了解有关继续配置的详细信息。执行此联系的方法是、侦听路由器定期发送的路由器公告消息、或者发送特定的路由器请求消息以要求路由器提供有关下一步操作的信息。
. *向节点提供方向*-路由器向节点提供如何继续自动配置的方向。或者、路由器会告知主机如何确定全局Internet地址。
. *配置全局地址*—主机使用其全局唯一Internet地址对自身进行配置。此地址通常由路由器提供给主机的网络前缀构成。




== 我该选择哪一个——DHCP 还是手动配置？

网络配置的默认方法是动态主机配置协议(Dynamic Host Configuration Protocol、DHCP)。除非您的网络没有DHCP服务器、否则请始终使用此选项。



== 什么是DHCP服务器？

动态主机配置协议(Dynamic Host Configuration Protocol、DHCP)是一种可自动执行Internet协议(IP)地址分配任务的协议。

必须为连接到TCP/IP网络的每个设备分配一个唯一的IP地址。这些设备包括存储阵列中的控制器。

如果没有DHCP、网络管理员可以手动输入这些IP地址。使用DHCP时、当客户端需要启动TCP/IP操作时、客户端会广播地址信息请求。DHCP服务器接收请求、在称为租赁期的指定时间段内分配新地址、并将该地址发送给客户端。使用DHCP时、设备每次连接到网络时都可以具有不同的IP地址。在某些系统中、即使设备仍处于连接状态、设备的IP地址也会发生更改。



== 如何配置DHCP服务器？

您必须将动态主机配置协议(DHCP)服务器配置为对存储阵列中的控制器使用静态Internet协议(IP)地址。

DHCP服务器分配的IP地址通常是动态的、可能会发生更改、因为它们的租赁期已到期。某些设备(例如服务器和路由器)需要使用静态地址。存储阵列中的控制器还需要静态IP地址。

有关如何分配静态地址的信息、请参见DHCP服务器的文档。



== 为什么需要更改控制器网络配置？

使用带外管理时、您必须为每个控制器设置网络配置、包括其Internet协议(IP)地址、子网掩码(子网掩码)和网关。

您可以使用动态主机配置协议(DHCP)服务器设置网络配置。如果您不使用DHCP服务器、则必须手动输入网络配置。



== 从何处获取网络配置？

您可以从网络管理员处获取Internet协议(IP)地址、子网掩码(子网掩码)和网关信息。

在控制器上配置端口时需要此信息。



== 什么是ICMP ping响应？

Internet控制消息协议(Internet Control Message Protocol、ICMP)是TCP/IP套件的协议之一。

`ICMP echo request`和`ICMP echo reply`消息通常称为`ping`消息。`Ping`是一款故障排除工具、系统管理员可使用此工具手动测试网络设备之间的连接、并测试网络延迟和数据包丢失。`ping`命令会将`ICMP echo request`发送到网络上的设备、并且设备会立即响应`ICMP echo reply`。有时、公司的网络安全策略要求在所有设备上禁用`ping`(`ICMP echo reply`)、以使未经授权的人员更难发现这些设备。



== 何时应刷新端口配置？

随时修改或升级DHCP服务器、并且与当前存储阵列和要使用的存储阵列相关的DHCP信息已更改、请刷新此服务器。

具体而言、如果您知道DHCP服务器将分配不同的地址、请从DHCP服务器刷新端口配置或iSNS服务器。

[NOTE]
====
刷新端口配置会对该端口上的所有iSCSI连接造成破坏。

====


== 配置管理端口后应执行什么操作？

如果更改了存储阵列的IP地址、则可能需要在SANtricity 统一管理器中更新全局阵列视图。

要在Unified Manager中更新全局阵列视图、请打开界面并转到菜单：Manage (管理)[Discover (发现)。

如果您仍在使用SANtricity 存储管理器、请转到企业管理窗口(EMW)、其中必须删除并重新添加新的IP地址。



== 为什么存储系统处于非最佳模式？

存储系统处于非最佳模式是由于系统配置无效状态所致。尽管处于此状态、但完全支持对现有卷进行正常I/O访问；但是、SANtricity系统管理器将禁止某些操作。

存储系统可能会过渡到"系统配置无效"、原因如下：

* 此控制器不合规、可能是因为其子型号ID (SMID)代码不正确或已超过高级功能限制。
* 正在执行内部服务操作、例如驱动器固件下载。
* 控制器超过奇偶校验错误阈值并进入锁定状态。
* 发生常规锁定情况。

