---
permalink: sm-hardware/hardware-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, hardware, terms 
summary: 了解硬件术语如何应用于存储阵列。 
---
= 硬件术语
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以下硬件术语适用于存储阵列。

.常规硬件术语：
====
[cols="25h,~"]
|===
| 组件 | Description 


 a| 
托架
 a| 
托架是指安装驱动器或其他组件的磁盘架中的插槽。



 a| 
控制器
 a| 
控制器由主板，固件和软件组成。它控制驱动器并实施 System Manager 功能。



 a| 
控制器架
 a| 
控制器架包含一组驱动器和一个或多个控制器箱。控制器箱用于存放控制器、主机接口卡(Host Interface Card、HIC)和电池。



 a| 
驱动器
 a| 
驱动器是一种为数据提供物理存储介质的机械设备或固态内存设备。



 a| 
驱动器架
 a| 
驱动器架也称为扩展架、其中包含一组驱动器和两个输入/输出模块(IOM)。IOM包含SAS端口、用于将驱动器架连接到控制器架或其他驱动器架。



 a| 
IOM (ESM)
 a| 
IOM是一个输入/输出模块、其中包含SAS端口、用于将驱动器架连接到控制器架。在以前的控制器型号中、IOM称为环境服务模块(ESM)。



 a| 
电源/风扇箱
 a| 
电源 / 风扇箱是一个可滑入磁盘架的组件。它包括一个电源和一个集成风扇。



 a| 
SFP
 a| 
SFP是一种小型可插拔(SFP)收发器。



 a| 
磁盘架
 a| 
磁盘架是安装在机柜或机架中的机箱。它包含存储阵列的硬件组件。磁盘架有两种类型：控制器磁盘架和驱动器磁盘架。控制器架包括控制器和驱动器。驱动器架包括输入 / 输出模块（ IOM ）和驱动器。



 a| 
存储阵列
 a| 
存储阵列包括磁盘架、控制器、驱动器、软件和固件。

|===
====
.控制器术语：
====
[cols="25h,~"]
|===
| 组件 | Description 


 a| 
控制器
 a| 
控制器由主板，固件和软件组成。它控制驱动器并实施 System Manager 功能。



 a| 
控制器架
 a| 
控制器架包含一组驱动器和一个或多个控制器箱。控制器箱用于存放控制器、主机接口卡(Host Interface Card、HIC)和电池。



 a| 
DHCP
 a| 
动态主机配置协议(DHCP)是Internet协议(IP)网络上使用的一种协议、用于动态分布网络配置参数、例如IP地址。



 a| 
DNS
 a| 
域名系统(Domain Name System、DNS)是一种命名系统、用于命名连接到Internet或专用网络的设备。DNS服务器维护一个域名目录、并将其转换为Internet协议(IP)地址。



 a| 
双工配置
 a| 
双工是存储阵列中的双控制器模块配置。双工系统在控制器、逻辑卷路径和磁盘路径方面是完全冗余的。如果一个控制器发生故障、另一个控制器将接管其I/O以保持可用性。双工系统还具有冗余风扇和电源。



 a| 
全双工/半双工连接
 a| 
全双工和半双工是指连接模式。在全双工模式下、两个设备可以同时双向通信。在半双工模式下、设备可以一次单向通信(一个设备发送消息、而另一个设备接收消息)。



 a| 
HIC
 a| 
可以选择将主机接口卡（ HIC ）安装在控制器箱中。控制器中内置的主机端口称为基板主机端口。HIC 中内置的主机端口称为 HIC 端口。



 a| 
ICMP ping响应
 a| 
Internet控制消息协议(Internet Control Message Protocol、ICMP)是网络计算机的操作系统用来发送消息的协议。ICMP消息可确定主机是否可访问以及从该主机获取数据包所需的时间。



 a| 
MAC 地址
 a| 
以太网使用介质访问控制标识符(MAC地址)来区分连接同一物理传输网络接口上两个端口的不同逻辑通道。



 a| 
管理客户端
 a| 
管理客户端是指安装了浏览器以访问System Manager的计算机。



 a| 
MTU
 a| 
最大传输单元(Maximum Transmission Unit、MTU)是可在网络中发送的最大数据包或帧。



 a| 
NTP
 a| 
网络时间协议(NTP)是一种网络协议、用于在数据网络中的计算机系统之间进行时钟同步。



 a| 
单工配置
 a| 
单工是存储阵列中的单控制器模块配置。单工系统不提供控制器或磁盘路径冗余、但具有冗余风扇和电源。



 a| 
VLAN
 a| 
虚拟局域网(VLAN)是一种逻辑网络、其行为与相同设备(交换机、路由器等)支持的其他网络在物理上是分开的。

|===
====
.驱动器术语：
====
[cols="25h,~"]
|===
| 组件 | Description 


 a| 
da.
 a| 
数据保证(Data Assurance、DA)是一项功能、用于检查并更正在数据通过控制器向下传输到驱动器时可能发生的错误。可以在池或卷组级别启用数据保证、主机使用光纤通道等具有DA功能的I/O接口。



 a| 
驱动器安全功能
 a| 
驱动器安全性是一种存储阵列功能，可通过全磁盘加密（ Full Disk Encryption ， FDE ）驱动器或联邦信息处理标准（ Federal Information Processing Standard ， FIPS ）驱动器提供额外的安全层。如果将这些驱动器与驱动器安全功能结合使用，则需要使用安全密钥才能访问其数据。从阵列中物理删除驱动器后、这些驱动器将无法运行、直到将其安装到另一个阵列中为止、此时、这些驱动器将处于安全锁定状态、直到提供了正确的安全密钥为止。



 a| 
驱动器架
 a| 
驱动器架也称为扩展架、其中包含一组驱动器和两个输入/输出模块(IOM)。IOM包含SAS端口、用于将驱动器架连接到控制器架或其他驱动器架。



 a| 
DULBE
 a| 
已取消分配或未写入逻辑块错误(DULBE")是NVMe驱动器上的一个选项、它允许EF300或EF600存储阵列支持资源配置的卷。



 a| 
FDE驱动器
 a| 
全磁盘加密(Full Disk Encryption、FDE)驱动器在硬件级别对磁盘驱动器执行加密。硬盘驱动器包含一个ASIC芯片、用于在写入期间对数据进行加密、然后在读取期间对数据进行解密。



 a| 
FIPS驱动器
 a| 
FIPS驱动器使用联邦信息处理标准(FIPS) 140-2级别2。它们本质上是FDE驱动器、符合美国政府标准、可确保强大的加密算法和方法。FIPS驱动器的安全标准高于FDE驱动器。



 a| 
HDD
 a| 
硬盘驱动器（ HDD ）是指使用带有磁性层的旋转金属盘的数据存储设备。



 a| 
热备用驱动器
 a| 
热备用磁盘在RAID 1、RAID 5或RAID 6卷组中充当备用驱动器。它们是功能完备的驱动器、不包含任何数据。如果卷组中的驱动器发生故障、控制器会自动将故障驱动器中的数据重新构建为热备用磁盘。



 a| 
NVMe
 a| 
Non-Volatile Memory Express (NVMe)是一种专为SSD驱动器等基于闪存的存储设备设计的接口。与以前的逻辑设备接口相比、NVMe可降低I/O开销并提高性能。



 a| 
（ SAS ）。
 a| 
串行连接 SCSI （ SAS ）是一种点对点串行协议，可将控制器直接链接到磁盘驱动器。



 a| 
支持安全的驱动器
 a| 
支持安全的驱动器可以是全磁盘加密(Full Disk Encryption、FDE)驱动器、也可以是联邦信息处理标准(Federal Information Processing Standard、FIPS)驱动器、这些驱动器可在写入期间对数据进行加密、并在读取期间对数据进行解密。这些驱动器被视为安全驱动器-_capable"、因为可以使用驱动器安全功能提高安全性。如果为这些驱动器使用的卷组和池启用了驱动器安全功能、则这些驱动器将变为secure—_enabled_.



 a| 
已启用安全保护的驱动器
 a| 
启用了安全保护的驱动器与驱动器安全功能结合使用。启用驱动器安全功能后、如果将驱动器安全应用于安全-_capable"驱动器上的池或卷组、则这些驱动器将变为安全_-enabled__。只能通过配置了正确安全密钥的控制器进行读写访问。这种增强的安全性可防止未经授权访问从存储阵列中物理删除的驱动器上的数据。



 a| 
SSD
 a| 
固态磁盘（ SSD ）是指使用固态内存（ Flash ）持久存储数据的数据存储设备。SSD 可模拟传统硬盘驱动器，并可与硬盘驱动器使用相同的接口。

|===
====
.iSCSI术语：
====
[cols="25h,~"]
|===
| 期限 | Description 


 a| 
CHAP
 a| 
质询握手身份验证协议(CHAP)方法可在初始链路期间验证目标和启动程序的身份。身份验证基于名为CHAP __secret__的共享安全密钥。



 a| 
控制器
 a| 
控制器由主板，固件和软件组成。它控制驱动器并实施 System Manager 功能。



 a| 
DHCP
 a| 
动态主机配置协议(DHCP)是Internet协议(IP)网络上使用的一种协议、用于动态分布网络配置参数、例如IP地址。



 a| 
IB
 a| 
InfiniBand （ IB ）是高性能服务器和存储系统之间数据传输的一种通信标准。



 a| 
ICMP ping响应
 a| 
Internet控制消息协议(Internet Control Message Protocol、ICMP)是网络计算机的操作系统用来发送消息的协议。ICMP消息可确定主机是否可访问以及从该主机获取数据包所需的时间。



 a| 
IQN
 a| 
iSCSI限定名称(IQN)标识符是iSCSI启动程序或iSCSI目标的唯一名称。



 a| 
iSER
 a| 
适用于RDMA的iSCSI扩展(iSER)是一种协议、用于扩展iSCSI协议、以便在InfiniBand或以太网等RDMA传输上运行。



 a| 
iSNS
 a| 
Internet存储名称服务(iSNS)是一种协议、允许在TCP/IP网络上自动发现、管理和配置iSCSI和光纤通道设备。



 a| 
MAC 地址
 a| 
以太网使用介质访问控制标识符(MAC地址)来区分连接同一物理传输网络接口上两个端口的不同逻辑通道。



 a| 
管理客户端
 a| 
管理客户端是指安装了浏览器以访问System Manager的计算机。



 a| 
MTU
 a| 
最大传输单元(Maximum Transmission Unit、MTU)是可在网络中发送的最大数据包或帧。



 a| 
RDMA
 a| 
远程直接内存访问(RDMA)是一项技术、允许网络计算机在主内存中交换数据、而无需涉及任一计算机的操作系统。



 a| 
未命名的发现会话
 a| 
启用未命名发现会话选项后、无需iSCSI启动程序指定目标IQN来检索控制器的信息。

|===
====
.NVMe术语：
====
[cols="25h,~"]
|===
| 期限 | Description 


 a| 
InfiniBand
 a| 
InfiniBand （ IB ）是高性能服务器和存储系统之间数据传输的一种通信标准。



 a| 
命名空间
 a| 
命名空间是指为块访问而格式化的NVM存储。它类似于SCSI中的逻辑单元、它与存储阵列中的卷相关。



 a| 
命名空间ID
 a| 
命名空间ID是NVMe控制器在命名空间中的唯一标识符、可设置为1到255之间的值。它类似于SCSI中的逻辑单元号(Logical Unit Number、LUN)。



 a| 
NQN
 a| 
NVMe限定名称(NQN)用于标识远程存储目标(存储阵列)。



 a| 
NVM
 a| 
非易失性内存(NVM)是许多类型的存储设备中使用的永久性内存。



 a| 
NVMe
 a| 
Non-Volatile Memory Express (NVMe)是一种专为SSD驱动器等基于闪存的存储设备设计的接口。与以前的逻辑设备接口相比、NVMe可降低I/O开销并提高性能。



 a| 
NVMe-oF
 a| 
基于网络结构的非易失性Memory Express (NVMe-oF)是一种规范、可使NVMe命令和数据通过网络在主机和存储之间传输。



 a| 
NVMe控制器
 a| 
NVMe控制器是在主机连接过程中创建的。它可在主机与存储阵列中的命名空间之间提供访问路径。



 a| 
NVMe队列
 a| 
队列用于通过NVMe接口传递命令和消息。



 a| 
NVMe 子系统
 a| 
具有NVMe主机连接的存储阵列。



 a| 
RDMA
 a| 
通过在网络接口卡(NIC)硬件中实施传输协议、远程直接内存访问(Remote Direct Memory Access、RDMA)可以更直接地将数据移入和移出服务器。



 a| 
RoCE
 a| 
基于融合以太网的 RDMA （ RoCE ）是一种网络协议，允许通过以太网远程直接内存访问（ RDMA ）。



 a| 
SSD
 a| 
固态磁盘（ SSD ）是指使用固态内存（ Flash ）持久存储数据的数据存储设备。SSD 可模拟传统硬盘驱动器，并可与硬盘驱动器使用相同的接口。

|===
====