---
permalink: sm-hardware/hardware-page-overview.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, hardware, page, components, 
summary: 硬件页面以图形方式描绘了存储阵列的物理组件。您可以从此处检查组件状态并执行与这些组件相关的某些功能。 
---
= 硬件页面和组件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
硬件页面以图形方式描绘了存储阵列的物理组件。您可以从此处检查组件状态并执行与这些组件相关的某些功能。



== 磁盘架

磁盘架是一个组件、其中包含存储阵列的硬件(控制器、电源/风扇箱和驱动器)。磁盘架有两种类型：

* *控制器架*-包含驱动器、电源/风扇箱和控制器。
* *驱动器架*(或*扩展架*)-包含驱动器、电源/风扇箱和两个输入/输出模块(IOM)。IOM (也称为环境服务模块(ESM))包括将驱动器架连接到控制器架的SAS端口。


磁盘架有三种大小、最多可容纳12、24或60个驱动器。每个磁盘架都包含一个ID编号、该ID编号由控制器固件分配。此ID显示在磁盘架视图的左上角。

硬件页面上的磁盘架视图显示了正面或背面组件。您可以通过从磁盘架视图右上角选择*显示磁盘架背面*或*显示磁盘架正面*来在这两个视图之间切换。您也可以从页面底部选择*全部显示前视图*或*全部显示后视图*。正面和背面视图显示以下内容：

* *前组件*—驱动器和空驱动器托架。
* *后端组件*—控制器和电源/风扇箱(用于控制器架)或IOM和电源/风扇箱(用于驱动器架)。


您可以执行以下与磁盘架相关的功能：

* 打开磁盘架的定位灯、以便找到磁盘架在机柜或机架中的物理位置。
* 更改磁盘架视图左上方显示的ID编号。
* 查看磁盘架设置、例如安装的驱动器类型和序列号。
* 上移或下移磁盘架视图以匹配存储阵列中的物理布局。




== 控制器

控制器是指实施存储阵列和管理功能的硬件和固件的组合。它包括缓存内存、驱动器支持和主机接口支持。

您可以执行与控制器相关的以下功能：

* 为管理端口配置IP地址和速度。
* 配置iSCSI主机连接(如果有iSCSI主机)。
* 配置网络时间协议(NTP)服务器和域名系统(DNS)服务器。
* 查看控制器状态和设置。
* 允许局域网外部的用户启动SSH会话并更改控制器上的设置。
* 将控制器置于脱机、联机或服务模式。




== 驱动器

存储阵列可以包括硬盘驱动器(HDD)或固态驱动器(SSD)。根据磁盘架大小、最多可以在磁盘架中安装12个、24个或60个驱动器。

您可以执行以下与驱动器相关的功能：

* 打开驱动器的定位灯、以便找到驱动器在磁盘架中的物理位置。
* 查看驱动器状态和设置。
* 重新分配驱动器(从逻辑上将故障驱动器替换为未分配的驱动器)、并在必要时手动重建驱动器。
* 手动使驱动器出现故障、以便您可以更换它。(如果某个驱动器发生故障、您可以在更换之前复制该驱动器的内容。)
* 分配或取消分配热备用磁盘。
* 擦除驱动器。

