---
permalink: sm-hardware/hot-spare-drives.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, hot, spare, drives, raid1, raid6, raid5 
summary: 对于System Manager、热备用磁盘可充当RAID 1、RAID 5或RAID 6卷组中的备用驱动器。 
---
= 热备用驱动器概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
热备件在SANtricity系统管理器的RAID 1、RAID 5或RAID 6卷组中用作备用驱动器。

它们是功能完备的驱动器、不包含任何数据。如果卷组中的某个驱动器发生故障、控制器会自动将故障驱动器中的数据重新构建到分配为热备用驱动器的驱动器中。

热备用磁盘不专用于特定卷组。它们可用于存储阵列中的任何故障驱动器、只要热备用驱动器和驱动器共享以下属性：

* 容量相等(或热备用磁盘容量更大)
* 相同介质类型(例如HDD或SSD)
* 相同的接口类型(例如SAS)




== 如何识别热备用磁盘

您可以通过初始设置向导或硬件页面分配热备用磁盘。要确定是否已分配热备用磁盘、请转到硬件页面并查找以粉色显示的任何驱动器托架。



== 热备用磁盘覆盖的工作原理

热备用磁盘覆盖范围如下：

* 您可以将未分配的驱动器预留为RAID 1、RAID 5或RAID 6卷组的热备用驱动器。
+
[NOTE]
====
热备用磁盘不能用于具有不同数据保护方法的池。池会在池的每个驱动器中预留备用容量(称为_preservation capacity_)、而不是预留额外的驱动器。如果池中的驱动器发生故障、则控制器将以该备用容量重建数据。

====
* 如果RAID 1、RAID 5或RAID 6卷组中的驱动器发生故障、控制器将自动使用冗余数据重建故障驱动器中的数据。热备用磁盘会自动替换故障驱动器、而无需物理交换。
* 在物理更换故障驱动器后、会从热备用驱动器到更换的驱动器执行回写操作。如果已将热备用驱动器指定为卷组的永久成员、则不需要执行回写操作。
* 卷组的托盘丢失保护和抽盒丢失保护是否可用取决于卷组中驱动器的位置。由于驱动器发生故障以及热备用驱动器的位置、托盘丢失保护和抽盒丢失保护可能会丢失。要确保托盘丢失保护和抽盒丢失保护不受影响、您必须更换故障驱动器以启动回写过程。
* 在更换故障驱动器时、存储阵列卷将保持联机并可访问、因为热备用驱动器会自动替换故障驱动器。




== 热备用驱动器容量注意事项

选择容量等于或大于要保护的驱动器总容量的驱动器。例如、如果您有一个配置容量为8 GiB的18 GiB驱动器、则可以使用一个9 GiB或更大的驱动器作为热备用驱动器。通常、除非驱动器的容量等于或大于存储阵列中最大驱动器的容量、否则不要将其分配为热备用驱动器。

[NOTE]
====
如果没有具有相同物理容量的热备用磁盘、则如果驱动器的"已用容量"等于或小于热备用驱动器的容量、则可以将容量较低的驱动器用作热备用磁盘。

====


== 介质和接口类型的注意事项

用作热备用磁盘的驱动器必须与要保护的驱动器共享相同的介质类型和接口类型。例如、HDD驱动器不能用作SSD驱动器的热备用磁盘。



== 支持安全的驱动器的注意事项

支持安全的驱动器(例如FDE或FIPS)可用作具有或不具有安全功能的驱动器的热备用磁盘。但是、不支持安全的驱动器不能用作具有安全功能的驱动器的热备用磁盘。

如果您选择一个已启用安全保护的驱动器来用作热备用磁盘、则System Manager会提示您先执行安全擦除、然后才能继续操作。安全擦除会将驱动器的安全属性重置为支持安全但未启用安全。

[NOTE]
====
启用驱动器安全功能后、如果从支持安全的驱动器创建池或卷组、则这些驱动器将变为_secure enabled"。只能通过配置了正确安全密钥的控制器进行读写访问。这种增强的安全性可防止未经授权访问从存储阵列中物理删除的驱动器上的数据。

====


== 建议的热备用驱动器数量

如果您使用初始设置向导自动创建热备用磁盘、则System Manager会为特定介质类型和接口类型的每30个驱动器创建一个热备用磁盘。否则、您可以在存储阵列中的卷组之间手动创建热备用驱动器。
