---
permalink: sm-hardware/limit-the-drive-view.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, limit, drive, view, 
summary: 如果存储阵列包含具有不同类型的物理和逻辑属性的驱动器、则硬件页面将提供筛选字段、以帮助您限制驱动器视图并查找特定驱动器。 
---
= 限制驱动器视图
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果存储阵列包含具有不同类型的物理和逻辑属性的驱动器、则硬件页面将提供筛选字段、以帮助您限制驱动器视图并查找特定驱动器。

驱动器筛选器可以将视图限制为在某些逻辑位置(例如卷组1)仅查看某些类型的物理驱动器(例如、所有SAS)以及某些安全属性(例如、支持安全)。您可以同时使用这些筛选器、也可以单独使用这些筛选器。

[NOTE]
====
如果所有驱动器共享相同的物理属性、则不会显示*显示驱动器...*筛选字段。如果所有驱动器共享相同的逻辑属性、则不会显示存储阵列*筛选器字段中的*任意位置。

====
.步骤
. 选择 * 硬件 * 。
. 在第一个筛选器字段(在*显示驱动器...*下)中、单击下拉箭头以显示可用的驱动器类型和安全属性。
+
驱动器类型可能包括：

+
** 驱动器介质类型(SSD、HDD)
** 驱动器接口类型
** 驱动器容量(最高到最低)
** 驱动器速度(最高到最低)安全属性可能包括：
** 支持安全保护
** 已启用安全保护
** 支持DA (数据保证)
+
如果所有驱动器的这些属性中有任何一个都相同、则它们不会显示在下拉列表中。例如、如果存储阵列包含SAS接口且速度为15000 RPM的所有SSD驱动器、但某些SSD具有不同的容量、则下拉列表仅显示容量作为筛选选项。

+
从字段中选择一个选项后、与您的筛选条件不匹配的驱动器将在图形视图中灰显。



. 在第二个筛选器框中、单击下拉箭头以显示驱动器的可用逻辑位置。
+
[NOTE]
====
如果需要清除筛选条件、请选择筛选框最右侧的*清除*。

====
+
逻辑位置可能包括：

+
** 池
** 卷组
** 热备用磁盘
** SSD 缓存
** 未分配
+
从字段中选择一个选项后、与您的筛选条件不匹配的驱动器将在图形视图中灰显。



. 或者、您也可以选择筛选器字段最右侧的*打开定位灯*来打开所显示驱动器的定位灯。
+
此操作可帮助您以物理方式查找存储阵列中的驱动器。


