---
permalink: sm-hardware/unlock-or-reset-a-locked-nvme-drive.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, unlock, reset, locked, fips, nvme, drives, 
summary: '如果您将一个或多个锁定的NVMe或FIPS驱动器插入存储阵列、则可以通过添加与这些驱动器关联的安全密钥文件来解锁驱动器数据。如果您没有安全密钥、则可以通过输入每个锁定驱动器的物理安全ID (PSID)对其执行重置、以重置其安全属性并擦除驱动器数据。' 
---
= 解锁或重置锁定的NVMe或FIPS驱动器
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您将一个或多个锁定的NVMe或FIPS驱动器插入存储阵列、则可以通过添加与这些驱动器关联的安全密钥文件来解锁驱动器数据。如果您没有安全密钥、则可以通过输入每个锁定驱动器的物理安全ID (PSID)对其执行重置、以重置其安全属性并擦除驱动器数据。

.开始之前
* 对于Unlock选项、请确保管理客户端(具有用于访问System Manager的浏览器的系统)上具有安全密钥文件(扩展名为`.slk`)。您还必须知道与密钥关联的密码短语。
* 对于"Reset"选项、您必须在要重置的每个驱动器上找到PSID。要找到PSID、请物理卸下驱动器、并在驱动器标签上找到PSID字符串(最多32个字符)、然后重新安装驱动器。


.关于此任务
此任务介绍如何通过将安全密钥文件导入到存储阵列中来解锁NVMe或FIPS驱动器中的数据。如果安全密钥不可用、此任务还会介绍如何对锁定的驱动器执行重置。

[NOTE]
====
如果驱动器已使用外部密钥管理服务器锁定、请在System Manager中选择菜单：设置(系统)>安全密钥管理、以配置外部密钥管理并解锁驱动器。

====
您可以从"硬件"页面或菜单：设置[系统>安全密钥管理]访问解锁功能。以下任务提供了硬件页面中的说明。

.步骤
. 选择 * 硬件 * 。
. 如果图中显示的是控制器，请单击*Drives*选项卡。
+
此图将发生变化、以显示驱动器、而不是控制器。

. 选择要解锁或重置的NVMe或FIPS驱动器。
+
此时将打开驱动器的上下文菜单。

. 选择*解锁*以应用安全密钥文件；如果没有安全密钥文件、则选择*重置*。
+
只有在选择锁定的NVMe或FIPS驱动器时、才会显示这些选项。

+
[CAUTION]
====
在重置操作期间、所有数据都会被擦除。只有在没有安全密钥的情况下、才能执行重置。重置锁定驱动器会永久删除驱动器上的所有数据、并将其安全属性重置为"支持安全"、但未启用。*此操作不可逆。*

====
. 执行以下操作之一：
+
.. *解锁*：在*解锁安全驱动器*对话框中、单击*浏览*、然后选择与要解锁的驱动器对应的安全密钥文件。接下来、输入密码短语、然后单击*解锁*。
.. *重置*：在*重置锁定驱动器*对话框中、在字段中输入PSID字符串、然后键入`reset`进行确认。单击*重置*。
+
对于解锁操作、只需执行一次此操作即可解锁所有NVMe或FIPS驱动器。对于重置操作、您必须分别选择要重置的每个驱动器。





.结果
现在、该驱动器可在另一个卷组或磁盘池中使用、也可在另一个存储阵列中使用。
