---
permalink: sm-hardware/view-drive-status-and-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, drive, status, settings, media, 
summary: 您可以查看驱动器的状态和设置、例如介质类型、接口类型和容量。 
---
= 查看驱动器状态和设置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以查看驱动器的状态和设置、例如介质类型、接口类型和容量。

.步骤
. 选择 * 硬件 * 。
. 如果图形显示了控制器、请单击*显示磁盘架正面*。
+
此图将发生变化、以显示驱动器、而不是控制器。

. 选择要查看其状态和设置的驱动器。
+
此时将打开驱动器的上下文菜单。

. 选择 * 查看设置 * 。
+
此时将打开驱动器设置对话框。

. 要查看所有设置、请单击对话框右上角的*显示更多设置*。
+
.字段详细信息
====
[cols="25h,~"]
|===
| 设置 | Description 


 a| 
Status
 a| 
显示最佳、脱机、非关键故障和故障。最佳状态表示所需的工作条件。



 a| 
模式
 a| 
显示已分配、未分配、热备用备用或热备用正在使用。



 a| 
位置
 a| 
显示驱动器所在的磁盘架和托架编号。



 a| 
已分配给/可以保护/保护
 a| 
如果将驱动器分配给池、卷组或SSD缓存、则此字段将显示"已分配给"。 此值可以是池名称、卷组名称或SSD缓存名称。如果驱动器已分配给热备用磁盘且其模式为备用、则此字段将显示"可保护"。 如果热备用磁盘可以保护一个或多个卷组、则会显示卷组名称。如果无法保护卷组、则显示0个卷组。

如果驱动器已分配给热备用磁盘且其模式正在使用中、则此字段将显示"正在保护"。 此值是受影响卷组的名称。

如果未分配此驱动器、则不会显示此字段。



 a| 
介质类型
 a| 
显示驱动器使用的录制介质类型、可以是硬盘驱动器(HDD)或固态磁盘(SSD)。



 a| 
已用持久性百分比(仅在存在SSD驱动器时显示)
 a| 
迄今为止写入驱动器的数据量除以理论写入总限制。



 a| 
接口类型
 a| 
显示驱动器使用的接口类型、例如SAS。



 a| 
驱动器路径冗余
 a| 
显示驱动器与控制器之间的连接是否为冗余(是)或非冗余(否)。



 a| 
容量(GiB)
 a| 
显示驱动器的可用容量(总配置容量)。



 a| 
速度（ RPM ）
 a| 
以RPM为单位显示速度(对于SSD不显示)。



 a| 
当前数据速率
 a| 
显示驱动器与存储阵列之间的数据传输速率。



 a| 
逻辑扇区大小(字节)
 a| 
显示驱动器使用的逻辑扇区大小。



 a| 
物理扇区大小(字节)
 a| 
显示驱动器使用的物理扇区大小。通常、硬盘驱动器的物理扇区大小为4096字节。



 a| 
驱动器固件版本
 a| 
显示了驱动器固件的修订版级别。



 a| 
全球范围的标识符
 a| 
显示了驱动器的唯一十六进制标识符。



 a| 
产品ID
 a| 
显示制造商分配的产品标识符。



 a| 
序列号
 a| 
显示驱动器的序列号。



 a| 
制造商
 a| 
显示了驱动器的供应商。



 a| 
制造日期
 a| 
显示驱动器的构建日期。


NOTE: 不适用于NVMe驱动器。



 a| 
支持安全保护
 a| 
显示驱动器是否支持安全(是)(否)。支持安全的驱动器可以是全磁盘加密(Full Disk Encryption、FDE)驱动器、也可以是联邦信息处理标准(Federal Information Processing Standard、FIPS)驱动器(级别140-2或140-3)、用于在写入期间对数据进行加密、并在读取期间对数据进行解密。这些驱动器被视为安全驱动器-_capable"、因为可以使用驱动器安全功能提高安全性。如果为这些驱动器使用的卷组和池启用了驱动器安全功能、则这些驱动器将变为secure—_enabled_.



 a| 
已启用安全保护
 a| 
显示驱动器是否已启用安全保护(是)(否)。启用了安全保护的驱动器与驱动器安全功能结合使用。启用驱动器安全功能后、如果将驱动器安全应用于安全-_capable"驱动器上的池或卷组、则这些驱动器将变为安全-_enabled_。只能通过配置了正确安全密钥的控制器进行读写访问。这种增强的安全性可防止未经授权访问从存储阵列中物理删除的驱动器上的数据。



 a| 
可读/写
 a| 
显示驱动器是否可读/写(是)(否)。



 a| 
驱动器安全密钥标识符
 a| 
显示了已启用安全的驱动器的安全密钥。驱动器安全性是一种存储阵列功能，可通过全磁盘加密（ Full Disk Encryption ， FDE ）驱动器或联邦信息处理标准（ Federal Information Processing Standard ， FIPS ）驱动器提供额外的安全层。如果将这些驱动器与驱动器安全功能结合使用，则需要使用安全密钥才能访问其数据。从阵列中物理删除驱动器后、这些驱动器将无法运行、直到将其安装到另一个阵列中为止、此时、这些驱动器将处于安全锁定状态、直到提供了正确的安全密钥为止。



 a| 
支持数据保证(Data Assurance、DA)
 a| 
显示数据保证(Data Assurance、DA)功能是否已启用(Yes)或未启用(No)。数据保证(Data Assurance、DA)是一项功能、用于检查并更正在数据通过控制器向下传输到驱动器时可能发生的错误。可以在池或卷组级别启用数据保证、主机使用光纤通道等具有DA功能的I/O接口。



 a| 
支持DULBE
 a| 
指示已取消分配或未写入逻辑块错误(DULBE")选项是启用("是")还是未启用("否")。DULBE"是NVMe驱动器上的一个选项、它允许EF300或EF600存储阵列支持资源配置的卷。

|===
====
. 单击 * 关闭 * 。

