---
permalink: sm-hardware/view-controller-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, controller, settings 
summary: 您可以查看有关控制器的信息、例如主机接口、驱动器接口和管理端口的状态。 
---
= 查看控制器设置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以查看有关控制器的信息、例如主机接口、驱动器接口和管理端口的状态。

.步骤
. 选择 * 硬件 * 。
. 如果图形显示了驱动器，请单击 * 显示磁盘架背面 * 。
+
此图将发生变化，以显示控制器，而不是驱动器。

. 执行以下操作之一以显示控制器设置：
+
** 单击控制器以显示上下文菜单、然后选择*查看设置*。
** 选择控制器图标(在*磁盘架*下拉列表旁边)。对于双工配置、从对话框中选择*控制器A*或*控制器B*、然后单击*下一步*。
+
此时将打开控制器设置对话框。



. 选择要在属性设置之间移动的选项卡。
+
某些选项卡的右上角有一个*显示更多设置*链接。

+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 选项卡 | Description 


 a| 
基础
 a| 
显示控制器状态、型号名称、更换部件号、当前固件版本和非易失性静态随机存取存储器(NVSRAM)版本。



 a| 
缓存
 a| 
显示了控制器的缓存设置、其中包括数据缓存、处理器缓存和缓存备份设备。如果控制器断电、缓存备份设备用于备份缓存中的数据。状态可以是"最佳"、"失败"、"已删除"、"未知"、"写保护"、 或不兼容。



 a| 
主机接口
 a| 
显示了主机接口信息以及每个端口的链路状态。主机接口是控制器与主机之间的连接、例如光纤通道或iSCSI。


NOTE: 主机接口卡(HIC)位于基板或插槽(托架)中。"基板"表示HIC端口内置在控制器中。"插槽"端口位于可选HIC上。



 a| 
驱动器接口
 a| 
显示了驱动器接口信息以及每个端口的链路状态。驱动器接口是控制器与驱动器(例如SAS)之间的连接。



 a| 
管理端口
 a| 
显示管理端口详细信息、例如用于访问控制器的主机名以及是否已启用远程登录。管理端口用于连接控制器和管理客户端、管理客户端是安装用于访问System Manager的浏览器的位置。



 a| 
DNS/NTP
 a| 
显示DNS服务器和NTP服务器的寻址方法和IP地址(如果已在System Manager中配置这些服务器)。

域名系统(Domain Name System、DNS)是一种命名系统、用于命名连接到Internet或专用网络的设备。DNS服务器维护一个域名目录、并将其转换为Internet协议(IP)地址。

网络时间协议(NTP)是一种网络协议、用于在数据网络中的计算机系统之间进行时钟同步。

|===
====
. 单击 * 关闭 * 。

