---
permalink: sm-hardware/view-hardware-components.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, hardware, components, filtering, 
summary: '"硬件"页面提供了排序和筛选功能、便于查找组件。' 
---
= 在 SANtricity System Manager 中查看硬件组件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"硬件"页面提供了排序和筛选功能、便于查找组件。

.步骤
. 选择 * 硬件 * 。
. 使用下表中所述的功能查看硬件组件。


[cols="25h,~"]
|===
| 功能 | Description 


 a| 
驱动器、控制器和组件视图
 a| 
要在前磁盘架视图和后磁盘架视图之间切换，请从最右侧选择*Drives*或*Controllers & Components*(显示的链接取决于当前视图)。“*驱动器*”视图显示驱动器和任何空驱动器托架。“*控制器和组件*”视图显示了控制器、所有IOM (ESM)模块、电源/风扇箱或空控制器托架。在页面底部，您还可以选择*显示所有驱动器*。



 a| 
驱动器视图筛选器
 a| 
如果存储阵列包含具有不同类型的物理和逻辑属性的驱动器、则*硬件*页面将包含驱动器视图筛选器。通过限制页面上显示的驱动器类型、这些筛选字段可帮助您快速找到特定驱动器。在*显示驱动器...*下、单击左侧的筛选字段(默认情况下、显示*任何驱动器类型*)以查看物理属性(例如容量和速度)的下拉列表。单击右侧的筛选器字段(默认情况下、显示*存储阵列中的任意位置*)以查看逻辑属性的下拉列表(例如、卷组分配)。您可以同时使用这些筛选器、也可以单独使用这些筛选器。

[NOTE]
====
如果存储阵列中的驱动器都共享相同的物理属性、则不会显示左侧的*任何驱动器类型*字段。如果所有驱动器都位于同一逻辑位置、则右侧的*存储阵列中的任意位置*字段不会显示。

====


 a| 
图例
 a| 
这些组件会以特定颜色显示、以描述其角色状态。要展开和折叠这些状态的说明、请单击*图例*。



 a| 
显示状态图标详细信息
 a| 
状态指示器可以包含可用性状态的文本说明。单击*显示状态图标详细信息*可显示或隐藏此状态文本。



 a| 
磁盘架/磁盘架图标
 a| 
每个磁盘架视图均提供一个相关命令列表以及属性和状态。单击*磁盘架*可查看命令的下拉列表。您还可以选择顶部的一个图标来查看各个组件的状态和属性：控制器、IOM (ESM)、电源、风扇、温度、 电池和SFP。



 a| 
磁盘架顺序
 a| 
可以在硬件页面上重新排列这些磁盘架。使用每个磁盘架视图右上角的向上和向下箭头更改磁盘架的顶部/底部顺序。

|===