---
permalink: sm-hardware/what-is-shelf-loss-protection-and-drawer-loss-protection.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, shelf, loss, protection, drawer, 
summary: 磁盘架丢失保护和抽盒丢失保护是池和卷组的属性、可用于在单个磁盘架或抽盒发生故障时保持数据访问。 
---
= 什么是磁盘架丢失保护和抽屉丢失保护？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
磁盘架丢失保护和抽盒丢失保护是池和卷组的属性、可用于在单个磁盘架或抽盒发生故障时保持数据访问。



== 磁盘架丢失保护

磁盘架是指包含驱动器或驱动器和控制器的机箱。磁盘架丢失保护功能可确保在与单个驱动器磁盘架完全失去通信时能够访问池或卷组中卷上的数据。完全失去通信的一个示例可能是驱动器架断电或两个I/O模块(IOM)均发生故障。

[NOTE]
====
如果池或卷组中的驱动器已发生故障、则无法保证磁盘架丢失保护。在这种情况下、如果无法访问某个驱动器架以及池或卷组中的另一个驱动器、则会导致数据丢失。

====
磁盘架丢失保护的标准取决于保护方法、如下表所述：

[cols="1a,1a,1a"]
|===
| 级别 | 磁盘架丢失保护的标准 | 所需的最小磁盘架数 


 a| 
池
 a| 
该池必须包含至少来自五个磁盘架的驱动器、并且每个磁盘架中的驱动器数量必须相等。磁盘架丢失保护不适用于高容量磁盘架；如果您的系统包含高容量磁盘架、请参阅"抽屉丢失保护"。
 a| 
5.



 a| 
RAID 6
 a| 
卷组在一个磁盘架中包含的驱动器不超过两个。
 a| 
3.



 a| 
RAID 3或RAID 5
 a| 
卷组中的每个驱动器都位于一个单独的磁盘架中。
 a| 
3.



 a| 
RAID 1
 a| 
RAID 1对中的每个驱动器都必须位于一个单独的磁盘架中。
 a| 
2.



 a| 
RAID 0
 a| 
无法实现磁盘架丢失保护。
 a| 
不适用

|===


== 抽盒丢失保护

抽盒是拉出以访问驱动器的磁盘架的一个隔室。只有大容量磁盘架才具有抽盒。抽盒丢失保护功能可确保在与单个抽盒完全失去通信时能够访问池或卷组中卷上的数据。完全失去通信的一个示例可能是抽盒断电或抽盒内的内部组件发生故障。

[NOTE]
====
如果池或卷组中的驱动器已发生故障、则不保证提供抽盒丢失保护。在这种情况下、如果无法访问某个抽盒(以及池或卷组中的另一个驱动器)、则会导致数据丢失。

====
抽盒丢失保护的标准取决于保护方法、如下表所述：

[cols="1a,1a,1a"]
|===
| 级别 | 抽盒丢失保护的标准 | 所需的最小抽盒数量 


 a| 
池
 a| 
候选池必须包含所有抽盒中的驱动器、并且每个抽盒中的驱动器数量必须相等。

池中必须至少包含五个抽盒中的驱动器、并且每个抽盒中的驱动器数量必须相等。

如果池包含15、20、25、30、35、 40、45、50、55或60个驱动器。首次创建后、可以将增量以5的倍数添加到池中。
 a| 
5.



 a| 
RAID 6
 a| 
卷组在一个抽屉中包含的驱动器不超过两个。
 a| 
3.



 a| 
RAID 3或RAID 5
 a| 
卷组中的每个驱动器都位于一个单独的抽盒中。
 a| 
3.



 a| 
RAID 1
 a| 
镜像对中的每个驱动器都必须位于一个单独的抽盒中。
 a| 
2.



 a| 
RAID 0
 a| 
无法实现抽盒丢失保护。
 a| 
不适用

|===