---
permalink: sm-hardware/what-is-ipv6-stateless-address-auto-configuration.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ipv6, stateless, address, auto, configuration, 
summary: 使用无状态自动配置时、主机不会从服务器获取地址和其他配置信息。 
---
= 什么是IPv6无状态地址自动配置？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用无状态自动配置时、主机不会从服务器获取地址和其他配置信息。

IPv6中的无状态自动配置功能包括链路本地地址、多播和邻居发现(ND)协议。IPv6可以从底层数据链路层地址生成地址的接口ID。

无状态自动配置与有状态自动配置互为补充。例如、主机可以使用无状态自动配置来配置自己的地址、但可以使用有状态自动配置来获取其他信息。有状态自动配置允许主机从服务器获取地址和其他配置信息。Internet协议版本6 (IPv6)还定义了一种方法、可通过此方法一次性重新编号网络上的所有IP地址。IPv6为网络上的设备定义了一种无需服务器即可自动配置其IP地址和其他参数的方法。

使用无状态自动配置时、设备会执行以下步骤：

. *生成链路本地地址*-设备生成链路本地地址、地址有10位、后跟54个零、后跟64位接口ID。
. *测试链路本地地址的唯一性*—节点将进行测试、以确保其生成的链路本地地址未在本地网络上使用。节点使用NDD协议发送邻居请求消息。作为响应、本地网络会侦听邻居公告消息、这表示另一个设备已在使用链路本地地址。如果是、则必须生成新的链路本地地址或自动配置失败、并且必须使用另一种方法。
. *分配链路本地地址*-如果设备通过唯一性测试、则设备会将链路本地地址分配给其IP接口。链路本地地址可用于在本地网络上进行通信、但不能通过Internet进行通信。
. *联系路由器*—节点尝试联系本地路由器、以了解有关继续配置的详细信息。执行此联系的方法是、侦听路由器定期发送的路由器公告消息、或者发送特定的路由器请求消息以要求路由器提供有关下一步操作的信息。
. *向节点提供方向*-路由器向节点提供如何继续自动配置的方向。或者、路由器会告知主机如何确定全局Internet地址。
. *配置全局地址*—主机使用其全局唯一Internet地址对自身进行配置。此地址通常由路由器提供给主机的网络前缀构成。

