---
permalink: um-manage/considerations-for-discovering-arrays.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, considerations, discovering, arrays 
summary: Unified Manager必须先发现要在组织网络中管理的存储阵列、然后才能显示和管理存储资源。您可以发现多个阵列、也可以发现一个阵列。 
---
= 发现阵列的注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在SANtricity Unified Manager显示和管理存储资源之前、它必须先发现要在组织网络中管理的存储阵列。您可以发现多个阵列、也可以发现一个阵列。



== 发现多个存储阵列

如果您选择发现多个阵列、请输入一个网络IP地址范围、然后Unified Manager将尝试单独连接到该范围中的每个IP地址。任何已成功访问的存储阵列都会显示在"Discover "页面上、并且可能会添加到您的管理域中。



== 发现单个存储阵列

如果您选择发现单个阵列、则输入存储阵列中一个控制器的单个IP地址、然后添加单个存储阵列。

[NOTE]
====
Unified Manager只会发现并显示分配给控制器的范围内的单个IP地址或IP地址。如果为这些控制器分配的备用控制器或IP地址不在此单个IP地址或IP地址范围内、则Unified Manager将不会发现或显示它们。但是、添加存储阵列后、所有关联的IP地址都将被发现并显示在管理视图中。

====


== 用户凭据

在发现过程中、您必须为要添加的每个存储阵列提供管理员密码。



== Web服务证书

在发现过程中、Unified Manager会验证发现的存储阵列是否正在使用受信任源的证书。Unified Manager对与浏览器建立的所有连接使用两种基于证书的身份验证：

* *可信证书*
+
对于Unified Manager发现的阵列、您可能需要安装证书颁发机构提供的其他受信任证书。

+
使用*导入*按钮导入这些证书。如果您之前已连接到此阵列、则一个或两个控制器证书要么已过期、已撤销、要么在其证书链中缺少根证书或中间证书。在管理存储阵列之前、您必须替换已过期或已撤销的证书、或者添加缺少的根证书或中间证书。

* *自签名证书*
+
也可以使用自签名证书。如果管理员尝试在未导入签名证书的情况下发现阵列、则Unified Manager将显示一个错误对话框、允许管理员接受自签名证书。存储阵列的自签名证书将标记为可信、存储阵列将添加到Unified Manager中。

+
如果您不相信与存储阵列的连接、请选择*取消*并验证存储阵列的安全证书策略、然后再将存储阵列添加到Unified Manager。


