---
permalink: um-manage/create-synchronous-mirrored-pair-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, create, synchronous, mirrored, pair 
summary: 要配置同步镜像、请创建一个镜像对、其中包括本地阵列上的主卷和远程阵列上的二级卷。 
---
= 创建同步镜像对
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要配置同步镜像、请创建一个镜像对、其中包括本地阵列上的主卷和远程阵列上的二级卷。

[NOTE]
====
EF600或EF300存储系统不支持此功能。

====
.开始之前
在创建镜像对之前、请满足Unified Manager的以下要求：

* Web服务代理服务必须正在运行。
* Unified Manager必须通过HTTPS连接在本地主机上运行。
* Unified Manager必须显示存储阵列的有效SSL证书。您可以使用Unified Manager接受自签名证书或安装自己的安全证书、并导航到菜单：Certificate[证书管理]。


此外、对于存储阵列和卷、请确保满足以下要求：

* 您计划用于镜像的两个存储阵列会在Unified Manager中发现。
* 每个存储阵列必须具有两个控制器。
* 主阵列和二级阵列中的每个控制器都必须配置一个以太网管理端口、并且必须连接到您的网络。
* 存储阵列的最低固件版本为7.84。(它们可以分别运行不同的操作系统版本。)
* 您必须知道本地和远程存储阵列的密码。
* 本地和远程存储阵列通过光纤通道网络结构进行连接。
* 您已创建要在同步镜像关系中使用的主卷和二级卷。
* 主卷必须是标准卷。它不能是精简卷或快照卷。
* 二级卷必须是标准卷。它不能是精简卷或快照卷。
* 二级卷应至少与主卷大小相同。


.关于此任务
创建同步镜像对的过程包括多步操作步骤。



== 第1步：选择主卷

在此步骤中、您可以选择要在同步镜像关系中使用的主卷。在本地存储阵列上选择主卷时、系统会显示一个列表、其中列出了该镜像对符合条件的所有卷。不符合使用条件的任何卷不会显示在该列表中。您选择的卷在镜像关系中具有主要角色。

.步骤
. 从*管理*页面中、选择要用于源的本地存储阵列。
. 选择菜单：操作[创建同步镜像对]。
+
此时将打开创建同步镜像对向导。

. 从符合条件的卷列表中、选择要用作镜像中主卷的卷。
. 选择*下一步*并转到 <<第2步：选择二级卷>>。




== 第2步：选择二级卷

在此步骤中、您可以选择要在镜像关系中使用的二级卷。在远程存储阵列上选择二级卷时、系统会显示一个列表、其中列出了该镜像对符合条件的所有卷。不符合使用条件的任何卷不会显示在该列表中。您选择的卷将在镜像关系中保留二级角色。

.步骤
. 选择要与本地存储阵列建立镜像关系的远程存储阵列。
+
[NOTE]
====
如果远程存储阵列受密码保护、则系统会提示输入密码。

====
+
** 存储阵列按其存储阵列名称列出。如果您尚未为存储阵列命名、则该存储阵列将列为"未命名"。
** 如果要使用的存储阵列不在列表中、请确保已在Unified Manager中发现它。


. 从符合条件的卷列表中、选择要用作镜像中二级卷的卷。
+
[NOTE]
====
如果选择的二级卷的容量大于主卷、则可用容量将限制为主卷的大小。

====
. 单击*下一步*并转到 <<第3步：选择同步设置>>。




== 第3步：选择同步设置

在此步骤中、您可以选择用于确定在通信中断后如何同步数据的设置。您可以设置在通信中断后主卷的控制器所有者与二级卷重新同步数据的优先级。您还必须选择手动或自动重新同步策略。

.步骤
. 使用滑块栏设置同步优先级。
+
同步优先级用于确定在通信中断后、与服务I/O请求相比、用于完成初始同步和重新同步操作的系统资源量。

+
此对话框中设置的优先级会同时对主卷和二级卷进行适用场景。您可以稍后转到System Manager并选择菜单：Storage[同步镜像>更多>编辑设置]来修改主卷上的速率。

+
同步优先级速率有五种：

+
** 最低
** 低
** 中等
** 高
** 最高
+
如果将同步优先级设置为最低速率、则会优先处理I/O活动、并且重新同步操作所需时间会更长。如果将同步优先级设置为最高比率、则会优先执行重新同步操作、但存储阵列的I/O活动可能会受到影响。



. 选择是手动还是自动重新同步远程存储阵列上的镜像对。
+
** *手动*(建议选项)—选择此选项可要求在恢复与镜像对的通信后手动恢复同步。此选项提供了恢复数据的最佳机会。
** *自动*—选择此选项可在与镜像对的通信恢复后自动开始重新同步。
+
要手动恢复同步、请转到System Manager并选择菜单：Storage[Synchronous Mirroring]、在表中突出显示镜像对、然后在*更多*下选择*恢复*。



. 单击*完成*以完成同步镜像序列。


.结果
激活镜像后、系统将执行以下操作：

* 开始在本地存储阵列和远程存储阵列之间进行初始同步。
* 设置同步优先级和重新同步策略。
* 保留控制器HIC编号最高的端口以进行镜像数据传输。
+
只有镜像对中二级卷的远程首选控制器所有者才会接受在此端口上收到的I/O请求。(允许在主卷上进行预留。)

* 创建两个预留容量卷、每个控制器一个、用于记录写入信息、以便从控制器重置和其他临时中断中恢复。
+
每个卷的容量为128 MiB。但是、如果将卷放置在池中、则会为每个卷预留4 GiB。



.完成后
转到System Manager并选择菜单：主页(查看正在执行的操作)以查看同步镜像操作的进度。此操作可能会很长，并且可能会影响系统性能。
