---
permalink: um-manage/create-asynchronous-mirrored-pair-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, create, asynchronous, mirrored, pair 
summary: 要配置异步镜像、请创建一个镜像对、其中包括本地阵列上的主卷和远程阵列上的二级卷。 
---
= 创建异步镜像对
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要配置异步镜像、请创建一个镜像对、其中包括本地阵列上的主卷和远程阵列上的二级卷。

[NOTE]
====
EF600或EF300存储系统不支持此功能。

====
.开始之前
在创建镜像对之前、请满足Unified Manager的以下要求：

* Web服务代理服务必须正在运行。
* Unified Manager必须通过HTTPS连接在本地主机上运行。
* Unified Manager必须显示存储阵列的有效SSL证书。您可以使用Unified Manager接受自签名证书或安装自己的安全证书、并导航到菜单：Certificate[证书管理]。


此外、对于存储阵列和卷、请确保满足以下要求：

* 每个存储阵列必须具有两个控制器。
* 必须在Unified Manager中发现这两个存储阵列。
* 主阵列和二级阵列中的每个控制器都必须配置一个以太网管理端口、并且必须连接到您的网络。
* 存储阵列的最低固件版本为7.84。(它们可以分别运行不同的操作系统版本。)
* 您必须知道本地和远程存储阵列的密码。
* 您必须在远程存储阵列上具有足够的可用容量、才能创建一个等于或大于要镜像的主卷的二级卷。
* 本地和远程存储阵列通过光纤通道网络结构或iSCSI接口进行连接。
* 您已创建要在异步镜像关系中使用的主卷和二级卷。
* 二级卷必须至少与主卷大小相同。


.关于此任务
创建异步镜像对的过程包括多步操作步骤。



== 第1步：创建或选择镜像一致性组

在此步骤中、您可以创建一个新的镜像一致性组或选择一个现有镜像一致性组。镜像一致性组是主卷和二级卷(镜像对)的容器、并为组中的所有对指定所需的重新同步方法(手动或自动)。

.步骤
. 从*管理*页面中、选择要用于源的本地存储阵列。
. 选择菜单：操作[创建异步镜像对]。
+
此时将打开创建异步镜像对向导。

. 选择现有镜像一致性组或创建新的镜像一致性组。
+
要选择现有组、请确保已选择*现有镜像一致性组*、然后从表中选择该组。一个一致性组可以包含多个镜像对。

+
要创建新组、请执行以下操作：

+
.. 选择*新的镜像一致性组*、然后单击*下一步*。
.. 输入最能描述要在两个存储阵列之间镜像的卷上的数据的唯一名称。名称只能由字母、数字和特殊字符下划线(_)、短划线(-)和哈希符号(#)组成。名称不能超过30个字符、并且不能包含空格。
.. 选择要与本地存储阵列建立镜像关系的远程存储阵列。
+
[NOTE]
====
如果远程存储阵列受密码保护、则系统会提示输入密码。

====
.. 选择是要手动还是自动同步镜像对：
+
*** *手动*-选择此选项可手动为此组中的所有镜像对启动同步。请注意、如果稍后要执行重新同步、则必须启动主存储阵列的System Manager、然后转到菜单：存储(异步镜像)、从*镜像一致性组*选项卡中选择组、然后选择菜单：更多(手动重新同步)。
*** *自动*—从上次更新开始到下次更新开始、选择所需的间隔、以*分钟*、*小时*或*天*为单位。例如、如果同步间隔设置为30分钟、而同步过程在下午4：00开始、则下一个过程将在下午4：30开始


.. 选择所需的警报设置：
+
*** 对于手动同步、请指定接收警报时的阈值(由剩余容量百分比定义)。
*** 对于自动同步、您可以设置三种警报方法： 如果同步未在特定时间长度内完成、远程阵列上的恢复点数据早于特定时间限制、并且预留容量接近特定阈值(由剩余容量百分比定义)。




. 选择*下一步*并转到 <<第2步：选择主卷>>。
+
如果定义了新的镜像一致性组、则Unified Manager会首先在本地存储阵列上创建镜像一致性组、然后在远程存储阵列上创建镜像一致性组。您可以通过为每个阵列启动System Manager来查看和管理镜像一致性组。

+
[NOTE]
====
如果Unified Manager在本地存储阵列上成功创建镜像一致性组、但无法在远程存储阵列上创建该一致性组、则它会自动从本地存储阵列中删除镜像一致性组。如果在Unified Manager尝试删除镜像一致性组时发生错误、您必须手动将其删除。

====




== 第2步：选择主卷

在此步骤中、您可以选择要在镜像关系中使用的主卷并分配其预留容量。在本地存储阵列上选择主卷时、系统会显示一个列表、其中列出了该镜像对符合条件的所有卷。不符合使用条件的任何卷不会显示在该列表中。

添加到本地存储阵列上的镜像一致性组的任何卷都将在镜像关系中发挥主要作用。

.步骤
. 从符合条件的卷列表中、选择要用作主卷的卷、然后单击*下一步*以分配预留容量。
. 从符合条件的候选卷列表中、选择为主卷预留的容量。
+
请记住以下准则：

+
** 预留容量的默认设置为基础卷容量的20%、通常此容量已足够。如果更改百分比、请单击*刷新候选项*。
** 所需容量因向主卷写入I/O的频率和大小以及保留容量所需的时间而异。
** 通常、如果存在以下一种或两种情况、请为预留容量选择更大的容量：
+
*** 您打算将镜像对保留很长时间。
*** 由于I/O活动繁重、主卷上的数据块会发生很大一部分更改。使用历史性能数据或其他操作系统实用程序帮助您确定主卷的典型I/O活动。




. 选择*下一步*并转到 <<第3步：选择二级卷>>。




== 第3步：选择二级卷

在此步骤中、您可以选择要在镜像关系中使用的二级卷并分配其预留容量。在远程存储阵列上选择二级卷时、系统会显示一个列表、其中列出了该镜像对符合条件的所有卷。不符合使用条件的任何卷不会显示在该列表中。

您添加到远程存储阵列上的镜像一致性组的任何卷都将在镜像关系中具有二级角色。

.步骤
. 从符合条件的卷列表中、选择要用作镜像对中二级卷的卷、然后单击*下一步*以分配预留容量。
. 从符合条件的候选卷列表中、选择为二级卷预留的容量。
+
请记住以下准则：

+
** 预留容量的默认设置为基础卷容量的20%、通常此容量已足够。如果更改百分比、请单击*刷新候选项*。
** 所需容量因向主卷写入I/O的频率和大小以及保留容量所需的时间而异。
** 通常、如果存在以下一种或两种情况、请为预留容量选择更大的容量：
+
*** 您打算将镜像对保留很长时间。
*** 由于I/O活动繁重、主卷上的数据块会发生很大一部分更改。使用历史性能数据或其他操作系统实用程序帮助您确定主卷的典型I/O活动。




. 选择*完成*以完成异步镜像序列。


.结果
Unified Manager将执行以下操作：

* 开始在本地存储阵列和远程存储阵列之间进行初始同步。
* 在本地存储阵列和远程存储阵列上为镜像对创建预留容量。



NOTE: 如果要镜像的卷是精简卷、则在初始同步期间、只会将配置的块(已分配容量而不是报告的容量)传输到二级卷。这样可以减少完成初始同步所需传输的数据量。
