---
permalink: um-manage/discover-multiple-arrays.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, discover, multiple, storage, arrays 
summary: 您可以发现多个阵列、以检测管理服务器所在子网中的所有存储阵列、并自动将发现的阵列添加到管理域中。 
---
= 发现多个存储阵列
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以发现多个阵列、以检测管理服务器所在子网中的所有存储阵列、并自动将发现的阵列添加到管理域中。

.开始之前
* 您必须使用具有安全管理员权限的用户配置文件登录。
* 必须正确设置和配置存储阵列。
* 存储阵列密码必须使用System Manager的"访问管理"图块进行设置。
* 要解析不可信的证书、您必须拥有证书颁发机构(CA)提供的可信证书文件、并且证书文件可在本地系统上使用。


发现阵列是一种多步骤操作步骤。



== 第1步：输入网络地址

您可以输入一个网络地址范围、以便在本地子网络中搜索。任何已成功访问的存储阵列都会显示在"Discover "页面上、并且可能会添加到您的管理域中。

如果出于任何原因需要停止发现操作、请单击*停止发现*。

.步骤
. 在 Manage 页面中，选择 * 添加 / 发现 * 。
+
此时将显示添加/发现对话框。

. 选择*发现网络范围内的所有存储阵列*单选按钮。
. 输入起始网络地址和结束网络地址以在本地子网络中搜索、然后单击*开始发现*。
+
发现过程将启动。完成此发现过程可能需要几分钟时间。发现存储阵列时、会填充"发现"页面上的表。

+
[NOTE]
====
如果未发现任何可管理的阵列，请验证这些存储阵列是否已正确连接到您的网络，以及其分配的地址是否在范围内。单击 * 新发现参数 * 以返回到 " 添加 / 发现 " 页面。

====
. 查看已发现的存储阵列列表。
. 选中要添加到管理域的任何存储阵列旁边的复选框、然后单击*下一步*。
+
Unified Manager会对要添加到管理域的每个阵列执行凭据检查。您可能需要解析与该阵列关联的任何自签名证书和不可信证书。

. 单击 * 下一步 * 继续执行向导中的下一步。




== 第2步：在发现期间解析自签名证书

在发现过程中、系统会验证存储阵列是否正在使用受信任源的证书。

.步骤
. 执行以下操作之一：
+
** 如果您信任与发现的存储阵列的连接、请继续访问向导中的下一个卡。自签名证书将标记为可信证书、存储阵列将添加到Unified Manager中。
** 如果您不相信与存储阵列的连接、请选择*取消*并验证每个存储阵列的安全证书策略、然后再将其中任何一个添加到Unified Manager。


. 单击 * 下一步 * 继续执行向导中的下一步。




== 第3步：在发现期间解析不可信的证书

如果存储阵列尝试建立与Unified Manager的安全连接、但此连接无法确认为安全连接、则会发生不可信证书。在阵列发现过程中、您可以通过导入可信第三方颁发的证书颁发机构(CA)证书(或CA签名证书)来解析不可信的证书。

如果满足以下任一条件、您可能需要安装其他受信任的CA证书：

* 您最近添加了一个存储阵列。
* 一个或两个证书均已过期。
* 一个或两个证书均已撤销。
* 一个或两个证书缺少根证书或中间证书。


.步骤
. 选中要为其解析不可信证书的任何存储阵列旁边的复选框、然后选择"*导入"*按钮。
+
此时将打开一个对话框、用于导入可信证书文件。

. 单击*浏览*以选择存储阵列的证书文件。
+
文件名显示在对话框中。

. 单击 * 导入 * 。
+
这些文件将上传并进行验证。

+
[NOTE]
====
如果任何存储阵列存在未解决的不可信证书问题、则不会添加到Unified Manager中。

====
. 单击 * 下一步 * 继续执行向导中的下一步。




== 第4步：提供密码

您必须输入要添加到管理域的存储阵列的密码。

.步骤
. 输入要添加到Unified Manager的每个存储阵列的密码。
. *可选：*将存储阵列与组关联：从下拉列表中、选择要与选定存储阵列关联的所需组。
. 单击 * 完成 * 。


.完成后
存储阵列将添加到管理域中并与选定组(如果指定)关联。

[NOTE]
====
Unified Manager连接到指定存储阵列可能需要几分钟的时间。

====