---
permalink: um-manage/faq-storage-mirroring.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= SANtricity Unified Manager 存储镜像常见问题解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== 在创建镜像一致性组之前、我需要了解哪些信息？

在创建镜像一致性组之前、请遵循以下准则。

满足以下Unified Manager要求：

* Web服务代理服务必须正在运行。
* Unified Manager必须通过HTTPS连接在本地主机上运行。
* Unified Manager必须显示存储阵列的有效SSL证书。您可以使用Unified Manager接受自签名证书或安装自己的安全证书、并导航到菜单：Certificate[证书管理]。


此外、请确保满足以下存储阵列要求：

* 必须在Unified Manager中发现这两个存储阵列。
* 每个存储阵列必须具有两个控制器。
* 主阵列和二级阵列中的每个控制器都必须配置一个以太网管理端口、并且必须连接到您的网络。
* 存储阵列的最低固件版本为7.84。(它们可以分别运行不同的操作系统版本。)
* 您必须知道本地和远程存储阵列的密码。
* 本地和远程存储阵列通过光纤通道网络结构或iSCSI接口进行连接。


[NOTE]
====
EF600/EF600C或EF300/EF300C存储系统不支持同步镜像。

====


== 在创建镜像对之前、我需要了解哪些信息？

创建镜像对之前、请遵循以下准则。

* 您必须有两个存储阵列。
* 每个存储阵列必须具有两个控制器。
* 必须在Unified Manager中发现这两个存储阵列。
* 主阵列和二级阵列中的每个控制器都必须配置一个以太网管理端口、并且必须连接到您的网络。
* 存储阵列的最低固件版本为7.84。(它们可以分别运行不同的操作系统版本。)
* 您必须知道本地和远程存储阵列的密码。
* 您必须在远程存储阵列上具有足够的可用容量、才能创建一个等于或大于要镜像的主卷的二级卷。
* 具有光纤通道(FC)或iSCSI主机端口的控制器支持异步镜像、而只有具有FC主机端口的控制器才支持同步镜像。


[NOTE]
====
EF600/EF600C或EF300/EF300C存储系统不支持同步镜像。

====


== 为什么要更改此百分比？

对于异步镜像操作、预留容量通常为基础卷的20%。通常、此容量足以满足要求。

所需容量因向基础卷写入I/O的频率和大小以及要使用存储对象的副本服务操作的时间而异。通常、如果存在以下一种或两种情况、请选择较大的预留容量百分比：

* 如果特定存储对象的复制服务操作的生命周期很长。
* 如果由于I/O活动繁重而导致基础卷上的大量数据块发生更改、使用历史性能数据或其他操作系统实用程序帮助您确定基础卷的典型I/O活动。




== 为什么我会看到多个预留容量候选项？

如果一个池或卷组中有多个卷满足您为存储对象选择的容量百分比量、则您将看到多个候选卷。

您可以通过更改要在基础卷上为复制服务操作预留的物理驱动器空间百分比来刷新建议候选对象列表。根据您的选择显示最佳候选对象。



== 为什么我看不到我的所有卷？

为镜像对选择主卷时、列表将显示所有符合条件的卷。

不符合使用条件的任何卷不会显示在该列表中。由于以下任一原因、卷可能不符合条件：

* 此卷不是最佳卷。
* 此卷已加入镜像关系。
* 对于同步镜像、镜像对中的主卷和二级卷必须是标准卷。它们不能是精简卷或快照卷。
* 对于异步镜像、精简卷必须启用自动扩展。



NOTE: 对于EF600和EF300控制器、异步镜像对中的主卷和二级卷必须匹配相同的协议、托盘级别、区块大小、安全类型和RAID级别。不符合条件的异步镜像对不会显示在可用卷列表中。



== 为什么我看不到远程存储阵列上的所有卷？

在远程存储阵列上选择二级卷时、列表将显示该镜像对的所有符合条件的卷。

不符合使用条件的任何卷不会显示在该列表中。由于以下任一原因、卷可能不符合条件：

* 此卷是一个非标准卷、例如Snapshot卷。
* 此卷不是最佳卷。
* 此卷已加入镜像关系。
* 对于异步镜像、主卷和二级卷之间的精简卷属性不匹配。
* 如果您使用的是数据保证(Data Assurance、DA)、则主卷和二级卷必须具有相同的DA设置。
+
** 如果主卷已启用DA、则二级卷必须已启用DA。
** 如果主卷未启用DA、则二级卷不能启用DA。


* 对于异步镜像、主卷和二级卷必须具有相同的驱动器安全功能。
+
** 如果主卷支持FIPS、则二级卷必须支持FIPS。
** 如果主卷支持FDE、则二级卷必须支持FDE。
** 如果主卷未使用驱动器安全、则二级卷不得使用驱动器安全。






== 同步优先级对同步速率有何影响？

同步优先级用于定义为同步活动分配的处理时间与系统性能相关。

主卷的控制器所有者在后台执行此操作。同时、控制器所有者会处理对主卷的本地I/O写入以及对二级卷的相关远程写入。由于重新同步会使控制器处理资源偏离I/O活动、因此重新同步可能会影响主机应用程序的性能。

请牢记以下准则、以帮助您确定同步优先级可能需要多长时间以及同步优先级如何影响系统性能。

可以使用以下优先级：

* 最低
* 低
* 中等
* 高
* 最高


最低优先级速率支持系统性能、但重新同步所需时间较长。最高优先级速率支持重新同步、但系统性能可能会受到影响。

这些准则大致近似于优先级之间的差异。

[cols="45h,~"]
|===
| 完全同步的优先级速率 | 与最高同步速率相比所用时间 


 a| 
最低
 a| 
约为最高优先级速率的八倍。



 a| 
低
 a| 
约为最高优先级速率的六倍。



 a| 
中等
 a| 
大约是最高优先级速率的三倍半。



 a| 
高
 a| 
大约是最高优先级速率时的两倍。

|===
卷大小和主机I/O速率负载会影响同步时间比较。



== 为什么建议使用手动同步策略？

建议使用手动重新同步、因为它可以让您以最佳机会恢复数据的方式管理重新同步过程。

如果使用自动重新同步策略、并且在重新同步期间发生间歇性通信问题、则二级卷上的数据可能会暂时损坏。重新同步完成后、数据将得到更正。
