---
permalink: um-manage/mirroring-overview.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, mirroring, 
summary: Unified Manager提供了SANtricity 镜像功能的配置选项、可使管理员在两个存储阵列之间复制数据以实现数据保护。 
---
= 镜像的工作原理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager提供了SANtricity 镜像功能的配置选项、可使管理员在两个存储阵列之间复制数据以实现数据保护。

[NOTE]
====
EF600或EF300存储系统不支持此功能。

====


== 镜像类型

SANtricity 应用程序包括两种类型的镜像：异步和同步。

异步镜像可按需或按计划复制数据卷、从而最大限度地减少或避免因数据损坏或丢失而导致的停机时间。异步镜像可捕获主卷在特定时间点的状态、并仅复制自上次映像捕获以来发生更改的数据。可以立即更新主站点、并在带宽允许的情况下更新二级站点。此信息将在网络资源可用时进行缓存并稍后发送。这种类型的镜像非常适合备份和归档等定期过程。

同步镜像可实时复制数据卷、以确保持续可用性。其目的是、在两个存储阵列之一发生灾难时、提供一份重要数据副本、从而实现零丢失数据的恢复点目标(RPO)。副本与生产数据在每一刻都是相同的、因为每次对主卷执行写入时、都会对二级卷执行写入。在使用主卷上所做的更改更新二级卷之前、主机不会收到写入成功的确认消息。这种类型的镜像非常适合用于灾难恢复等业务连续性目的。



== 镜像类型之间的差异

下表介绍了这两种镜像类型之间的主要区别。

[cols="1a,1a,1a"]
|===
| 属性 | 异步 | 同步 


 a| 
复制方法
 a| 
时间点—镜像是按需执行的、也可以根据用户定义的计划自动执行。
 a| 
持续—镜像会自动持续执行、每次写入主机时都会复制数据。



 a| 
距离
 a| 
支持阵列之间的长距离。通常、距离仅受网络功能和通道扩展技术的限制。
 a| 
限制为阵列之间的距离较短。通常、距离必须在本地存储阵列10公里(6.2英里)以内、才能满足延迟和应用程序性能要求。



 a| 
通信方法
 a| 
标准IP或光纤通道网络。
 a| 
仅限光纤通道网络。



 a| 
卷类型
 a| 
标准或精简。
 a| 
仅限标准配置。

|===