---
permalink: um-manage/mirroring-configuration-workflow.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, mirroring, configuration, workflow 
summary: 您可以在Unified Manager中配置异步或同步镜像、然后使用System Manager管理同步。 
---
= 镜像配置工作流
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在Unified Manager中配置异步或同步镜像、然后使用System Manager管理同步。



== 异步镜像工作流

异步镜像涉及以下工作流：

. 在Unified Manager中执行初始配置：
+
.. 选择本地存储阵列作为数据传输的源。
.. 创建或选择现有镜像一致性组、该组是本地阵列上主卷和远程阵列上二级卷的容器。主卷和二级卷称为"镜像对"。 如果您是首次创建镜像一致性组、则可以指定是要执行手动同步还是计划同步。
.. 从本地存储阵列中选择主卷、然后确定其预留容量。预留容量是为复制操作分配的物理容量。
.. 选择一个远程存储阵列作为传输的目标、一个二级卷、然后确定其预留容量。
.. 开始从主卷到二级卷的初始数据传输。根据卷大小、此初始传输可能需要几小时的时间。


. 检查初始同步的进度：
+
.. 在Unified Manager中、为本地阵列启动System Manager。
.. 在System Manager中、查看镜像操作的状态。镜像完成后、镜像对的状态为"最佳"。


. 您也可以在System Manager中重新计划或手动执行后续数据传输。只有新的块和更改的块才会从主卷传输到二级卷。
+
[NOTE]
====
由于异步复制是定期进行的、因此系统可以整合更改的块并节省网络带宽。对写入吞吐量和写入延迟的影响最小。

====




== 同步镜像工作流

同步镜像涉及以下工作流：

. 在Unified Manager中执行初始配置：
+
.. 选择一个本地存储阵列作为数据传输的源。
.. 从本地存储阵列中选择主卷。
.. 选择一个远程存储阵列作为数据传输的目标、然后选择一个二级卷。
.. 选择同步和重新同步优先级。
.. 开始从主卷到二级卷的初始数据传输。根据卷大小、此初始传输可能需要几小时的时间。


. 检查初始同步的进度：
+
.. 在Unified Manager中、为本地阵列启动System Manager。
.. 在System Manager中、查看镜像操作的状态。镜像完成后、镜像对的状态为"最佳"。 这两个阵列会尝试通过正常操作保持同步。只有新的块和更改的块才会从主卷传输到二级卷。


. 您也可以在System Manager中更改同步设置。
+
[NOTE]
====
由于同步复制是持续的、因此两个站点之间的复制链路必须提供足够的带宽功能。

====

