---
permalink: um-manage/overview-upgrade-center-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, upgrade, center 
summary: 从升级中心、您可以管理多个存储阵列的SANtricity OS软件和NVSRAM升级。 
---
= 升级中心概述
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从升级中心、您可以管理多个存储阵列的SANtricity OS软件和NVSRAM升级。



== 升级如何工作？

下载最新的操作系统软件、然后升级一个或多个阵列。



=== 升级工作流

以下步骤提供了执行软件升级的高级工作流。

. 您可以从支持站点下载最新的SANtricity OS软件文件(可从Unified Manager的"支持"页面中找到一个链接)。将此文件保存在管理主机系统(在浏览器中访问Unified Manager的主机)上、然后解压缩此文件。
. 在Unified Manager中、您可以将SANtricity OS软件文件和NVSRAM文件加载到存储库(存储文件的Web服务代理服务器的一个区域)。您可以从菜单：升级中心[升级SANtricity 操作系统软件或从升级中心>管理软件存储库]添加文件。
. 将文件加载到存储库中后、您可以选择要在升级中使用的文件。从升级SANtricity OS软件页面(菜单：升级中心[升级SANtricity OS软件])中、选择SANtricity OS软件文件和NVSRAM文件。选择软件文件后、此页面上将显示兼容存储阵列列表。然后、选择要使用新软件升级的存储阵列。(不能选择不兼容的阵列。)
. 然后、您可以立即开始软件传输和激活、也可以选择稍后暂存文件以进行激活。在升级过程中、Unified Manager将执行以下任务：
+
.. 对存储阵列执行运行状况检查、以确定是否存在任何可能阻止升级完成的条件。如果任何阵列未通过运行状况检查，您可以跳过该特定阵列并继续对其他阵列进行升级，也可以停止整个过程并对未通过的阵列进行故障排除。
.. 将升级文件传输到每个控制器。
.. 重新启动控制器并激活新的SANtricity OS软件、一次一个控制器。激活期间、现有SANtricity OS文件将替换为新文件。
+
[NOTE]
====
您还可以指定稍后激活此软件。

====






=== 立即或分阶段升级

您可以立即激活升级，也可以稍后暂存升级。您可以选择稍后激活，原因如下：

* * 当前时间 * —激活软件可能需要很长时间，因此您可能需要等待 I/O 负载变轻。根据 I/O 负载和缓存大小，完成控制器升级通常需要 15 到 25 分钟。控制器会在激活期间重新启动并进行故障转移，因此在升级完成之前性能可能会比平常低。
* * 软件包类型 * —您可能需要先在一个存储阵列上测试新软件和固件，然后再升级其他存储阵列上的文件。


要激活暂存软件、请转到菜单：Support[升级中心]、然后单击标记为SANtricity OS控制器软件升级的区域中的*激活*。



=== 运行状况检查

运行状况检查会在升级过程中运行、但您也可以在开始之前单独运行运行运行运行状况检查(转到菜单：升级中心[升级前运行状况检查])。

运行状况检查会评估所有存储系统组件、以确保升级可以继续进行。以下情况可能会阻止升级：

* 已分配的驱动器出现故障
* 正在使用热备件
* 卷组不完整
* 正在运行排他操作
* 缺少卷
* 控制器处于非最佳状态
* 事件日志事件数量过多
* 配置数据库验证失败
* 使用旧版 DAC 存储的驱动器




== 升级前需要了解哪些信息？

在升级多个存储阵列之前、请在规划过程中查看主要注意事项。



=== 当前版本

您可以从Unified Manager的"管理"页面查看每个已发现存储阵列的当前SANtricity OS软件版本。此版本显示在SANtricity OS软件列中。单击每行中的 SANtricity OS 版本时，会在弹出对话框中显示控制器固件和 NVSRAM 信息。



=== 其他需要升级的组件

在升级过程中、您可能还需要升级主机的多路径/故障转移驱动程序或HBA驱动程序、以便主机可以正确地与控制器进行交互。

有关兼容性信息，请参见 https://imt.netapp.com/matrix/#welcome["NetApp 互操作性表"^]。另请参见适用于您的操作系统的快速指南中的过程。快速指南可从获取 https://docs.netapp.com/us-en/e-series/index.html["E 系列和 SANtricity 文档"^]。



=== 双控制器

如果存储阵列包含两个控制器，并且您安装了多路径驱动程序，则在升级期间，存储阵列可以继续处理 I/O 。在升级期间，将执行以下过程：

. 控制器 A 将其所有 LUN 故障转移到控制器 B
. 升级在控制器 A 上进行
. 控制器 A 将收回其 LUN 以及控制器 B 的所有 LUN 。
. 升级在控制器 B 上进行


升级完成后，您可能需要在控制器之间手动重新分布卷，以确保卷返回到正确的所属控制器。
