---
permalink: sm-settings/automatic-load-balancing-overview.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, automatic, load, balancing, 
summary: 自动负载平衡可随着时间的推移对负载变化做出动态响应、并自动调整卷控制器所有权、以便在工作负载在控制器之间移动时更正任何负载不平衡问题、从而改进I/O资源管理。 
---
= 了解 SANtricity 软件中的自动负载平衡
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
自动负载平衡可随着时间的推移对负载变化做出动态响应、并自动调整卷控制器所有权、以便在工作负载在控制器之间移动时更正任何负载不平衡问题、从而改进I/O资源管理。

系统会持续监控每个控制器的工作负载、并在主机上安装的多路径驱动程序的配合下、在必要时自动实现平衡。在控制器之间自动重新平衡工作负载时、存储管理员无需再承担手动调整卷控制器所有权以适应存储阵列上的负载变化的负担。

启用自动负载平衡后、它将执行以下功能：

* 自动监控和平衡控制器资源利用率。
* 根据需要自动调整卷控制器所有权、从而优化主机和存储阵列之间的I/O带宽。




== 启用和禁用自动负载平衡

默认情况下、所有存储阵列都会启用自动负载平衡。

您可能需要在存储阵列上禁用自动负载平衡、原因如下：

* 您不希望自动更改特定卷的控制器所有权以平衡工作负载。
* 您正在高度调整的环境中运行、在此环境中、负载分布会有针对性地进行设置、以便在控制器之间实现特定的分布。




== 支持自动负载平衡功能的主机类型

即使在存储阵列级别启用了自动负载平衡、您为主机或主机集群选择的主机类型也会直接影响此功能的运行方式。

在控制器之间平衡存储阵列的工作负载时、自动负载平衡功能会尝试移动两个控制器均可访问且仅映射到能够支持自动负载平衡功能的主机或主机集群的卷。

此行为可防止主机因负载平衡过程而无法访问卷；但是、映射到不支持自动负载平衡的主机的卷会影响存储阵列平衡工作负载的能力。要使自动负载平衡平衡平衡工作负载、多路径驱动程序必须支持TPG、并且下表中必须包括主机类型。

[NOTE]
====
要将主机集群视为能够自动负载平衡、该组中的所有主机都必须能够支持自动负载平衡。

====
[cols="1a,1a"]
|===
| 支持自动负载平衡的主机类型 | 使用此多路径驱动程序 


 a| 
Windows或Windows集群模式
 a| 
MPIO与NetApp E系列DSM



 a| 
Linux DM-MP (内核3.10或更高版本)
 a| 
DM-MP与`sCSI DH_ALUA`设备处理程序



 a| 
VMware
 a| 
采用`VMW_SATA_ALUA存储阵列类型`插件的原生 多路径插件(NMP)

|===
[NOTE]
====
除次要例外情况外、不支持自动负载平衡的主机类型继续正常运行、无论是否启用了此功能。一个例外情况是、如果系统发生故障转移、则当数据路径返回时、存储阵列会将未映射或未分配的卷移回所属控制器。不会移动映射或分配给非自动负载平衡主机的任何卷。

====
请参见 https://mysupport.netapp.com/matrix["互操作性表工具"^] 有关特定多路径驱动程序、操作系统级别和控制器驱动器托盘支持的兼容性信息。



== 验证操作系统与自动负载平衡功能的兼容性

在设置新系统(或迁移现有系统)之前、请验证操作系统与自动负载平衡功能的兼容性。

. 转至 https://mysupport.netapp.com/matrix["互操作性表工具"^] 以查找解决方案 并验证支持。
+
如果您的系统运行的是Red Hat Enterprise Linux 6或SUSE Linux Enterprise Server 11、请联系技术支持。

. 更新并配置`/etc/multipath.conf文件`。
. 确保适用的供应商和产品的`renet_attached _device_handler`和`detect_prio`均设置为`yes`、或者使用默认设置。

