---
permalink: sm-settings/change-saml-role-mappings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, saml, role, mappings, 
summary: 如果先前已为访问管理配置SAML、则可以更改IdP组与存储阵列的预定义角色之间的角色映射。 
---
= 更改SAML角色映射
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果先前已为访问管理配置SAML、则可以更改IdP组与存储阵列的预定义角色之间的角色映射。

.开始之前
* 您必须使用包含安全管理员权限的用户配置文件登录。否则、不会显示访问管理功能。
* IdP管理员已在IdP系统中配置用户属性和组成员资格。
* 已配置并启用SAML。


.步骤
. 选择菜单：设置[访问管理]。
. 选择* SAML *选项卡。
. 选择*角色映射*。
+
此时将打开角色映射对话框。

. 为预定义角色分配IdP用户属性和组。一个组可以分配多个角色。
+
[CAUTION]
====
请注意、在启用SAML时、您不会删除权限、否则您将无法访问System Manager。

====
+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 正在设置 ... | Description 


 a| 
*映射*



 a| 
用户属性
 a| 
指定要映射的SAML组的属性(例如、"member for")。



 a| 
属性值
 a| 
指定要映射的组的属性值。



 a| 
角色
 a| 
单击此字段、然后选择要映射到此属性的存储阵列角色之一。您必须单独为此组选择要包含的每个角色。要登录到System Manager、需要将监控角色与其他角色结合使用。必须至少将安全管理员角色分配给一个组。映射的角色包括以下权限：

** *存储管理*—对存储对象(例如卷和磁盘池)具有完全读/写访问权限、但无法访问安全配置。
** *安全管理*—访问访问管理、证书管理、审核日志管理中的安全配置、以及打开或关闭原有管理界面(符号)的功能。
** *支持管理*—访问存储阵列上的所有硬件资源、故障数据、MEL事件和控制器固件升级。无法访问存储对象或安全配置。
** *监控*—对所有存储对象的只读访问、但无法访问安全配置。


|===
====
+

NOTE: 包括管理员在内的所有用户都需要"监控"角色。如果没有"监控"角色、则System Manager将无法正常运行。

. 或者、也可以单击*添加另一个映射*以输入更多组到角色的映射。
. 单击 * 保存 * 。


.结果
完成此任务后、所有活动用户会话都将终止。仅会保留当前用户会话。
