---
permalink: sm-settings/configure-snmp-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, snmp, alerts, 
summary: '要配置简单网络管理协议(Simple Network Management Protocol、SNMP)警报、您必须至少确定一台存储阵列的事件监控器可以发送SNMP陷阱的服务器。此配置需要社区名称或用户名以及服务器的IP地址。' 
---
= 配置SNMP警报
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要配置简单网络管理协议(Simple Network Management Protocol、SNMP)警报、您必须至少确定一台存储阵列的事件监控器可以发送SNMP陷阱的服务器。此配置需要社区名称或用户名以及服务器的IP地址。

.开始之前
* 必须为网络服务器配置SNMP服务应用程序。您需要此服务器的网络地址(IPv4或IPv6地址)、以便事件监控器可以向该地址发送陷阱消息。您可以使用多个服务器(最多允许10个服务器)。
* 已使用SNMP服务应用程序在服务器上复制和编译管理信息库(Management Information Base、MIB)文件。此MIB文件定义了要监控和管理的数据。
+
如果您没有MIB文件、可以从NetApp支持站点获取：

+
** 转至 https://mysupport.netapp.com/site/global/dashboard["NetApp 支持"^]。
** 单击*下载*选项卡、然后选择*下载*。
** 单击* E系列SANtricity 操作系统控制器软件*。
** 选择*下载最新版本*。
** 登录。
** 接受警告声明和许可协议。
** 向下滚动、直到看到您的控制器类型对应的MIB文件、然后单击链接以下载此文件。




.关于此任务
此任务介绍如何识别陷阱目标的SNMP服务器、然后测试您的配置。

.步骤
. 选择菜单：设置[警报]。
. 选择* SNMP *选项卡。
+
首次设置时、SNMP选项卡会显示"Configure Communities/Users"。

. 选择*配置社区/用户*。
+
此时将打开选择SNMP版本对话框。

. 为警报选择SNMP版本、可以是* SNMPv2c*或* SNMPv3 *。
+
根据您的选择、将打开配置社区对话框或配置SNMPv3用户对话框。

. 按照SNMPv2c (社区)或SNMPv3 (用户)的相应说明进行操作：
+
** * SNMPv2c (社区)*—在配置社区对话框中、为网络服务器输入一个或多个社区字符串。社区名称是一个字符串、用于标识一组已知的管理工作站、通常由网络管理员创建。它仅包含可打印的ASCII字符。您最多可以添加256个社区。完成后、单击*保存*。
** * SNMPv3 (用户)*—在配置SNMPv3用户对话框中、单击*添加*、然后输入以下信息：
+
*** *用户名*-输入一个名称以标识用户、该名称最长可达31个字符。
*** *引擎ID*-选择引擎ID、此ID用于为消息生成身份验证和加密密钥、并且在管理域上必须是唯一的。在大多数情况下、应选择*本地*。如果您使用的是非标准配置、请选择*自定义*；此时将显示另一个字段、您必须在其中输入权威引擎ID作为十六进制字符串、并且字符数为偶数、长度介于10到32个字符之间。
*** *身份验证凭据*-选择一种身份验证协议、以确保用户的身份。接下来、输入一个身份验证密码、设置或更改身份验证协议时需要此密码。密码长度必须介于8到128个字符之间。
*** *隐私凭据*-选择用于对消息内容进行加密的隐私协议。接下来、输入隐私密码、设置或更改隐私协议时需要此密码。密码长度必须介于8到128个字符之间。完成后、单击*添加*、然后单击*关闭*。




. 在选择了SNMP选项卡的警报页面中、单击*添加陷阱目标*。
+
此时将打开添加陷阱目标对话框。

. 输入一个或多个陷阱目标、选择其关联的社区名称或用户名、然后单击*添加*。
+
** *陷阱目标*-输入运行SNMP服务的服务器的IPv4或IPv6地址。
** *社区名称或用户名*-从下拉列表中、为此陷阱目标选择社区名称(SNMPv2c)或用户名(SNMPv3)。(如果您仅定义了一个、则此名称已显示在此字段中。)
** *发送身份验证失败陷阱*-如果要在SNMP请求因社区名称或用户名无法识别而被拒绝时向陷阱目标发出警报、请选择此选项(复选框)。单击*添加*后、陷阱目标和关联名称将显示在*警报*页面的* SNMP*选项卡中。


. 要确保陷阱有效、请从表中选择一个陷阱目标、然后单击*测试陷阱目标*向配置的地址发送测试陷阱。


.结果
每当发生可更改的事件时、事件监控器都会向服务器发送SNMP陷阱。
