---
permalink: sm-settings/configure-iscsi-ports-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, iSCSI, ports, systems 
summary: 如果控制器包含iSCSI主机连接、则可以从系统页面配置iSCSI端口设置。 
---
= 配置iSCSI端口
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果控制器包含iSCSI主机连接、则可以从系统页面配置iSCSI端口设置。

.开始之前
* 控制器必须包含iSCSI端口；否则、iSCSI设置不可用。
* 您必须知道网络速度(端口与主机之间的数据传输速率)。


[NOTE]
====
只有当存储阵列支持iSCSI时、才会显示iSCSI设置和功能。

====
.步骤
. 选择菜单：设置[系统]。
. 在* iSCSI设置*下、选择*配置iSCSI端口*。
+
[NOTE]
====
只有当System Manager检测到控制器上的iSCSI端口时、才会显示配置iSCSI端口选项。

====
. 选择包含要配置的iSCSI端口的控制器。
. 在下拉列表中，选择要配置的端口，然后单击 * 下一步 * 。
. 选择配置端口设置，然后单击 * 下一步 * 。
+
要查看所有端口设置，请单击对话框右侧的 * 显示更多端口设置 * 链接。

+
.字段详细信息
====
[cols="1a,1a"]
|===
| 端口设置 | Description 


 a| 
已配置以太网端口速度(仅针对某些类型的主机接口卡显示)
 a| 
在端口上选择与SFP速度功能匹配的速度。



 a| 
正向错误更正(FEC)模式(仅针对某些类型的主机接口卡显示)
 a| 
如果需要、请为指定主机端口选择一种FEC模式。


NOTE: Reed Solomon模式不支持25 Gbps端口速度。



 a| 
启用 IPv4/Enable IPv6
 a| 
选择一个或两个选项以启用对 IPv4 和 IPv6 网络的支持。


NOTE: 如果要禁用端口访问、请取消选中这两个复选框。



 a| 
TCP 侦听端口（可通过单击 * 显示更多端口设置 * 来使用。）
 a| 
如有必要，请输入新的端口号。

侦听端口是控制器用于侦听主机 iSCSI 启动程序的 iSCSI 登录的 TCP 端口号。默认侦听端口为 3260 。您必须输入 3260 或 49152 到 65535 之间的值。



 a| 
MTU 大小（可通过单击 * 显示更多端口设置 * 来获取。）
 a| 
如有必要，请为最大传输单元（ Maximum Transmission Unit ， MTU ）输入一个新大小（以字节为单位）。

默认最大传输单元（ Maximum Transmission Unit ， MTU ）大小为每帧 1500 字节。您必须输入一个介于 1500 和 9000 之间的值。



 a| 
启用 ICMP ping 响应
 a| 
选择此选项可启用 Internet 控制消息协议（ Internet Control Message Protocol ， ICMP ）。网络计算机的操作系统使用此协议发送消息。这些 ICMP 消息可确定主机是否可访问以及从该主机获取数据包所需的时间。

|===
====
+
如果选择了 * 启用 IPv* ，则在单击 * 下一步 * 后，将打开一个对话框，用于选择 IPv4 设置。如果选择了 * 启用 IPv6* ，则在单击 * 下一步 * 后，将打开一个对话框，用于选择 IPv6 设置。如果同时选择了这两个选项，则 IPv4 设置对话框将首先打开，然后单击 * 下一步 * ， IPv6 设置对话框将打开。

. 自动或手动配置 IPv4 和 / 或 IPv6 设置。要查看所有端口设置，请单击对话框右侧的 * 显示更多设置 * 链接。
+
.字段详细信息
====
[cols="1a,1a"]
|===
| 端口设置 | Description 


 a| 
自动获取配置
 a| 
选择此选项可自动获取配置。



 a| 
手动指定静态配置
 a| 
选择此选项，然后在字段中输入静态地址。(如果需要、可以剪切地址并将其粘贴到字段中。) 对于IPv4、请包括网络子网掩码和网关。对于 IPv6 ，请包括可路由的 IP 地址和路由器 IP 地址。



 a| 
启用 VLAN 支持（可通过单击 * 显示更多设置 * 来获取。）
 a| 
选择此选项可启用 VLAN 并输入其 ID 。VLAN 是一种逻辑网络，其行为与相同交换机，相同路由器或这两者所支持的其他物理和虚拟局域网（ LAN ）在物理上是分开的。



 a| 
启用以太网优先级（可通过单击 * 显示更多设置 * 来使用）。
 a| 
选择此选项可启用用于确定网络访问优先级的参数。使用滑块选择介于1 (最低)和7 (最高)之间的优先级。

在以太网等共享局域网（ LAN ）环境中，许多工作站可能会争用网络访问权限。访问权限按先到先得原则提供。两个工作站可能会同时尝试访问网络，这会导致两个工作站重新关闭并等待，然后再重试。对于只有一个工作站连接到交换机端口的交换式以太网，此过程会最小化。

|===
====
. 单击 * 完成 * 。

