---
permalink: sm-settings/configure-syslog-server-for-audit-logs.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, syslog, server, audit, logs, 
summary: 如果要将审核日志归档到外部系统日志服务器、则可以配置该服务器与存储阵列之间的通信。建立连接后、审核日志会自动保存到系统日志服务器。 
---
= 为审核日志配置系统日志服务器
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要将审核日志归档到外部系统日志服务器、则可以配置该服务器与存储阵列之间的通信。建立连接后、审核日志会自动保存到系统日志服务器。

.开始之前
* 您必须使用包含安全管理员权限的用户配置文件登录。否则、不会显示访问管理功能。
* 系统日志服务器地址、协议和端口号必须可用。服务器地址可以是完全限定域名、IPv4地址或IPv6地址。
* 如果您的服务器使用安全协议(例如TLS)、则本地系统上必须具有证书颁发机构(CA)证书。CA证书用于标识服务器和客户端之间安全连接的网站所有者。


.步骤
. 选择菜单：设置[访问管理]。
. 从审核日志选项卡中、选择*配置系统日志服务器*。
+
此时将打开配置系统日志服务器对话框。

. 单击 * 添加 * 。
+
此时将打开添加系统日志服务器对话框。

. 输入服务器的信息、然后单击*添加*。
+
** *服务器地址*-输入完全限定域名、IPv4地址或IPv6地址。
** *协议*-从下拉列表中选择一个协议(例如TLS、UDP或TCP)。
** *上传证书(可选)*—如果您选择了TLS协议但尚未上传签名的CA证书、请单击*浏览*上传证书文件。如果没有可信证书、则不会将审核日志归档到系统日志服务器。
+
[NOTE]
====
如果证书稍后变得无效、TLS握手将失败。因此、将向审核日志发布错误消息、并且不再向系统日志服务器发送消息。要解决此问题描述 、您必须修复系统日志服务器上的证书、然后转到菜单：设置(审核日志>配置系统日志服务器>测试全部)。

====
** *端口*-输入系统日志接收器的端口号。单击*添加*后、配置系统日志服务器对话框将打开、并在页面上显示已配置的系统日志服务器。


. 要测试服务器与存储阵列的连接、请选择*全部测试*。


.结果
配置后、所有新审核日志都会发送到系统日志服务器。不会传输先前的日志。要进一步配置警报的系统日志设置、请参见 https://docs.netapp.com/us-en/e-series-santricity/sm-settings/configure-syslog-server-for-alerts.html["为系统日志服务器配置警报"]。
