---
permalink: sm-settings/configure-iscsi-authentication.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, iscsi, authentication, 
summary: '为了提高iSCSI网络的安全性、您可以在控制器(目标)和主机(启动程序)之间设置身份验证。' 
---
= 配置iSCSI身份验证
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
为了提高iSCSI网络的安全性、您可以在控制器(目标)和主机(启动程序)之间设置身份验证。

System Manager使用质询握手身份验证协议(Challenge Handshake Authentication Protocol、CHAP)方法、在初始链接期间验证目标和启动程序的身份。身份验证基于名为_CHAP secret_的共享安全密钥。

.开始之前
您可以在为目标(控制器)设置CHAP密钥之前或之后为启动程序(iSCSI主机)设置CHAP密钥。在按照此任务中的说明进行操作之前、您应等待主机先建立iSCSI连接、然后在各个主机上设置CHAP密钥。建立连接后、主机的IQN名称及其CHAP密钥将在iSCSI身份验证对话框中列出(如本任务所述)、您无需手动输入它们。

.关于此任务
您可以选择以下身份验证方法之一：

* *单向身份验证*—使用此设置允许控制器对iSCSI主机的身份进行身份验证(单向身份验证)。
* *双向身份验证*—使用此设置可允许控制器和iSCSI主机执行身份验证(双向身份验证)。此设置可通过使控制器对iSCSI主机的身份进行身份验证来提供第二级安全性、进而使iSCSI主机对控制器的身份进行身份验证。


[NOTE]
====
只有当存储阵列支持iSCSI时、iSCSI设置和功能才会显示在设置页面上。

====
.步骤
. 选择菜单：设置[系统]。
. 在iSCSI设置下、单击*配置身份验证*。
+
此时将显示配置身份验证对话框、其中显示了当前设置的方法。此外、还会显示是否已配置任何主机的CHAP机密。

. 选择以下选项之一：
+
** *无身份验证*-如果不希望控制器对iSCSI主机的身份进行身份验证、请选择此选项并单击*完成*。此时、对话框将关闭、您将完成配置。
** *单向身份验证*—要允许控制器对iSCSI主机的身份进行身份验证、请选择此选项并单击*下一步*以显示配置目标CHAP对话框。
** *双向身份验证*—要允许控制器和iSCSI主机执行身份验证、请选择此选项并单击*下一步*以显示配置目标CHAP对话框。


. 对于单向或双向身份验证、输入或确认控制器(目标)的CHAP密钥。CHAP密钥必须介于12到57个可打印ASCII字符之间。
+
[NOTE]
====
如果先前为控制器配置了CHAP密钥、则会屏蔽字段中的字符。如有必要、您可以替换现有字符(新字符不会屏蔽)。

====
. 执行以下操作之一：
+
** 如果要配置_one-way_身份验证、请单击*完成*。此时、对话框将关闭、您将完成配置。
** 如果要配置_two-way_身份验证、请单击*下一步*以显示配置启动程序CHAP对话框。


. 对于双向身份验证、请输入或确认任何iSCSI主机(启动程序)的CHAP密钥、该密钥可以是12到57个可打印ASCII字符。如果不想为特定主机配置双向身份验证、请将启动程序CHAP机密字段留空。
+
[NOTE]
====
如果先前为主机配置了CHAP密钥、则字段中的字符将被屏蔽。如有必要、您可以替换现有字符(新字符不会屏蔽)。

====
. 单击 * 完成 * 。


.结果
除非未指定身份验证、否则在控制器和iSCSI主机之间的iSCSI登录序列期间会进行身份验证。
