---
permalink: sm-settings/configure-nvme-over-roce-ports-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, nvme, roce, ports, 
summary: '如果您的控制器包括通过RoCE连接NVMe (基于融合以太网的RDMA)、则可以从系统页面配置NVMe端口设置。' 
---
= 在 SANtricity System Manager 中配置 NVMe over RoCE 端口
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您的控制器包括通过RoCE连接NVMe (基于融合以太网的RDMA)、则可以从系统页面配置NVMe端口设置。

.开始之前
* 您的控制器必须包含一个基于RoCE的NVMe主机端口；否则、System Manager中不提供基于RoCE的NVMe设置。
* 您必须知道主机连接的IP地址。


.步骤
. 选择菜单：设置[系统]。
. 在*基于ROCE的NVMe设置*下、选择*配置基于ROCE的NVMe端口*。
. 选择具有要配置的基于RoCE的NVMe端口的控制器。单击 * 下一步 * 。
. 从下拉列表中选择要配置的HIC端口。单击 * 下一步 * 。
. 配置端口设置。
+
要查看所有端口设置，请单击对话框右侧的 * 显示更多端口设置 * 链接。

+
.字段详细信息
[%collapsible]
====
[cols="1a,1a"]
|===
| 端口设置 | Description 


 a| 
已配置以太网端口速度
 a| 
在端口上选择与SFP速度功能匹配的速度。



 a| 
启用 IPv4/Enable IPv6
 a| 
选择一个或两个选项以启用对 IPv4 和 IPv6 网络的支持。


NOTE: 如果要禁用端口访问、请取消选中这两个复选框。



 a| 
MTU 大小（可通过单击 * 显示更多端口设置 * 来获取。）
 a| 
如有必要，请为最大传输单元（ Maximum Transmission Unit ， MTU ）输入一个新大小（以字节为单位）。

默认最大传输单元（ Maximum Transmission Unit ， MTU ）大小为每帧 1500 字节。您必须输入一个介于 1500 和 9000 之间的值。

|===
====
+
如果选择了 * 启用 IPv* ，则在单击 * 下一步 * 后，将打开一个对话框，用于选择 IPv4 设置。如果选择了 * 启用 IPv6* ，则在单击 * 下一步 * 后，将打开一个对话框，用于选择 IPv6 设置。如果同时选择了这两个选项，则 IPv4 设置对话框将首先打开，然后单击 * 下一步 * ， IPv6 设置对话框将打开。

. 自动或手动配置 IPv4 和 / 或 IPv6 设置。
+
.字段详细信息
[%collapsible]
====
[cols="1a,1a"]
|===
| 端口设置 | Description 


 a| 
自动获取配置
 a| 
选择此选项可自动获取配置。



 a| 
手动指定静态配置
 a| 
选择此选项，然后在字段中输入静态地址。(如果需要、可以剪切地址并将其粘贴到字段中。) 对于IPv4、请包括网络子网掩码和网关。对于 IPv6 ，请包括可路由的 IP 地址和路由器 IP 地址。如果要为EF600存储阵列配置支持200 GB的HIC、则此对话框会显示两组网络参数字段、一组用于物理端口(外部)、一组用于虚拟端口(内部)。您应为这两个端口分配唯一的参数。通过这些设置、主机可以在每个端口之间建立一条路径、并使HIC实现最高性能。如果不为虚拟端口分配IP地址、HIC将以大约一半的速度运行。

|===
====
. 单击 * 完成 * 。

