---
permalink: sm-settings/create-internal-security-key.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, internal, security, key, 
summary: 要使用驱动器安全功能、您可以创建一个内部安全密钥、该密钥由存储阵列中的控制器和支持安全功能的驱动器共享。内部密钥会保留在控制器的永久性内存上。 
---
= 创建内部安全密钥
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要使用驱动器安全功能、您可以创建一个内部安全密钥、该密钥由存储阵列中的控制器和支持安全功能的驱动器共享。内部密钥会保留在控制器的永久性内存上。

.开始之前
* 存储阵列中必须安装支持安全功能的驱动器。这些驱动器可以是全磁盘加密(Full Disk Encryption、FDE)驱动器或联邦信息处理标准(Federal Information Processing Standard、FIPS)驱动器。
* 必须启用驱动器安全功能。否则、将在此任务期间打开无法创建安全密钥对话框。如有必要、请联系您的存储供应商、了解有关启用驱动器安全功能的说明。


[NOTE]
====
如果存储阵列中同时安装了FDE和FIPS驱动器、则它们将共享同一个安全密钥。

====
.关于此任务
在此任务中、您可以定义要与内部安全密钥关联的标识符和密码短语。

[NOTE]
====
驱动器安全密码短语与存储阵列的管理员密码无关。

====
.步骤
. 选择菜单：设置[系统]。
. 在*安全密钥管理*下、选择*创建内部密钥*。
+
如果尚未生成安全密钥、则会打开创建安全密钥对话框。

. 在以下字段中输入信息：
+
** *定义安全密钥标识符*-您可以接受默认值(存储阵列名称和时间戳、此名称和时间戳由控制器固件生成)、也可以输入您自己的值。最多可以输入189个字母数字字符、不带空格、标点符号或符号。
+
[NOTE]
====
系统会自动生成附加到您输入的字符串两端的其他字符。生成的字符可确保标识符是唯一的。

====
** *定义密码短语/重新输入密码短语*-输入并确认密码短语。此值可以包含8到32个字符、并且必须包括以下每个字符：
+
*** 大写字母(一个或多个)。请注意、密码短语区分大小写。
*** 一个数字(一个或多个)。
*** 非字母数字字符、例如！、*、@(一个或多个)。




+
[CAUTION]
====
*请务必记录您的条目以供日后使用*。如果您需要从存储阵列移动启用了安全保护的驱动器、则必须知道用于解锁驱动器数据的标识符和密码短语。

====
. 单击 * 创建 * 。
+
安全密钥存储在控制器上的不可访问位置。除了实际密钥之外、还会从浏览器下载一个加密密钥文件。

+
[NOTE]
====
下载文件的路径可能取决于浏览器的默认下载位置。

====
. 记下您的密钥标识符、密码短语以及下载的密钥文件的位置、然后单击*关闭*。


.结果
现在、您可以创建启用了安全保护的卷组或池、也可以在现有卷组和池上启用安全性。

[NOTE]
====
每当关闭驱动器电源然后再次打开时、所有启用了安全保护的驱动器都会更改为安全锁定状态。在这种状态下、只有在驱动器初始化期间控制器应用正确的安全密钥后、才能访问数据。如果有人以物理方式删除已锁定的驱动器并将其安装到其他系统中、则安全锁定状态将阻止对其数据进行未经授权的访问。

====
.完成后
您应验证此安全密钥、以确保此密钥文件未损坏。
