---
permalink: sm-settings/drive-security-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, drive, security, terms, 
summary: 了解驱动器安全术语如何应用于存储阵列。 
---
= 驱动器安全术语
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解驱动器安全术语如何应用于存储阵列。

[cols="25h,~"]
|===
| 期限 | Description 


 a| 
驱动器安全功能
 a| 
驱动器安全性是一种存储阵列功能，可通过全磁盘加密（ Full Disk Encryption ， FDE ）驱动器或联邦信息处理标准（ Federal Information Processing Standard ， FIPS ）驱动器提供额外的安全层。如果将这些驱动器与驱动器安全功能结合使用，则需要使用安全密钥才能访问其数据。从阵列中物理删除驱动器后、这些驱动器将无法运行、直到将其安装到另一个阵列中为止、此时、这些驱动器将处于安全锁定状态、直到提供了正确的安全密钥为止。



 a| 
FDE驱动器
 a| 
全磁盘加密(Full Disk Encryption、FDE)驱动器在硬件级别对磁盘驱动器执行加密。硬盘驱动器包含一个ASIC芯片、用于在写入期间对数据进行加密、然后在读取期间对数据进行解密。



 a| 
FIPS驱动器
 a| 
FIPS驱动器使用联邦信息处理标准(FIPS) 140-2级别2。它们本质上是FDE驱动器、符合美国政府标准、可确保强大的加密算法和方法。FIPS驱动器的安全标准高于FDE驱动器。



 a| 
管理客户端
 a| 
一种本地系统(计算机、平板电脑等)、其中包括用于访问System Manager的浏览器。



 a| 
密码短语
 a| 
密码短语用于对安全密钥进行加密、以用于备份。在因驱动器迁移或机头交换而导入备份的安全密钥时、必须提供用于加密安全密钥的相同密码短语。密码短语可以包含8到32个字符。

[NOTE]
====
驱动器安全密码短语与存储阵列的管理员密码无关。

====


 a| 
支持安全的驱动器
 a| 
支持安全的驱动器可以是全磁盘加密(Full Disk Encryption、FDE)驱动器、也可以是联邦信息处理标准(Federal Information Processing Standard、FIPS)驱动器、这些驱动器可在写入期间对数据进行加密、并在读取期间对数据进行解密。这些驱动器被视为安全驱动器-_capable"、因为可以使用驱动器安全功能提高安全性。如果为这些驱动器使用的卷组和池启用了驱动器安全功能、则这些驱动器将变为secure—_enabled_.



 a| 
已启用安全保护的驱动器
 a| 
启用了安全保护的驱动器与驱动器安全功能结合使用。启用驱动器安全功能后、如果将驱动器安全应用于安全-_capable"驱动器上的池或卷组、则这些驱动器将变为安全_-enabled__。只能通过配置了正确安全密钥的控制器进行读写访问。这种增强的安全性可防止未经授权访问从存储阵列中物理删除的驱动器上的数据。



 a| 
安全密钥
 a| 
安全密钥是指在存储阵列中启用了安全保护的驱动器和控制器之间共享的字符串。无论何时关闭和打开驱动器的电源、启用了安全保护的驱动器都会变为安全锁定状态、直到控制器应用安全密钥为止。如果从存储阵列中删除启用了安全保护的驱动器、则该驱动器的数据将被锁定。在将驱动器重新安装到其他存储阵列中时、它会先查找安全密钥、然后再重新访问数据。要解锁数据、必须应用原始安全密钥。您可以使用以下方法之一创建和管理安全密钥：

* 内部密钥管理—在控制器的永久性内存上创建和维护安全密钥。
* 外部密钥管理—在外部密钥管理服务器上创建和维护安全密钥。




 a| 
安全密钥标识符
 a| 
安全密钥标识符是在创建密钥期间与安全密钥关联的字符串。标识符存储在控制器以及与安全密钥关联的所有驱动器上。

|===