---
permalink: sm-settings/enable-iscsi-discovery-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, iscsi, discovery, settings, 
summary: 您可以启用与在iSCSI网络中发现存储设备相关的设置。 
---
= 启用iSCSI发现设置
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以启用与在iSCSI网络中发现存储设备相关的设置。

通过目标发现设置、您可以使用Internet存储名称服务(iSNS)协议注册存储阵列的iSCSI信息、还可以确定是否允许未命名的发现会话。

如果iSNS服务器使用静态IP地址、则该地址必须可用于iSNS注册。支持IPv4和IPv6。

您可以启用与iSCSI发现相关的以下设置：

* *启用iSNS服务器以注册目标*-启用后、存储阵列将从iSNS服务器注册其iSCSI限定名称(IQN)和端口信息。此设置允许iSNS发现、以便启动程序可以从iSNS服务器检索IQN和端口信息。
* *启用未命名的发现会话*-启用未命名的发现会话后、启动程序(iSCSI主机)无需在发现类型连接的登录顺序期间提供目标(控制器)的IQN。禁用后、主机需要提供IQN、以便与控制器建立发现会话。但是、正常(I/O轴承)会话始终需要目标IQN。禁用此设置可以防止未经授权的iSCSI主机仅使用其IP地址连接到控制器。


[NOTE]
====
只有当存储阵列支持iSCSI时、iSCSI设置和功能才会显示在设置页面上。

====
.步骤
. 选择菜单：设置[系统]。
. 在* iSCSI设置*下、单击*查看/编辑目标发现设置*。
+
此时将显示目标发现设置对话框。在*启用iSNS服务器*...字段下方、此对话框指示控制器是否已注册。

. 要注册控制器、请选择*启用iSNS服务器以注册我的目标*、然后选择以下选项之一：
+
** *自动从DHCP服务器获取配置*-如果要使用动态主机配置协议(DHCP)服务器配置iSNS服务器、请选择此选项。请注意、如果使用此选项、则必须将控制器上的所有iSCSI端口配置为也使用DHCP。如有必要、请更新控制器iSCSI端口设置以启用此选项。
+
[NOTE]
====
要使DHCP服务器提供iSNS服务器地址、必须将DHCP服务器配置为使用选项43 -"`Vendor Specific Information"。` 此选项需要包含iSNS服务器IPv4地址、以数据字节0xA-0xd (10-13)为单位。

====
** *手动指定静态配置*-如果要输入iSNS服务器的静态IP地址、请选择此选项。(如果需要、可以剪切地址并将其粘贴到字段中。) 在字段中、输入IPv4地址或IPv6地址。如果同时配置了这两者、则IPv4为默认值。此外、输入TCP侦听端口(使用默认值3205或输入介于49152和65535之间的值)。


. 要允许存储阵列参与未命名的发现会话、请选择*启用未命名的发现会话*。
+
** 启用后、无需iSCSI启动程序指定目标IQN即可检索控制器的信息。
** 禁用后、除非启动程序提供目标IQN、否则会阻止发现会话。禁用未命名的发现会话可提高安全性。


. 单击 * 保存 * 。


当System Manager尝试向iSNS服务器注册控制器时、会显示一个进度条。此过程可能需要长达五分钟的时间。
