---
permalink: sm-settings/faq-nvme-protocol.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= SANtricity System Manager 的 NVMe 协议常见问题解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== 如何解读基于网络结构的NVMe统计信息？

查看基于网络结构的NVMe统计信息对话框显示NVMe子系统和RDMA接口的统计信息。所有统计信息均为只读、无法设置。

* * NVMe子系统统计信息*-显示NVMe控制器及其队列的统计信息。NVMe控制器可在主机与存储阵列中的命名空间之间提供访问路径。您可以查看连接故障、重置和关闭等项的NVMe子系统统计信息。有关这些统计信息的详细信息、请单击*查看表标题的图例*。
* * RDMA接口统计信息*-提供RDMA接口上所有基于网络结构的NVMe端口的统计信息、其中包括与每个交换机端口关联的性能统计信息和链路错误信息。只有当基于网络结构的NVMe端口可用时、才会显示此选项卡。有关统计信息的详细信息、请单击*查看表标题的图例*。


您可以将其中每个统计信息作为原始统计信息或基线统计信息进行查看。原始统计信息是自控制器启动以来收集的所有统计信息。基线统计信息是自设置基线时间以来收集的时间点统计信息。



== 要配置或诊断基于InfiniBand的NVMe、还需要执行哪些操作？

下表列出了可用于配置和管理基于InfiniBand的NVMe会话的SANtricity系统管理器功能。

[NOTE]
====
只有当存储阵列的控制器包含基于InfiniBand的NVMe端口时、基于InfiniBand的NVMe设置才可用。

====
[cols="35h,~"]
|===
| Action | 位置 


 a| 
配置基于InfiniBand的NVMe端口
 a| 
. 选择 * 硬件 * 。
. 选择*控制器和组件*选项卡。
. 选择一个控制器。
. 选择 * 配置基于 InfiniBand 端口的 NVMe * 。


或

. 选择菜单：设置[系统]。
. 向下滚动到*基于InfiniBand的NVMe设置*、然后选择*配置基于InfiniBand端口的NVMe *。




 a| 
查看基于InfiniBand的NVMe统计信息
 a| 
. 选择菜单：设置[系统]。
. 向下滚动到*基于InfiniBand的NVMe设置*、然后选择*查看基于网络结构的NVMe统计信息*。


|===


== 要通过RoCE配置或诊断NVMe、还需要执行哪些操作？

您可以从硬件和设置页面配置和管理基于RoCE的NVMe。

[NOTE]
====
只有当存储阵列的控制器包含基于RoCE的NVMe端口时、基于RoCE的NVMe设置才可用。

====
[cols="35h,~"]
|===
| Action | 位置 


 a| 
配置基于RoCE的NVMe端口
 a| 
. 选择 * 硬件 * 。
. 选择*控制器和组件*选项卡。
. 选择一个控制器。
. 选择 * 配置基于 RoCE 的 NVMe 端口 * 。


或

. 选择菜单：设置[系统]。
. 向下滚动到*基于RoCE的NVMe设置*、然后选择*配置基于RoCE的NVMe端口*。




 a| 
查看基于网络结构的NVMe统计信息
 a| 
. 选择菜单：设置[系统]。
. 向下滚动到*基于RoCE的NVMe设置*、然后选择*查看基于网络结构的NVMe统计信息*。


|===


== 为什么一个物理端口有两个IP地址？

EF600存储阵列可以包含两个HIC—一个外部HIC和一个内部HIC。

在此配置中、外部HIC连接到内部辅助HIC。您可以从外部HIC访问的每个物理端口都具有来自内部HIC的关联虚拟端口。

要获得最大200 GB性能、必须为物理端口和虚拟端口分配唯一的IP地址、以便主机可以与每个端口建立连接。如果不为虚拟端口分配IP地址、HIC将以大约一半的速度运行。



== 为什么一个物理端口有两组参数？

EF600存储阵列可以包含两个HIC—一个外部HIC和一个内部HIC。

在此配置中、外部HIC连接到内部辅助HIC。您可以从外部HIC访问的每个物理端口都具有来自内部HIC的关联虚拟端口。

要获得最大200 GB的性能、您必须为物理端口和虚拟端口分配参数、以便主机可以与每个端口建立连接。如果不为虚拟端口分配参数、HIC将以大约一半的可用速度运行。
