---
permalink: sm-settings/save-storage-array-configuration.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, save, storage array, configuration, 
summary: 您可以将存储阵列的配置信息保存在脚本文件中、以节省设置具有相同配置的其他存储阵列所需的时间。 
---
= 保存存储阵列配置
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将存储阵列的配置信息保存在脚本文件中、以节省设置具有相同配置的其他存储阵列所需的时间。

.开始之前
存储阵列不得执行任何更改其逻辑配置设置的操作。这些操作的示例包括创建或删除卷、下载控制器固件、分配或修改热备用驱动器或向卷组添加容量(驱动器)。

.关于此任务
保存存储阵列配置会生成一个命令行界面(CLI)脚本、其中包含存储阵列设置、卷配置、主机配置或存储阵列的主机到卷分配。您可以使用此生成的命令行界面脚本将配置复制到具有完全相同硬件配置的另一个存储阵列。

但是、您不应使用此生成的命令行界面脚本进行灾难恢复。要执行系统还原、请使用手动创建的配置数据库备份文件、或者联系技术支持以从最新的AutoSupport数据中获取此数据。

此操作不会_保存以下设置：

* 电池的使用寿命
* 控制器的时间
* 非易失性静态随机存取存储器(NVSRAM)设置
* 任何高级功能
* 存储阵列密码
* 硬件组件的运行状态和状态
* 卷组的运行状态(最佳除外)和状态
* 复制服务、例如镜像和卷复制


[CAUTION]
====
*应用程序错误的风险*—如果存储阵列正在执行将更改任何逻辑配置设置的操作、请勿使用此选项。这些操作的示例包括创建或删除卷、下载控制器固件、分配或修改热备用驱动器或向卷组添加容量(驱动器)。

====
.步骤
. 选择菜单：设置[系统]。
. 选择*保存存储阵列配置*。
. 选择要保存的配置项：
+
** 存储阵列设置
** 卷配置
** 主机配置
** 主机到卷分配


+
[NOTE]
====
如果选择*主机到卷分配*项、则默认情况下也会选择*卷配置*项和*主机配置*项。如果不同时保存"卷配置"和"主机配置"、则无法保存"主机到卷分配"。

====
. 单击 * 保存 * 。
+
此文件将保存在浏览器的"Downloads"文件夹中、名为`storage-array-configuration.cfg`。



.完成后
要将已保存的存储阵列配置加载到另一个存储阵列、请使用带有`-f`选项的SANtricity 命令行界面(SMcli)应用`.cfg`文件。

[NOTE]
====
此外、您还可以使用Unified Manager界面将存储阵列配置加载到其他存储阵列(选择菜单：管理[导入设置])。

====