---
permalink: sm-settings/view-iscsi-sessions-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, iscsi, sessions, 
summary: 您可以查看有关与存储阵列的iSCSI连接的详细信息。iSCSI会话可以与异步镜像关系中的主机或远程存储阵列进行。 
---
= 在 SANtricity System Manager 中查看 iSCSI 会话
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以查看有关与存储阵列的iSCSI连接的详细信息。iSCSI会话可以与异步镜像关系中的主机或远程存储阵列进行。

.步骤
. 选择菜单：设置[系统]。
. 选择*查看/结束iSCSI会话*。
+
此时将显示当前iSCSI会话的列表。

. *可选：*要查看有关特定iSCSI会话的追加信息 、请选择一个会话、然后单击*查看详细信息*。
+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 项目 | Description 


 a| 
会话标识符(SSID)
 a| 
一个十六进制字符串、用于标识iSCSI启动程序与iSCSI目标之间的会话。SSID由ISID和TPGT组成。



 a| 
启动程序会话ID (ISID)
 a| 
会话标识符的启动程序部分。启动程序将在登录期间指定ISID。



 a| 
目标门户组
 a| 
iSCSI目标。



 a| 
目标门户组标记(TPGT)
 a| 
会话标识符的目标部分。iSCSI目标门户组的16位数字标识符。



 a| 
启动程序iSCSI名称
 a| 
启动程序的全球唯一名称。



 a| 
启动程序iSCSI标签
 a| 
System Manager中设置的用户标签。



 a| 
启动程序iSCSI别名
 a| 
也可以与iSCSI节点关联的名称。此别名允许组织将用户友好型字符串与iSCSI名称相关联。但是、别名不能替代iSCSI名称。启动程序iSCSI别名只能在主机上设置、而不能在System Manager中设置



 a| 
主机
 a| 
向存储阵列发送输入和输出的服务器。



 a| 
连接ID (CID)
 a| 
启动程序与目标之间会话中连接的唯一名称。启动程序将生成此ID、并在登录请求期间将其呈现给目标。在注销以关闭连接期间、也会显示连接ID。



 a| 
端口标识符
 a| 
与连接关联的控制器端口。



 a| 
启动程序IP地址
 a| 
启动程序的IP地址。



 a| 
协商登录参数
 a| 
在iSCSI会话登录期间处理的参数。



 a| 
身份验证方法
 a| 
对要访问iSCSI网络的用户进行身份验证的技术。有效值为* CHAP *和*无*。



 a| 
标题摘要方法
 a| 
显示iSCSI会话可能的标头值的技术。HeaderDigest和DataDigest可以是*无*或* CRC32C*。两者的默认值均为*无*。



 a| 
数据摘要方法
 a| 
用于显示iSCSI会话的可能数据值的技术。HeaderDigest和DataDigest可以是*无*或* CRC32C*。两者的默认值均为*无*。



 a| 
最大连接数
 a| 
iSCSI会话允许的最大连接数。最大连接数可以是1到4。默认值为*。



 a| 
目标别名
 a| 
与目标关联的标签。



 a| 
启动程序别名
 a| 
与启动程序关联的标签。



 a| 
目标IP地址
 a| 
iSCSI会话的目标的IP地址。不支持DNS名称。



 a| 
初始R2T
 a| 
初始传输就绪状态。状态可以是*是*或*否*。



 a| 
最大突发长度
 a| 
此iSCSI会话的最大SCSI有效负载(以字节为单位)。最大突发长度可以介于512到262、144 (256 KB)之间。默认值为* 262、144 (256 KB)*。



 a| 
第一个突发长度
 a| 
此iSCSI会话中未经请求的数据的SCSI有效负载(以字节为单位)。第一个突发长度可以介于512到131、072 (128 KB)之间。默认值为*、65、536 (64 KB)*。



 a| 
默认等待时间
 a| 
在连接终止或连接重置后尝试建立连接之前等待的最小秒数。默认等待时间值可以介于0到3600之间。默认值为*。2



 a| 
要保留的默认时间
 a| 
连接终止或连接重置后仍可进行连接的最大秒数。默认保留时间可以为0到3600。默认值为*20*。



 a| 
最大未完成R2T
 a| 
此iSCSI会话未完成的最大"可传输"数。最大未完成的可传输值可以介于1到16之间。默认值为* 1 *。



 a| 
错误恢复级别
 a| 
此iSCSI会话的错误恢复级别。错误恢复级别值始终设置为*。



 a| 
最大接收数据段长度
 a| 
启动程序或目标可以在任何iSCSI有效负载数据单元(PDU)中接收的最大数据量。



 a| 
目标名称
 a| 
目标的官方名称(而不是别名)。格式为_iqn_的目标名称。



 a| 
启动程序名称
 a| 
启动程序的官方名称(而不是别名)。使用_iqn_或_eui_格式的启动程序名称。

|===
====
. *可选：*要将报告保存到文件中、请单击*保存*。
+
此文件将保存在浏览器的"Downloads"文件夹中、文件名为`iscsi-session-connections.txt`。


