---
permalink: sm-settings/what-is-cache-flushing.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, cache, flushing, 
summary: 当缓存中未写入的数据量达到某个级别时、控制器会定期将缓存的数据写入驱动器。此写入过程称为刷新。 
---
= 什么是缓存刷新？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当缓存中未写入的数据量达到某个级别时、控制器会定期将缓存的数据写入驱动器。此写入过程称为"刷新"。

控制器使用两种算法来刷新缓存：基于需求和基于年龄。控制器使用基于需求的算法、直到缓存的数据量降至缓存刷新阈值以下。默认情况下、当80%的缓存正在使用时、将开始刷新。

在System Manager中、您可以设置"开始`S请求缓存刷新`"阈值、以便最适合您环境中使用的I/O类型。在以写入操作为主的环境中、您应将"开始需求缓存刷新`S`"百分比设置为高、以增加缓存处理任何新写入请求而无需转到磁盘的可能性。高百分比设置会限制缓存刷新的数量、以使更多数据保留在缓存中、从而增加缓存命中的几率。

在I/O不稳定(发生数据突发)的环境中、您可以使用低缓存刷新、以便系统在数据突发之间频繁地刷新缓存。在处理各种负载的多样化I/O环境中、或者在负载类型未知时、将阈值设置为50%、以作为一个良好的中间地带。请注意、如果您选择的起始百分比低于80%、则性能可能会降低、因为主机读取所需的数据可能不可用。选择较低的百分比还会增加保持缓存级别所需的磁盘写入次数、从而增加系统开销。

基于期限的算法指定写入数据在符合向磁盘转储的条件之前可以保留在缓存中的时间段。在达到缓存刷新阈值之前、控制器会使用基于期限的算法。默认值为10秒、但此时间段仅在非活动期间计算在内。您不能在System Manager中修改刷新计时、而是必须在命令行界面(CLI)中使用*设置存储阵列*命令。

[CAUTION]
====
*可能丢失数据*-如果启用*不使用电池的写入缓存*选项并且没有通用电源进行保护、则可能会丢失数据。此外、如果您没有控制器电池、并且启用了*无电池写入缓存*选项、则可能会丢失数据。

====