---
permalink: sm-support/activate-controller-software-and-firmware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, activate, controller, software, firmware 
summary: 您可以选择立即激活升级文件、也可以等到更方便的时间再激活。 
---
= 激活控制器软件和固件
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以选择立即激活升级文件、也可以等到更方便的时间再激活。

.关于此任务
您可以下载和传输这些文件、而无需激活它们。您可以选择稍后激活，原因如下：

* *当前时间*—激活软件和固件可能需要很长时间、因此您可能需要等待I/O负载减轻。控制器会在激活期间进行故障转移，因此在升级完成之前性能可能会比平常低。
* * 软件包类型 * —您可能需要先在一个存储阵列上测试新软件和固件，然后再升级其他存储阵列上的文件。


如果您的软件或固件已传输但未激活、则System Manager主页页面的通知区域以及升级中心页面将显示一条通知。

[CAUTION]
====
激活过程启动后，您无法停止它。

====
.步骤
. 选择菜单：Support[升级中心]。
. 在标记为SANtricity 操作系统控制器软件升级的区域中、单击*激活*、然后确认您要执行此操作。
+
您可以在升级前运行状况检查期间取消此操作、但不能在激活期间取消。

+
升级前运行状况检查将开始。如果升级前运行状况检查通过、则升级过程将继续激活文件。如果升级前运行状况检查失败，请使用 Recovery Guru 或联系技术支持以解决此问题。对于某些类型的情况、技术支持可能会建议您通过选中*允许升级*复选框来继续升级、尽管存在错误。

+
成功完成升级前运行状况检查后，将激活。激活所需的时间取决于您的存储阵列配置以及要激活的组件。

. *可选：*要查看已升级内容的列表、请单击*保存日志*。
+
此文件将保存在浏览器的 "Downloads" 文件夹中，名为 `drive_upgrade_log-timestamp.txt` 。



.完成后
* 验证所有组件是否均显示在硬件页面上。
* 选中软件和固件清单对话框以验证新的软件和固件版本（转到菜单：支持 [ 升级中心 ] ，然后单击 * 软件和固件清单 * 链接）。
* 如果您升级了控制器 NVSRAM ，则在激活过程中，应用于现有 NVSRAM 的任何自定义设置都将丢失。激活过程完成后，您需要再次将自定义设置应用于 NVSRAM 。

