---
permalink: sm-support/enable-or-disable-autosupport-features.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, disable, autosupport, 
summary: 您可以在初始设置期间启用AutoSupport 功能和各个AutoSupport 功能、也可以稍后启用或禁用它们。 
---
= 启用或禁用AutoSupport 功能
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在初始设置期间启用AutoSupport 功能和各个AutoSupport 功能、也可以稍后启用或禁用它们。

.开始之前
如果要启用AutoSupport OnDemand或远程诊断、则AutoSupport 交付方法必须设置为HTTPS。

.关于此任务
您可以随时禁用AutoSupport 功能、但强烈建议您保持启用状态。如果存储阵列出现问题、启用AutoSupport 功能可以显著加快确定和解决问题的速度。

AutoSupport 功能由三个单独启用的功能组成。

* *基本AutoSupport *—允许存储阵列自动收集数据并将其发送给技术支持。
* * AutoSupport OnDemand *—允许技术支持在对问题描述 进行故障排除时根据需要请求重新传输先前的AutoSupport 派单。所有传输均从存储阵列启动、而不是从AutoSupport 服务器启动。存储阵列会定期与AutoSupport 服务器进行检查、以确定是否存在任何待处理的重新传输请求并做出相应的响应。
* *远程诊断*—允许技术支持在对问题描述 进行故障排除时根据需要请求新的最新AutoSupport 派单。所有传输均从存储阵列启动、而不是从AutoSupport 服务器启动。存储阵列会定期与AutoSupport 服务器进行检查、以确定是否存在任何待处理的新请求并做出相应的响应。


.步骤
. 选择菜单：Support[支持中心> AutoSupport ]选项卡。
. 选择*启用/禁用AutoSupport 功能*。
. 选中要启用的AutoSupport 功能旁边的复选框。
+
这些功能彼此相关、如对话框中各项的缩进所示。例如、您必须先启用AutoSupport OnDemand、然后才能启用远程诊断。

. 单击 * 保存 * 。
+
如果禁用AutoSupport 、则主页页面上将显示一条通知。您可以通过单击*忽略*来取消通知。


