---
permalink: sm-support/faq-autosupport.html 
sidebar: sidebar 
keywords:  
summary: 如果您只是想快速了解问题解答，此常见问题解答会很有帮助。 
---
= SANtricity System Manager 的 AutoSupport 常见问题解答
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== 我正在收集哪些数据？

通过AutoSupport 功能和手动支持数据收集功能、可以在客户支持包中收集数据、以便由技术支持进行远程故障排除和问题分析。

客户支持包会将有关存储阵列的所有类型的信息收集到一个压缩文件中。收集的信息包括物理配置、逻辑配置、版本信息、事件、日志文件、 和性能数据。只有技术支持才会使用此信息来解决存储阵列的问题。



== 无法读取的扇区数据显示了什么？

您可以显示有关在存储阵列中的驱动器上检测到的不可读扇区的详细数据。

不可读扇区日志首先显示最新的不可读扇区。此日志包含有关包含不可读扇区的卷的以下信息。这些字段可排序。

[cols="25h,~"]
|===
| 字段 | Description 


 a| 
受影响的卷
 a| 
显示卷的标签。如果缺少的卷包含无法读取的扇区、则会为缺少的卷显示全球通用标识符。



 a| 
逻辑单元号(LUN)
 a| 
显示卷的LUN。如果卷没有LUN、则对话框将显示不适用。



 a| 
已分配给
 a| 
显示有权访问卷的主机或主机集群。如果主机、主机集群甚至默认集群无法访问此卷、则此对话框将显示不适用。

|===
要查看有关无法读取的扇区的追加信息 、请单击卷旁边的加号(+)。

[cols="25h,~"]
|===
| 字段 | Description 


 a| 
日期/时间
 a| 
显示检测到不可读扇区的日期和时间。



 a| 
卷逻辑块地址
 a| 
显示了卷的逻辑块地址(LBA)。



 a| 
驱动器位置
 a| 
显示了驱动器架、抽盒(如果驱动器架具有抽盒)和托架位置。



 a| 
驱动器逻辑块地址
 a| 
显示了驱动器的LBA。



 a| 
故障类型
 a| 
显示了以下故障类型之一：

* *物理*—物理介质错误。
* *逻辑*—条带中其他位置出现读取错误、导致数据不可读。例如、由于卷中其他位置出现介质错误而导致的扇区不可读。
* *不一致*—冗余数据不一致。
* *数据保证*-数据保证错误。


|===


== 什么是运行状况映像？

运行状况映像是指控制器处理器内存的原始数据转储、技术支持可使用该数据转储来诊断控制器的问题。

固件在检测到某些错误时会自动生成运行状况映像。在某些故障排除情形下、技术支持可能会要求您检索运行状况映像文件并将其发送给它们。



== AutoSupport 功能的作用是什么？

AutoSupport 功能由三个单独启用的功能组成。

* *基本AutoSupport *—允许存储阵列自动收集数据并将其发送给技术支持。
* * AutoSupport OnDemand *—允许技术支持在对问题描述 进行故障排除时根据需要请求重新传输先前的AutoSupport 派单。所有传输均从存储阵列启动、而不是从AutoSupport 服务器启动。存储阵列会定期与AutoSupport 服务器进行检查、以确定是否存在任何待处理的重新传输请求并做出相应的响应。
* *远程诊断*—允许技术支持在对问题描述 进行故障排除时根据需要请求新的最新AutoSupport 派单。所有传输均从存储阵列启动、而不是从AutoSupport 服务器启动。存储阵列会定期与AutoSupport 服务器进行检查、以确定是否存在任何待处理的新请求并做出相应的响应。




== 通过AutoSupport 功能收集哪种类型的数据？

AutoSupport 功能包含三种标准派单类型：事件派单、计划派单以及按需和远程诊断派单。

AutoSupport 数据不包含任何用户数据。

* *事件派单*
+
如果系统上发生需要主动通知技术支持的事件、则AutoSupport 功能会自动发送事件触发的派单。

+
** 受管存储阵列上发生支持事件时发送。
** 包括有关事件发生时存储阵列所发生情况的全面快照。


* *计划内派单*
+
AutoSupport 功能会定期自动发送多个派单。

+
** *每日派单*—在用户可配置的时间间隔内每天发送一次。包括当前系统事件日志和性能数据。
** *每周派单*—在用户可配置的时间间隔和日期内每周发送一次。包括配置和系统状态信息。


* * AutoSupport OnDemand和远程诊断派单*
+
** * AutoSupport OnDemand *—允许技术支持在对问题描述 进行故障排除时根据需要请求重新传输先前的AutoSupport 派单。所有传输均从存储阵列启动、而不是从AutoSupport 服务器启动。存储阵列会定期与AutoSupport 服务器进行检查、以确定是否存在任何待处理的重新传输请求并做出相应的响应。
** *远程诊断*—允许技术支持在对问题描述 进行故障排除时根据需要请求新的最新AutoSupport 派单。所有传输均从存储阵列启动、而不是从AutoSupport 服务器启动。存储阵列会定期与AutoSupport 服务器进行检查、以确定是否存在任何待处理的新请求并做出相应的响应。






== 如何配置AutoSupport 功能的交付方法？

AutoSupport功能支持使用HTTPS和SMTP协议将AutoSupport派单发送给技术支持。

.开始之前
* 必须启用AutoSupport 功能。您可以在AutoSupport 页面上查看它是否已启用。
* 必须在网络中安装和配置DNS服务器。必须在System Manager中配置DNS服务器地址(此任务可从硬件页面访问)。


.关于此任务
查看不同的协议：

* * HTTPS *-允许您使用HTTPS直接连接到目标技术支持服务器。如果要启用AutoSupport OnDemand或远程诊断、则AutoSupport 交付方法必须设置为HTTPS。
* *电子邮件*-用于使用电子邮件服务器作为发送AutoSupport 派单的传送方法。


[NOTE]
====
* HTTPS和电子邮件方法之间的差异*。使用SMTP的电子邮件传送方法与HTTPS传送方法有一些重要区别。首先、电子邮件方法的派单大小限制为5 MB、这意味着不会派送某些ASUP数据收集。其次、AutoSupport OnDemand功能仅适用于HTTPS交付方法。

====
.步骤
. 选择菜单：Support[支持中心> AutoSupport ]选项卡。
. 选择 * 配置 AutoSupport 交付方法 * 。
+
此时将显示一个对话框、其中列出了派单交付方法。

. 选择所需的交付方法、然后选择该交付方法的参数。执行以下操作之一：
+
** 如果选择HTTPS、请选择以下交付参数之一：
+
*** *直接*—此传送参数为默认选择。通过选择此选项、您可以使用HTTPS协议直接连接到目标技术支持系统。
*** *通过代理服务器*-选择此选项可以指定与目标技术支持系统建立连接所需的HTTP代理服务器详细信息。您必须指定主机地址和端口号。但是、如果需要、您只需要输入主机身份验证详细信息(用户名和密码)。
*** *通过代理自动配置脚本(PAC)*—指定代理自动配置(PAC)脚本文件的位置。通过PAC文件、系统可以自动选择适当的代理服务器、以便与目标技术支持系统建立连接。


** 如果选择了电子邮件、请输入以下信息：
+
*** 作为完全限定域名、IPv4地址或IPv6地址的邮件服务器地址。
*** AutoSupport 派遣电子邮件的发件人字段中显示的电子邮件地址。
*** *可选；如果要执行配置测试。* AutoSupport 系统收到测试派单时发送确认的电子邮件地址。
*** 如果要对消息进行加密、请选择* SMTPS *或* STARTTLS *作为加密类型、然后选择加密消息的端口号。否则、请选择*无*。
*** 如果需要、请输入用于向传出发件人和邮件服务器进行身份验证的用户名和密码。




. 单击*测试配置*、使用指定的传输参数测试与技术支持服务器的连接。如果启用了AutoSupport 按需功能、则系统还会测试AutoSupport 按需派单交付的连接。
+
如果配置测试失败、请检查您的配置设置并重新运行测试。如果测试仍失败、请联系技术支持。

. 单击 * 保存 * 。




== 什么是配置数据？

选择收集配置数据后、系统将保存RAID配置数据库的当前状态。

RAID配置数据库包含控制器上卷组和磁盘池的所有数据。`s配置数据功能可保存与用于保存storageArray dbmDatabase`的命令行界面命令相同的信息。



== 在升级SANtricity OS软件之前、我需要了解哪些信息？

在升级控制器的软件和固件之前、请注意以下事项。

* 您已阅读此文档和`reADME.txt`文件、并已确定要执行升级。
* 您知道是否要升级IOM固件。
+
通常，您应同时升级所有组件。但是、如果您不希望在SANtricity 操作系统控制器软件升级过程中升级IOM固件、或者技术支持已指示您降级IOM固件(您只能使用命令行界面降级固件)、则可能决定不升级IOM固件。

* 您知道是否要升级控制器NVSRAM文件。
+
通常，您应同时升级所有组件。但是，如果您的文件已修补或为自定义版本，并且您不想覆盖此文件，则您可能会决定不升级控制器 NVSRAM 文件。

* 您知道是要立即激活还是稍后激活。
+
稍后激活的原因可能包括：

+
** *当前时间*—激活软件和固件可能需要很长时间、因此您可能需要等待I/O负载减轻。控制器会在激活期间进行故障转移，因此在升级完成之前性能可能会比平常低。
** * 软件包类型 * —您可能需要先在一个存储阵列上测试新软件和固件，然后再升级其他存储阵列上的文件。




这些组件是SANtricity 操作系统控制器软件升级的一部分：

* *管理软件*—System Manager是用于管理存储阵列的软件。
* * 控制器固件 * —控制器固件用于管理主机和卷之间的 I/O 。
* * 控制器 NVSRA* - 控制器 NVSRAM 是一个控制器文件，用于指定控制器的默认设置。
* * IOM 固件 * — I/O 模块（ IOM ）固件用于管理控制器与驱动器架之间的连接。它还会监控组件的状态。
* * 监控软件 * —监控软件是运行该软件的控制器上的虚拟机。


在升级过程中、可能还需要升级主机的多路径/故障转移驱动程序和/或HBA驱动程序、以便主机可以正确地与控制器进行交互。

[NOTE]
====
要确定是否发生这种情况、请参见 https://mysupport.netapp.com/matrix["NetApp 互操作性表工具"^]。

====
如果存储阵列仅包含一个控制器或您未安装多路径驱动程序，请停止存储阵列的 I/O 活动，以防止出现应用程序错误。如果存储阵列有两个控制器，并且您安装了多路径驱动程序，则无需停止 I/O 活动。


CAUTION: 升级期间、请勿更改存储阵列。



== 暂停IOM自动同步前需要了解哪些信息？

暂停IOM自动同步可防止下次升级SANtricity OS控制器软件时升级IOM固件。

通常、控制器软件和IOM固件会作为捆绑包进行升级。如果要保留在机箱上的特殊IOM固件版本、则可以暂停IOM自动同步。否则、您将在下次升级控制器软件时还原到与控制器软件捆绑在一起的IOM固件。



== 为什么固件升级进度如此缓慢？

固件升级进度取决于系统的整体负载。

在驱动器固件的联机升级期间、如果在快速重建过程中发生卷传输、系统将对传输的卷启动完全重建。此操作可能需要相当长的时间。实际完整重建时间取决于多个因素、包括重建操作期间发生的I/O活动量、卷组中的驱动器数量、重建优先级设置以及驱动器性能。



== 升级驱动器固件前需要了解哪些信息？

在升级驱动器固件之前、请注意以下事项。

* 作为预防措施、请使用磁盘到磁盘备份、卷副本(到不受计划的固件升级影响的卷组)或远程镜像备份数据。
* 您可能只需要升级几个驱动器、即可测试新固件的行为、以确保其正常运行。如果新固件运行正常、请升级其余驱动器。
* 如果有任何故障驱动器、请在开始固件升级之前修复它们。
* 如果驱动器可以执行脱机升级、请停止与驱动器关联的所有卷的I/O活动。停止I/O活动后、不会执行与这些卷关联的配置操作。
* 升级驱动器固件时、请勿删除任何驱动器。
* 升级驱动器固件时、请勿对存储阵列进行任何配置更改。




== 如何选择要执行的升级类型？

您可以根据池或卷组的状态选择要对驱动器执行的升级类型。

* * 联机 *
+
如果池或卷组支持冗余并处于最佳状态、则可以使用联机方法升级驱动器固件。联机方法会在存储阵列处理使用这些驱动器的关联卷的I/O时下载firmware _o。您不必停止使用这些驱动器的关联卷的I/O。这些驱动器一次升级一个、并升级到与这些驱动器关联的卷。如果驱动器未分配给池或卷组、则可以使用联机或脱机方法更新其固件。使用联机方法升级驱动器固件时、系统性能可能会受到影响。

* * 脱机 *
+
如果池或卷组不支持冗余(RAID 0)或已降级、则必须使用脱机方法升级驱动器固件。脱机方法将在所有I/O活动均已停止时升级固件_only、并使用这些驱动器将其升级到关联卷。您必须停止使用这些驱动器的任何关联卷的所有I/O。如果驱动器未分配给池或卷组、则可以使用联机或脱机方法更新其固件。


