---
permalink: sm-support/review-the-possible-software-and-firmware-upgrade-errors.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, software, firmware, upgrade, errors 
summary: 在控制器软件升级或驱动器固件升级期间可能会发生错误。 
---
= 查看可能的软件和固件升级错误
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在控制器软件升级或驱动器固件升级期间可能会发生错误。

[cols="25h,~,~"]
|===
| 固件下载错误 | Description | 建议的操作 


 a| 
已分配的驱动器出现故障
 a| 
无法升级存储阵列中已分配的驱动器。
 a| 
出现此故障的一个原因可能是驱动器没有相应的签名。确保受影响的驱动器为授权驱动器。有关详细信息，请联系技术支持。

更换驱动器时，请确保更换驱动器的容量等于或大于要更换的故障驱动器。

您可以在存储阵列接收 I/O 时更换故障驱动器



 a| 
集成热备用驱动器
 a| 
如果此驱动器标记为热备用磁盘、并且正在用于卷组、则固件升级过程将失败。
 a| 
必须先更正此错误情况，然后才能升级固件。启动 System Manager 并使用 Recovery Guru 解决此问题。



 a| 
卷组不完整
 a| 
如果卷组中的任何驱动器被绕过、删除或无响应、则会将其视为不完整的卷组。不完整的卷组将阻止固件升级。
 a| 
如果一个或多个卷组或磁盘池不完整，则必须更正此错误情况，然后才能升级固件。启动 System Manager 并使用 Recovery Guru 解决此问题。



 a| 
当前在任何卷组上运行的独占操作（后台介质 / 奇偶校验扫描除外）
 a| 
如果正在对卷执行任何独占操作、则无法升级固件。
 a| 
如果正在执行一个或多个独占操作，则必须先完成这些操作，然后才能升级固件。使用 System Manager 监控操作进度。



 a| 
缺少卷
 a| 
如果缺少任何卷、则无法升级固件。
 a| 
您必须先更正缺少的卷情况，然后才能升级固件。启动 System Manager 并使用 Recovery Guru 解决此问题。



 a| 
任一控制器处于非最佳状态
 a| 
如果任一控制器处于非最佳状态、则无法升级固件。
 a| 
其中一个存储阵列控制器需要注意。必须先更正此情况，然后才能升级固件。启动 System Manager 并使用 Recovery Guru 解决此问题。



 a| 
SPM 验证数据库控制器检查失败
 a| 
无法升级固件、因为存储分区映射数据库已损坏。
 a| 
控制器上发生存储分区映射数据库错误。请联系技术支持以解决此问题描述。



 a| 
配置数据库验证(如果存储阵列的控制器版本支持)
 a| 
无法升级固件、因为配置数据库已损坏。
 a| 
控制器上发生配置数据库错误。请联系技术支持以解决此问题描述。



 a| 
与 Mel 相关的检查
 a| 
无法升级固件、因为事件日志包含错误。
 a| 
请联系技术支持以解决此问题描述。



 a| 
过去 7 天报告了 10 个以上的 DDN 信息性或严重 MEL 事件
 a| 
无法升级固件、因为过去七天报告的信息性或严重MEL事件超过10个。
 a| 
请联系技术支持以解决此问题描述。



 a| 
过去 7 天报告了超过 2 页 2C 的严重 MEL 事件
 a| 
无法升级固件、因为过去七天报告的关键MEL事件超过两页2 C。
 a| 
请联系技术支持以解决此问题描述。



 a| 
过去 7 天报告了 2 个以上的 " 降级驱动器通道 " 严重 MEL 事件
 a| 
无法升级固件、因为过去七天报告了两个以上降级驱动器通道严重MEL事件。
 a| 
请联系技术支持以解决此问题描述。



 a| 
过去 7 天内超过 4 个关键 MEL 条目
 a| 
无法升级固件、因为过去七天报告的严重事件日志条目超过四个。
 a| 
请联系技术支持以解决此问题描述。



 a| 
需要有效的管理IP地址。
 a| 
要执行此操作、需要有效的控制器IP地址。
 a| 
请联系技术支持以解决此问题描述。



 a| 
此命令要求为每个控制器提供一个活动管理IP地址。
 a| 
此操作需要为与存储阵列关联的每个控制器提供一个控制器IP地址。
 a| 
请联系技术支持以解决此问题描述。



 a| 
返回未处理的下载文件类型。
 a| 
不支持指定的下载文件。
 a| 
请联系技术支持以解决此问题描述。



 a| 
固件下载上传操作步骤 期间发生错误。
 a| 
固件下载失败、因为控制器无法处理此请求。验证存储阵列是否处于最佳状态、然后重试此操作。
 a| 
如果验证存储阵列是否为最佳阵列后再次出现此错误、请联系技术支持以解决此问题描述。



 a| 
固件激活操作步骤 期间发生错误。
 a| 
固件激活失败、因为控制器无法处理此请求。验证存储阵列是否处于最佳状态、然后重试此操作。
 a| 
如果验证存储阵列是否为最佳阵列后再次出现此错误、请联系技术支持以解决此问题描述。



 a| 
等待控制器\｛0｝重新启动时已超时。
 a| 
重新启动后、管理软件无法重新连接到控制器\｛0｝。验证存储阵列是否具有可操作的连接路径、如果此操作未成功完成、请重试此操作。
 a| 
如果验证存储阵列是否为最佳阵列后再次出现此错误、请联系技术支持以解决此问题描述。

|===
您可以使用System Manager中的Recovery Guru来更正其中某些情况。但是、在某些情况下、您可能需要联系技术支持。有关最新控制器固件下载的信息、请访问存储阵列。此信息有助于技术支持了解阻止固件升级和下载的错误情况。
