---
permalink: sm-support/upgrade-controller-software-and-firmware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, upgrade, software, firmware 
summary: '您可以升级存储阵列的软件以及IOM固件和非易失性静态随机存取存储器(NVSRAM)(可选)、以确保您具有所有最新功能并修复了错误。' 
---
= 在 SANtricity System Manager 中升级控制器软件和固件
:allow-uri-read: 


[role="lead"]
您可以升级存储阵列的软件以及IOM固件和非易失性静态随机存取存储器(NVSRAM)(可选)、以确保您具有所有最新功能并修复了错误。

.开始之前
* 您知道是否要升级IOM固件。
+
通常，您应同时升级所有组件。但是，如果您不希望在 SANtricity OS 软件升级过程中升级 IOM 固件，或者技术支持已指示您降级 IOM 固件（您只能使用命令行界面降级固件），则可能决定不升级 IOM 固件。

* 您知道是否要升级控制器NVSRAM文件。
+
通常，您应同时升级所有组件。但是，如果您的文件已修补或为自定义版本，并且您不想覆盖此文件，则您可能会决定不升级控制器 NVSRAM 文件。

* 您知道是要立即激活操作系统升级还是稍后激活。
+
稍后激活的原因可能包括：

+
** *当前时间*—激活软件和固件可能需要很长时间、因此您可能需要等待I/O负载减轻。控制器会在激活期间进行故障转移，因此在升级完成之前性能可能会比平常低。
** * 软件包类型 * —您可能需要先在一个存储阵列上测试新软件和固件，然后再升级其他存储阵列上的文件。


* 您知道是要从不安全的驱动器还是内部安全的驱动器切换、以使用外部密钥管理服务器(KMS)来保护驱动器的安全。
* 您知道是否要在存储阵列中使用基于角色的访问控制。


.关于此任务
您可以选择仅升级操作系统软件文件或仅升级控制器NVSRAM文件、也可以选择同时升级这两个文件。

只有在技术支持要求时、才执行此操作。

[CAUTION]
====
* 数据丢失或存储阵列损坏的风险 * —升级期间请勿更改存储阵列。为存储阵列供电。

====
.步骤
. 如果存储阵列仅包含一个控制器或您未安装多路径驱动程序，请停止存储阵列的 I/O 活动，以防止出现应用程序错误。如果存储阵列有两个控制器，并且您安装了多路径驱动程序，则无需停止 I/O 活动。
. 选择菜单：Support[升级中心]。
. 将新文件从支持站点下载到您的管理客户端。
+
.. 单击* NetApp支持*以启动支持网站。
.. 在支持网站上、单击*下载*选项卡、然后选择*下载*。
.. 选择* E系列SANtricity 操作系统控制器软件*。
.. 按照其余说明进行操作。


+
[NOTE]
====
8.42 及更高版本需要使用数字签名固件。如果您尝试下载未签名的固件，则会显示一个错误，并中止下载。

====
. 如果此时不想升级IOM固件、请单击*暂停IOM自动同步*。
+
如果存储阵列具有一个控制器，则不会升级 IOM 固件。

. 在SANtricity OS软件升级下、单击*开始升级*。
+
此时将显示升级SANtricity OS软件对话框。

. 选择一个或多个文件以开始升级过程：
+
.. 单击*浏览*并导航到从支持网站下载的操作系统软件文件、选择SANtricity 操作系统软件文件。
.. 单击 * 浏览 * 并导航到从支持站点下载的 NVSRAM 文件，以选择控制器 NVSRAM 文件。控制器 NVSRAM 文件的文件名类似于 `N2800-830000-000.DLP` 。


+
执行以下操作：

+
** 默认情况下，仅显示与当前存储阵列配置兼容的文件。
** 选择要升级的文件时，将显示该文件的名称和大小。


. *可选：*如果您选择了要升级的SANtricity 操作系统软件文件、则可以通过选中*立即传输文件、但不升级(稍后激活升级)*复选框将文件传输到控制器而不激活这些文件。
. 单击 * 开始 * ，然后确认您要执行此操作。
+
您可以在升级前运行状况检查期间取消此操作，但不能在传输或激活期间取消此操作。

. *可选：*要查看已升级内容的列表、请单击*保存日志*。
+
此文件将保存在浏览器的 "Downloads" 文件夹中，名为 `drive_upgrade_log-timestamp.txt` 。



.完成后
* 验证所有组件是否均显示在硬件页面上。
* 选中软件和固件清单对话框以验证新的软件和固件版本（转到菜单：支持 [ 升级中心 ] ，然后单击 * 软件和固件清单 * 链接）。
* 如果您升级了控制器 NVSRAM ，则在激活过程中，应用于现有 NVSRAM 的任何自定义设置都将丢失。激活过程完成后，您需要再次将自定义设置应用于 NVSRAM 。

