---
permalink: sm-support/view-unreadable-sectors-log.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, unreadable, sectors, log 
summary: 您可以保存无法读取的扇区日志并将文件发送给技术支持以进行分析。 
---
= 查看 SANtricity System Manager 中不可读扇区日志
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以保存无法读取的扇区日志并将文件发送给技术支持以进行分析。

.关于此任务
无法读取的扇区日志包含因驱动器报告不可恢复的介质错误而导致的无法读取扇区的详细记录。在正常I/O期间以及在重建等修改操作期间检测到不可读扇区。如果在存储阵列上检测到不可读扇区、则会针对该存储阵列显示Need Attention警报。Recovery Guru可区分需要关注哪些无法读取的扇区状况。无法恢复不可读扇区中包含的任何数据、应将其视为丢失。

无法读取的扇区日志最多可存储1、000个无法读取的扇区。如果无法读取的扇区日志达到1、000个条目、则会满足以下条件：

* 如果在重建期间检测到新的不可读扇区、则重建将失败、并且不会记录任何条目。
* 对于在I/O期间检测到的新不可读扇区、I/O将失败、并且不会记录任何条目。
+
[NOTE]
====
这些操作包括在溢出之前成功完成的RAID 5写入和RAID 6写入。

====


[CAUTION]
====
*可能的数据丢失*—从无法读取的扇区恢复是一种复杂的操作步骤 、可能涉及多种不同的方法。只有在技术支持要求时、才执行此操作。

====
.步骤
. 选择菜单：Support[支持中心>诊断]选项卡。
. 选择*查看/清除不可读扇区*。
. 要保存无法读取的扇区日志、请执行以下操作：
+
.. 在表的第一列中、您可以选择要保存不可读扇区日志的单个卷(单击每个卷旁边的复选框)、也可以选择所有卷(选中表标题中的复选框)。
+
要查找特定卷、您可以对任意列进行排序、也可以在*筛选器*框中键入字符。

.. 单击 * 保存 * 。


+
此文件将保存在浏览器的"Downloads"文件夹中、名称为`irrored-扇 区.txt`。

. 如果技术支持指示您清除无法读取的扇区日志、请执行以下步骤：
+
.. 在表的第一列中、您可以选择要清除不可读扇区日志的单个卷(单击每个卷旁边的复选框)、也可以选择所有卷(选中表标题中的复选框)。
.. 单击*清除*、然后确认要执行此操作。



