---
permalink: sm-support/view-events-using-the-event-log.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, events, 
summary: 您可以查看事件日志、其中提供了存储阵列上发生的事件的历史记录。 
---
= 使用事件日志查看事件
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以查看事件日志、其中提供了存储阵列上发生的事件的历史记录。

.步骤
. 选择菜单：Support[事件日志]。
+
此时将显示"Event Log"页面。

+
.页面详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 项目 | Description 


 a| 
查看全部字段
 a| 
在所有事件之间切换、仅在严重事件和警告事件之间切换。



 a| 
筛选字段
 a| 
筛选事件。仅用于显示与特定组件相关的事件、特定事件等



 a| 
选择列图标。
 a| 
用于选择其他要查看的列。其他列会提供有关事件的追加信息。



 a| 
复选框
 a| 
用于选择要保存的事件。表标题中的复选框将选择所有事件。



 a| 
日期/时间列
 a| 
事件的日期和时间戳、具体取决于控制器时钟。


NOTE: 事件日志最初会根据序列号对事件进行排序。通常、此序列对应于日期和时间。但是、存储阵列中的两个控制器时钟可能不同步。在这种情况下、事件日志中可能会出现与事件以及显示的日期和时间相关的一些可感知的不一致情况。



 a| 
优先级列
 a| 
存在以下优先级值：

** *严重*—存储阵列存在问题。但是、如果您立即采取措施、则可能会防止丢失对数据的访问。严重事件用于发出警报通知。所有严重事件都将通过SNMP陷阱发送到任何网络管理客户端或您配置的电子邮件收件人。
** *警告*—发生错误、导致存储阵列的性能和从其他错误中恢复的能力下降。
** *信息*—与存储阵列相关的非关键信息。




 a| 
组件类型列
 a| 
受事件影响的组件。组件可以是硬件、例如驱动器或控制器、也可以是软件、例如控制器固件。



 a| 
组件位置列
 a| 
组件在存储阵列中的物理位置。



 a| 
问题描述 列
 a| 
事件的问题描述。

*示例*-`D写入失败-重试已用尽`



 a| 
序列号列
 a| 
一个64位编号、用于唯一标识存储阵列的特定日志条目。此数字会随每个新事件日志条目递增一个。要显示此信息、请单击*选择列*图标。



 a| 
事件类型列
 a| 
一个4位数的数字、用于标识每种类型的已记录事件。要显示此信息、请单击*选择列*图标。



 a| 
事件特定代码列
 a| 
此信息由技术支持使用。要显示此信息、请单击*选择列*图标。



 a| 
事件类别列
 a| 
** "*故障"*—存储阵列中的某个组件出现故障、例如驱动器故障或电池故障。
** 状态更改*—存储阵列中状态发生更改的元素；例如、卷过渡到最佳状态或控制器过渡到脱机状态。
** "*内部"*–不需要用户操作的内部控制器操作；例如、控制器已完成每日开始。
** "**命令"*—已向存储阵列发出的命令；例如、已分配热备用磁盘。
** "#Error*–在存储阵列上检测到错误情况；例如、控制器无法同步和清除缓存、或者在存储阵列上检测到冗余错误。
** *常规*—不适合任何其他类别的任何事件。要显示此信息、请单击"**选择列"*图标。




 a| 
Logged by列
 a| 
记录事件的控制器的名称。要显示此信息、请单击"**选择列"*图标。

|===
====
. 要从存储阵列检索新事件、请单击"*刷新"*。
+
可能需要几分钟的时间、才能记录事件并在事件日志页面中显示。

. 将事件日志保存到文件：
+
.. 选中要保存的每个事件旁边的复选框。
.. 单击 * 保存 * 。
+
此文件将保存在浏览器的"Downloads"文件夹中、名称为`major-event-log-timestamp.log`。



. 要从事件日志中清除事件、请执行以下操作：
+
事件日志会先存储大约8、000个事件、然后再将事件替换为新事件。如果要保留事件、可以保存这些事件并从事件日志中清除它们。

+
.. 首先、保存事件日志。
.. 单击*全部清除*、然后确认您要执行此操作。



