---
permalink: sm-support/view-storage-array-profile.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, storage, array, profile 
summary: 存储阵列配置文件可提供存储阵列的所有组件和属性的问题描述。 
---
= 查看存储阵列配置文件
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
存储阵列配置文件可提供存储阵列的所有组件和属性的问题描述。

.关于此任务
您可以在恢复期间使用存储阵列配置文件作为辅助工具、也可以概述存储阵列的当前配置。您可能希望在管理客户端上保存存储阵列配置文件的副本、并在存储阵列中保留存储阵列配置文件的硬副本。如果配置发生更改、请为存储阵列配置文件创建一个新副本。

.步骤
. 选择菜单：Support[支持中心>支持资源]选项卡。
. 向下滚动到 * 启动详细存储阵列信息 * ，然后选择 * 存储阵列配置文件 * 。
+
此时、报告将显示在您的屏幕上。

+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 部分 | Description 


 a| 
存储阵列
 a| 
显示了您可以配置的所有选项以及存储阵列的系统静态选项。这些选项包括控制器数量、驱动器架、驱动器、磁盘池、卷组、 卷和热备用驱动器；允许的驱动器架、驱动器、固态磁盘(SSD)和卷的最大数量；快照组、快照映像、快照卷和一致性组的数量；功能信息；固件版本信息；机箱序列号信息；AutoSupport 状态和AutoSupport 计划信息； 用于自动支持数据收集和计划支持数据收集的设置；存储阵列全球通用标识符(World Wide Identifier、WWID)；以及介质扫描和缓存设置。



 a| 
存储
 a| 
显示了存储阵列中所有存储设备的列表。根据您的存储阵列配置、存储部分可能会显示这些子部分。

** *磁盘池*-显示存储阵列中所有磁盘池的列表。
** *卷组*-显示存储阵列中所有卷组的列表。卷和可用容量按创建顺序列出。
** *卷*-显示存储阵列中所有卷的列表。列出的信息包括卷名称、卷状态、容量、RAID级别、卷组或磁盘池、驱动器类型以及其他详细信息。
** *缺少卷*-显示存储阵列中当前处于缺失状态的所有卷的列表。列出的信息包括每个缺少的卷的全球通用标识符(World Wide Identifier、WWID)。




 a| 
复制服务
 a| 
显示了用于存储阵列的所有副本服务的列表。根据您的存储阵列配置、复制服务部分可能会显示以下子部分：

** *卷副本*-显示存储阵列中所有副本对的列表。列出的信息包括副本数量、副本对名称、状态、开始时间戳和其他详细信息。
** *快照组*-显示存储阵列中所有快照组的列表。
** *快照映像*-显示存储阵列中所有快照的列表。
** * Snapshot Volumes*—显示存储阵列中所有Snapshot卷的列表。
** *一致性组*-显示存储阵列中所有一致性组的列表。
** *成员卷*-显示存储阵列中所有一致性组成员卷的列表。
** *镜像组*-显示所有镜像卷的列表。
** *预留容量*-显示存储阵列中所有预留容量卷的列表。




 a| 
主机分配
 a| 
显示了存储阵列中的主机分配列表。列出的信息包括卷名称、逻辑单元号(LUN)、控制器ID、主机名或主机集群名称以及卷状态。列出的追加信息 包括拓扑定义和主机类型定义。



 a| 
硬件
 a| 
显示了存储阵列中所有硬件的列表。根据您的存储阵列配置、硬件部分可能会显示这些子部分。

** *控制器*-显示存储阵列中所有控制器的列表、其中包括控制器位置、状态和配置。此外、它还包括驱动器通道信息、主机通道信息和以太网端口信息。
** *驱动器*-显示存储阵列中所有驱动器的列表。驱动器按磁盘架ID、抽盒ID、插槽ID顺序列出。列出的信息包括磁盘架ID、抽盒ID、插槽ID、状态、原始容量、 每个驱动器的介质类型、接口类型、当前数据速率、产品ID和固件版本。驱动器部分还包括驱动器通道信息、热备用磁盘覆盖信息和使用寿命信息(仅适用于SSD驱动器)。损耗寿命信息包括已用持久性百分比、即迄今为止写入SSD驱动器的数据量除以驱动器的理论总写入限制。
** *驱动器通道*-显示存储阵列中所有驱动器通道的信息。列出的信息包括通道状态、链路状态(如果适用)、驱动器计数和累积错误计数。
** *磁盘架*-显示存储阵列中所有磁盘架的信息。列出的信息包括驱动器类型以及磁盘架中每个组件的状态信息。磁盘架组件可能包括电池组、小型可插拔(SFP)收发器、电源风扇箱或输入/输出模块(IOM)箱。如果存储阵列使用了安全密钥、则硬件部分还会显示安全密钥标识符。




 a| 
功能
 a| 
显示了每个主机或主机集群安装的功能包列表以及允许的最大快照组、快照(原有)和卷数。功能部分中的信息还包括驱动器安全性、即存储阵列是启用了安全性还是禁用了安全性。

|===
====
. 要搜索存储阵列配置文件、请在*查找*文本框中键入搜索词、然后单击*查找*。
+
所有匹配的术语均会突出显示。要一次滚动浏览一个所有结果，请继续单击 * 查找 * 。

. 要保存存储阵列配置文件、请单击*保存*。
+
此文件将保存在浏览器的"Downloads"文件夹中、名称为`storage-array-profile.txt`。


