---
permalink: sm-support/what-do-i-need-to-know-before-upgrading-the-santricity-os-software.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, upgrading, santricity, os, software 
summary: 在升级控制器的软件和固件之前、请注意以下事项。 
---
= 在升级SANtricity OS软件之前、我需要了解哪些信息？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在升级控制器的软件和固件之前、请注意以下事项。

* 您已阅读此文档和`reADME.txt`文件、并已确定要执行升级。
* 您知道是否要升级IOM固件。
+
通常，您应同时升级所有组件。但是、如果您不希望在SANtricity 操作系统控制器软件升级过程中升级IOM固件、或者技术支持已指示您降级IOM固件(您只能使用命令行界面降级固件)、则可能决定不升级IOM固件。

* 您知道是否要升级控制器NVSRAM文件。
+
通常，您应同时升级所有组件。但是，如果您的文件已修补或为自定义版本，并且您不想覆盖此文件，则您可能会决定不升级控制器 NVSRAM 文件。

* 您知道是要立即激活还是稍后激活。
+
稍后激活的原因可能包括：

+
** *当前时间*—激活软件和固件可能需要很长时间、因此您可能需要等待I/O负载减轻。控制器会在激活期间进行故障转移，因此在升级完成之前性能可能会比平常低。
** * 软件包类型 * —您可能需要先在一个存储阵列上测试新软件和固件，然后再升级其他存储阵列上的文件。




这些组件是SANtricity 操作系统控制器软件升级的一部分：

* *管理软件*—System Manager是用于管理存储阵列的软件。
* * 控制器固件 * —控制器固件用于管理主机和卷之间的 I/O 。
* * 控制器 NVSRA* - 控制器 NVSRAM 是一个控制器文件，用于指定控制器的默认设置。
* * IOM 固件 * — I/O 模块（ IOM ）固件用于管理控制器与驱动器架之间的连接。它还会监控组件的状态。
* * 监控软件 * —监控软件是运行该软件的控制器上的虚拟机。


在升级过程中、可能还需要升级主机的多路径/故障转移驱动程序和/或HBA驱动程序、以便主机可以正确地与控制器进行交互。

[NOTE]
====
要确定是否发生这种情况、请参见 https://mysupport.netapp.com/matrix["NetApp 互操作性表工具"^]。

====
如果存储阵列仅包含一个控制器或您未安装多路径驱动程序，请停止存储阵列的 I/O 活动，以防止出现应用程序错误。如果存储阵列有两个控制器，并且您安装了多路径驱动程序，则无需停止 I/O 活动。


CAUTION: 升级期间、请勿更改存储阵列。
