---
permalink: um-certificates/certificate-terminology-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, certificate, terminology 
summary: 以下术语适用于证书管理。 
---
= 证书术语
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以下术语适用于证书管理。

[cols="25h,~"]
|===
| 期限 | Description 


 a| 
CA
 a| 
证书颁发机构(Certificate Authority、CA)是一个受信任的实体、负责颁发称为数字证书的电子文档以确保Internet安全。这些证书用于标识网站所有者、从而可以在客户端和服务器之间建立安全连接。



 a| 
CSR
 a| 
证书签名请求(CSR)是从申请人发送给证书颁发机构(CA)的一条消息。CSR会验证CA对证书进行问题描述 所需的信息。



 a| 
证书
 a| 
出于安全考虑、证书用于标识站点所有者、从而防止攻击者模拟站点。此证书包含有关站点所有者的信息以及对此信息进行认证(签名)的可信实体的身份。



 a| 
证书链
 a| 
一种文件层次结构、用于向证书添加一层安全保护。通常、此链包含一个位于层次结构顶部的根证书、一个或多个中间证书以及用于标识实体的服务器证书。



 a| 
中间证书
 a| 
一个或多个中间证书从证书链中的根分支。CA颁发一个或多个中间证书、充当受保护根证书和服务器证书之间的中间人。



 a| 
密钥库
 a| 
密钥库是主机管理系统上的存储库、其中包含私钥及其对应的公有 密钥和证书。这些密钥和证书用于标识您自己的实体、例如控制器。



 a| 
根证书
 a| 
根证书位于证书链中的层次结构顶部、其中包含用于对其他证书签名的专用密钥。根标识特定的CA组织。如果对所有网络设备使用相同的CA、则只需要一个根证书。



 a| 
签名证书
 a| 
由证书颁发机构(CA)验证的证书。此数据文件包含一个专用密钥、可确保通过HTTPS连接在服务器和客户端之间以加密形式发送数据。此外、签名证书还包括实体所有者的详细信息(通常为服务器或网站)以及由字母和数字组成的数字签名。签名证书使用信任链、因此最常用于生产环境。也称为"CA签名证书"或"管理证书"。



 a| 
自签名证书
 a| 
自签名证书由实体的所有者进行验证。此数据文件包含一个专用密钥、可确保通过HTTPS连接在服务器和客户端之间以加密形式发送数据。它还包括由字母和数字组成的数字签名。自签名证书与CA签名证书使用的信任链不同、因此最常用于测试环境。也称为"预安装"证书。



 a| 
服务器证书
 a| 
服务器证书位于证书链的底部。它标识您的特定实体、例如网站或其他设备。存储系统中的每个控制器都需要一个单独的服务器证书。



 a| 
信任存储库
 a| 
信任存储库是一个存储库、其中包含来自CA等可信第三方的证书。

|===