---
permalink: um-certificates/edit-directory-server-settings-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, edit, directory, server, settings, role, mappings 
summary: 如果您之前在Access Management中配置了目录服务器、则可以随时更改其设置。设置包括服务器连接信息和组到角色映射。 
---
= 编辑目录服务器设置和角色映射
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您之前在Access Management中配置了目录服务器、则可以随时更改其设置。设置包括服务器连接信息和组到角色映射。

.开始之前
* 您必须使用包含安全管理员权限的用户配置文件登录。否则、不会显示访问管理功能。
* 必须定义目录服务器。


.步骤
. 选择*访问管理*。
. 选择*目录服务*选项卡。
. 如果定义了多个服务器、请从表中选择要编辑的服务器。
. 选择*查看/编辑设置*。
+
此时将打开目录服务器设置对话框。

. 在*服务器设置*选项卡中、更改所需设置。
+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 正在设置 ... | Description 


 a| 
*配置设置*



 a| 
域
 a| 
LDAP服务器的域名。对于多个域、请在逗号分隔列表中输入域。域名用于登录(_username_@_domain_)以指定要对其进行身份验证的目录服务器。



 a| 
服务器URL
 a| 
用于以形式访问LDAP服务器的URL `ldap[s]://host:port`。



 a| 
绑定帐户(可选)
 a| 
用于对LDAP服务器进行搜索查询以及在组内进行搜索的只读用户帐户。



 a| 
绑定密码(可选)
 a| 
绑定帐户的密码。(输入绑定帐户时会显示此字段。)



 a| 
保存前测试服务器连接
 a| 
检查系统是否可以与LDAP服务器配置进行通信。单击*保存*后会进行测试。如果选中此复选框且测试失败、则不会更改配置。您必须解决此错误或清除此复选框、才能跳过测试并重新编辑配置。



 a| 
*权限设置*



 a| 
搜索基础DN
 a| 
用于搜索用户的LDAP环境、通常采用的形式 `CN=Users, DC=cpoc, DC=local`。



 a| 
username属性
 a| 
绑定到用户ID进行身份验证的属性。例如：`sAMAccountName`。



 a| 
组属性
 a| 
用户上的组属性列表、用于组到角色映射。例如：`memberOf、managedObjects`。

|===
====
. 在*角色映射*选项卡中、更改所需的映射。
+
.字段详细信息
[%collapsible]
====
[cols="25h,~"]
|===
| 正在设置 ... | Description 


 a| 
*映射*



 a| 
组DN
 a| 
要映射的LDAP用户组的域名。支持正则表达式。如果这些特殊正则表达式字符不属于正则表达式模式、则必须使用反斜杠(\)进行转义：

\.[]｛｝()<>*+-=！？^$|



 a| 
角色
 a| 
要映射到组DN的角色。您必须单独为此组选择要包含的每个角色。要登录到SANtricity Unified Manager、需要将监控角色与其他角色结合使用。这些角色包括：

** *存储管理*—对阵列上的存储对象具有完全读/写访问权限、但无法访问安全配置。
** *安全管理*—访问访问管理和证书管理中的安全配置。
** *支持管理*—访问存储阵列上的所有硬件资源、故障数据和MEL事件。无法访问存储对象或安全配置。
** *监控*—对所有存储对象的只读访问、但无法访问安全配置。


|===
====
+

NOTE: 包括管理员在内的所有用户都需要"监控"角色。

. 如果需要、请单击*添加另一个映射*以输入更多组到角色的映射。
. 单击 * 保存 * 。


.结果
完成此任务后、所有活动用户会话都将终止。仅会保留当前用户会话。
