---
permalink: um-admin/administrator-password-protection-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, administrator, password, protection 
summary: 您必须使用管理员密码配置SANtricity Unified Manager、以防止未经授权的访问。 
---
= 设置管理员密码保护
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须为Unified Manager配置管理员密码、以防止其遭受未经授权的访问。



== 管理员密码和用户配置文件

首次启动Unified Manager时、系统会提示您设置管理员密码。具有管理员密码的任何用户都可以对存储阵列进行配置更改。

除了管理员密码之外、Unified Manager界面还包括预先配置的用户配置文件、其中包含一个或多个映射到这些配置文件的角色。有关详细信息，请参见 link:../um-certificates/how-access-management-works-unified.html["访问管理的工作原理"]。

无法更改用户和映射。只能修改密码。要更改密码、请参见：

* link:change-admin-password-unified.html["更改管理员密码"]
* link:../um-certificates/change-passwords-unified.html["更改本地用户配置文件的密码"]




== 会话超时

在单个管理会话期间、软件仅会提示您输入密码一次。默认情况下、会话在30分钟处于非活动状态后超时、此时您必须再次输入密码。如果另一个用户从另一个管理客户端访问软件并在会话期间更改了密码、则在下次尝试配置操作或查看操作时、系统会提示您输入密码。

出于安全原因、您只能在软件进入"锁定"状态之前尝试输入五次密码。在此状态下、软件将拒绝后续的密码尝试。您必须等待10分钟才能重置为"正常"状态、然后才能再次尝试输入密码。

您可以调整会话超时、也可以完全禁用会话超时。有关详细信息，请参见 link:manage-session-timeouts-unified.html["管理会话超时"]。
